import http from 'node:http';
import crypto from 'node:crypto';
const { subtle } = crypto.webcrypto;
const PORT=Number(process.env.PORT||8788);
const RELAY_ID='nvsn-relay-reference-001';
const MAX_BODY=262144;
const MAX_SKEW_MS=300000;
const DEFAULT_TTL_MS=86400000;
const MAX_TTL_MS=604800000;
const messages=new Map();
const registrations=new Map();
const authNonces=new Map();
const buckets=new Map();
const limits={submit:60,read:120,ack:120,register:20};
const now=()=>Date.now();
const b64ToBytes=s=>Uint8Array.from(Buffer.from(s,'base64'));
const sha256Hex=s=>crypto.createHash('sha256').update(s).digest('hex');
const stable=v=>Array.isArray(v)?'['+v.map(stable).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}':JSON.stringify(v);
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-neogram-identity,x-neogram-timestamp,x-neogram-nonce,x-neogram-public-key,x-neogram-signature','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data));};
const clean=()=>{const t=now();for(const [id,m] of messages)if(m.expires_at_ms<=t)messages.delete(id);for(const [n,e] of authNonces)if(e<=t)authNonces.delete(n);};
const rate=(identity,kind)=>{const minute=Math.floor(now()/60000);const key=`${identity}:${kind}:${minute}`;const count=(buckets.get(key)||0)+1;buckets.set(key,count);return count<=limits[kind];};
const bodyOf=req=>new Promise((resolve,reject)=>{let body='';let size=0;req.on('data',c=>{size+=c.length;if(size>MAX_BODY){reject(new Error('body_too_large'));req.destroy();return;}body+=c;});req.on('end',()=>resolve(body));req.on('error',reject);});
async function importEcdsaRaw(rawB64){return subtle.importKey('raw',b64ToBytes(rawB64),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);}
async function verifyRequest(req,path,body){const identity=req.headers['x-neogram-identity'];const timestamp=req.headers['x-neogram-timestamp'];const nonce=req.headers['x-neogram-nonce'];const publicKey=req.headers['x-neogram-public-key'];const signature=req.headers['x-neogram-signature'];if(!identity||!timestamp||!nonce||!publicKey||!signature)return {ok:false,status:401,error:'missing_auth_headers'};const ts=Date.parse(String(timestamp));if(!Number.isFinite(ts)||Math.abs(now()-ts)>MAX_SKEW_MS)return {ok:false,status:401,error:'timestamp_outside_window'};clean();if(authNonces.has(String(nonce)))return {ok:false,status:409,error:'request_replay'};const canonical=[req.method,path,String(timestamp),String(nonce),sha256Hex(body)].join('\n');try{const key=await importEcdsaRaw(String(publicKey));const valid=await subtle.verify({name:'ECDSA',hash:'SHA-256'},key,b64ToBytes(String(signature)),new TextEncoder().encode(canonical));if(!valid)return {ok:false,status:401,error:'invalid_request_signature'};authNonces.set(String(nonce),now()+600000);return {ok:true,identity:String(identity),publicKey:String(publicKey)};}catch{return {ok:false,status:401,error:'invalid_request_key'};}}
async function verifyEnvelope(env){try{if(env.protocol!=='NTP'||env.version!=='1.0'||!env.message_id||!env.nonce||!env.expires_at)return false;if(!env.security?.signature||!env.security?.public_key)return false;if(!env.message?.encrypted||!env.message?.ciphertext||!env.message?.iv)return false;if('payload' in env.message)return false;const copy=structuredClone(env);copy.security.signature=null;copy.security.state='SIGNING';const key=await importEcdsaRaw(env.security.public_key);return subtle.verify({name:'ECDSA',hash:'SHA-256'},key,b64ToBytes(env.security.signature),new TextEncoder().encode(stable(copy)));}catch{return false;}}
function expiryFor(env){const requested=Date.parse(env.expires_at);if(!Number.isFinite(requested))return null;const max=now()+MAX_TTL_MS;if(requested<=now())return null;return Math.min(requested,max);}
function publicMessage(record){return {message_id:record.envelope.message_id,source:record.envelope.source,destination:record.envelope.destination,created_at:record.envelope.created_at,expires_at:record.envelope.expires_at,status:record.status,envelope:record.envelope};}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://relay.local');const path=url.pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-neogram-identity,x-neogram-timestamp,x-neogram-nonce,x-neogram-public-key,x-neogram-signature','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end();}clean();if(req.method==='GET'&&path==='/health')return json(res,200,{ok:true,product:'Neogram',service:'nvsn-relay-reference',relay_id:RELAY_ID,protocol:'NTP/1.0',version:'0.5',live:false,storage:'encrypted-envelope-only'});
let body='';if(req.method==='POST'){try{body=await bodyOf(req);}catch(e){return json(res,e.message==='body_too_large'?413:400,{error:e.message});}}
if(req.method==='POST'&&path==='/v0.5/relay/register'){const auth=await verifyRequest(req,path,body);if(!auth.ok)return json(res,auth.status,{error:auth.error});if(!rate(auth.identity,'register'))return json(res,429,{error:'rate_limited'});let input;try{input=JSON.parse(body||'{}');}catch{return json(res,400,{error:'invalid_json'});}if(input.neo_id!==auth.identity)return json(res,403,{error:'identity_mismatch'});registrations.set(auth.identity,{neo_id:auth.identity,signing_public_key:auth.publicKey,encryption_public_key:input.encryption_public_key||null,encryption_fingerprint:input.encryption_fingerprint||null,registered_at:new Date().toISOString()});return json(res,201,{relay_id:RELAY_ID,registration:registrations.get(auth.identity)});}
if(req.method==='POST'&&path==='/v0.5/messages'){const auth=await verifyRequest(req,path,body);if(!auth.ok)return json(res,auth.status,{error:auth.error});if(!rate(auth.identity,'submit'))return json(res,429,{error:'rate_limited'});let env;try{env=JSON.parse(body||'{}');}catch{return json(res,400,{error:'invalid_json'});}if(env.source?.neo_id!==auth.identity)return json(res,403,{error:'source_identity_mismatch'});if(env.security?.public_key!==auth.publicKey)return json(res,403,{error:'signing_key_mismatch'});if(!(await verifyEnvelope(env)))return json(res,400,{error:'invalid_or_unencrypted_ntp_envelope'});const expires=expiryFor(env);if(!expires)return json(res,400,{error:'expired_or_invalid_ttl'});if(messages.has(env.message_id))return json(res,409,{error:'duplicate_message_id'});messages.set(env.message_id,{envelope:env,status:'STORED',stored_at:new Date().toISOString(),expires_at_ms:expires,acks:[]});return json(res,202,{relay_id:RELAY_ID,message_id:env.message_id,status:'STORED',expires_at:new Date(expires).toISOString()});}
const mailbox=path.match(/^\/v0\.5\/mailbox\/([^/]+)$/);if(req.method==='GET'&&mailbox){const identity=decodeURIComponent(mailbox[1]);const auth=await verifyRequest(req,path,'');if(!auth.ok)return json(res,auth.status,{error:auth.error});if(auth.identity!==identity)return json(res,403,{error:'mailbox_identity_mismatch'});if(!rate(identity,'read'))return json(res,429,{error:'rate_limited'});const items=[];for(const record of messages.values())if(record.envelope.destination?.value===identity&&record.expires_at_ms>now()&&record.status!=='ACKNOWLEDGED'){record.status='DELIVERED';items.push(publicMessage(record));}return json(res,200,{relay_id:RELAY_ID,neo_id:identity,items});}
const ack=path.match(/^\/v0\.5\/messages\/([^/]+)\/ack$/);if(req.method==='POST'&&ack){const messageId=decodeURIComponent(ack[1]);const auth=await verifyRequest(req,path,body);if(!auth.ok)return json(res,auth.status,{error:auth.error});if(!rate(auth.identity,'ack'))return json(res,429,{error:'rate_limited'});const record=messages.get(messageId);if(!record)return json(res,404,{error:'message_not_found'});if(record.envelope.destination?.value!==auth.identity)return json(res,403,{error:'ack_identity_mismatch'});let input={};try{input=JSON.parse(body||'{}');}catch{return json(res,400,{error:'invalid_json'});}const ackRecord={ack_id:`ack:${crypto.randomUUID()}`,message_id:messageId,neo_id:auth.identity,status:input.status||'ACKNOWLEDGED',created_at:new Date().toISOString()};record.acks.push(ackRecord);record.status='ACKNOWLEDGED';return json(res,200,{relay_id:RELAY_ID,...ackRecord});}
return json(res,404,{error:'not_found'});});
server.listen(PORT,()=>console.log(`Neogram NVSN relay reference listening on ${PORT}`));
