// NEO Statements compatibility layer.
// Primary mode: credential-free GitHub Pages snapshots generated by GitHub Actions.
// Optional service mode remains supported when explicitly configured.
async function scanStatementService(q){
  const cfg=window.NEO_SCAN_CONFIG||{};
  const snapshotBase=String(cfg.statementsSnapshotBase||'').replace(/\/$/,'');
  const serviceBase=String(cfg.statementsServiceUrl||'').replace(/\/$/,'');
  const timeout=Math.max(1000,Number(cfg.statementsServiceTimeoutMs||8000));

  let envelope;
  let sourceMode='github-pages-snapshot';

  if(snapshotBase){
    const snapshotUrl=`${snapshotBase}/${encodeURIComponent(q)}.json`;
    const response=await fetch(snapshotUrl,{headers:{accept:'application/json'},signal:AbortSignal.timeout(timeout)});
    if(response.ok){
      envelope=await response.json();
    }else if(response.status!==404){
      throw new Error(`statement-snapshot-${response.status}`);
    }
  }

  if(!envelope&&serviceBase){
    sourceMode='authenticated-service';
    const response=await fetch(`${serviceBase}/v1/statements?address=${encodeURIComponent(q)}`,{
      headers:{accept:'application/json'},
      signal:AbortSignal.timeout(timeout)
    });
    if(!response.ok)throw new Error(`statement-service-${response.status}`);
    envelope=await response.json();
  }

  if(!envelope)throw new Error('statement-snapshot-not-published');

  const statement=envelope?.data||envelope;
  if(!statement?.sources)throw new Error('invalid-statement-envelope');

  const sources=statement.sources;
  const verified=(source)=>source?.status==='verified';
  const entries=(source)=>Array.isArray(source?.entries)?source.entries:[];
  const amount=(entry)=>entry&&entry.amount!==undefined&&entry.unit?`${entry.amount} ${entry.unit}`:null;

  const bitcoinEntries=entries(sources.bitcoin);
  const counterpartyEntries=entries(sources.counterparty);
  const cesEntries=entries(sources.ces);
  const cesBalance=cesEntries.find(entry=>entry?.recordType==='balance');
  const cesTransactions=cesEntries.filter(entry=>entry?.recordType!=='balance');

  const bitcoin=verified(sources.bitcoin)
    ? (amount(bitcoinEntries[0])||`Verified · ${bitcoinEntries.length} record${bitcoinEntries.length===1?'':'s'}`)
    : 'Unavailable';
  const counterparty=verified(sources.counterparty)
    ? `${counterpartyEntries.length} verified asset balance${counterpartyEntries.length===1?'':'s'}`
    : 'Unavailable';
  const ces=verified(sources.ces)
    ? `${amount(cesBalance)||'Verified balance'} · ${cesTransactions.length} transaction${cesTransactions.length===1?'':'s'}`
    : 'Unavailable · no verified CES snapshot published';

  const renderRows=window.rows;
  if(typeof renderRows!=='function')throw new Error('statement-renderer-unavailable');
  document.getElementById('result').innerHTML=`${renderRows('NEO Statement — Reconciliation',[
    ['Account',statement.account||q],
    ['Bitcoin',bitcoin],
    ['Counterparty',counterparty],
    ['CES',ces],
    ['Offline / off-book','Unavailable · attested source not supplied'],
    ['Reconciliation',statement.reconciliationStatus||'—'],
    ['Cross-ledger total',statement.consolidatedTotal==null?'Not computed — unlike units are never silently summed':statement.consolidatedTotal],
    ['Statement schema',statement.statementSchema||'neo.statement.v1'],
    ['Service schema',statement.schema||'neo.statement.service.v1'],
    ['Generated',statement.generatedAt||envelope.generatedAt||'—'],
    ['Source',sourceMode==='github-pages-snapshot'?'GitHub Actions → GitHub Pages':'Authenticated service'],
    ['Request ID',envelope?.requestId||'—']
  ],'STATEMENT')}<div class="empty">Source mode: ${sourceMode==='github-pages-snapshot'?'GitHub-native read-only snapshot':'authenticated service'}. Secrets remain in GitHub Actions or the configured backend and are never exposed to the browser. Every ledger retains its native unit and provenance.</div>`;
}
