import assert from 'node:assert/strict';
import { once } from 'node:events';
process.env.NODE_ENV='test';process.env.NEO_REALTY_ADMIN_TOKEN='postgres-admin-token';process.env.NEO_REALTY_FRONTEND_ORIGIN='';if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL required');
const {createApp}=await import('./server.js');const server=createApp().listen(0);await once(server,'listening');const address=server.address();if(!address||typeof address==='string')throw new Error('server_not_listening');const base=`http://127.0.0.1:${address.port}`;const admin={authorization:'Bearer postgres-admin-token'};
try{
  assert.equal((await fetch(`${base}/ready`)).status,200);await fetch(`${base}/admin/reset`,{method:'POST',headers:admin});
  const createdResponse=await fetch(`${base}/properties`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({listingType:'sale',propertyType:'multifamily',address:{line1:'500 Bitcoin Boulevard',city:'Houston',region:'TX',postalCode:'77002',country:'US',latitude:29.7604,longitude:-95.3698},facts:{units:20,occupancyPct:94,annualNoi:327371},pricing:{askingFiat:6000000,fiatCurrency:'USD',displayWorldCurrency:'∞6000000'},neo:{neoPadsEligible:true,counterpartyAsset:'HOMESHARES',homeSharesEnabled:true,settlementAssets:['BTC','XCP','NOMNI']},authority:{claimStatus:'verified'}})});assert.equal(createdResponse.status,201);const created=await createdResponse.json() as any;assert.equal(created.data.status,'pending_verification');const id=created.data.id as string;
  const evidence=await fetch(`${base}/admin/properties/${id}/evidence`,{method:'POST',headers:{...admin,'content-type':'application/json'},body:JSON.stringify({evidenceType:'deed_reference',reference:'county-record-reference-001',sha256:'abc123'})});assert.equal(evidence.status,201);const evidenceBody=await evidence.json() as any;assert.match(evidenceBody.disclaimer,/not itself proof/i);const evidenceId=evidenceBody.data.id;
  const review=await fetch(`${base}/admin/evidence/${evidenceId}/review`,{method:'POST',headers:{...admin,'content-type':'application/json'},body:JSON.stringify({decision:'accepted',note:'reference reviewed'})});assert.equal(review.status,200);assert.equal((await review.json() as any).data.reviewStatus,'accepted');
  const approved=await fetch(`${base}/admin/properties/${id}/authority`,{method:'POST',headers:{...admin,'content-type':'application/json'},body:JSON.stringify({decision:'verified',verificationMethod:'document_review'})});assert.equal(approved.status,200);
  const mapSearch=await fetch(`${base}/properties?minLat=29&maxLat=30&minLng=-96&maxLng=-95&propertyType=multifamily`);const mapBody=await mapSearch.json() as any;assert.equal(mapBody.count,1);assert.equal(mapBody.data[0].id,id);
  const outside=await fetch(`${base}/properties?minLat=31&maxLat=32&minLng=-96&maxLng=-95`);assert.equal((await outside.json() as any).count,0);
  const detail=await fetch(`${base}/properties/${id}`);assert.equal(detail.status,200);const detailBody=await detail.json() as any;assert.equal(detailBody.data.neo.counterpartyAsset,'HOMESHARES');
  const listedEvidence=await fetch(`${base}/admin/properties/${id}/evidence`,{headers:admin});assert.equal((await listedEvidence.json() as any).count,1);
  console.log('NEO Realty Postgres map/evidence integration flow passed');
}finally{server.close();}
