const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const now=()=>new Date().toISOString();
const clean=v=>String(v||'').replace(/\/+$/,'');
function auth(request,env){if(!env.MODULE_ADAPTER_TOKEN)return true;const h=request.headers.get('authorization')||'';return h===`Bearer ${env.MODULE_ADAPTER_TOKEN}`}
function headers(env){const h={accept:'application/json','content-type':'application/json','x-neo-actor':'neo-memory-ingest'};if(env.MODULE_ADAPTER_TOKEN)h.authorization=`Bearer ${env.MODULE_ADAPTER_TOKEN}`;if(env.CF_ACCESS_CLIENT_ID)h['CF-Access-Client-Id']=env.CF_ACCESS_CLIENT_ID;if(env.CF_ACCESS_CLIENT_SECRET)h['CF-Access-Client-Secret']=env.CF_ACCESS_CLIENT_SECRET;return h}
async function fetchJson(url,env){const r=await fetch(url,{headers:headers(env),signal:AbortSignal.timeout(12000)});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}: ${b.error||'request failed'}`);return b}
function mem(env){const id=env.MEMORY_GRAPH.idFromName('neo-operational-memory');return env.MEMORY_GRAPH.get(id)}
async function memoryCall(env,path,method='GET',body){const r=await mem(env).fetch(new Request(`https://memory${path}`,{method,headers:{'content-type':'application/json','x-neo-actor':'neo-memory-ingest'},body:body?JSON.stringify(body):undefined}));let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`memory ${r.status}`);return b}
async function entity(env,b){return memoryCall(env,'/entities','POST',b)}
async function edge(env,b){try{return await memoryCall(env,'/edges','POST',b)}catch(e){if(/Both edge endpoints/.test(e.message))throw e;return{ok:false,warning:e.message}}}
async function seedCore(env){const rows=[
{id:'system:neo',type:'SYSTEM',name:'NEO System',summary:'Parent architecture spanning Consumer, Enterprise and private Government surfaces.',status:'ACTIVE',source:'architecture/neo-hosts.json'},
{id:'entry:neo',type:'SYSTEM',name:'neo.holytemples.org',aliases:['NEO System Gateway'],summary:'Canonical NEO System entrypoint.',status:'ACTIVE',source:'architecture/neo-hosts.json',metadata:{url:'https://neo.holytemples.org',visibility:'public-system-entry'}},
{id:'entry:hub',type:'SYSTEM',name:'hub.holytemples.org',aliases:['NEO Hub'],summary:'Canonical public NEO Hub entrypoint.',status:'ACTIVE',source:'architecture/neo-hosts.json',metadata:{url:'https://hub.holytemples.org',visibility:'public-hub'}},
{id:'module:neosync',type:'MODULE',name:'NEOsync',summary:'Private Government executive AI and orchestration layer.',status:'ACTIVE',source:'registry/agents.yaml'},
{id:'module:command-board',type:'MODULE',name:'NEOsync Executive Command Board',summary:'Private conversational command surface with confirmation-gated actions.',status:'ACTIVE',source:'cloudflare/neo-command-board'},
{id:'module:memory-graph',type:'MODULE',name:'NEOsync Operational Memory Graph',summary:'Persistent operational entities, relationships, provenance and context.',status:'ACTIVE',source:'cloudflare/neo-memory-graph'},
{id:'module:memory-ingest',type:'MODULE',name:'NEOsync Memory Ingestion',summary:'Automatic ingestion and context-linking service for approved NEO sources.',status:'ACTIVE',source:'cloudflare/neo-memory-ingest'}];
for(const r of rows)await entity(env,r);
const links=[
{id:'edge:neo-entry',from:'system:neo',to:'entry:neo',relation:'HAS_CANONICAL_ENTRYPOINT',label:'canonical system entrypoint',source:'architecture/neo-official-entrypoints.json'},
{id:'edge:hub-entry',from:'system:neo',to:'entry:hub',relation:'HAS_PUBLIC_HUB',label:'public NEO hub',source:'architecture/neo-official-entrypoints.json'},
{id:'edge:neosync-system',from:'module:neosync',to:'system:neo',relation:'ORCHESTRATES_WITHIN',source:'registry/agents.yaml'},
{id:'edge:command-neosync',from:'module:command-board',to:'module:neosync',relation:'INTERFACE_FOR',source:'cloudflare/neo-command-board'},
{id:'edge:command-memory',from:'module:command-board',to:'module:memory-graph',relation:'USES_CONTEXT_FROM',source:'cloudflare/neo-command-board'},
{id:'edge:ingest-memory',from:'module:memory-ingest',to:'module:memory-graph',relation:'WRITES_APPROVED_CONTEXT_TO',source:'cloudflare/neo-memory-ingest'}];
for(const r of links)await edge(env,r);
return{entities:rows.length,edges:links.length}}
async function ingestInbox(env,report){if(!env.EXECUTIVE_INBOX_URL)return;const d=await fetchJson(clean(env.EXECUTIVE_INBOX_URL)+'/api/inbox',env);for(const i of d.items||[]){const id=`inbox:${i.id}`;await entity(env,{id,type:i.kind==='ENTERPRISE_APPROVAL'?'DECISION':'EVENT',name:i.title||i.id,summary:i.summary||'',status:i.disposition?.status||'OPEN',source:'neo-executive-inbox',metadata:{priority:i.priority,sourceSystem:i.source,module:i.module,dueAt:i.dueAt||null}});await edge(env,{id:`edge:${id}:neosync`,from:'module:neosync',to:id,relation:'MONITORS',source:'neo-memory-ingest',confidence:1});report.inbox++}}
async function ingestGovernment(env,report){if(!env.GOVERNMENT_API_URL)return;const d=await fetchJson(clean(env.GOVERNMENT_API_URL)+'/api/adapters',env);for(const a of d.adapters||[]){const id=`gov-module:${a.id}`;await entity(env,{id,type:'MODULE',name:a.name||a.id,summary:`Government adapter ${a.state||'UNKNOWN'} via ${a.mode||'unknown mode'}.`,status:a.state||'ACTIVE',source:'neo-government-adapter-fabric',metadata:{adapterId:a.id,mode:a.mode,endpoint:a.endpoint||null}});await edge(env,{id:`edge:${id}:neo`,from:'system:neo',to:id,relation:'CONTAINS_MODULE',source:'neo-memory-ingest',confidence:1});report.modules++}}
async function ingestCommandBoard(env,report){if(!env.NEOSYNC_COMMAND_BOARD_URL)return;const d=await fetchJson(clean(env.NEOSYNC_COMMAND_BOARD_URL)+'/api/snapshot',env);for(const t of d.tasks||[]){const id=`command-task:${t.id}`;await entity(env,{id,type:'TASK',name:t.title||t.id,summary:t.description||'',status:t.status||'OPEN',source:'neo-command-board',metadata:{assignee:t.assignee,office:t.office,dueAt:t.dueAt||null,linkedSource:t.linkedSource||null}});await edge(env,{id:`edge:${id}:command`,from:'module:command-board',to:id,relation:'TRACKS_TASK',source:'neo-memory-ingest',confidence:1});report.tasks++}}
async function sync(env){const report={startedAt:now(),core:null,inbox:0,modules:0,tasks:0,errors:[]};try{report.core=await seedCore(env)}catch(e){report.errors.push(`core: ${e.message}`)}for(const fn of [ingestInbox,ingestGovernment,ingestCommandBoard]){try{await fn(env,report)}catch(e){report.errors.push(e.message)}}report.completedAt=now();report.ok=report.errors.length===0;return report}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return json({ok:true,service:'neo-memory-ingest',version:'1.0',capabilities:['scheduled-ingestion','automatic-context-linking','official-entrypoint-seeding']});if(!auth(request,env))return json({error:'Unauthorized'},401);if(request.method==='POST'&&u.pathname==='/sync')return json(await sync(env));if(request.method==='GET'&&u.pathname==='/preview')return json({sources:{executiveInbox:!!env.EXECUTIVE_INBOX_URL,government:!!env.GOVERNMENT_API_URL,commandBoard:!!env.NEOSYNC_COMMAND_BOARD_URL},officialEntrypoints:['https://neo.holytemples.org','https://hub.holytemples.org']});return json({error:'Not found'},404)},async scheduled(_event,env,_ctx){await sync(env)}};
