const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function renderDealDeskDashboard({opportunities=[],approvalQueue=[],asOf=new Date().toISOString()}={}){
  const hot=opportunities.filter(x=>(x?.opportunity?.qualification?.score||0)>=80);
  const pipeline=opportunities.reduce((map,x)=>{
    const stage=x?.opportunity?.stage||'unknown';
    map[stage]=(map[stage]||0)+1;
    return map;
  },{});
  const cards=opportunities.length?opportunities.map(x=>{
    const o=x.opportunity||{},p=x.normalized||{},q=o.quote||{},score=o.qualification?.score||0;
    return `<article class="deal"><div><span class="grade">${
      esc(o.qualification?.grade||'-')
    }</span><h2>${esc(p.organization||p.name)}</h2><p>${esc(o.dealClass)} · ${score}/100 · ${esc(o.stage)}</p></div><div class="ask">${q.ask?'$'+Number(q.ask).toLocaleString('en-US'):'TERMS GATED'}</div></article>`;
  }).join(''):'<div class="empty">No sourced opportunities loaded.</div>';
  const approvals=approvalQueue.length?approvalQueue.map(x=>`<li><strong>${esc(x.prospect?.organization||x.prospect?.name||'Prospect')}</strong><span>${esc((x.reasons||[]).join(', '))}</span></li>`).join(''):'<li><span>No pending gated deals.</span></li>';
  const body=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NEO Deal Desk</title><style>:root{color-scheme:dark;--bg:#030806;--panel:#09150f;--line:#274031;--ink:#eefbf1;--muted:#9bb0a0;--green:#4cff7a;--gold:#d7b760}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 Inter,system-ui}main{width:min(1180px,calc(100% - 2rem));margin:auto;padding:2rem 0 4rem}header{display:flex;justify-content:space-between;gap:1rem;align-items:end;border-bottom:1px solid var(--line);padding-bottom:1.2rem}h1{font:700 clamp(2rem,5vw,4rem)/1 Georgia,serif;margin:.35rem 0}.tag{color:var(--green);font-weight:800;letter-spacing:.12em;font-size:.75rem}.muted,p,span{color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.8rem;margin:1.2rem 0}.metric,.panel,.deal{background:var(--panel);border:1px solid var(--line);border-radius:.85rem;padding:1rem}.metric strong{display:block;font-size:1.7rem}.layout{display:grid;grid-template-columns:2fr 1fr;gap:1rem}.deal{display:flex;justify-content:space-between;gap:1rem;align-items:center;margin-bottom:.65rem}.deal h2{font:700 1.05rem Georgia,serif;margin:.2rem 0}.grade{display:inline-grid;place-items:center;width:30px;height:30px;border:1px solid var(--green);border-radius:50%;color:var(--green);font-weight:900}.ask{font-weight:850;color:var(--gold);white-space:nowrap}.panel h2{font-family:Georgia,serif}.panel ul{list-style:none;padding:0}.panel li{display:grid;gap:.2rem;padding:.7rem 0;border-bottom:1px solid var(--line)}.empty{padding:2rem;text-align:center;color:var(--muted)}@media(max-width:800px){.metrics{grid-template-columns:1fr 1fr}.layout{grid-template-columns:1fr}.deal{align-items:flex-start;flex-direction:column}}</style></head><body><main><header><div><div class="tag">NIA-013 · COMMERCIAL OPERATIONS</div><h1>NEO Deal Desk</h1><p>Public-source prospect intelligence, qualification, pricing and approval control.</p></div><div class="muted">As of ${esc(asOf)}</div></header><section class="metrics"><div class="metric"><span>Pipeline</span><strong>${opportunities.length}</strong></div><div class="metric"><span>Hot leads</span><strong>${hot.length}</strong></div><div class="metric"><span>Approvals</span><strong>${approvalQueue.length}</strong></div><div class="metric"><span>Stages</span><strong>${Object.keys(pipeline).length}</strong></div></section><div class="layout"><section><div class="tag">OPPORTUNITIES</div>${cards}</section><aside class="panel"><div class="tag">HUMAN GATE</div><h2>Approval Queue</h2><ul>${approvals}</ul></aside></div></main></body></html>`;
  return body;
}
