package org.neosystem.guardian;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.util.ArrayList;
import java.util.List;

/** Explicit Work Shield UI. Foreground mode is opt-in, visible, stoppable, metadata-only defense. */
public final class WorkShieldActivity extends Activity {
    private static final String BASELINE="baseline", APP_BASELINE="app_baseline"; private static final long INTERVAL_MS=30000L;
    private final Handler handler=new Handler(Looper.getMainLooper()); private LinearLayout content; private TextView chip; private boolean enabled; private GuardianWorkShield.Snapshot last; private GuardianAppDefense.Inventory appLast;
    private final Runnable pulse=new Runnable(){@Override public void run(){if(!enabled)return;runPostureCheck(false);handler.postDelayed(this,INTERVAL_MS);}};
    @Override protected void onCreate(Bundle state){super.onCreate(state);setContentView(shell());showHome();}
    @Override protected void onPause(){super.onPause();handler.removeCallbacks(pulse);}
    @Override protected void onResume(){super.onResume();if(enabled)handler.post(pulse);}
    private View shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(6,9,14));LinearLayout header=new LinearLayout(this);header.setPadding(dp(18),dp(18),dp(18),dp(14));header.setGravity(Gravity.CENTER_VERTICAL);header.setBackgroundColor(Color.rgb(14,20,29));header.addView(text("NEO Guardian • Work Shield v3.3",22,true,Color.WHITE),new LinearLayout.LayoutParams(0,-2,1));chip=text("OFF",12,true,Color.rgb(255,184,77));header.addView(chip);root.addView(header);ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(18),dp(18),dp(28));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return root;}
    private void showHome(){content.removeAllViews();card("NOUS / N0 EVIDENCE POLICY","Device and app observables are evidence, not automatic proof of monitoring or attack. CORROBORATED_ATTACK requires at least two independent channels and two sources. Consequential action remains human-approved.",Color.rgb(75,220,170));Button toggle=button(enabled?"STOP VISIBLE SESSION":"START VISIBLE SESSION");toggle.setOnClickListener(v->{enabled=!enabled;chip.setText(enabled?"ACTIVE":"OFF");handler.removeCallbacks(pulse);if(enabled){last=GuardianWorkShield.capture(this);appLast=GuardianAppDefense.capture(this);saveBaseline(last,appLast);GuardianAuditChain.append(this,"INFO|OBSERVATION|Work Shield visible session started");handler.post(pulse);}else GuardianAuditChain.append(this,"INFO|OBSERVATION|Work Shield visible session stopped");showHome();});content.addView(toggle);
        Button foreground=button("START OPT-IN FOREGROUND DEFENSE");foreground.setOnClickListener(v->startForegroundDefense());content.addView(foreground);Button stop=button("STOP FOREGROUND DEFENSE");stop.setOnClickListener(v->stopService(new Intent(this,GuardianForegroundService.class)));content.addView(stop);
        Button now=button("SCAN POSTURE + APPS NOW");now.setOnClickListener(v->runPostureCheck(true));content.addView(now);Button infra=button("CHECK NEO INFRASTRUCTURE");infra.setOnClickListener(v->runInfrastructureCheck());content.addView(infra);
        card("ENCRYPTED BASELINE",value(BASELINE,"No posture baseline stored yet.")+"\nApp inventory digest: "+value(APP_BASELINE,"not captured"),Color.rgb(105,169,255));card("TAMPER-EVIDENT LOCAL LEDGER",GuardianAuditChain.read(this),Color.rgb(153,168,187));}
    private void startForegroundDefense(){try{Intent i=new Intent(this,GuardianForegroundService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);GuardianAuditChain.append(this,"INFO|OBSERVATION|User opted into visible foreground defense");Toast.makeText(this,"Foreground defense active. Android shows a permanent notification with STOP.",Toast.LENGTH_LONG).show();}catch(Throwable t){Toast.makeText(this,"Foreground defense could not start on this Android configuration.",Toast.LENGTH_LONG).show();}}
    private void runPostureCheck(boolean render){GuardianWorkShield.Snapshot current=GuardianWorkShield.capture(this);GuardianAppDefense.Inventory apps=GuardianAppDefense.capture(this);List<GuardianWorkShield.Finding> findings=new ArrayList<>(GuardianWorkShield.evaluate(current,true));findings.addAll(GuardianAppDefense.compare(appLast,apps));String delta=compare(last,current);last=current;appLast=apps;saveBaseline(current,apps);GuardianWorkShield.Severity max=GuardianWorkShield.Severity.INFO;for(GuardianWorkShield.Finding f:findings){if(f.severity.ordinal()>max.ordinal())max=f.severity;String hash=GuardianAuditChain.append(this,f.severity+"|"+f.state+"|"+f.title+"|"+f.evidence);GuardianSecureStoreSafe.put(this,"last_hacker_envelope",GuardianNousEnvelope.from(f,"guardian.android",hash));}if(!"no observable posture change".equals(delta))GuardianAuditChain.append(this,"MEDIUM|SUSPICION|Posture changed|"+delta);if(max.ordinal()>=GuardianWorkShield.Severity.HIGH.ordinal())Toast.makeText(this,"Guardian detected a HIGH-risk observable. Review evidence before treating it as monitoring or compromise.",Toast.LENGTH_LONG).show();if(render){content.removeAllViews();card("POSTURE DELTA",delta,"no observable posture change".equals(delta)?Color.rgb(75,220,170):Color.rgb(255,184,77));for(GuardianWorkShield.Finding f:findings)renderFinding(f);Button back=button("BACK");back.setOnClickListener(v->showHome());content.addView(back);}}
    private void renderFinding(GuardianWorkShield.Finding f){int color=f.severity.ordinal()>=GuardianWorkShield.Severity.HIGH.ordinal()?Color.rgb(255,105,105):f.severity.ordinal()>=GuardianWorkShield.Severity.MEDIUM.ordinal()?Color.rgb(255,184,77):Color.rgb(105,169,255);card(f.severity+" • "+f.state+" • "+f.title,"1 Evidence: "+f.evidence+"\n2 Affected: "+f.affected+"\n3 Confidence: "+f.confidence+"\n4 Containment: "+f.containment+"\n5 Credential action: "+(f.rotateCredentials?"consider only after verification":"not indicated")+"\n6 Remediation: "+f.remediation+"\n7 Verification: "+f.verification+"\n8 NOUS disposition: N0 / corroboration required before attack classification",color);}
    private void runInfrastructureCheck(){chip.setText("CHECKING");new Thread(()->{List<GuardianInfrastructureHealth.Result> results=GuardianInfrastructureHealth.run();runOnUiThread(()->{content.removeAllViews();for(GuardianInfrastructureHealth.Result r:results){card((r.healthy?"HEALTHY • ":"REVIEW • ")+r.name,"URL: "+r.url+"\nHTTP: "+r.httpStatus+"\nTLS subject: "+r.certificateSubject+"\nResult: "+r.detail,r.healthy?Color.rgb(75,220,170):Color.rgb(255,184,77));GuardianAuditChain.append(this,(r.healthy?"INFO|OBSERVATION|":"MEDIUM|SUSPICION|")+r.name+"|"+r.detail);}Button back=button("BACK");back.setOnClickListener(v->{chip.setText(enabled?"ACTIVE":"OFF");showHome();});content.addView(back);});}).start();}
    private String compare(GuardianWorkShield.Snapshot a,GuardianWorkShield.Snapshot b){if(a==null||b==null)return "baseline initialized";StringBuilder d=new StringBuilder();if(a.secureLock!=b.secureLock)d.append("secureLock changed; ");if(a.adbEnabled!=b.adbEnabled)d.append("ADB changed; ");if(a.developerMode!=b.developerMode)d.append("developerMode changed; ");if(a.vpnActive!=b.vpnActive)d.append("VPN changed; ");if(!eq(a.networkType,b.networkType))d.append("network changed ").append(a.networkType).append("→").append(b.networkType).append("; ");if(!eq(a.privateDnsMode,b.privateDnsMode))d.append("Private DNS changed; ");if(!eq(a.securityPatch,b.securityPatch))d.append("security patch changed; ");return d.length()==0?"no observable posture change":d.toString();}
    private void saveBaseline(GuardianWorkShield.Snapshot s,GuardianAppDefense.Inventory apps){try{GuardianSecureStore.put(this,BASELINE,"patch="+s.securityPatch+"; lock="+s.secureLock+"; adb="+s.adbEnabled+"; dev="+s.developerMode+"; vpn="+s.vpnActive+"; network="+s.networkType+"; dns="+s.privateDnsMode);GuardianSecureStore.put(this,APP_BASELINE,apps.digest);}catch(Throwable ignored){}}
    private String value(String k,String fallback){String v=GuardianSecureStore.get(this,k);return v==null?fallback:v;}
    private void card(String title,String body,int color){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(14),dp(16),dp(14));TextView t=text(title,15,true,color),b=text(body,13,false,Color.rgb(210,220,232));b.setPadding(0,dp(6),0,0);box.addView(t);box.addView(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));content.addView(box,p);}private Button button(String label){Button b=new Button(this);b.setText(label);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,0,0,dp(12));b.setLayoutParams(p);return b;}private TextView text(String s,int size,boolean bold,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(null,1);return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private boolean eq(String a,String b){return a==null?b==null:a.equals(b);}
    private static final class GuardianSecureStoreSafe{static void put(Activity c,String k,String v){try{GuardianSecureStore.put(c,k,v);}catch(Throwable ignored){}}}
}
