export type LiveState='LIVE'|'DEGRADED'|'CONFIG_REQUIRED'|'OFFLINE'
export type LiveService={id:string;name:string;state:LiveState;detail:string;latencyMs?:number;observedAt:string}
export type BitcoinTelemetry={height:number;fastestFee?:number;halfHourFee?:number;hourFee?:number;mempoolCount?:number;mempoolVsize?:number;latencyMs:number}
export type NormalizedAssetBalance={asset:string;quantity:number;rawQuantity:number;divisible:boolean}

const env=((import.meta as ImportMeta & {env?:Record<string,string|undefined>}).env)||{}
const BITCOIN_API=(env.VITE_BITCOIN_ESPLORA_URL||'https://blockstream.info/api').replace(/\/$/,'')
const MEMPOOL_API=(env.VITE_MEMPOOL_API_URL||'https://mempool.space/api').replace(/\/$/,'')
const COUNTERPARTY_API=(env.VITE_COUNTERPARTY_API_URL||'https://api.counterparty.io:4000/v2').replace(/\/$/,'')
const LIGHTNING_HEALTH=env.VITE_LIGHTNING_HEALTH_URL
const TELECOM_HEALTH=env.VITE_TELECOM_HEALTH_URL

async function timedFetch(url:string,timeoutMs=7000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);const start=performance.now();try{const response=await fetch(url,{signal:controller.signal,headers:{accept:'application/json,text/plain;q=0.9,*/*;q=0.8'}});return{response,latencyMs:Math.round(performance.now()-start)}}finally{clearTimeout(timer)}}
export async function readBitcoinTip(){const{response,latencyMs}=await timedFetch(`${BITCOIN_API}/blocks/tip/height`);if(!response.ok)throw new Error(`Bitcoin API ${response.status}`);const height=Number(await response.text());if(!Number.isFinite(height))throw new Error('Invalid Bitcoin tip response');return{height,latencyMs}}
export async function readBitcoinTelemetry():Promise<BitcoinTelemetry>{const tip=await readBitcoinTip();let fastestFee:number|undefined,halfHourFee:number|undefined,hourFee:number|undefined,mempoolCount:number|undefined,mempoolVsize:number|undefined;try{const [feesRes,memRes]=await Promise.all([timedFetch(`${MEMPOOL_API}/v1/fees/recommended`),timedFetch(`${MEMPOOL_API}/mempool`)]);if(feesRes.response.ok){const f=await feesRes.response.json() as Record<string,number>;fastestFee=f.fastestFee;halfHourFee=f.halfHourFee;hourFee=f.hourFee}if(memRes.response.ok){const m=await memRes.response.json() as {count?:number;vsize?:number};mempoolCount=m.count;mempoolVsize=m.vsize}}catch{}return{...tip,fastestFee,halfHourFee,hourFee,mempoolCount,mempoolVsize}}
export async function readBitcoinAddress(address:string){const{response,latencyMs}=await timedFetch(`${BITCOIN_API}/address/${encodeURIComponent(address)}`);if(!response.ok)throw new Error(`Bitcoin address API ${response.status}`);const data=await response.json() as {chain_stats?:{funded_txo_sum?:number;spent_txo_sum?:number;tx_count?:number},mempool_stats?:{funded_txo_sum?:number;spent_txo_sum?:number;tx_count?:number}};const chain=data.chain_stats||{},mempool=data.mempool_stats||{};return{confirmedSats:(chain.funded_txo_sum||0)-(chain.spent_txo_sum||0),unconfirmedSats:(mempool.funded_txo_sum||0)-(mempool.spent_txo_sum||0),txCount:(chain.tx_count||0)+(mempool.tx_count||0),latencyMs}}
export async function readCounterpartyBalances(address:string){const{response,latencyMs}=await timedFetch(`${COUNTERPARTY_API}/addresses/${encodeURIComponent(address)}/balances`);if(!response.ok)throw new Error(`Counterparty API ${response.status}`);const payload=await response.json() as {result?:any[]}|any[];const rows=Array.isArray(payload)?payload:Array.isArray(payload.result)?payload.result:[];const balances:NormalizedAssetBalance[]=rows.map((row:any)=>{const asset=String(row.asset||row.asset_info?.asset||'UNKNOWN');const raw=Number(row.quantity??row.quantity_normalized??0);const divisible=row.asset_info?.divisible!==false;const normalized=typeof row.quantity_normalized==='number'?row.quantity_normalized:(divisible?raw/1e8:raw);return{asset,quantity:normalized,rawQuantity:raw,divisible}});return{balances,latencyMs}}
async function checkBitcoin():Promise<LiveService>{const observedAt=new Date().toISOString();try{const r=await readBitcoinTelemetry();return{id:'btc',name:'Bitcoin / Esplora',state:'LIVE',detail:`Tip ${r.height.toLocaleString()}${r.fastestFee?` · ${r.fastestFee} sat/vB fast`:''}`,latencyMs:r.latencyMs,observedAt}}catch(error){return{id:'btc',name:'Bitcoin / Esplora',state:'OFFLINE',detail:error instanceof Error?error.message:'Bitcoin read failed',observedAt}}}
async function checkCounterparty():Promise<LiveService>{const observedAt=new Date().toISOString();try{const{response,latencyMs}=await timedFetch(`${COUNTERPARTY_API}/healthz`);if(!response.ok)throw new Error(`Counterparty API ${response.status}`);return{id:'xcp',name:'Counterparty Core v2',state:'LIVE',detail:'Read-only API health check passed',latencyMs,observedAt}}catch(error){return{id:'xcp',name:'Counterparty Core v2',state:'DEGRADED',detail:`Set VITE_COUNTERPARTY_API_URL for a reachable node. ${error instanceof Error?error.message:''}`.trim(),observedAt}}}
async function checkOptional(id:string,name:string,url:string|undefined):Promise<LiveService>{const observedAt=new Date().toISOString();if(!url)return{id,name,state:'CONFIG_REQUIRED',detail:`Set ${id==='ln'?'VITE_LIGHTNING_HEALTH_URL':'VITE_TELECOM_HEALTH_URL'} to enable live health`,observedAt};try{const{response,latencyMs}=await timedFetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);return{id,name,state:'LIVE',detail:'Credential-gated health endpoint reachable',latencyMs,observedAt}}catch(error){return{id,name,state:'OFFLINE',detail:error instanceof Error?error.message:'Health check failed',observedAt}}}
export async function getLiveNetworkSnapshot():Promise<LiveService[]>{return Promise.all([checkBitcoin(),checkCounterparty(),checkOptional('ln','Lightning Node',LIGHTNING_HEALTH),checkOptional('telco','Telecom / SIP-SMS-IVR',TELECOM_HEALTH),Promise.resolve({id:'world',name:'World Currency Layer',state:'LIVE' as const,detail:'Quote/display adapter active; settlement remains disabled',observedAt:new Date().toISOString()}),Promise.resolve({id:'nvsn',name:'NVSN Bridge',state:'LIVE' as const,detail:'Software routing boundary active; no radio control',observedAt:new Date().toISOString()})])}
