import { createRemoteJWKSet, jwtVerify } from 'jose';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const now=()=>new Date().toISOString();
const norm=s=>String(s||'').trim();
const allowedTypes=new Set(['PERSON','ORGANIZATION','MODULE','PROJECT','CASE','TASK','DECISION','POLICY','DOCUMENT','SYSTEM','OFFICE','EVENT']);
async function authorize(request,env){if(!env.ACCESS_TEAM_DOMAIN||!env.ACCESS_AUD)return{ok:false,status:503,message:'NEOsync memory access is not configured.'};const token=request.headers.get('CF-Access-Jwt-Assertion');if(!token)return{ok:false,status:401,message:'Authentication required.'};try{const issuer=`https://${env.ACCESS_TEAM_DOMAIN}`;const jwks=createRemoteJWKSet(new URL(`${issuer}/cdn-cgi/access/certs`));const{payload}=await jwtVerify(token,jwks,{issuer,audience:env.ACCESS_AUD});const email=String(payload.email||request.headers.get('Cf-Access-Authenticated-User-Email')||'').toLowerCase();const allow=String(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(allow.length&&!allow.includes(email))return{ok:false,status:403,message:'Executive authorization required.'};return{ok:true,email,payload}}catch{return{ok:false,status:401,message:'Invalid or expired access session.'}}}
export class MemoryGraphStore{
  constructor(state){this.storage=state.storage}
  async entity(id){return this.storage.get(`entity:${id}`)}
  async entities(){return[...(await this.storage.list({prefix:'entity:'})).values()]}
  async edges(){return[...(await this.storage.list({prefix:'edge:'})).values()]}
  async events(){return[...(await this.storage.list({prefix:'event:'})).values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,200)}
  async upsertEntity(b,actor){const id=norm(b.id)||crypto.randomUUID(),type=String(b.type||'').toUpperCase();if(!allowedTypes.has(type))throw Object.assign(new Error('Invalid entity type.'),{status:400});const prior=await this.entity(id);const row={id,type,name:norm(b.name||prior?.name).slice(0,240),aliases:Array.isArray(b.aliases)?b.aliases.slice(0,20):prior?.aliases||[],summary:String(b.summary??prior?.summary??'').slice(0,6000),status:norm(b.status||prior?.status||'ACTIVE').toUpperCase(),source:b.source??prior?.source??null,metadata:{...(prior?.metadata||{}),...(b.metadata||{})},createdAt:prior?.createdAt||now(),createdBy:prior?.createdBy||actor,updatedAt:now(),updatedBy:actor};if(!row.name)throw Object.assign(new Error('Entity name required.'),{status:400});await this.storage.put(`entity:${id}`,row);await this.log(actor,'ENTITY_UPSERT',id,row.name);return row}
  async addEdge(b,actor){const from=norm(b.from),to=norm(b.to),relation=norm(b.relation).toUpperCase();if(!from||!to||!relation)throw Object.assign(new Error('from, to, and relation are required.'),{status:400});if(!(await this.entity(from))||!(await this.entity(to)))throw Object.assign(new Error('Both edge endpoints must exist.'),{status:404});const id=norm(b.id)||crypto.randomUUID(),row={id,from,to,relation,label:norm(b.label||relation),confidence:Number.isFinite(Number(b.confidence))?Math.max(0,Math.min(1,Number(b.confidence))):1,source:b.source||null,metadata:b.metadata||{},createdAt:now(),createdBy:actor};await this.storage.put(`edge:${id}`,row);await this.log(actor,'EDGE_CREATE',id,`${from} ${relation} ${to}`);return row}
  async log(actor,action,target,note=''){const row={id:crypto.randomUUID(),actor,action,target,note:String(note).slice(0,3000),createdAt:now()};await this.storage.put(`event:${Date.now()}:${row.id}`,row);return row}
  async search(q){const terms=norm(q).toLowerCase().split(/\s+/).filter(Boolean);const rows=await this.entities();return rows.map(e=>{const hay=[e.name,...(e.aliases||[]),e.summary,e.type,e.status,JSON.stringify(e.metadata||{})].join(' ').toLowerCase();const score=terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0);return{...e,_score:score}}).filter(e=>!terms.length||e._score>0).sort((a,b)=>b._score-a._score||String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,50).map(({_score,...e})=>e)}
  async neighbors(id,depth=1){const entities=Object.fromEntries((await this.entities()).map(e=>[e.id,e])),edges=await this.edges();const seen=new Set([id]);let frontier=[id];for(let d=0;d<Math.max(1,Math.min(3,depth));d++){const next=[];for(const edge of edges){if(frontier.includes(edge.from)&&!seen.has(edge.to)){seen.add(edge.to);next.push(edge.to)}if(frontier.includes(edge.to)&&!seen.has(edge.from)){seen.add(edge.from);next.push(edge.from)}}frontier=next}return{entities:[...seen].map(x=>entities[x]).filter(Boolean),edges:edges.filter(e=>seen.has(e.from)&&seen.has(e.to))}}
  async context(ids=[]){const all=await this.entities(),edges=await this.edges();const selected=ids.length?new Set(ids):new Set(all.filter(e=>['ACTIVE','OPEN','IN_PROGRESS','REVIEW','HOLD'].includes(e.status)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,40).map(e=>e.id));for(const edge of edges){if(selected.has(edge.from))selected.add(edge.to);if(selected.has(edge.to))selected.add(edge.from)}return{generatedAt:now(),entities:all.filter(e=>selected.has(e.id)).slice(0,80),edges:edges.filter(e=>selected.has(e.from)&&selected.has(e.to)).slice(0,160)}}
  async fetch(request){const u=new URL(request.url),actor=request.headers.get('x-neo-actor')||'unknown';try{
    if(request.method==='GET'&&u.pathname==='/entities')return json({entities:await this.entities()});
    if(request.method==='POST'&&u.pathname==='/entities')return json({ok:true,entity:await this.upsertEntity(await request.json(),actor)},201);
    if(request.method==='POST'&&u.pathname==='/edges')return json({ok:true,edge:await this.addEdge(await request.json(),actor)},201);
    if(request.method==='GET'&&u.pathname==='/search')return json({results:await this.search(u.searchParams.get('q')||'')});
    const gm=u.pathname.match(/^\/graph\/([^/]+)$/);if(request.method==='GET'&&gm)return json(await this.neighbors(decodeURIComponent(gm[1]),Number(u.searchParams.get('depth')||1)));
    if(request.method==='GET'&&u.pathname==='/context')return json(await this.context((u.searchParams.get('ids')||'').split(',').filter(Boolean)));
    if(request.method==='GET'&&u.pathname==='/events')return json({events:await this.events()});
    return json({error:'Memory graph route not found.'},404);
  }catch(e){return json({error:e.message},e.status||400)}}
}
function stub(env,actor){const id=env.MEMORY_GRAPH.idFromName('neo-operational-memory'),s=env.MEMORY_GRAPH.get(id);return path=>s.fetch(new Request(`https://memory${path}`,{headers:{'x-neo-actor':actor}}))}
async function call(env,actor,path,init={}){const id=env.MEMORY_GRAPH.idFromName('neo-operational-memory'),s=env.MEMORY_GRAPH.get(id);return s.fetch(new Request(`https://memory${path}`,{method:init.method||'GET',headers:{'content-type':'application/json','x-neo-actor':actor},body:init.body?JSON.stringify(init.body):undefined}))}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return json({ok:true,service:'neo-memory-graph',version:'1.0',capabilities:['entities','relationships','search','traversal','context','audit']});const a=await authorize(request,env);if(!a.ok)return json({ok:false,error:a.message},a.status);if(u.pathname.startsWith('/api/')){const path=u.pathname.slice(4)+u.search;const r=await call(env,a.email,path,{method:request.method,body:['GET','HEAD'].includes(request.method)?undefined:await request.json()});return new Response(r.body,{status:r.status,headers:{'content-type':'application/json','cache-control':'no-store'}})}if(u.pathname==='/'||u.pathname==='/memory')return new Response('<!doctype html><meta charset="utf-8"><title>NEOsync Operational Memory</title><style>body{background:#050807;color:#eaffef;font-family:system-ui;max-width:900px;margin:40px auto;padding:20px}code{color:#7cff9b}.card{border:1px solid #26422f;background:#0b120e;padding:18px;border-radius:16px}</style><div class="card"><h1>NEOsync Operational Memory + Executive Knowledge Graph</h1><p>Authenticated private service is online.</p><p>Use <code>/api/search?q=...</code>, <code>/api/graph/&lt;entity-id&gt;</code>, and <code>/api/context</code> from authorized NEOsync services.</p><p>State changes require authenticated API calls. This service stores operational relationships and audit metadata; it does not itself execute financial, legal, enforcement, or custody actions.</p></div>',{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex,nofollow'}});return json({error:'Not found'},404)}};
