import {createHash,randomUUID} from 'node:crypto'
import {requireRole,audit} from './service.mjs'

const isoDay=v=>new Date(v).toISOString().slice(0,10)
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}
const day=d=>d.toISOString().slice(0,10)
export function isBusinessDay(date,holidays=[]){const d=typeof date==='string'?parse(date):date,n=d.getUTCDay();return n!==0&&n!==6&&!holidays.includes(day(d))}
export function addPolicyDays(start,count,{businessDays=false,holidays=[]}={}){let d=parse(isoDay(start)),added=0;while(added<count){d.setUTCDate(d.getUTCDate()+1);if(!businessDays||isBusinessDay(d,holidays))added++}return day(d)}
export function calculateDeadline({triggerAt,days,businessDays=false,holidays=[]}){if(!triggerAt||!Number.isInteger(days)||days<0)throw new Error('triggerAt and non-negative integer days required');return addPolicyDays(triggerAt,days,{businessDays,holidays})}
export function ruleFingerprint(rule){return hash({name:rule.name,jurisdiction:rule.jurisdiction,procedure:rule.procedure,days:rule.days,businessDays:!!rule.businessDays,holidays:rule.holidays||[],authority:rule.authority||null})}
export function createRuleProfile(db,service,principal,workspaceId,input){requireRole(db,workspaceId,principal.userId,'JUDGE');if(!input.name||!input.jurisdiction||!input.procedure)throw new Error('name, jurisdiction and procedure required');const id=input.id||randomUUID(),now=new Date().toISOString(),rule={...input,id,holidays:input.holidays||[]};const fingerprint=ruleFingerprint(rule);db.prepare(`INSERT INTO service_rule_profiles(id,workspace_id,name,jurisdiction,procedure,days,business_days,holidays_json,authority_json,rule_fingerprint,enabled,created_by,updated_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,workspaceId,input.name,input.jurisdiction,input.procedure,input.days||0,input.businessDays?1:0,JSON.stringify(rule.holidays),JSON.stringify(input.authority||null),fingerprint,input.enabled===false?0:1,principal.userId,now,now);audit(db,workspaceId,principal.userId,'SERVICE_RULE_CREATED',{id,fingerprint});return {...rule,fingerprint,enabled:input.enabled!==false,createdAt:now}}
export function listRuleProfiles(db,principal,workspaceId){requireRole(db,workspaceId,principal.userId,'VIEWER');return db.prepare(`SELECT * FROM service_rule_profiles WHERE workspace_id=? ORDER BY created_at DESC`).all(workspaceId).map(r=>({id:r.id,name:r.name,jurisdiction:r.jurisdiction,procedure:r.procedure,days:r.days,businessDays:!!r.business_days,holidays:JSON.parse(r.holidays_json),authority:JSON.parse(r.authority_json||'null'),fingerprint:r.rule_fingerprint,enabled:!!r.enabled,createdAt:r.created_at}))}
export function recomputeRecipientDeadline(db,service,principal,workspaceId,{recipientId,ruleId,triggerAt}){requireRole(db,workspaceId,principal.userId,'CLERK');const rule=db.prepare(`SELECT * FROM service_rule_profiles WHERE id=? AND workspace_id=? AND enabled=1`).get(ruleId,workspaceId);if(!rule)throw new Error('Enabled rule profile not found');const recipient=db.prepare(`SELECT * FROM service_recipients WHERE id=? AND workspace_id=?`).get(recipientId,workspaceId);if(!recipient)throw new Error('Service recipient not found');const deadlineAt=calculateDeadline({triggerAt,days:rule.days,businessDays:!!rule.business_days,holidays:JSON.parse(rule.holidays_json)});db.prepare(`UPDATE service_recipients SET deadline_at=?,updated_at=? WHERE id=?`).run(deadlineAt,new Date().toISOString(),recipientId);audit(db,workspaceId,principal.userId,'SERVICE_DEADLINE_RECOMPUTED',{recipientId,ruleId,triggerAt,deadlineAt,ruleFingerprint:rule.rule_fingerprint});return {recipientId,ruleId,triggerAt,deadlineAt,ruleFingerprint:rule.rule_fingerprint}}
export function recordAlternateServiceDecision(db,service,principal,workspaceId,input){requireRole(db,workspaceId,principal.userId,'JUDGE');if(!input.recipientId||!input.decision)throw new Error('recipientId and decision required');const id=randomUUID(),now=new Date().toISOString(),record={id,workspaceId,recipientId:input.recipientId,decision:input.decision,method:input.method||null,reason:input.reason||'',authority:input.authority||null,approvedBy:principal.userId,createdAt:now};record.fingerprint=hash(record);db.prepare(`INSERT INTO alternate_service_decisions(id,workspace_id,recipient_id,decision,method,reason,authority_json,approved_by,fingerprint,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,workspaceId,input.recipientId,input.decision,input.method||null,input.reason||'',JSON.stringify(input.authority||null),principal.userId,record.fingerprint,now);audit(db,workspaceId,principal.userId,'ALTERNATE_SERVICE_DECISION',{id,recipientId:input.recipientId,decision:input.decision,fingerprint:record.fingerprint});return record}
export function listAlternateServiceDecisions(db,principal,workspaceId,recipientId=''){requireRole(db,workspaceId,principal.userId,'VIEWER');const rows=recipientId?db.prepare(`SELECT * FROM alternate_service_decisions WHERE workspace_id=? AND recipient_id=? ORDER BY created_at DESC`).all(workspaceId,recipientId):db.prepare(`SELECT * FROM alternate_service_decisions WHERE workspace_id=? ORDER BY created_at DESC`).all(workspaceId);return rows.map(r=>({...r,authority:JSON.parse(r.authority_json||'null')}))}
