import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {TribunalService} from './service.mjs'
import {queueCommunication,saveProviderConfig} from './communications.mjs'
import {acknowledgeProviderReceipt,adapterStatus,runCommunicationWorker} from './providerWorkers.mjs'

function db(){const d=new DatabaseSync(':memory:');d.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE memberships(workspace_id TEXT NOT NULL REFERENCES workspaces(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(workspace_id,user_id));
CREATE TABLE invitations(token_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),email TEXT NOT NULL,role TEXT NOT NULL,expires_at TEXT NOT NULL,accepted_at TEXT,invited_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE communication_templates(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,name TEXT NOT NULL,channel TEXT NOT NULL,subject_template TEXT NOT NULL,body_template TEXT NOT NULL,created_by TEXT NOT NULL,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE provider_configs(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,provider_type TEXT NOT NULL,label TEXT NOT NULL,config_envelope TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE communication_outbox(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,notice_id TEXT,channel TEXT NOT NULL,destination TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT,last_error TEXT,provider_ref TEXT,receipt_json TEXT,created_by TEXT NOT NULL,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE audit_log(seq INTEGER PRIMARY KEY AUTOINCREMENT,workspace_id TEXT NOT NULL,actor_user_id TEXT NOT NULL,action TEXT NOT NULL,subject TEXT NOT NULL,payload_hash TEXT NOT NULL,previous_hash TEXT,entry_hash TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);`);return d}
function setup(){process.env.NEO_TRIBUNAL_MASTER_KEY='test-master-key';process.env.NEO_TRIBUNAL_RECEIPT_KEY='receipt-key';const service=new TribunalService(db());service.register({email:'chief@example.test',displayName:'Chief',password:'very-secure-1'});const principal=service.principal(service.login({email:'chief@example.test',password:'very-secure-1'}).token);const ws=service.createWorkspace(principal,{name:'Global District'});return{service,principal,ws,db:service.db}}

test('worker completes local record and holds external delivery at provider boundary',()=>{const {service,principal,ws,db}=setup();queueCommunication(db,service,principal,ws.id,{channel:'RECORD',destination:'record',body:'internal'});saveProviderConfig(db,service,principal,ws.id,{providerType:'SMTP',label:'Primary SMTP',enabled:true,secretConfig:{host:'smtp.example.test'}});const email=queueCommunication(db,service,principal,ws.id,{channel:'EMAIL',destination:'person@example.test',body:'notice'});const run=runCommunicationWorker(db,service,principal,ws.id,{limit:10});assert.equal(run.processed,2);const stored=db.prepare('SELECT * FROM communication_outbox WHERE id=?').get(email.id);assert.equal(stored.status,'AWAITING_PROVIDER');assert.match(stored.provider_ref,/^smtp:/);const adapters=adapterStatus(db,service,principal,ws.id);assert.equal(adapters.find(a=>a.type==='SMTP').ready,true)})

test('provider acknowledgement creates signed receipt',()=>{const {service,principal,ws,db}=setup();saveProviderConfig(db,service,principal,ws.id,{providerType:'WEBHOOK',label:'Webhook',enabled:true,secretConfig:{url:'https://example.test'}});const item=queueCommunication(db,service,principal,ws.id,{channel:'WEBHOOK',destination:'https://example.test',body:'payload'});runCommunicationWorker(db,service,principal,ws.id,{});const receipt=acknowledgeProviderReceipt(db,service,principal,ws.id,item.id,{outcome:'DELIVERED',receipt:{code:200}});assert.equal(receipt.status,'DELIVERED');assert.equal(receipt.receipt.algorithm,'HMAC-SHA256');assert.equal(receipt.receipt.signature.length,64)})
