import test from 'node:test'
import assert from 'node:assert/strict'
import {openTribunalDb} from './db.mjs'
import {TribunalService} from './service.mjs'
import {ensurePublicRecordsSchema,publishPublicRecord} from './publicRecords.mjs'
import {ensurePublicDocketSchema,listPublicDocket,listWorkspaceDocket,publicCaseDocket,publishDocketEvent,withdrawDocketEvent} from './publicDocket.mjs'

const setup=()=>{process.env.NEO_TRIBUNAL_MASTER_KEY='public-docket-test-master-key-1234567890';const db=openTribunalDb(':memory:');ensurePublicRecordsSchema(db);ensurePublicDocketSchema(db);const service=new TribunalService(db);service.register({email:'clerk-test@example.test',displayName:'Judge',password:'password123'});const principal=service.principal(service.login({email:'clerk-test@example.test',password:'password123'}).token);const workspace=service.createWorkspace(principal,{name:'World Interfaith Court'});return {db,service,principal,workspace}}

test('published records can anchor a public docket chronology',()=>{const {db,service,principal,workspace}=setup();const record=publishPublicRecord(db,service,principal,workspace.id,{claimNo:'WIC-2026-013',recordType:'ORDER',title:'Scheduling Order',summary:'Public scheduling order.',publicPayload:{hearingDate:'2026-10-12'}});const event=publishDocketEvent(db,service,principal,workspace.id,{claimNo:'WIC-2026-013',eventKind:'ORDER',eventDate:'2026-09-24T12:00:00Z',title:'Scheduling Order Entered',summary:'Scheduling order entered on the public docket.',publicRecordId:record.recordId});assert.equal(event.claimNo,'WIC-2026-013');assert.equal(event.fingerprint.length,64);assert.equal(listPublicDocket(db,{claimNo:'WIC-2026-013'}).length,1);assert.equal(publicCaseDocket(db,'WIC-2026-013').orders.length,1);assert.equal(service.verifyAudit(workspace.id).valid,true);assert.equal(db.prepare('SELECT MAX(version) version FROM schema_meta').get().version,8)})

test('withdrawn docket events leave the administrative ledger but disappear publicly',()=>{const {db,service,principal,workspace}=setup();const event=publishDocketEvent(db,service,principal,workspace.id,{claimNo:'WIC-2026-014',eventKind:'NOTICE',eventDate:'2026-09-24',title:'Notice',summary:'Public notice.'});withdrawDocketEvent(db,service,principal,workspace.id,event.eventId);assert.equal(listPublicDocket(db,{claimNo:'WIC-2026-014'}).length,0);assert.equal(listWorkspaceDocket(db,service,principal,workspace.id,'WITHDRAWN').length,1);assert.throws(()=>publicCaseDocket(db,'WIC-2026-014'),/not found/)})

test('docket rejects cross-claim public-record linkage',()=>{const {db,service,principal,workspace}=setup();const record=publishPublicRecord(db,service,principal,workspace.id,{claimNo:'WIC-A',recordType:'ORDER',title:'Order',summary:'Order.'});assert.throws(()=>publishDocketEvent(db,service,principal,workspace.id,{claimNo:'WIC-B',eventKind:'ORDER',eventDate:'2026-09-24',title:'Wrong link',summary:'Mismatch.',publicRecordId:record.recordId}),/mismatch/)})
