import test from 'node:test'
import assert from 'node:assert/strict'
import {openTribunalDb} from './db.mjs'
import {TribunalService} from './service.mjs'
import {buildServicePackage,communicationsAuditBundle,providerHealth,queueNoticeService} from './serviceNotice.mjs'

function setup(){process.env.NEO_TRIBUNAL_MASTER_KEY='test-master-key';const db=openTribunalDb(':memory:'),service=new TribunalService(db);service.register({email:'chief@example.test',displayName:'Chief',password:'very-secure-1'});const principal=service.principal(service.login({email:'chief@example.test',password:'very-secure-1'}).token),ws=service.createWorkspace(principal,{name:'Global District'});return{db,service,principal,ws}}

test('v1.4 builds hearing-linked service packages and queues multi-channel notice service',()=>{const{db,service,principal,ws}=setup();const notice=service.saveNotice(principal,ws.id,{claimNo:'WT-1401',subject:'Notice of Hearing',body:'You are hereby notified.',status:'DRAFT'});const hearing=service.saveHearing(principal,ws.id,{claimNo:'WT-1401',startsAt:'2026-09-10T15:00:00Z',durationMinutes:45,location:'World Interfaith Tribunal'});const packet=buildServicePackage(db,service,principal,ws.id,{noticeId:notice.noticeId,hearingId:hearing.hearingId});assert.equal(packet.claimNo,'WT-1401');assert.equal(packet.calendar.format,'ICS');assert.equal(packet.payloadHash.length,64);const queued=queueNoticeService(db,service,principal,ws.id,{noticeId:notice.noticeId,hearingId:hearing.hearingId,destinations:[{channel:'RECORD',destination:'case-record'},{channel:'EMAIL',destination:'respondent@example.test'}]});assert.equal(queued.queued.length,2);assert.equal(db.prepare('SELECT COUNT(*) n FROM communication_outbox WHERE notice_id=?').get(notice.noticeId).n,2);const bundle=communicationsAuditBundle(db,service,principal,ws.id,{noticeId:notice.noticeId});assert.equal(bundle.entries.length,2);assert.equal(bundle.payloadHash.length,64)})

test('v1.4 provider health reports enabled configs and queue pressure',()=>{const{db,service,principal,ws}=setup();db.prepare('INSERT INTO provider_configs(id,workspace_id,provider_type,label,config_envelope,enabled,created_by,updated_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run('smtp-1',ws.id,'SMTP','Primary SMTP',JSON.stringify({iv:'AA==',tag:'AA==',data:'AA=='}),1,principal.userId,new Date().toISOString(),new Date().toISOString());const health=providerHealth(db,service,principal,ws.id);assert.equal(health.providers.length,1);assert.equal(health.providers[0].type,'SMTP');assert.equal(health.providers[0].enabled,true)})
