import {createServer} from 'node:http'
import {openTribunalDb} from './db.mjs'
import {TribunalService} from './service.mjs'
import {changePassword,consumePasswordReset,issuePasswordReset,listDeliveries,operationalReport,recordDelivery} from './adminOps.mjs'
import {communicationsReport,createTemplate,hearingIcs,listOutbox,listProviderConfigs,listTemplates,processCommunication,queueCommunication,retryDeadLetter,saveProviderConfig} from './communications.mjs'
import {acknowledgeProviderReceipt,adapterStatus,runCommunicationWorker} from './providerWorkers.mjs'
import {buildServicePackage,communicationsAuditBundle,providerHealth,queueNoticeService,verifyProviderCallback} from './serviceNotice.mjs'
import {issueProofOfService,listProofs,listServiceRecipients,recordServiceAttempt,registerServiceRecipient,serviceCompliance,verifyServiceLedger} from './serviceLedger.mjs'
import {alternateServicePlan,buildProofPacket,evaluateServiceEscalations,serviceTimeline} from './serviceCompliance.mjs'
import {complianceRecommendations,syncCommunicationReceipts} from './serviceComplianceSync.mjs'
import {createRuleProfile,listRuleProfiles,recomputeRecipientDeadline,recordAlternateServiceDecision,listAlternateServiceDecisions} from './deadlinePolicy.mjs'
import {claimPublicIntake,ensurePublicIntakeSchema,listPublicIntakes,promotePublicIntake,submitPublicIntake} from './publicIntake.mjs'
import {ensurePublicRecordsSchema,getPublishedRecord,listPublishedRecords,listWorkspacePublicRecords,publishPublicRecord,withdrawPublicRecord} from './publicRecords.mjs'
const db=openTribunalDb(),service=new TribunalService(db),port=Number(process.env.PORT||8787),hits=new Map(),intakeHits=new Map()
ensurePublicIntakeSchema(db)
ensurePublicRecordsSchema(db)
function json(res,status,body,headers={}){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type,x-neo-signature','access-control-allow-methods':'GET,POST,PUT,PATCH,OPTIONS',...headers});res.end(typeof body==='string'?body:JSON.stringify(body))}
function html(res,status,content){res.writeHead(status,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});res.end(content)}
async function body(req){const chunks=[];for await(const chunk of req){chunks.push(chunk);if(chunks.reduce((n,c)=>n+c.length,0)>65536)throw new Error('Request body too large.')}if(!chunks.length)return {};const raw=Buffer.concat(chunks).toString('utf8'),type=String(req.headers['content-type']||'').split(';')[0].trim().toLowerCase();if(type==='application/x-www-form-urlencoded')return Object.fromEntries(new URLSearchParams(raw));return JSON.parse(raw)}
const token=req=>String(req.headers.authorization||'').replace(/^Bearer\s+/i,'')
const sourceIp=req=>String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()
function match(path,pattern){const a=path.split('/').filter(Boolean),b=pattern.split('/').filter(Boolean);if(a.length!==b.length)return null;const p={};for(let i=0;i<b.length;i++){if(b[i].startsWith(':'))p[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return null}return p}
function rateLimit(req){const id=`${sourceIp(req)}:${Math.floor(Date.now()/60000)}`,n=(hits.get(id)||0)+1;hits.set(id,n);return n<=240}
function intakeRateLimit(req){const id=`${sourceIp(req)}:${Math.floor(Date.now()/600000)}`,n=(intakeHits.get(id)||0)+1;intakeHits.set(id,n);return n<=6}
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const receiptHtml=receipt=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>World Interfaith Court Intake Receipt</title><style>body{font-family:system-ui,sans-serif;max-width:760px;margin:4rem auto;padding:0 1.25rem;line-height:1.55}code{overflow-wrap:anywhere}a{color:inherit}</style></head><body><h1>World Interfaith Court Intake Receipt</h1><p>Your submission has entered the institutional review queue.</p><p><strong>Receipt:</strong> ${escapeHtml(receipt.receiptCode)}</p><p><strong>Status:</strong> ${escapeHtml(receipt.status)}</p><p><strong>Payload SHA-256:</strong> <code>${escapeHtml(receipt.payloadHash)}</code></p><p>${escapeHtml(receipt.boundary)}</p><p><a href="https://holytemples.org/world-interfaith-court/">Return to the World Interfaith Court</a></p></body></html>`
const server=createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});if(!rateLimit(req))return json(res,429,{error:'Rate limit exceeded.'});const url=new URL(req.url,'http://localhost');try{
if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,service:'neo-tribunal-backend',version:'1.12',schema:7,time:new Date().toISOString(),communicationsWorker:'scheduler-ready',serviceAutomation:'ready',serviceLedger:'hash-chained',serviceCompliance:'console-ready',deadlinePolicy:'ready',publicIntake:'moderated',publicRecords:'neo-pacer-live'})
if(req.method==='POST'&&url.pathname==='/v1/public/intake'){if(!intakeRateLimit(req))return json(res,429,{error:'Public intake rate limit exceeded.'});const input=await body(req),receipt=submitPublicIntake(db,input,{sourceIp:sourceIp(req),userAgent:req.headers['user-agent']||''});const wantsHtml=String(req.headers.accept||'').includes('text/html')||String(req.headers['content-type']||'').startsWith('application/x-www-form-urlencoded');return wantsHtml?html(res,201,receiptHtml(receipt)):json(res,201,receipt)}
if(req.method==='GET'&&url.pathname==='/v1/public/records')return json(res,200,{items:listPublishedRecords(db,{q:url.searchParams.get('q')||'',claimNo:url.searchParams.get('claimNo')||'',recordType:url.searchParams.get('recordType')||'',limit:url.searchParams.get('limit')||100})});let publicMatch=match(url.pathname,'/v1/public/records/:recordId');if(publicMatch&&req.method==='GET')return json(res,200,getPublishedRecord(db,publicMatch.recordId))
if(req.method==='POST'&&url.pathname==='/v1/auth/register')return json(res,201,service.register(await body(req)));if(req.method==='POST'&&url.pathname==='/v1/auth/login')return json(res,200,service.login(await body(req)));if(req.method==='POST'&&url.pathname==='/v1/auth/reset/consume')return json(res,200,consumePasswordReset(db,await body(req)));if(req.method==='POST'&&url.pathname==='/v1/auth/logout'){service.logout(token(req));return json(res,200,{ok:true})}const principal=service.principal(token(req));if(req.method==='POST'&&url.pathname==='/v1/auth/password')return json(res,200,changePassword(db,principal,await body(req)));if(req.method==='GET'&&url.pathname==='/v1/workspaces')return json(res,200,{items:service.listWorkspaces(principal)});if(req.method==='POST'&&url.pathname==='/v1/workspaces')return json(res,201,service.createWorkspace(principal,await body(req)));if(req.method==='POST'&&url.pathname==='/v1/invitations/accept')return json(res,200,service.acceptInvite(principal,(await body(req)).token));let p
p=match(url.pathname,'/v1/workspaces/:workspaceId/invitations');if(p&&req.method==='POST')return json(res,201,service.invite(principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/members');if(p&&req.method==='GET')return json(res,200,{items:service.listMembers(principal,p.workspaceId)});p=match(url.pathname,'/v1/workspaces/:workspaceId/members/:userId');if(p&&req.method==='PATCH')return json(res,200,service.setMemberRole(principal,p.workspaceId,p.userId,(await body(req)).role));p=match(url.pathname,'/v1/workspaces/:workspaceId/password-resets');if(p&&req.method==='POST')return json(res,201,issuePasswordReset(db,service,principal,p.workspaceId,await body(req)))
p=match(url.pathname,'/v1/workspaces/:workspaceId/intakes');if(p&&req.method==='GET')return json(res,200,{items:listPublicIntakes(db,service,principal,p.workspaceId,url.searchParams.get('status')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/intakes/:intakeId/claim');if(p&&req.method==='POST')return json(res,200,claimPublicIntake(db,service,principal,p.workspaceId,p.intakeId));p=match(url.pathname,'/v1/workspaces/:workspaceId/intakes/:intakeId/promote');if(p&&req.method==='POST')return json(res,201,promotePublicIntake(db,service,principal,p.workspaceId,p.intakeId,await body(req)))
p=match(url.pathname,'/v1/workspaces/:workspaceId/public-records');if(p&&req.method==='POST')return json(res,201,publishPublicRecord(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listWorkspacePublicRecords(db,service,principal,p.workspaceId,url.searchParams.get('status')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/public-records/:recordId/withdraw');if(p&&req.method==='POST')return json(res,200,withdrawPublicRecord(db,service,principal,p.workspaceId,p.recordId))
p=match(url.pathname,'/v1/workspaces/:workspaceId/cases');if(p&&req.method==='GET')return json(res,200,{items:service.listCases(principal,p.workspaceId,url.searchParams.get('q')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/cases/:claimNo');if(p&&req.method==='GET')return json(res,200,service.getCase(principal,p.workspaceId,p.claimNo));if(p&&req.method==='PUT'){const i=await body(req);return json(res,200,service.saveCase(principal,p.workspaceId,{...i.caseFile,claimNo:p.claimNo},i.expectedRevision))}
p=match(url.pathname,'/v1/workspaces/:workspaceId/efiles');if(p&&req.method==='POST')return json(res,201,service.fileEFile(principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:service.listEFiles(principal,p.workspaceId,url.searchParams.get('claimNo')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/notices');if(p&&req.method==='POST')return json(res,201,service.saveNotice(principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:service.listNotices(principal,p.workspaceId,url.searchParams.get('claimNo')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/hearings');if(p&&req.method==='POST')return json(res,201,service.saveHearing(principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:service.listHearings(principal,p.workspaceId,url.searchParams.get('claimNo')||'')})
p=match(url.pathname,'/v1/workspaces/:workspaceId/deliveries');if(p&&req.method==='POST')return json(res,201,recordDelivery(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listDeliveries(db,service,principal,p.workspaceId,url.searchParams.get('noticeId')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/reports/operations');if(p&&req.method==='GET')return json(res,200,operationalReport(db,service,principal,p.workspaceId))
p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/templates');if(p&&req.method==='POST')return json(res,201,createTemplate(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listTemplates(db,service,principal,p.workspaceId)});p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/providers');if(p&&req.method==='POST')return json(res,201,saveProviderConfig(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listProviderConfigs(db,service,principal,p.workspaceId)});p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/adapters');if(p&&req.method==='GET')return json(res,200,{items:adapterStatus(db,service,principal,p.workspaceId)});p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/outbox');if(p&&req.method==='POST')return json(res,201,queueCommunication(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listOutbox(db,service,principal,p.workspaceId,url.searchParams.get('status')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/outbox/:id/process');if(p&&req.method==='POST')return json(res,200,processCommunication(db,service,principal,p.workspaceId,p.id,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/outbox/:id/receipt');if(p&&req.method==='POST')return json(res,200,acknowledgeProviderReceipt(db,service,principal,p.workspaceId,p.id,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/outbox/:id/retry');if(p&&req.method==='POST')return json(res,200,retryDeadLetter(db,service,principal,p.workspaceId,p.id));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/worker/run');if(p&&req.method==='POST')return json(res,200,runCommunicationWorker(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/report');if(p&&req.method==='GET')return json(res,200,communicationsReport(db,service,principal,p.workspaceId));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/provider-health');if(p&&req.method==='GET')return json(res,200,providerHealth(db,service,principal,p.workspaceId));p=match(url.pathname,'/v1/workspaces/:workspaceId/communications/audit-bundle');if(p&&req.method==='GET')return json(res,200,communicationsAuditBundle(db,service,principal,p.workspaceId,{noticeId:url.searchParams.get('noticeId')||''}))
p=match(url.pathname,'/v1/workspaces/:workspaceId/service/package');if(p&&req.method==='POST')return json(res,200,buildServicePackage(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/queue');if(p&&req.method==='POST')return json(res,201,queueNoticeService(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/recipients');if(p&&req.method==='POST')return json(res,201,registerServiceRecipient(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listServiceRecipients(db,service,principal,p.workspaceId,url.searchParams.get('claimNo')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/service/attempts');if(p&&req.method==='POST')return json(res,201,recordServiceAttempt(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/proofs');if(p&&req.method==='POST')return json(res,201,issueProofOfService(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listProofs(db,service,principal,p.workspaceId,url.searchParams.get('claimNo')||'')});p=match(url.pathname,'/v1/workspaces/:workspaceId/service/compliance/:claimNo');if(p&&req.method==='GET')return json(res,200,serviceCompliance(db,service,principal,p.workspaceId,p.claimNo));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/compliance/:claimNo/timeline');if(p&&req.method==='GET')return json(res,200,{items:serviceTimeline(db,service,principal,p.workspaceId,p.claimNo)});p=match(url.pathname,'/v1/workspaces/:workspaceId/service/compliance/:claimNo/escalations');if(p&&req.method==='POST')return json(res,200,evaluateServiceEscalations(db,service,principal,p.workspaceId,p.claimNo,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/compliance/:claimNo/proof-packet');if(p&&req.method==='GET')return json(res,200,buildProofPacket(db,service,principal,p.workspaceId,p.claimNo));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/compliance/:claimNo/recommendations');if(p&&req.method==='POST')return json(res,200,complianceRecommendations(db,service,principal,p.workspaceId,p.claimNo,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/sync-receipts');if(p&&req.method==='POST')return json(res,200,syncCommunicationReceipts(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/alternate-plan');if(p&&req.method==='POST')return json(res,201,alternateServicePlan(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/ledger/verify');if(p&&req.method==='GET')return json(res,200,verifyServiceLedger(db,service,principal,p.workspaceId))
p=match(url.pathname,'/v1/workspaces/:workspaceId/service/rules');if(p&&req.method==='POST')return json(res,201,createRuleProfile(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listRuleProfiles(db,principal,p.workspaceId,service)});p=match(url.pathname,'/v1/workspaces/:workspaceId/service/deadlines/recompute');if(p&&req.method==='POST')return json(res,200,recomputeRecipientDeadline(db,service,principal,p.workspaceId,await body(req)));p=match(url.pathname,'/v1/workspaces/:workspaceId/service/alternate-decisions');if(p&&req.method==='POST')return json(res,201,recordAlternateServiceDecision(db,service,principal,p.workspaceId,await body(req)));if(p&&req.method==='GET')return json(res,200,{items:listAlternateServiceDecisions(db,principal,p.workspaceId,url.searchParams.get('recipientId')||'',service)})
p=match(url.pathname,'/v1/workspaces/:workspaceId/provider-callback/verify');if(p&&req.method==='POST'){service.authorize(principal,p.workspaceId,'CLERK');const i=await body(req);return json(res,200,{valid:verifyProviderCallback(i.payload,i.signature)})};p=match(url.pathname,'/v1/workspaces/:workspaceId/hearings/:hearingId/calendar.ics');if(p&&req.method==='GET'){const i=hearingIcs(db,service,principal,p.workspaceId,p.hearingId);return json(res,200,i.content,{'content-type':'text/calendar; charset=utf-8','x-neo-payload-sha256':i.payloadHash,'x-neo-export-id':i.exportId})};p=match(url.pathname,'/v1/workspaces/:workspaceId/audit/export');if(p&&req.method==='GET')return json(res,200,service.exportAudit(principal,p.workspaceId,url.searchParams.get('afterSeq')||0));p=match(url.pathname,'/v1/workspaces/:workspaceId/audit/verify');if(p&&req.method==='GET'){service.authorize(principal,p.workspaceId,'REVIEWER');return json(res,200,service.verifyAudit(p.workspaceId))};return json(res,404,{error:'Not found'})
}catch(error){const message=error instanceof Error?error.message:String(error),status=/Authentication|required|credentials/i.test(message)?401:/membership|role|invitation email/i.test(message)?403:/conflict/i.test(message)?409:/too large|rate limit/i.test(message)?413:400;return json(res,status,{error:message})}})
server.listen(port,()=>console.log(JSON.stringify({level:'info',event:'server_started',service:'neo-tribunal-backend',version:'1.12',schema:7,deadlinePolicy:'ready',publicIntake:'moderated',publicRecords:'neo-pacer-live',port})))
