import test from 'node:test'
import assert from 'node:assert/strict'
import {DatabaseSync} from 'node:sqlite'
import {TribunalService} from './service.mjs'

function db(){const d=new DatabaseSync(':memory:');d.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE workspaces(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE memberships(workspace_id TEXT NOT NULL REFERENCES workspaces(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(workspace_id,user_id));
CREATE TABLE invitations(token_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),email TEXT NOT NULL,role TEXT NOT NULL,expires_at TEXT NOT NULL,accepted_at TEXT,invited_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE cases(claim_no TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),envelope_json TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE efiles(filing_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),claim_no TEXT NOT NULL,envelope_json TEXT NOT NULL,filed_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE notices(notice_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),claim_no TEXT NOT NULL,envelope_json TEXT NOT NULL,status TEXT NOT NULL,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE hearings(hearing_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),claim_no TEXT NOT NULL,envelope_json TEXT NOT NULL,starts_at TEXT NOT NULL,status TEXT NOT NULL,updated_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE audit_log(seq INTEGER PRIMARY KEY AUTOINCREMENT,workspace_id TEXT NOT NULL,actor_user_id TEXT NOT NULL,action TEXT NOT NULL,subject TEXT NOT NULL,payload_hash TEXT NOT NULL,previous_hash TEXT,entry_hash TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);`);return d}

function setup(){process.env.NEO_TRIBUNAL_MASTER_KEY='test-master-key';const service=new TribunalService(db());service.register({email:'chief@example.test',displayName:'Chief',password:'very-secure-1'});const login=service.login({email:'chief@example.test',password:'very-secure-1'});const chief=service.principal(login.token);const ws=service.createWorkspace(chief,{name:'Global District'});return {service,chief,ws,token:login.token}}

test('auth workspace invite encrypted case sync and audit chain',()=>{const {service,chief,ws}=setup();service.register({email:'clerk@example.test',displayName:'Clerk',password:'very-secure-2'});const clerk=service.principal(service.login({email:'clerk@example.test',password:'very-secure-2'}).token);const invite=service.invite(chief,ws.id,{email:'clerk@example.test',role:'CLERK'});service.acceptInvite(clerk,invite.token);const saved=service.saveCase(clerk,ws.id,{claimNo:'WT-1001',caseType:'CIVIL',statement:'Encrypted server record.'});assert.equal(saved.revision,1);assert.equal(service.getCase(clerk,ws.id,'WT-1001').caseFile.statement,'Encrypted server record.');assert.throws(()=>service.saveCase(clerk,ws.id,{claimNo:'WT-1001',statement:'stale'},0),/Revision conflict/);assert.equal(service.saveCase(clerk,ws.id,{claimNo:'WT-1001',statement:'revision two'},1).revision,2);assert.equal(service.verifyAudit(ws.id).valid,true);assert.ok(service.exportAudit(chief,ws.id).entries.length>=4)})

test('server RBAC blocks viewer writes',()=>{const {service,chief,ws}=setup();service.register({email:'view@example.test',displayName:'Viewer',password:'very-secure-4'});const viewer=service.principal(service.login({email:'view@example.test',password:'very-secure-4'}).token);service.acceptInvite(viewer,service.invite(chief,ws.id,{email:'view@example.test',role:'VIEWER'}).token);assert.throws(()=>service.saveCase(viewer,ws.id,{claimNo:'WT-2001'}),/Role CLERK/)})

test('v1 workspace discovery e-file notice hearing and logout lifecycle',()=>{const {service,chief,ws,token}=setup();assert.equal(service.listWorkspaces(chief)[0].id,ws.id);const filing=service.fileEFile(chief,ws.id,{claimNo:'WT-3001',caseType:'TEMPLE_INJUSTICE',statement:'Filed record'});assert.equal(filing.status,'FILED');assert.equal(service.listEFiles(chief,ws.id,'WT-3001').length,1);const notice=service.saveNotice(chief,ws.id,{claimNo:'WT-3001',recipient:'Respondent',status:'SENT'});assert.equal(service.listNotices(chief,ws.id,'WT-3001')[0].noticeId,notice.noticeId);const hearing=service.saveHearing(chief,ws.id,{claimNo:'WT-3001',startsAt:'2026-09-01T15:00:00Z'});assert.equal(service.listHearings(chief,ws.id,'WT-3001')[0].hearingId,hearing.hearingId);assert.throws(()=>service.saveHearing(chief,ws.id,{claimNo:'WT-3002',startsAt:'2026-09-01T15:00:00Z'}),/conflict/i);service.logout(token);assert.throws(()=>service.principal(token),/Authentication/)})
