package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;

/** v4.12 consolidated NEO Account + Cloud status. Metadata only; no document/chat bodies or wallet/XCP Key material. */
public class AccountCloudStatusActivity extends Activity {
 @Override public void onCreate(Bundle s){super.onCreate(s);build();}
 @Override protected void onResume(){super.onResume();build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(22));r.setBackgroundColor(Color.rgb(1,5,3));sv.addView(r);ProfileSyncVault profile=new ProfileSyncVault(this);AccountE2eeVault e2ee=new AccountE2eeVault(this);e2ee.ensure();String tree=getSharedPreferences("omnitrix_cloud_provider",MODE_PRIVATE).getString("tree","");JSONArray trusted=trusted();JSONArray index=FileNativeStore.index(this);int active=0,trash=0,review=0;for(int i=0;i<index.length();i++){JSONObject m=index.optJSONObject(i);if(m==null)continue;if(m.optBoolean("deleted"))trash++;else active++;if(m.optBoolean("needsReview"))review++;}r.addView(text("NEO ACCOUNT + CLOUD",24,Color.WHITE));r.addView(text("Omnitrix Suit v4.12 · NEO-0001",12,Color.rgb(116,255,151)));r.addView(card("ACCOUNT E2EE\nActive on this device\nDevice: "+profile.deviceId()));r.addView(card("TRUSTED DEVICES\n"+trusted.length()+" additional device(s)"));r.addView(card("STORAGE PROVIDER\n"+(tree.isEmpty()?"Not connected":"Connected via Android SAF")));r.addView(card("FILE STATE\nActive "+active+" · Trash "+trash+" · Needs review "+review+" · Queue "+SuiteSyncBus.read(this,"queue").length()));r.addView(card("BACKGROUND SYNC\n"+BackgroundFileSync.status(this)));r.addView(card("CHAT SYNC\n"+ChatSyncHealth.status(this)));Button security=button("ACCOUNT E2EE / TRUSTED DEVICES");r.addView(security,new LinearLayout.LayoutParams(-1,dp(50)));security.setOnClickListener(v->startActivity(new Intent(this,TrustedDevicesActivity.class)));Button provider=button("STORAGE PROVIDER");r.addView(provider,new LinearLayout.LayoutParams(-1,dp(50)));provider.setOnClickListener(v->startActivity(new Intent(this,CloudProviderActivity.class)));Button health=button("SYNC HEALTH / RECOVERY");r.addView(health,new LinearLayout.LayoutParams(-1,dp(50)));health.setOnClickListener(v->startActivity(new Intent(this,SyncHealthActivity.class)));r.addView(text("Account E2EE is separate from wallet signing. XCP Key material is not synchronized, exported, or displayed by NEO Cloud.",11,Color.LTGRAY));setContentView(sv);}
 private JSONArray trusted(){try{return new JSONArray(getSharedPreferences("omnitrix_trusted_devices_v1",MODE_PRIVATE).getString("devices","[]"));}catch(Exception e){return new JSONArray();}}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(14),dp(12),dp(14));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(6));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(6),0,dp(6));return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
