package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Build;import androidx.core.app.NotificationCompat;import org.json.*;

/** Local notification routing for unread/mention state. No message content leaves the device. */
public final class ChatNotificationRouter {
 private static final String CHANNEL="neo_chat_activity";private ChatNotificationRouter(){}
 public static void ensureChannel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(n!=null)n.createNotificationChannel(new NotificationChannel(CHANNEL,"Noogle Chat",NotificationManager.IMPORTANCE_DEFAULT));}}
 public static void scan(Context c,String fileId,JSONObject chat){ensureChannel(c);if(Build.VERSION.SDK_INT>=33&&c.checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)return;String alias=StructuredWorkspace.localAlias(chat);JSONArray channels=chat.optJSONArray("channels");if(channels==null)return;NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(n==null)return;for(int i=0;i<channels.length();i++){JSONObject ch=channels.optJSONObject(i);if(ch==null)continue;String cid=ch.optString("id"),name=ch.optString("name","channel");int unread=StructuredWorkspace.unreadCount(chat,cid,alias),mentions=StructuredWorkspace.mentionCount(chat,cid,alias);int id=(fileId+":"+cid).hashCode();if(unread<=0){n.cancel(id);continue;}Intent open=new Intent(c,SuiteWave2Activity.class).putExtra(SuiteWave2Activity.EXTRA_ID,"noogle-chat").putExtra(SuiteWave2Activity.EXTRA_NAME,"Noogle Chat").putExtra("file_id",fileId).putExtra("channel_id",cid);PendingIntent pi=PendingIntent.getActivity(c,id,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String title=mentions>0?mentions+" mention"+(mentions==1?"":"s")+" in #"+name:unread+" unread in #"+name;Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,CHANNEL):new Notification.Builder(c);b.setSmallIcon(R.mipmap.ic_launcher).setContentTitle(title).setContentText("Open Noogle Chat to review messages.").setAutoCancel(true).setContentIntent(pi);n.notify(id,b.build());}}
}
