package io.neo.omnitrix;

import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** Dedicated v4.7 thread view over the same encrypted file-native Chat body. */
public class ChatThreadActivity extends Activity {
 public static final String EXTRA_FILE_ID="file_id",EXTRA_ROOT_ID="root_id";private String fileId,rootId;private JSONObject chat,meta;private LinearLayout body;
 @Override public void onCreate(Bundle s){super.onCreate(s);fileId=getIntent().getStringExtra(EXTRA_FILE_ID);rootId=getIntent().getStringExtra(EXTRA_ROOT_ID);build();}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(22));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);meta=FileNativeStore.find(this,fileId);if(meta==null){body.addView(text("Chat file not found",14,Color.WHITE));setContentView(sv);return;}chat=StructuredWorkspace.chat(FileNativeStore.body(this,fileId));JSONArray msgs=chat.optJSONArray("messages");JSONObject root=null;if(msgs!=null)for(int i=0;i<msgs.length();i++){JSONObject m=msgs.optJSONObject(i);if(m!=null&&rootId!=null&&rootId.equals(m.optString("id"))){root=m;break;}}body.addView(text("Noogle Chat · Thread",23,Color.WHITE));if(root==null){body.addView(text("Thread root not found",14,Color.LTGRAY));setContentView(sv);return;}String channel=root.optString("channelId");body.addView(text(root.optString("author","Local")+": "+root.optString("text"),14,Color.rgb(210,240,218)));if(msgs!=null)for(int i=0;i<msgs.length();i++){JSONObject r=msgs.optJSONObject(i);if(r!=null&&rootId.equals(r.optString("threadId")))body.addView(text("↳ "+r.optString("author","Local")+": "+r.optString("text"),13,Color.rgb(170,215,183)));}EditText author=input("Author");author.setText("Local");body.addView(author);EditText reply=input("Reply");reply.setMinLines(4);reply.setGravity(Gravity.TOP);body.addView(reply,new LinearLayout.LayoutParams(-1,dp(120)));Button send=new Button(this);send.setText("SEND THREAD REPLY + E2EE SYNC");body.addView(send,new LinearLayout.LayoutParams(-1,dp(52)));send.setOnClickListener(v->{String msg=reply.getText().toString().trim();if(msg.isEmpty())return;StructuredWorkspace.addMessage(chat,msg,author.getText().toString(),channel,rootId);JSONObject saved=FileNativeStore.saveId(this,fileId,"noogle-chat",meta.optString("title","Noogle Chat"),StructuredWorkspace.pretty(chat),true);Toast.makeText(this,"Saved rev "+saved.optLong("rev")+"; encrypted sync scheduled",Toast.LENGTH_SHORT).show();recreate();});setContentView(sv);}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(6),0,dp(6));return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
