package io.neo.omnitrix;

import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;

/** v4.8 participant identity/role/read-state manager for Noogle Chat. */
public class ChatMembersActivity extends Activity {
 public static final String EXTRA_FILE_ID="file_id";private String fileId;private JSONObject chat,meta;private LinearLayout body;
 @Override public void onCreate(Bundle s){super.onCreate(s);fileId=getIntent().getStringExtra(EXTRA_FILE_ID);meta=FileNativeStore.find(this,fileId);if(meta==null){finish();return;}chat=StructuredWorkspace.chat(FileNativeStore.body(this,fileId));build();}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(22));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);body.addView(text("CHAT MEMBERS + READ STATE",22,Color.WHITE));body.addView(text("Local identity: "+StructuredWorkspace.localAlias(chat),12,Color.rgb(116,255,151)));JSONArray members=chat.optJSONArray("members"),channels=chat.optJSONArray("channels");if(members!=null)for(int i=0;i<members.length();i++){JSONObject m=members.optJSONObject(i);if(m==null)continue;String alias=m.optString("alias"),role=m.optString("role","member");body.addView(text(alias+" · "+role+(m.optBoolean("local")?" · this device":""),13,Color.rgb(205,235,213)));if(channels!=null)for(int j=0;j<channels.length();j++){JSONObject c=channels.optJSONObject(j);if(c==null)continue;String cid=c.optString("id"),name=c.optString("name");int unread=StructuredWorkspace.unreadCount(chat,cid,alias),mentions=StructuredWorkspace.mentionCount(chat,cid,alias);body.addView(text("   #"+name+": "+unread+" unread · "+mentions+" mentions",11,Color.rgb(142,182,154)));}if(!m.optBoolean("local")){Spinner roles=new Spinner(this);String[] rs={"member","moderator","admin"};roles.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,rs));for(int x=0;x<rs.length;x++)if(rs[x].equals(role))roles.setSelection(x);body.addView(roles);Button update=button("UPDATE ROLE");body.addView(update);update.setOnClickListener(v->{if(StructuredWorkspace.updateMemberRole(chat,alias,String.valueOf(roles.getSelectedItem()))){save();recreate();}});Button remove=button("REMOVE MEMBER");body.addView(remove);remove.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Remove "+alias+"?").setPositiveButton("REMOVE",(d,w)->{if(StructuredWorkspace.removeMember(chat,alias)){save();recreate();}}).setNegativeButton("Cancel",null).show());}}
 EditText alias=input("New participant alias");body.addView(alias);Spinner role=new Spinner(this);role.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"member","moderator","admin"}));body.addView(role);Button add=button("ADD PARTICIPANT");body.addView(add);add.setOnClickListener(v->{if(StructuredWorkspace.addMember(chat,alias.getText().toString(),String.valueOf(role.getSelectedItem()))){save();recreate();}else Toast.makeText(this,"Alias is empty or already exists",Toast.LENGTH_SHORT).show();});setContentView(sv);}
 private void save(){FileNativeStore.saveId(this,fileId,"noogle-chat",meta.optString("title","Noogle Chat"),StructuredWorkspace.pretty(chat),true);}
 private EditText input(String h){EditText e=new EditText(this);e.setHint(h);return e;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
