package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.DocumentsContract;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;

/** v3.6 provider boundary. Uses Android Storage Access Framework so Drive/Dropbox/local providers can be selected without embedding vendor secrets. */
public class CloudProviderActivity extends Activity {
    private static final int PICK_TREE=3601; private TextView provider,device,status; private Spinner policy; private ProfileSyncVault vault;
    @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);vault=new ProfileSyncVault(this);build();}
    private void build(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(24));sv.addView(r);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);r.addView(logo,new LinearLayout.LayoutParams(dp(70),dp(70)));r.addView(text("CLOUD PROVIDERS",24,Color.rgb(229,255,236)));r.addView(text("Omnitrix Suit v3.6 · NEO-0001",11,Color.rgb(104,185,130)));device=card("DEVICE\n"+vault.deviceId());r.addView(device);provider=card("PROVIDER\n"+currentProvider());r.addView(provider);r.addView(text("Conflict policy",12,Color.rgb(118,255,151)));policy=new Spinner(this);String[] policies={"newest-wins-with-copy","keep-both","local-first","remote-first"};ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,policies);policy.setAdapter(a);String cp=vault.load().optString("conflictPolicy","newest-wins-with-copy");for(int i=0;i<policies.length;i++)if(policies[i].equals(cp))policy.setSelection(i);r.addView(policy,new LinearLayout.LayoutParams(-1,dp(52)));Button bind=primary("CHOOSE CLOUD / STORAGE FOLDER");r.addView(bind,new LinearLayout.LayoutParams(-1,dp(52)));bind.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_TREE);});Button manifest=secondary("WRITE SYNC MANIFEST");LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,dp(50));mp.setMargins(0,dp(8),0,0);r.addView(manifest,mp);manifest.setOnClickListener(v->writeManifest());status=text("Provider access is delegated to Android. Google Drive, Dropbox, local storage, or another installed document provider can supply the selected folder.",12,Color.rgb(184,218,194));status.setPadding(0,dp(16),0,dp(12));r.addView(status);TextView note=text("Provider credentials never enter GitHub or the Omnitrix public source. The local profile sync manifest is encrypted with Android Keystore. The provider-side manifest contains only non-secret sync metadata; end-to-end multi-device content encryption requires the later account-key exchange gate.",11,Color.rgb(109,145,121));r.addView(note);shell.addView(sv,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"NEO"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==PICK_TREE&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);try{getContentResolver().takePersistableUriPermission(u,flags);}catch(Exception ignored){}getSharedPreferences("omnitrix_cloud_provider",MODE_PRIVATE).edit().putString("tree",u.toString()).apply();JSONObject m=vault.load();try{m.put("provider","android-saf");m.put("providerUri",u.toString());m.put("conflictPolicy",policy.getSelectedItem().toString());vault.save(m);}catch(Exception e){}provider.setText("PROVIDER\n"+u);SuiteSyncBus.notify(this,"Noogle Cloud","Cloud/storage provider bound to NEO-0001");status.setText("Provider folder connected. You can now write the non-secret sync manifest.");}}
    private String currentProvider(){String u=getSharedPreferences("omnitrix_cloud_provider",MODE_PRIVATE).getString("tree","");return u.isEmpty()?"Not connected":u;}
    private void writeManifest(){String tree=getSharedPreferences("omnitrix_cloud_provider",MODE_PRIVATE).getString("tree","");if(tree.isEmpty()){status.setText("Choose a cloud/storage folder first.");return;}try{JSONObject local=vault.load();local.put("conflictPolicy",policy.getSelectedItem().toString());local.put("provider","android-saf");vault.save(local);JSONObject remote=new JSONObject();remote.put("schema","neo.omnitrix.remote-sync-index/v1");remote.put("profile","NEO-0001");remote.put("deviceId",vault.deviceId());remote.put("updatedAt",System.currentTimeMillis());remote.put("conflictPolicy",policy.getSelectedItem().toString());remote.put("queuedItems",SuiteSyncBus.read(this,"queue").length());Uri treeUri=Uri.parse(tree);Uri parent=DocumentsContract.buildDocumentUriUsingTree(treeUri,DocumentsContract.getTreeDocumentId(treeUri));Uri target=find(parent,treeUri,"omnitrix-NEO-0001-sync.json");if(target==null)target=DocumentsContract.createDocument(getContentResolver(),parent,"application/json","omnitrix-NEO-0001-sync.json");if(target==null)throw new IOException("Provider refused manifest creation");try(OutputStream out=getContentResolver().openOutputStream(target,"wt")){if(out==null)throw new IOException("Provider output unavailable");out.write(remote.toString(2).getBytes(StandardCharsets.UTF_8));}SuiteSyncBus.notify(this,"Noogle Cloud","Provider sync manifest updated");status.setText("Sync manifest written successfully. No private keys, passwords, OAuth tokens, or wallet secrets were included.");}catch(Exception e){status.setText("Manifest write failed: "+(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()));}}
    private Uri find(Uri parent,Uri tree,String name){Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getDocumentId(parent));String[] p={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME};try(android.database.Cursor c=getContentResolver().query(children,p,null,null,null)){if(c!=null)while(c.moveToNext())if(name.equals(c.getString(1)))return DocumentsContract.buildDocumentUriUsingTree(tree,c.getString(0));}catch(Exception ignored){}return null;}
    private TextView card(String s){TextView t=text(s,14,Color.rgb(220,255,230));t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(8));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
