package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** v4.2 explicit conflict resolver. Never silently overwrites a divergent local file. */
public class ConflictReviewActivity extends Activity{
 public static final String EXTRA_ID="id";private String copyId,baseId;private JSONObject copy,base;
 @Override public void onCreate(Bundle b){super.onCreate(b);copyId=getIntent().getStringExtra(EXTRA_ID);copy=FileNativeStore.find(this,copyId);baseId=copy==null?"":copy.optString("conflictOf");base=FileNativeStore.find(this,baseId);build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(24));r.setBackgroundColor(Color.rgb(1,5,3));sv.addView(r);r.addView(text("CONFLICT REVIEW",24,Color.rgb(229,255,236)));r.addView(text("Omnitrix Suit v4.2 · explicit reconciliation",11,Color.rgb(104,185,130)));if(copy==null||base==null){r.addView(card("Conflict pair is unavailable. No file was changed."));setContentView(sv);return;}r.addView(text("LOCAL CURRENT",12,Color.rgb(118,255,151)));r.addView(card(base.optString("title")+" · rev "+base.optLong("rev")+"\n"+FileNativeStore.body(this,baseId)));r.addView(text("REMOTE CONFLICT COPY",12,Color.rgb(118,255,151)));r.addView(card(copy.optString("title")+" · rev "+copy.optLong("rev")+"\n"+FileNativeStore.body(this,copyId)));Button local=primary("KEEP LOCAL CURRENT + ARCHIVE CONFLICT COPY");r.addView(local,new LinearLayout.LayoutParams(-1,dp(52)));local.setOnClickListener(v->{FileNativeStore.markReviewed(this,copyId);FileNativeStore.tombstone(this,copyId);Toast.makeText(this,"Local current retained; conflict copy archived",Toast.LENGTH_LONG).show();finish();});Button remote=primary("USE CONFLICT COPY AS NEW CURRENT REVISION");r.addView(remote,new LinearLayout.LayoutParams(-1,dp(52)));remote.setOnClickListener(v->{String content=FileNativeStore.body(this,copyId);FileNativeStore.saveId(this,baseId,base.optString("app"),base.optString("title"),content,base.optBoolean("offline",true));FileNativeStore.markReviewed(this,copyId);FileNativeStore.tombstone(this,copyId);Toast.makeText(this,"Conflict content promoted as a new stable-ID revision",Toast.LENGTH_LONG).show();finish();});Button both=secondary("KEEP BOTH AS SEPARATE FILES");r.addView(both,new LinearLayout.LayoutParams(-1,dp(50)));both.setOnClickListener(v->{FileNativeStore.markReviewed(this,copyId);Toast.makeText(this,"Both files retained; conflict copy marked reviewed",Toast.LENGTH_LONG).show();finish();});r.addView(text("No automatic merge is performed. Each resolution is explicit, revisioned, and queued for encrypted provider sync.",11,Color.rgb(110,145,121)));setContentView(sv);}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(12));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(8),0,dp(8));return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
