package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.bitcoinj.base.BitcoinNetwork;import org.bitcoinj.base.ScriptType;import org.bitcoinj.crypto.DumpedPrivateKey;import java.util.Locale;import java.util.concurrent.*;

/** v4.14 consumer-first Omnitrix home. Secondary tools live in Apps instead of crowding Home. */
public class ConsumerHomeActivity extends Activity {
 private final ExecutorService io=Executors.newSingleThreadExecutor();private XcpKeyVault vault;private TextView portfolio,status;private String address="";
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);vault=new XcpKeyVault(this);buildUi();load();}
 private void buildUi(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(24),dp(20),dp(24));scroll.addView(root);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);head.addView(logo,new LinearLayout.LayoutParams(dp(64),dp(64)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(12),0,0,0);words.addView(text("Omnitrix",28,Color.rgb(228,255,235)));words.addView(text("Everything NEO. One place.",12,Color.rgb(104,185,130)));head.addView(words);root.addView(head);
  portfolio=hero("Portfolio\nWallet not connected");root.addView(portfolio);status=text("Explore Omnitrix without a wallet, or connect your protected XCP Key when you need wallet features.",12,Color.rgb(181,214,191));status.setPadding(0,dp(10),0,dp(16));root.addView(status);
  Button browser=primary("Search with Noogle");root.addView(browser,new LinearLayout.LayoutParams(-1,dp(54)));browser.setOnClickListener(v->startActivity(new Intent(this,NoogleBrowserActivity.class)));
  LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.HORIZONTAL);Button wallet=secondary("Wallet");Button apps=secondary("All Apps");quick.addView(wallet,new LinearLayout.LayoutParams(0,dp(50),1f));quick.addView(apps,new LinearLayout.LayoutParams(0,dp(50),1f));root.addView(quick);wallet.setOnClickListener(v->startActivity(new Intent(this,WalletDashboardActivity.class)));apps.setOnClickListener(v->startActivity(new Intent(this,SuiteLauncherActivity.class)));
  TextView more=text("MARKET + TOOLS",11,Color.rgb(104,185,130));more.setPadding(0,dp(22),0,dp(8));root.addView(more);LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);Button market=quiet("Market");Button cloud=quiet("Cloud");Button miner=quiet("Miner");tools.addView(market,new LinearLayout.LayoutParams(0,dp(46),1f));tools.addView(cloud,new LinearLayout.LayoutParams(0,dp(46),1f));tools.addView(miner,new LinearLayout.LayoutParams(0,dp(46),1f));root.addView(tools);market.setOnClickListener(v->startActivity(new Intent(this,MarketMatrixActivity.class)));cloud.setOnClickListener(v->startActivity(new Intent(this,NeoCloudHubActivity.class)));miner.setOnClickListener(v->startActivity(new Intent(this,MinerControlActivity.class)));
  shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"Home"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);}
 private void load(){if(!vault.hasKey())return;status.setText("Refreshing portfolio…");io.execute(()->{try{address=vault.withUnlockedXcpKey(k->DumpedPrivateKey.fromBase58(BitcoinNetwork.MAINNET,new String(k)).getKey().toAddress(ScriptType.P2PKH,BitcoinNetwork.MAINNET).toString());WalletNetwork.WalletSnapshot w=WalletNetwork.load(address);MarketNetwork.Matrix m=MarketNetwork.load();runOnUiThread(()->render(w,m));}catch(Exception e){runOnUiThread(()->status.setText("Portfolio is locked. Open Wallet when you want to authenticate."));}});}
 private void render(WalletNetwork.WalletSnapshot w,MarketNetwork.Matrix m){double b=w.btcSats/100000000.0,xv=parse(w.find("XCP").display()),nv=parse(w.find("NOMNI").display());double total=(m.btcUsd>0?b*m.btcUsd:0)+(m.xcpUsd()>0?xv*m.xcpUsd():0)+(m.nomniUsd()>0?nv*m.nomniUsd():0);portfolio.setText(total>0?String.format(Locale.US,"Portfolio\n$%,.2f USD",total):"Portfolio\nConnected");status.setText("Wallet connected · public balances refreshed");}
 private double parse(String s){try{return Double.parseDouble(s.replace(",",""));}catch(Exception e){return 0;}}private TextView hero(String s){TextView t=text(s,23,Color.rgb(222,255,231));t.setPadding(dp(18),dp(18),dp(18),dp(18));t.setBackgroundColor(Color.rgb(5,25,13));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(100));p.setMargins(0,dp(20),0,0);t.setLayoutParams(p);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=quiet(s);b.setTextSize(13);return b;}private Button quiet(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinWidth(0);b.setMinimumWidth(0);b.setTextSize(12);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
