package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.bitcoinj.base.BitcoinNetwork;import org.bitcoinj.base.ScriptType;import org.bitcoinj.crypto.DumpedPrivateKey;import java.util.Locale;import java.util.concurrent.*;

/** Omnitrix v3.0 consumer-first home surface for NEO-0001. */
public class ConsumerHomeActivity extends Activity {
 private final ExecutorService io=Executors.newSingleThreadExecutor(); private XcpKeyVault vault; private TextView profile,portfolio,btc,xcp,nomni,status; private String address="";
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);vault=new XcpKeyVault(this);buildUi();load();}
 private void buildUi(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(20));scroll.addView(root);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);head.addView(logo,new LinearLayout.LayoutParams(dp(72),dp(72)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(text("OMNITRIX",26,Color.rgb(228,255,235)));words.addView(text("Consumer Home · Suit v3.0",12,Color.rgb(104,185,130)));head.addView(words);root.addView(head);
  profile=card("NEO-0001\nFounding Profile · ACTIVE");root.addView(profile);
  Button suit=primary("OPEN FULL OMNITRIX SUIT");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(56));sp.setMargins(0,dp(12),0,0);root.addView(suit,sp);suit.setOnClickListener(v->startActivity(new Intent(this,SuiteLauncherActivity.class)));
  portfolio=hero("PORTFOLIO\nLoading…");root.addView(portfolio);LinearLayout assets=new LinearLayout(this);assets.setOrientation(LinearLayout.HORIZONTAL);btc=mini("BTC\n—");xcp=mini("XCP\n—");nomni=mini("∞ NOMNI\n—");assets.addView(btc,new LinearLayout.LayoutParams(0,dp(92),1f));assets.addView(xcp,new LinearLayout.LayoutParams(0,dp(92),1f));assets.addView(nomni,new LinearLayout.LayoutParams(0,dp(92),1f));root.addView(assets);
  status=text("Loading public portfolio intelligence…",12,Color.rgb(181,214,191));status.setPadding(0,dp(12),0,dp(12));root.addView(status);
  LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);LinearLayout r1=new LinearLayout(this),r2=new LinearLayout(this);addLaunch(r1,"BROWSER",MainActivityV14.class);addLaunch(r1,"WALLET",WalletDashboardActivity.class);addLaunch(r1,"MARKET",MarketMatrixActivity.class);addLaunch(r2,"MINER",MinerControlActivity.class);addLaunch(r2,"TRACK TX",TxStatusActivity.class);Button refresh=tile("REFRESH");refresh.setOnClickListener(v->load());r2.addView(refresh,new LinearLayout.LayoutParams(0,dp(70),1f));grid.addView(r1);grid.addView(r2);root.addView(grid);
  TextView note=text("The Suit launcher is the shared consumer catalog for Noogle and NEO services. Portfolio totals include only assets with a defensible live market price; illiquid pairs stay visible but are excluded from USD total.",11,Color.rgb(105,145,118));note.setPadding(0,dp(18),0,0);root.addView(note);
  shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"NEO"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);
 }
 private void load(){if(!vault.hasKey()){portfolio.setText("PORTFOLIO\nXCP Key not secured");status.setText("Secure your XCP Key from the Omnitrix security entry to activate NEO-0001 portfolio reads.");return;}status.setText("Refreshing wallet and market data…");io.execute(()->{try{address=vault.withUnlockedXcpKey(k->DumpedPrivateKey.fromBase58(BitcoinNetwork.MAINNET,new String(k)).getKey().toAddress(ScriptType.P2PKH,BitcoinNetwork.MAINNET).toString());WalletNetwork.WalletSnapshot w=WalletNetwork.load(address);MarketNetwork.Matrix m=MarketNetwork.load();runOnUiThread(()->render(w,m));}catch(Exception e){runOnUiThread(()->status.setText("Portfolio refresh unavailable: "+safe(e)));}});}
 private void render(WalletNetwork.WalletSnapshot w,MarketNetwork.Matrix m){double b=w.btcSats/100000000.0;WalletNetwork.AssetBalance xb=w.find("XCP"),nb=w.find("NOMNI");double xv=parse(xb.display()),nv=parse(nb.display());double bUsd=m.btcUsd>0?b*m.btcUsd:0,xUsd=m.xcpUsd()>0?xv*m.xcpUsd():0,nUsd=m.nomniUsd()>0?nv*m.nomniUsd():0,total=bUsd+xUsd+nUsd;btc.setText(String.format(Locale.US,"BTC\n%.8f",b));xcp.setText("XCP\n"+xb.display());nomni.setText("∞ NOMNI\n"+nb.display());portfolio.setText(total>0?String.format(Locale.US,"PORTFOLIO\n$%,.2f USD",total):"PORTFOLIO\nMarket valuation unavailable");status.setText("Live public portfolio data loaded"+(address.isEmpty()?"":" · "+address.substring(0,Math.min(8,address.length()))+"…"));}
 private double parse(String s){try{return Double.parseDouble(s.replace(",",""));}catch(Exception e){return 0;}}
 private void addLaunch(LinearLayout row,String label,Class<?> c){Button b=tile(label);b.setOnClickListener(v->startActivity(new Intent(this,c)));row.addView(b,new LinearLayout.LayoutParams(0,dp(70),1f));}
 private TextView hero(String s){TextView t=text(s,22,Color.rgb(222,255,231));t.setPadding(dp(16),dp(16),dp(16),dp(16));t.setBackgroundColor(Color.rgb(5,25,13));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(104));lp.setMargins(0,dp(12),0,dp(10));t.setLayoutParams(lp);return t;}private TextView card(String s){TextView t=text(s,14,Color.rgb(206,255,219));t.setPadding(dp(14),dp(12),dp(14),dp(12));t.setBackgroundColor(Color.rgb(4,17,10));return t;}private TextView mini(String s){TextView t=text(s,13,Color.rgb(215,255,225));t.setPadding(dp(8),dp(12),dp(8),dp(8));t.setGravity(Gravity.CENTER);t.setBackgroundColor(Color.rgb(5,20,12));return t;}private Button tile(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(11);b.setTextColor(Color.rgb(190,235,202));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private String safe(Exception e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():s;}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
