package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;

/** v4.1 multi-file cloud library with stable-ID history, trash restore, conflict review and background sync status. */
public class FileLibraryActivity extends Activity{
 private LinearLayout body;
 @Override public void onCreate(Bundle b){super.onCreate(b);migrateLegacy();BackgroundFileSync.schedulePeriodic(this);build();}
 private void migrateLegacy(){SharedPreferences w1=getSharedPreferences("omnitrix_wave1",MODE_PRIVATE);String[][] one={{"noogle-docs","Noogle Docs"},{"noogle-sheets","Noogle Sheets"},{"noogle-slides","Noogle Slides"},{"noogle-keep","Noogle Keep"}};for(String[] x:one){String text=w1.getString(x[0],"");if(!text.isEmpty()&&FileNativeStore.findByApp(this,x[0])==null)FileNativeStore.create(this,x[0],x[1],text,true);}SharedPreferences w2=getSharedPreferences("omnitrix_suite",MODE_PRIVATE);String[][] two={{"noogle-forms","Noogle Forms"},{"noogle-chat","Noogle Chat"}};for(String[] x:two){String text=w2.getString("wave2_"+x[0],"");if(!text.isEmpty()&&FileNativeStore.findByApp(this,x[0])==null)FileNativeStore.create(this,x[0],x[1],text,true);}}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(24));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);body.addView(text("NEO CLOUD FILES",24,Color.rgb(229,255,236)));body.addView(text("Omnitrix Suit v4.1 · NEO-0001 · Multi-file E2EE",11,Color.rgb(104,185,130)));body.addView(text("Background: "+BackgroundFileSync.status(this),10,Color.rgb(110,145,121)));Button sync=primary("SYNC NOW — VERIFY / RECONCILE / UPLOAD");body.addView(sync,new LinearLayout.LayoutParams(-1,dp(52)));sync.setOnClickListener(v->{JSONObject pull=FileNativeTransport.pullAll(this),push=FileNativeTransport.pushAll(this);Toast.makeText(this,"Applied "+pull.optInt("applied")+" · conflicts "+pull.optInt("conflicts")+" · uploaded "+push.optInt("uploaded")+" · failed "+(pull.optInt("failed")+push.optInt("failed")),Toast.LENGTH_LONG).show();recreate();});JSONArray a=FileNativeStore.index(this);int active=0,trash=0,review=0;for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m!=null){if(m.optBoolean("deleted"))trash++;else active++;if(m.optBoolean("needsReview"))review++;}}body.addView(text("FILES "+active+" · TRASH "+trash+" · NEEDS REVIEW "+review,12,Color.rgb(118,255,151)));if(a.length()==0)body.addView(card("No file-native records yet. Save a Doc, Sheet, Slide, Keep note, Form, or Chat workspace."));for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String s=m.optString("title")+"\n"+m.optString("app")+" · rev "+m.optLong("rev")+" · "+m.optString("sync")+(m.optBoolean("needsReview")?" · REVIEW":"")+(m.optBoolean("deleted")?" · TRASH":"")+(m.optBoolean("offline")?" · OFFLINE":"");TextView t=card(s);String id=m.optString("id");t.setOnClickListener(v->fileActions(id));body.addView(t);}TextView note=text("Tap a file for offline, conflict-review, revision-history, delete, or restore actions. Restoring history preserves the same stable file ID and creates a new revision.",11,Color.rgb(110,145,121));note.setPadding(0,dp(14),0,0);body.addView(note);setContentView(sv);}
 private void fileActions(String id){JSONObject m=FileNativeStore.find(this,id);if(m==null)return;if(m.optBoolean("deleted")){new AlertDialog.Builder(this).setTitle(m.optString("title")).setItems(new String[]{"Restore from trash","View revision history"},(d,w)->{if(w==0){FileNativeStore.restoreDeleted(this,id);Toast.makeText(this,"Restored with stable ID; sync scheduled",Toast.LENGTH_SHORT).show();recreate();}else historyDialog(id);}).show();return;}String offline=m.optBoolean("offline")?"Remove offline availability":"Make available offline";String review=m.optBoolean("needsReview")?"Mark conflict reviewed / keep this copy":"Conflict status: clear";new AlertDialog.Builder(this).setTitle(m.optString("title")).setItems(new String[]{offline,"View / restore revision history",review,"Move to trash"},(d,w)->{if(w==0){FileNativeStore.setOffline(this,id,!m.optBoolean("offline"));recreate();}else if(w==1)historyDialog(id);else if(w==2){if(m.optBoolean("needsReview")){FileNativeStore.markReviewed(this,id);Toast.makeText(this,"Conflict copy retained and queued as reviewed",Toast.LENGTH_SHORT).show();recreate();}}else{FileNativeStore.tombstone(this,id);Toast.makeText(this,"Deletion tombstone queued",Toast.LENGTH_SHORT).show();recreate();}}).show();}
 private void historyDialog(String id){JSONArray h=FileNativeStore.history(this,id);if(h.length()==0){Toast.makeText(this,"No prior revisions yet",Toast.LENGTH_SHORT).show();return;}String[] rows=new String[h.length()];long[] revs=new long[h.length()];for(int i=0;i<h.length();i++){JSONObject x=h.optJSONObject(i);revs[i]=x==null?0:x.optLong("rev");String hash=x==null?"":x.optString("hash");rows[i]="Revision "+revs[i]+" · "+hash.substring(0,Math.min(12,hash.length()));}new AlertDialog.Builder(this).setTitle("Revision history").setItems(rows,(d,w)->new AlertDialog.Builder(this).setMessage("Restore revision "+revs[w]+" as a new revision of this same file ID?").setPositiveButton("Restore",(dd,ww)->{FileNativeStore.restoreRevision(this,id,revs[w]);Toast.makeText(this,"Revision restored with stable ID; sync scheduled",Toast.LENGTH_SHORT).show();recreate();}).setNegativeButton("Cancel",null).show()).show();}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
