package io.neo.omnitrix;

import android.content.*;import android.net.Uri;import android.provider.DocumentsContract;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;

/** v3.9 encrypted per-file provider transport over Android Storage Access Framework. */
public final class FileNativeTransport{
 private FileNativeTransport(){}
 public static JSONObject pushAll(Context c){JSONObject out=new JSONObject();int ok=0,fail=0;JSONArray a=FileNativeStore.index(c);for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null||"synced".equals(m.optString("sync")))continue;try{push(c,m.getString("id"));ok++;}catch(Exception e){fail++;SuiteSyncBus.notify(c,"Noogle Cloud","Retry queued for "+m.optString("title"));}}try{out.put("uploaded",ok);out.put("failed",fail);}catch(Exception ignored){}return out;}
 public static void push(Context c,String id)throws Exception{String tree=tree(c);if(tree.isEmpty())throw new IOException("No provider folder connected");JSONObject rec=FileNativeStore.exportRecord(c,id);if(rec==null)throw new IOException("File not found");JSONObject meta=rec.getJSONObject("meta");AccountE2eeVault vault=new AccountE2eeVault(c);vault.ensure();String enc=vault.encryptText(rec.toString());JSONObject env=new JSONObject();env.put("schema","neo.omnitrix.file/v1");env.put("profile","NEO-0001");env.put("id",id);env.put("rev",meta.optLong("rev"));env.put("hash",meta.optString("hash"));env.put("deviceId",new ProfileSyncVault(c).deviceId());env.put("updatedAt",meta.optLong("updatedAt"));env.put("payload",enc);env.put("signature",vault.sign(enc));write(c,tree,"neo-file-"+id+".json",env.toString());FileNativeStore.markSynced(c,id,meta.optLong("rev"));}
 public static JSONObject pullAll(Context c){JSONObject out=new JSONObject();int applied=0,conflicts=0,rejected=0;try{String tree=tree(c);if(tree.isEmpty())throw new IOException("No provider folder connected");JSONArray names=list(c,tree);for(int i=0;i<names.length();i++){String name=names.optString(i);if(!name.startsWith("neo-file-")||!name.endsWith(".json"))continue;try{String raw=read(c,tree,name);JSONObject env=new JSONObject(raw);AccountE2eeVault vault=new AccountE2eeVault(c);String enc=env.getString("payload");if(!vault.sign(enc).equals(env.getString("signature")))throw new SecurityException("Signature mismatch");String device=env.optString("deviceId");if(!isTrusted(c,device)&&!device.equals(new ProfileSyncVault(c).deviceId()))throw new SecurityException("Untrusted device");JSONObject remote=new JSONObject(vault.decryptText(enc));JSONObject rm=remote.getJSONObject("meta");JSONObject local=FileNativeStore.find(c,rm.getString("id"));if(local!=null&&local.optLong("rev")>local.optLong("remoteRev",0)&&rm.optLong("rev")>local.optLong("remoteRev",0)&&!local.optString("hash").equals(rm.optString("hash"))){FileNativeStore.conflictCopy(c,remote);conflicts++;if(rm.optLong("updatedAt")>=local.optLong("updatedAt"))FileNativeStore.importRecord(c,remote);}else{FileNativeStore.importRecord(c,remote);applied++;}}catch(SecurityException e){rejected++;}catch(Exception e){SuiteSyncBus.notify(c,"Noogle Cloud","Pull retry needed for "+name);}}}catch(Exception e){SuiteSyncBus.notify(c,"Noogle Cloud","File-native pull failed: "+e.getMessage());}try{out.put("applied",applied);out.put("conflicts",conflicts);out.put("rejected",rejected);}catch(Exception ignored){}return out;}
 private static boolean isTrusted(Context c,String id){try{JSONArray a=new JSONArray(c.getSharedPreferences("omnitrix_trusted_devices_v1",Context.MODE_PRIVATE).getString("devices","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return true;}}catch(Exception ignored){}return false;}
 private static String tree(Context c){return c.getSharedPreferences("omnitrix_cloud_provider",Context.MODE_PRIVATE).getString("tree","");}
 private static void write(Context c,String tree,String name,String body)throws Exception{Uri t=Uri.parse(tree),parent=DocumentsContract.buildDocumentUriUsingTree(t,DocumentsContract.getTreeDocumentId(t)),target=find(c,t,parent,name);if(target==null)target=DocumentsContract.createDocument(c.getContentResolver(),parent,"application/json",name);if(target==null)throw new IOException("Provider refused file creation");try(OutputStream o=c.getContentResolver().openOutputStream(target,"wt")){if(o==null)throw new IOException("Provider output unavailable");o.write(body.getBytes(StandardCharsets.UTF_8));}}
 private static String read(Context c,String tree,String name)throws Exception{Uri t=Uri.parse(tree),parent=DocumentsContract.buildDocumentUriUsingTree(t,DocumentsContract.getTreeDocumentId(t)),u=find(c,t,parent,name);if(u==null)throw new FileNotFoundException(name);try(InputStream in=c.getContentResolver().openInputStream(u)){if(in==null)throw new IOException("Provider input unavailable");ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] x=new byte[8192];for(int n;(n=in.read(x))>0;)b.write(x,0,n);return b.toString("UTF-8");}}
 private static JSONArray list(Context c,String tree){JSONArray a=new JSONArray();try{Uri t=Uri.parse(tree),p=DocumentsContract.buildDocumentUriUsingTree(t,DocumentsContract.getTreeDocumentId(t)),children=DocumentsContract.buildChildDocumentsUriUsingTree(t,DocumentsContract.getDocumentId(p));String[] cols={DocumentsContract.Document.COLUMN_DISPLAY_NAME};try(android.database.Cursor cur=c.getContentResolver().query(children,cols,null,null,null)){if(cur!=null)while(cur.moveToNext())a.put(cur.getString(0));}}catch(Exception ignored){}return a;}
 private static Uri find(Context c,Uri tree,Uri parent,String name){Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getDocumentId(parent));String[] p={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME};try(android.database.Cursor q=c.getContentResolver().query(children,p,null,null,null)){if(q!=null)while(q.moveToNext())if(name.equals(q.getString(1)))return DocumentsContract.buildDocumentUriUsingTree(tree,q.getString(0));}catch(Exception ignored){}return null;}
}
