package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** v3.9 file-native cloud library and sync status surface. */
public class FileLibraryActivity extends Activity{
 private LinearLayout body;
 @Override public void onCreate(Bundle b){super.onCreate(b);migrateLegacy();build();}
 private void migrateLegacy(){SharedPreferences w1=getSharedPreferences("omnitrix_wave1",MODE_PRIVATE);String[][] one={{"noogle-docs","Noogle Docs"},{"noogle-sheets","Noogle Sheets"},{"noogle-slides","Noogle Slides"},{"noogle-keep","Noogle Keep"}};for(String[] x:one){String body=w1.getString(x[0],"");if(!body.isEmpty()&&FileNativeStore.findByApp(this,x[0])==null)FileNativeStore.save(this,x[0],x[1],body,true);}SharedPreferences w2=getSharedPreferences("omnitrix_suite",MODE_PRIVATE);String[][] two={{"noogle-forms","Noogle Forms"},{"noogle-chat","Noogle Chat"}};for(String[] x:two){String body=w2.getString("wave2_"+x[0],"");if(!body.isEmpty()&&FileNativeStore.findByApp(this,x[0])==null)FileNativeStore.save(this,x[0],x[1],body,true);}}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(24));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);body.addView(text("NEO CLOUD FILES",24,Color.rgb(229,255,236)));body.addView(text("Omnitrix Suit v3.9 · NEO-0001 · File-native E2EE",11,Color.rgb(104,185,130)));Button push=primary("UPLOAD PENDING ENCRYPTED FILES");body.addView(push,new LinearLayout.LayoutParams(-1,dp(52)));push.setOnClickListener(v->{JSONObject r=FileNativeTransport.pushAll(this);Toast.makeText(this,"Uploaded "+r.optInt("uploaded")+" · failed "+r.optInt("failed"),Toast.LENGTH_LONG).show();recreate();});Button pull=secondary("DOWNLOAD / VERIFY / RECONCILE");body.addView(pull,new LinearLayout.LayoutParams(-1,dp(50)));pull.setOnClickListener(v->{JSONObject r=FileNativeTransport.pullAll(this);Toast.makeText(this,"Applied "+r.optInt("applied")+" · conflicts "+r.optInt("conflicts")+" · rejected "+r.optInt("rejected"),Toast.LENGTH_LONG).show();recreate();});JSONArray a=FileNativeStore.index(this);body.addView(text("FILES ("+a.length()+")",12,Color.rgb(118,255,151)));if(a.length()==0)body.addView(card("No file-native records yet. Save a Doc, Sheet, Slide, Keep note, Form, or Chat workspace."));for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String s=m.optString("title")+"\n"+m.optString("app")+" · rev "+m.optLong("rev")+" · "+m.optString("sync")+(m.optBoolean("deleted")?" · DELETED":"")+(m.optBoolean("offline")?" · OFFLINE":"");TextView t=card(s);String id=m.optString("id");t.setOnClickListener(v->{JSONObject cur=FileNativeStore.find(this,id);if(cur==null)return;FileNativeStore.setOffline(this,id,!cur.optBoolean("offline"));Toast.makeText(this,"Offline availability updated",Toast.LENGTH_SHORT).show();recreate();});t.setOnLongClickListener(v->{FileNativeStore.tombstone(this,id);Toast.makeText(this,"Deletion tombstone queued",Toast.LENGTH_SHORT).show();recreate();return true;});body.addView(t);}TextView note=text("Tap a file to toggle selective offline availability. Long-press to create a deletion tombstone. Conflict copies are preserved as separate records rather than silently overwriting content.",11,Color.rgb(110,145,121));note.setPadding(0,dp(14),0,0);body.addView(note);setContentView(sv);}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
