package io.neo.omnitrix;

import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** v4.8 editor for stable Form questions plus response analytics. */
public class FormManageActivity extends Activity {
 public static final String EXTRA_FILE_ID="file_id";private String fileId;private JSONObject form,meta;private LinearLayout body;
 @Override public void onCreate(Bundle s){super.onCreate(s);fileId=getIntent().getStringExtra(EXTRA_FILE_ID);meta=FileNativeStore.find(this,fileId);if(meta==null){finish();return;}form=StructuredWorkspace.form(FileNativeStore.body(this,fileId));build();}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(22));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);body.addView(text("FORM MANAGER + ANALYTICS",22,Color.WHITE));body.addView(text(meta.optString("title","Noogle Form"),13,Color.rgb(116,255,151)));JSONObject analytics=StructuredWorkspace.responseAnalytics(form);body.addView(text("Responses: "+analytics.optInt("responses"),13,Color.LTGRAY));JSONArray stats=analytics.optJSONArray("questions"),qs=form.optJSONArray("questions");if(qs!=null)for(int i=0;i<qs.length();i++){JSONObject q=qs.optJSONObject(i);if(q==null)continue;JSONObject st=stats==null?null:stats.optJSONObject(i);String line=(i+1)+". "+q.optString("prompt")+" · "+q.optString("type")+(q.optBoolean("required")?" · required":"");if(st!=null)line+=" · "+st.optDouble("completionRate")+"% answered";body.addView(text(line,13,Color.rgb(205,235,213)));if(st!=null&&"choice".equals(q.optString("type"))){JSONObject counts=st.optJSONObject("counts");JSONArray names=counts==null?null:counts.names();if(names!=null)for(int j=0;j<names.length();j++){String n=names.optString(j);body.addView(text("   "+n+": "+counts.optInt(n),11,Color.rgb(142,182,154)));}}String qid=q.optString("id");Button edit=button("EDIT QUESTION");body.addView(edit);edit.setOnClickListener(v->editQuestion(qid));Button del=button("DELETE QUESTION");body.addView(del);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete question?").setMessage("The question and its answer field will be removed from this form revision. Existing other answers remain.").setPositiveButton("DELETE",(d,w)->{if(StructuredWorkspace.deleteQuestion(form,qid)){save();recreate();}}).setNegativeButton("Cancel",null).show());}setContentView(sv);}
 private void editQuestion(String id){JSONObject q=findQuestion(id);if(q==null)return;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText prompt=input("Prompt");prompt.setText(q.optString("prompt"));box.addView(prompt);Spinner type=new Spinner(this);String[] types={"text","choice","number","date","email"};type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,types));for(int i=0;i<types.length;i++)if(types[i].equals(q.optString("type")))type.setSelection(i);box.addView(type);EditText options=input("Choice options, comma-separated");JSONArray a=q.optJSONArray("options");StringBuilder joined=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++){if(i>0)joined.append(", ");joined.append(a.optString(i));}options.setText(joined.toString());box.addView(options);CheckBox req=new CheckBox(this);req.setText("Required");req.setChecked(q.optBoolean("required"));box.addView(req);new AlertDialog.Builder(this).setTitle("Edit question").setView(box).setPositiveButton("SAVE",(d,w)->{if(StructuredWorkspace.updateQuestion(form,id,prompt.getText().toString(),String.valueOf(type.getSelectedItem()),req.isChecked(),options.getText().toString())){save();recreate();}}).setNegativeButton("Cancel",null).show();}
 private JSONObject findQuestion(String id){JSONArray q=form.optJSONArray("questions");if(q!=null)for(int i=0;i<q.length();i++){JSONObject x=q.optJSONObject(i);if(x!=null&&id.equals(x.optString("id")))return x;}return null;}
 private void save(){FileNativeStore.saveId(this,fileId,"noogle-forms",meta.optString("title","Noogle Form"),StructuredWorkspace.pretty(form),true);}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);return e;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
