package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;

/** v4.9 response review/export + local analytics dashboard. Source data remains in FileNativeStore/E2EE. */
public class FormResponsesActivity extends Activity {
 public static final String EXTRA_FILE_ID="file_id";private String fileId;private LinearLayout body;
 @Override public void onCreate(Bundle s){super.onCreate(s);fileId=getIntent().getStringExtra(EXTRA_FILE_ID);build();}
 private void build(){ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(22));body.setBackgroundColor(Color.rgb(1,5,3));sv.addView(body);body.addView(text("Noogle Forms · Responses + Analytics",23,Color.WHITE));JSONObject meta=FileNativeStore.find(this,fileId);if(meta==null){body.addView(text("Form file not found.",14,Color.LTGRAY));setContentView(sv);return;}JSONObject form=StructuredWorkspace.form(FileNativeStore.body(this,fileId));JSONArray qs=form.optJSONArray("questions"),rs=form.optJSONArray("responses");int total=rs==null?0:rs.length();body.addView(text(meta.optString("title","Noogle Form")+" · "+total+" responses",12,Color.rgb(116,255,151)));renderAnalytics(form,qs,total);body.addView(text("INDIVIDUAL RESPONSES",12,Color.rgb(116,255,151)));if(rs==null||rs.length()==0)body.addView(text("No submitted responses yet.",14,Color.LTGRAY));else for(int i=0;i<rs.length();i++){JSONObject r=rs.optJSONObject(i);if(r==null)continue;body.addView(text("Response "+(i+1)+" · "+r.optString("id"),13,Color.WHITE));JSONObject a=r.optJSONObject("answers");if(qs!=null)for(int q=0;q<qs.length();q++){JSONObject d=qs.optJSONObject(q);if(d==null)continue;String val=a==null?"":a.optString(d.optString("id"));body.addView(text(d.optString("prompt")+": "+val,12,Color.rgb(202,233,210)));}}Button share=new Button(this);share.setText("EXPORT RESPONSES AS CSV");body.addView(share,new LinearLayout.LayoutParams(-1,dp(52)));share.setOnClickListener(v->shareCsv(form,meta.optString("title","Noogle Form")));setContentView(sv);}
 private void renderAnalytics(JSONObject form,JSONArray qs,int total){body.addView(text("ANALYTICS",12,Color.rgb(116,255,151)));JSONObject all=StructuredWorkspace.analytics(form);if(qs==null||qs.length()==0){body.addView(text("Add questions to generate analytics.",13,Color.LTGRAY));return;}for(int i=0;i<qs.length();i++){JSONObject q=qs.optJSONObject(i);if(q==null)continue;JSONObject a=all.optJSONObject(q.optString("id"));if(a==null)continue;int answered=a.optInt("answered"),blank=a.optInt("blank");int pct=total==0?0:(int)Math.round(answered*100.0/total);body.addView(text(q.optString("prompt")+" · "+pct+"% answered · "+blank+" blank",13,Color.WHITE));JSONObject counts=a.optJSONObject("counts");if(counts!=null){java.util.Iterator<String> keys=counts.keys();while(keys.hasNext()){String k=keys.next();int n=counts.optInt(k);int cp=answered==0?0:(int)Math.round(n*100.0/answered);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);bar.setProgress(cp);body.addView(text(k+" · "+n+" ("+cp+"%)",12,Color.rgb(202,233,210)));body.addView(bar,new LinearLayout.LayoutParams(-1,dp(18)));}}}}
 private void shareCsv(JSONObject form,String title){String csv=StructuredWorkspace.responsesCsv(form);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_SUBJECT,title+" responses");i.putExtra(Intent.EXTRA_TEXT,csv);try{startActivity(Intent.createChooser(i,"Export form responses"));}catch(Exception e){Toast.makeText(this,"No compatible share target",Toast.LENGTH_SHORT).show();}}
 private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(6),0,dp(6));return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
