package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** Omnitrix Suit v3.9 E2EE cloud/sync dashboard. */
public class NeoCloudHubActivity extends Activity {
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);build();}
 private void build(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(24));sv.addView(r);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);r.addView(logo,new LinearLayout.LayoutParams(dp(70),dp(70)));r.addView(text("NEO CLOUD + SYNC",24,Color.rgb(229,255,236)));r.addView(text("Omnitrix Suit v3.9 · NEO-0001 · File-native E2EE",11,Color.rgb(104,185,130)));ProfileSyncVault pv=new ProfileSyncVault(this);AccountE2eeVault e2ee=new AccountE2eeVault(this);e2ee.ensure();TextView intro=text("Device "+pv.deviceId()+" · encrypted account content key active · per-file provider sync enabled.",12,Color.rgb(184,218,194));intro.setPadding(0,dp(10),0,dp(12));r.addView(intro);Button files=primary("NEO CLOUD FILES / SYNC STATUS");r.addView(files,new LinearLayout.LayoutParams(-1,dp(52)));files.setOnClickListener(v->startActivity(new Intent(this,FileLibraryActivity.class)));Button security=secondary("ACCOUNT E2EE / TRUSTED DEVICES");r.addView(security,new LinearLayout.LayoutParams(-1,dp(50)));security.setOnClickListener(v->startActivity(new Intent(this,TrustedDevicesActivity.class)));Button providers=secondary("CLOUD / STORAGE PROVIDER");r.addView(providers,new LinearLayout.LayoutParams(-1,dp(50)));providers.setOnClickListener(v->startActivity(new Intent(this,CloudProviderActivity.class)));section(r,"RECENT FILES / ACTIVITY",SuiteSyncBus.read(this,"recent"));section(r,"FAVORITES",SuiteSyncBus.read(this,"favorites"));section(r,"NOTIFICATIONS",SuiteSyncBus.read(this,"notifications"));section(r,"OFFLINE SYNC QUEUE",SuiteSyncBus.read(this,"queue"));TextView note=text("v3.9 adds file-native records with stable IDs, revision counters, SHA-256 content hashes, deletion tombstones, selective offline availability, signed encrypted provider objects, and conflict-copy reconciliation. Wallet/XCP Key material remains outside NEO Cloud.",11,Color.rgb(110,145,121));note.setPadding(0,dp(16),0,dp(10));r.addView(note);shell.addView(sv,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"NEO"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);}
 private void section(LinearLayout r,String title,JSONArray a){TextView h=text(title,12,Color.rgb(118,255,151));h.setPadding(0,dp(14),0,dp(6));r.addView(h);if(a.length()==0){r.addView(card("Nothing here yet."));return;}for(int i=0;i<Math.min(a.length(),8);i++){JSONObject o=a.optJSONObject(i);if(o!=null)r.addView(card(o.optString("app")+" · "+o.optString("title")+(o.optString("state").isEmpty()?"":"\n"+o.optString("state"))));}}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(6));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
