package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.webkit.*;import android.widget.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;

/** v4.3 dedicated Omnitrix/Noogle browser entry surface for internal deep links and suite search intents. */
public class NoogleBrowserActivity extends Activity {
 public static final String EXTRA_URL="open_url",EXTRA_QUERY="search_query";private static final String HOME="https://shemsizedek.github.io/neo-system/noogle/";private WebView web;private EditText address;
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);build();configure();String target=resolve(getIntent());web.loadUrl(target);}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(web!=null)web.loadUrl(resolve(i));}
 private String resolve(Intent i){String u=i==null?null:i.getStringExtra(EXTRA_URL);if(u!=null&&u.startsWith("https://"))return u;String q=i==null?null:i.getStringExtra(EXTRA_QUERY);if(q!=null&&!q.trim().isEmpty())try{return HOME+"?q="+URLEncoder.encode(q.trim(),StandardCharsets.UTF_8.name());}catch(Exception ignored){}Uri d=i==null?null:i.getData();if(d!=null&&"https".equalsIgnoreCase(d.getScheme()))return d.toString();return HOME;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(1,5,3));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(6),dp(5),dp(6),dp(5));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);bar.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));Button back=nav("‹");back.setOnClickListener(v->{if(web.canGoBack())web.goBack();else finish();});bar.addView(back);Button reload=nav("↻");reload.setOnClickListener(v->web.reload());bar.addView(reload);address=new EditText(this);address.setSingleLine(true);address.setTextColor(Color.WHITE);address.setHintTextColor(Color.rgb(105,135,114));address.setHint("Search Noogle or enter HTTPS URL");address.setImeOptions(2);address.setOnEditorActionListener((v,a,e)->{navigate(address.getText().toString());return true;});LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(42),1f);ap.setMargins(dp(5),0,0,0);bar.addView(address,ap);root.addView(bar,new LinearLayout.LayoutParams(-1,dp(54)));web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1f));setContentView(root);}
 private void configure(){WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSafeBrowsingEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);web.setBackgroundColor(Color.rgb(1,5,3));web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(u.startsWith("https://"))return false;if(u.startsWith("mailto:")||u.startsWith("tel:")){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}return true;}Toast.makeText(NoogleBrowserActivity.this,"Blocked unsafe URL scheme",Toast.LENGTH_SHORT).show();return true;}@Override public void onPageFinished(WebView v,String u){address.setText(u!=null&&u.startsWith(HOME)?"":u);}});}
 private void navigate(String raw){String v=raw==null?"":raw.trim();if(v.isEmpty())return;if(v.startsWith("https://"))web.loadUrl(v);else if(v.matches("^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}(/.*)?$"))web.loadUrl("https://"+v);else try{web.loadUrl(HOME+"?q="+URLEncoder.encode(v,StandardCharsets.UTF_8.name()));}catch(Exception ignored){web.loadUrl(HOME);}}
 private Button nav(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(190,235,202));b.setBackgroundColor(Color.TRANSPARENT);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(9),0,dp(9),0);return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}
