package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.webkit.*;import android.widget.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.util.*;

/** v4.4 unified Noogle/Omnitrix browser entry surface with lightweight tabs and suite deep-link routing. */
public class NoogleBrowserActivity extends Activity {
 public static final String EXTRA_URL="open_url",EXTRA_QUERY="search_query";private static final String HOME="https://shemsizedek.github.io/neo-system/noogle/";private WebView web;private EditText address;private final ArrayList<String> tabs=new ArrayList<>();private int active=0;
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);build();configure();String target=resolve(getIntent());tabs.add(target);web.loadUrl(target);}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String target=resolve(i);if(tabs.isEmpty())tabs.add(target);else tabs.set(active,target);if(web!=null)web.loadUrl(target);}
 private String resolve(Intent i){String u=i==null?null:i.getStringExtra(EXTRA_URL);if(u!=null&&u.startsWith("https://"))return u;String q=i==null?null:i.getStringExtra(EXTRA_QUERY);if(q!=null&&!q.trim().isEmpty())try{return HOME+"?q="+URLEncoder.encode(q.trim(),StandardCharsets.UTF_8.name());}catch(Exception ignored){}Uri d=i==null?null:i.getData();if(d!=null&&"https".equalsIgnoreCase(d.getScheme()))return d.toString();return HOME;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(1,5,3));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(6),dp(5),dp(6),dp(5));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);logo.setContentDescription("Noogle home");logo.setOnClickListener(v->open(HOME));bar.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));Button back=nav("‹");back.setOnClickListener(v->{if(web.canGoBack())web.goBack();else finish();});bar.addView(back);Button reload=nav("↻");reload.setOnClickListener(v->web.reload());bar.addView(reload);address=new EditText(this);address.setSingleLine(true);address.setTextColor(Color.WHITE);address.setHintTextColor(Color.rgb(105,135,114));address.setHint("Search Noogle or enter HTTPS URL");address.setImeOptions(2);address.setOnEditorActionListener((v,a,e)->{navigate(address.getText().toString());return true;});LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,dp(42),1f);ap.setMargins(dp(5),0,dp(5),0);bar.addView(address,ap);Button tab=nav("▣");tab.setOnClickListener(v->showTabs());bar.addView(tab);Button full=nav("⋮");full.setOnClickListener(v->showMenu());bar.addView(full);root.addView(bar,new LinearLayout.LayoutParams(-1,dp(54)));web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1f));setContentView(root);}
 private void configure(){WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSafeBrowsingEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);web.setBackgroundColor(Color.rgb(1,5,3));web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(u.startsWith("https://"))return false;if(u.startsWith("mailto:")||u.startsWith("tel:")){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}return true;}Toast.makeText(NoogleBrowserActivity.this,"Blocked unsafe URL scheme",Toast.LENGTH_SHORT).show();return true;}@Override public void onPageFinished(WebView v,String u){address.setText(u!=null&&u.startsWith(HOME)?"":u);if(!tabs.isEmpty())tabs.set(active,u==null?HOME:u);}});}
 private void navigate(String raw){String v=raw==null?"":raw.trim();if(v.isEmpty())return;if(v.startsWith("https://"))open(v);else if(v.matches("^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}(/.*)?$"))open("https://"+v);else try{open(HOME+"?q="+URLEncoder.encode(v,StandardCharsets.UTF_8.name()));}catch(Exception ignored){open(HOME);}}
 private void open(String url){if(tabs.isEmpty())tabs.add(url);else tabs.set(active,url);web.loadUrl(url);}
 private void newTab(){tabs.add(HOME);active=tabs.size()-1;web.clearHistory();web.loadUrl(HOME);}
 private void showTabs(){String[] rows=new String[tabs.size()+1];for(int i=0;i<tabs.size();i++)rows[i]=(i==active?"● ":"○ ")+tabs.get(i);rows[rows.length-1]="＋ New tab";new AlertDialog.Builder(this).setTitle("Omnitrix Tabs").setItems(rows,(d,w)->{if(w==tabs.size())newTab();else{active=w;web.clearHistory();web.loadUrl(tabs.get(active));}}).setNegativeButton("Done",null).show();}
 private void showMenu(){new AlertDialog.Builder(this).setTitle("Omnitrix Browser v4.4").setItems(new String[]{"New tab","Noogle home","Share page","Open legacy full browser"},(d,w)->{if(w==0)newTab();else if(w==1)open(HOME);else if(w==2)share();else startActivity(new Intent(this,MainActivityV14.class));}).show();}
 private void share(){String u=web.getUrl();if(u==null)u=HOME;Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,u);startActivity(Intent.createChooser(i,"Share with"));}
 private Button nav(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(190,235,202));b.setBackgroundColor(Color.TRANSPARENT);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(9),0,dp(9),0);return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}
