package io.neo.omnitrix;

import android.content.*;import android.net.Uri;import android.provider.DocumentsContract;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;

/** v3.8 signed E2EE provider transport and conflict-copy engine. */
public final class ProviderSyncEngine {
 private static final String FILE="omnitrix-NEO-0001-e2ee.json", PREFS="omnitrix_provider_sync_v2";
 private final Context c; private final AccountE2eeVault e2ee; private final ProfileSyncVault profile;
 public ProviderSyncEngine(Context c){this.c=c.getApplicationContext();e2ee=new AccountE2eeVault(c);profile=new ProfileSyncVault(c);e2ee.ensure();}
 public String upload(){try{Uri tree=tree();JSONArray q=SuiteSyncBus.read(c,"queue");JSONObject payload=new JSONObject();payload.put("schema","neo.omnitrix.sync-payload/v2");payload.put("profile","NEO-0001");payload.put("deviceId",profile.deviceId());payload.put("updatedAt",System.currentTimeMillis());payload.put("items",q);String encrypted=e2ee.encryptText(payload.toString());JSONObject env=envelope(encrypted,payload.getLong("updatedAt"),profile.deviceId());write(tree,FILE,env.toString(2));prefs().edit().putLong("lastUpload",payload.getLong("updatedAt")).putString("lastHash",sha(encrypted)).apply();SuiteSyncBus.clearQueue(c);SuiteSyncBus.notify(c,"Noogle Cloud","Encrypted provider upload completed");return "Uploaded "+q.length()+" encrypted item(s).";}catch(Exception e){retry("upload",e);return "Upload failed: "+msg(e);}}
 public String download(){try{Uri tree=tree();String raw=read(tree,FILE);if(raw==null||raw.isEmpty())return "No remote E2EE payload found.";JSONObject env=new JSONObject(raw);String encrypted=env.getString("payload"),sig=env.getString("signature"),device=env.optString("deviceId","");if(!constant(sig,e2ee.sign(encrypted)))throw new SecurityException("Remote signature verification failed");if(!trusted(device))throw new SecurityException("Remote device is not trusted: "+device);String plain=e2ee.decryptText(encrypted);JSONObject remote=new JSONObject(plain);long remoteTs=remote.optLong("updatedAt",0), localTs=prefs().getLong("lastLocalMutation",0), last=prefs().getLong("lastDownload",0);JSONArray items=remote.optJSONArray("items");if(items==null)items=new JSONArray();String policy=new ProfileSyncVault(c).load().optString("conflictPolicy","newest-wins-with-copy");boolean conflict=localTs>last&&remoteTs>last;if(conflict){String conflictCopy="conflict-"+System.currentTimeMillis()+".json";write(tree,conflictCopy,plain);SuiteSyncBus.notify(c,"Noogle Cloud","Conflict preserved as "+conflictCopy);if("local-first".equals(policy))return "Conflict detected. Local state kept; remote copy preserved.";}for(int i=items.length()-1;i>=0;i--){JSONObject o=items.optJSONObject(i);if(o!=null)SuiteSyncBus.queueSync(c,o.optString("app"),o.optString("title"),o.optString("ref"));}prefs().edit().putLong("lastDownload",remoteTs).putString("lastRemoteHash",sha(encrypted)).apply();SuiteSyncBus.notify(c,"Noogle Cloud","Verified encrypted provider download completed");return "Downloaded and verified "+items.length()+" item(s)"+(conflict?" with conflict copy.":".");}catch(Exception e){retry("download",e);return "Download failed: "+msg(e);}}
 public void markLocalMutation(){prefs().edit().putLong("lastLocalMutation",System.currentTimeMillis()).apply();}
 public String status(){return "upload="+prefs().getLong("lastUpload",0)+" · download="+prefs().getLong("lastDownload",0)+" · retries="+retryCount();}
 private JSONObject envelope(String encrypted,long ts,String device)throws Exception{JSONObject o=new JSONObject();o.put("schema","neo.omnitrix.provider-envelope/v2");o.put("profile","NEO-0001");o.put("deviceId",device);o.put("updatedAt",ts);o.put("payload",encrypted);o.put("signature",e2ee.sign(encrypted));return o;}
 private boolean trusted(String d){if(d.equals(profile.deviceId()))return true;try{JSONArray a=new JSONArray(c.getSharedPreferences("omnitrix_trusted_devices_v1",Context.MODE_PRIVATE).getString("devices","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&d.equals(o.optString("id")))return true;}}catch(Exception ignored){}return false;}
 private Uri tree(){String s=c.getSharedPreferences("omnitrix_cloud_provider",Context.MODE_PRIVATE).getString("tree","");if(s.isEmpty())throw new IllegalStateException("No provider folder connected");return Uri.parse(s);}
 private void write(Uri tree,String name,String text)throws Exception{Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));Uri target=find(parent,tree,name);if(target==null)target=DocumentsContract.createDocument(c.getContentResolver(),parent,"application/json",name);if(target==null)throw new IOException("Provider refused file creation");try(OutputStream out=c.getContentResolver().openOutputStream(target,"wt")){if(out==null)throw new IOException("Provider output unavailable");out.write(text.getBytes(StandardCharsets.UTF_8));}}
 private String read(Uri tree,String name)throws Exception{Uri parent=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));Uri target=find(parent,tree,name);if(target==null)return null;try(InputStream in=c.getContentResolver().openInputStream(target)){if(in==null)return null;ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[4096];for(int n;(n=in.read(buf))>0;)b.write(buf,0,n);return b.toString("UTF-8");}}
 private Uri find(Uri parent,Uri tree,String name){Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getDocumentId(parent));String[] p={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME};try(android.database.Cursor cur=c.getContentResolver().query(children,p,null,null,null)){if(cur!=null)while(cur.moveToNext())if(name.equals(cur.getString(1)))return DocumentsContract.buildDocumentUriUsingTree(tree,cur.getString(0));}catch(Exception ignored){}return null;}
 private void retry(String op,Exception e){int n=prefs().getInt("retryCount",0)+1;prefs().edit().putInt("retryCount",n).putString("lastError",op+": "+msg(e)).apply();SuiteSyncBus.notify(c,"Noogle Cloud","Provider "+op+" queued for retry: "+msg(e));}
 private int retryCount(){return prefs().getInt("retryCount",0);}private SharedPreferences prefs(){return c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);}private String sha(String s)throws Exception{byte[] h=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:h)b.append(String.format("%02x",x));return b.toString();}private boolean constant(String a,String b){return MessageDigest.isEqual(a.getBytes(StandardCharsets.UTF_8),b.getBytes(StandardCharsets.UTF_8));}private String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
}
