package io.neo.omnitrix;

import org.json.*;import java.util.UUID;

/** Structured E2EE file-body codec for Noogle Forms and Chat. */
public final class StructuredWorkspace {
 private StructuredWorkspace(){}
 private static String uid(){return UUID.randomUUID().toString();}
 public static JSONObject form(String body){
  JSONObject p=parse(body);if(p.has("questions")){try{p.put("schema","neo.noogle.form/v4");if(!p.has("formId"))p.put("formId",uid());if(!p.has("responses"))p.put("responses",new JSONArray());JSONArray q=p.optJSONArray("questions");if(q!=null)for(int i=0;i<q.length();i++){JSONObject d=q.optJSONObject(i);if(d!=null&&!d.has("options"))d.put("options",new JSONArray());}return p;}catch(Exception ignored){}}
  try{JSONObject o=new JSONObject();o.put("schema","neo.noogle.form/v4");o.put("formId",uid());o.put("description",body==null?"":body);o.put("questions",new JSONArray());o.put("responses",new JSONArray());return o;}catch(Exception e){return new JSONObject();}
 }
 public static void addQuestion(JSONObject f,String prompt,String type,boolean required){addQuestion(f,prompt,type,required,"");}
 public static void addQuestion(JSONObject f,String prompt,String type,boolean required,String choices){try{JSONArray a=f.optJSONArray("questions");if(a==null){a=new JSONArray();f.put("questions",a);}JSONObject q=new JSONObject();q.put("id",uid());q.put("prompt",prompt==null?"":prompt.trim());q.put("type",type==null?"text":type);q.put("required",required);JSONArray opts=new JSONArray();if(choices!=null)for(String s:choices.split(",")){String v=s.trim();if(!v.isEmpty())opts.put(v);}q.put("options",opts);a.put(q);}catch(Exception ignored){}}
 public static void addResponse(JSONObject f,JSONObject answers){try{JSONArray a=f.optJSONArray("responses");if(a==null){a=new JSONArray();f.put("responses",a);}JSONObject r=new JSONObject();r.put("id",uid());r.put("createdAt",System.currentTimeMillis());r.put("answers",answers==null?new JSONObject():answers);a.put(r);}catch(Exception ignored){}}
 public static String responsesCsv(JSONObject f){StringBuilder b=new StringBuilder();JSONArray q=f.optJSONArray("questions"),r=f.optJSONArray("responses");b.append("response_id,created_at");if(q!=null)for(int i=0;i<q.length();i++){JSONObject d=q.optJSONObject(i);b.append(',').append(csv(d==null?"question":d.optString("prompt")));}b.append('\n');if(r!=null)for(int i=0;i<r.length();i++){JSONObject row=r.optJSONObject(i);if(row==null)continue;b.append(csv(row.optString("id"))).append(',').append(row.optLong("createdAt"));JSONObject a=row.optJSONObject("answers");if(q!=null)for(int j=0;j<q.length();j++){JSONObject d=q.optJSONObject(j);String v=a==null||d==null?"":a.optString(d.optString("id"));b.append(',').append(csv(v));}b.append('\n');}return b.toString();}
 private static String csv(String s){String v=s==null?"":s;return "\""+v.replace("\"","\"\"")+"\"";}
 public static JSONObject chat(String body){
  JSONObject p=parse(body);if(p.has("messages")){try{p.put("schema","neo.noogle.chat/v4");if(!p.has("workspaceId"))p.put("workspaceId",uid());JSONArray channels=p.optJSONArray("channels");String legacyId=p.optString("channelId");String legacyName=p.optString("channel","general");if(channels==null||channels.length()==0){channels=new JSONArray();JSONObject c=new JSONObject();c.put("id",legacyId.isEmpty()?uid():legacyId);c.put("name",legacyName.isEmpty()?"general":legacyName);c.put("createdAt",System.currentTimeMillis());c.put("lastReadAt",0);channels.put(c);p.put("channels",channels);}for(int i=0;i<channels.length();i++){JSONObject c=channels.optJSONObject(i);if(c!=null&&!c.has("lastReadAt"))c.put("lastReadAt",0);}String active=p.optString("activeChannelId");if(active.isEmpty()){JSONObject c=channels.optJSONObject(0);active=c==null?uid():c.optString("id",uid());p.put("activeChannelId",active);}JSONArray a=p.optJSONArray("messages");if(a!=null)for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m!=null){if(!m.has("id"))m.put("id",uid());if(!m.has("channelId"))m.put("channelId",active);if(!m.has("threadId"))m.put("threadId",JSONObject.NULL);}}return p;}catch(Exception ignored){}}
  try{JSONObject o=new JSONObject();o.put("schema","neo.noogle.chat/v4");o.put("workspaceId",uid());o.put("participants","");JSONArray channels=new JSONArray();JSONObject c=new JSONObject();String cid=uid();c.put("id",cid);c.put("name","general");c.put("createdAt",System.currentTimeMillis());c.put("lastReadAt",0);channels.put(c);o.put("channels",channels);o.put("activeChannelId",cid);o.put("messages",new JSONArray());return o;}catch(Exception e){return new JSONObject();}
 }
 public static String addChannel(JSONObject chat,String name){try{JSONArray a=chat.optJSONArray("channels");if(a==null){a=new JSONArray();chat.put("channels",a);}String id=uid();JSONObject c=new JSONObject();c.put("id",id);String n=name==null?"":name.trim();c.put("name",n.isEmpty()?"channel":n);c.put("createdAt",System.currentTimeMillis());c.put("lastReadAt",System.currentTimeMillis());a.put(c);chat.put("activeChannelId",id);return id;}catch(Exception e){return "";}}
 public static boolean renameChannel(JSONObject chat,String channelId,String name){try{JSONArray a=chat.optJSONArray("channels");if(a==null)return false;String n=name==null?"":name.trim();if(n.isEmpty())return false;for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null&&channelId.equals(c.optString("id"))){c.put("name",n);return true;}}}catch(Exception ignored){}return false;}
 public static boolean deleteChannel(JSONObject chat,String channelId){try{JSONArray a=chat.optJSONArray("channels");if(a==null||a.length()<=1)return false;JSONArray out=new JSONArray();String next="";for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c==null)continue;if(!channelId.equals(c.optString("id"))){out.put(c);if(next.isEmpty())next=c.optString("id");}}chat.put("channels",out);JSONArray msgs=chat.optJSONArray("messages"),kept=new JSONArray();if(msgs!=null)for(int i=0;i<msgs.length();i++){JSONObject m=msgs.optJSONObject(i);if(m!=null&&!channelId.equals(m.optString("channelId")))kept.put(m);}chat.put("messages",kept);if(channelId.equals(chat.optString("activeChannelId")))chat.put("activeChannelId",next);return true;}catch(Exception ignored){}return false;}
 public static void setActiveChannel(JSONObject chat,String channelId){try{if(channelId!=null&&!channelId.trim().isEmpty())chat.put("activeChannelId",channelId.trim());}catch(Exception ignored){}}
 public static void markChannelRead(JSONObject chat,String channelId){try{JSONArray a=chat.optJSONArray("channels");if(a!=null)for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null&&channelId.equals(c.optString("id"))){c.put("lastReadAt",System.currentTimeMillis());break;}}}catch(Exception ignored){}}
 public static int unreadCount(JSONObject chat,String channelId,String localAlias){long read=0;JSONArray c=chat.optJSONArray("channels");if(c!=null)for(int i=0;i<c.length();i++){JSONObject x=c.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("id"))){read=x.optLong("lastReadAt");break;}}int n=0;JSONArray m=chat.optJSONArray("messages");if(m!=null)for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("channelId"))&&x.optLong("createdAt")>read&&!x.optString("author").equalsIgnoreCase(localAlias==null?"Local":localAlias))n++;}return n;}
 public static int mentionCount(JSONObject chat,String channelId,String alias){String needle="@"+(alias==null||alias.trim().isEmpty()?"Local":alias.trim()).toLowerCase();long read=0;JSONArray c=chat.optJSONArray("channels");if(c!=null)for(int i=0;i<c.length();i++){JSONObject x=c.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("id"))){read=x.optLong("lastReadAt");break;}}int n=0;JSONArray m=chat.optJSONArray("messages");if(m!=null)for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("channelId"))&&x.optLong("createdAt")>read&&x.optString("text").toLowerCase().contains(needle))n++;}return n;}
 public static void addMessage(JSONObject chat,String text,String author){addMessage(chat,text,author,chat.optString("activeChannelId"),null);}
 public static void addMessage(JSONObject chat,String text,String author,String channelId,String threadId){try{JSONArray a=chat.optJSONArray("messages");if(a==null){a=new JSONArray();chat.put("messages",a);}JSONObject m=new JSONObject();m.put("id",uid());m.put("channelId",channelId==null||channelId.trim().isEmpty()?chat.optString("activeChannelId"):channelId.trim());m.put("text",text==null?"":text.trim());m.put("author",author==null||author.trim().isEmpty()?"Local":author.trim());m.put("createdAt",System.currentTimeMillis());if(threadId==null||threadId.trim().isEmpty())m.put("threadId",JSONObject.NULL);else m.put("threadId",threadId.trim());a.put(m);}catch(Exception ignored){}}
 public static String pretty(JSONObject o){return o==null?"{}":o.toString();}
 private static JSONObject parse(String s){try{return s==null||s.trim().isEmpty()?new JSONObject():new JSONObject(s);}catch(Exception e){return new JSONObject();}}
}
