package io.neo.omnitrix;

import org.json.*;import java.util.UUID;

/** Structured E2EE file-body codec for Noogle Forms and Chat. */
public final class StructuredWorkspace {
 private StructuredWorkspace(){}
 private static String uid(){return UUID.randomUUID().toString();}
 public static JSONObject form(String body){
  JSONObject p=parse(body);if(p.has("questions")){try{p.put("schema","neo.noogle.form/v5");if(!p.has("formId"))p.put("formId",uid());if(!p.has("responses"))p.put("responses",new JSONArray());JSONArray q=p.optJSONArray("questions");if(q!=null)for(int i=0;i<q.length();i++){JSONObject d=q.optJSONObject(i);if(d!=null){if(!d.has("id"))d.put("id",uid());if(!d.has("options"))d.put("options",new JSONArray());}}return p;}catch(Exception ignored){}}
  try{JSONObject o=new JSONObject();o.put("schema","neo.noogle.form/v5");o.put("formId",uid());o.put("description",body==null?"":body);o.put("questions",new JSONArray());o.put("responses",new JSONArray());return o;}catch(Exception e){return new JSONObject();}
 }
 public static void addQuestion(JSONObject f,String prompt,String type,boolean required){addQuestion(f,prompt,type,required,"");}
 public static void addQuestion(JSONObject f,String prompt,String type,boolean required,String choices){try{JSONArray a=f.optJSONArray("questions");if(a==null){a=new JSONArray();f.put("questions",a);}JSONObject q=new JSONObject();q.put("id",uid());q.put("prompt",prompt==null?"":prompt.trim());q.put("type",type==null?"text":type);q.put("required",required);q.put("options",choices(choices));a.put(q);}catch(Exception ignored){}}
 public static boolean updateQuestion(JSONObject f,String id,String prompt,String type,boolean required,String values){try{JSONArray a=f.optJSONArray("questions");if(a==null)return false;for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q!=null&&id.equals(q.optString("id"))){String p=prompt==null?"":prompt.trim();if(p.isEmpty())return false;q.put("prompt",p);q.put("type",type==null?"text":type);q.put("required",required);q.put("options",choices(values));return true;}}}catch(Exception ignored){}return false;}
 public static boolean deleteQuestion(JSONObject f,String id){try{JSONArray q=f.optJSONArray("questions");if(q==null)return false;JSONArray out=new JSONArray();boolean removed=false;for(int i=0;i<q.length();i++){JSONObject x=q.optJSONObject(i);if(x!=null&&id.equals(x.optString("id"))){removed=true;continue;}if(x!=null)out.put(x);}if(!removed)return false;f.put("questions",out);JSONArray r=f.optJSONArray("responses");if(r!=null)for(int i=0;i<r.length();i++){JSONObject row=r.optJSONObject(i),a=row==null?null:row.optJSONObject("answers");if(a!=null)a.remove(id);}return true;}catch(Exception ignored){}return false;}
 private static JSONArray choices(String values){JSONArray a=new JSONArray();if(values!=null)for(String s:values.split(",")){String v=s.trim();if(!v.isEmpty())a.put(v);}return a;}
 public static void addResponse(JSONObject f,JSONObject answers){try{JSONArray a=f.optJSONArray("responses");if(a==null){a=new JSONArray();f.put("responses",a);}JSONObject r=new JSONObject();r.put("id",uid());r.put("createdAt",System.currentTimeMillis());r.put("answers",answers==null?new JSONObject():answers);a.put(r);}catch(Exception ignored){}}
 public static JSONObject responseAnalytics(JSONObject f){JSONObject out=new JSONObject();try{JSONArray qs=f.optJSONArray("questions"),rs=f.optJSONArray("responses");int total=rs==null?0:rs.length();out.put("responses",total);JSONArray items=new JSONArray();if(qs!=null)for(int i=0;i<qs.length();i++){JSONObject q=qs.optJSONObject(i);if(q==null)continue;String qid=q.optString("id");JSONObject item=new JSONObject();item.put("id",qid);item.put("prompt",q.optString("prompt"));item.put("type",q.optString("type"));int answered=0;JSONObject counts=new JSONObject();if(rs!=null)for(int j=0;j<rs.length();j++){JSONObject row=rs.optJSONObject(j),ans=row==null?null:row.optJSONObject("answers");String v=ans==null?"":ans.optString(qid,"").trim();if(!v.isEmpty()){answered++;if("choice".equals(q.optString("type")))counts.put(v,counts.optInt(v)+1);}}item.put("answered",answered);item.put("completionRate",total==0?0:Math.round(answered*1000.0/total)/10.0);item.put("counts",counts);items.put(item);}out.put("questions",items);}catch(Exception ignored){}return out;}
 public static String responsesCsv(JSONObject f){StringBuilder b=new StringBuilder();JSONArray q=f.optJSONArray("questions"),r=f.optJSONArray("responses");b.append("response_id,created_at");if(q!=null)for(int i=0;i<q.length();i++){JSONObject d=q.optJSONObject(i);b.append(',').append(csv(d==null?"question":d.optString("prompt")));}b.append('\n');if(r!=null)for(int i=0;i<r.length();i++){JSONObject row=r.optJSONObject(i);if(row==null)continue;b.append(csv(row.optString("id"))).append(',').append(row.optLong("createdAt"));JSONObject a=row.optJSONObject("answers");if(q!=null)for(int j=0;j<q.length();j++){JSONObject d=q.optJSONObject(j);String v=a==null||d==null?"":a.optString(d.optString("id"));b.append(',').append(csv(v));}b.append('\n');}return b.toString();}
 private static String csv(String s){String v=s==null?"":s;return "\""+v.replace("\"","\"\"")+"\"";}
 public static JSONObject chat(String body){
  JSONObject p=parse(body);if(p.has("messages")){try{p.put("schema","neo.noogle.chat/v5");if(!p.has("workspaceId"))p.put("workspaceId",uid());if(!p.has("localAlias"))p.put("localAlias","Local");JSONArray members=p.optJSONArray("members");if(members==null||members.length()==0){members=new JSONArray();JSONObject me=new JSONObject();me.put("id",uid());me.put("alias",p.optString("localAlias","Local"));me.put("role","owner");me.put("local",true);members.put(me);String legacy=p.optString("participants","");if(!legacy.trim().isEmpty())for(String s:legacy.split(",")){String a=s.trim();if(a.isEmpty()||a.equalsIgnoreCase(p.optString("localAlias","Local")))continue;JSONObject m=new JSONObject();m.put("id",uid());m.put("alias",a);m.put("role","member");m.put("local",false);members.put(m);}p.put("members",members);}JSONArray channels=p.optJSONArray("channels");String legacyId=p.optString("channelId"),legacyName=p.optString("channel","general");if(channels==null||channels.length()==0){channels=new JSONArray();JSONObject c=new JSONObject();c.put("id",legacyId.isEmpty()?uid():legacyId);c.put("name",legacyName.isEmpty()?"general":legacyName);c.put("createdAt",System.currentTimeMillis());channels.put(c);p.put("channels",channels);}String active=p.optString("activeChannelId");if(active.isEmpty()){JSONObject c=channels.optJSONObject(0);active=c==null?uid():c.optString("id",uid());p.put("activeChannelId",active);}JSONObject readBy=p.optJSONObject("readBy");if(readBy==null){readBy=new JSONObject();p.put("readBy",readBy);}String local=p.optString("localAlias","Local");JSONObject localReads=readBy.optJSONObject(local);if(localReads==null){localReads=new JSONObject();readBy.put(local,localReads);for(int i=0;i<channels.length();i++){JSONObject c=channels.optJSONObject(i);if(c!=null)localReads.put(c.optString("id"),c.optLong("lastReadAt",0));}}JSONArray a=p.optJSONArray("messages");if(a!=null)for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m!=null){if(!m.has("id"))m.put("id",uid());if(!m.has("channelId"))m.put("channelId",active);if(!m.has("threadId"))m.put("threadId",JSONObject.NULL);}}return p;}catch(Exception ignored){}}
  try{JSONObject o=new JSONObject();o.put("schema","neo.noogle.chat/v5");o.put("workspaceId",uid());o.put("localAlias","Local");JSONArray members=new JSONArray();JSONObject me=new JSONObject();me.put("id",uid());me.put("alias","Local");me.put("role","owner");me.put("local",true);members.put(me);o.put("members",members);JSONArray channels=new JSONArray();JSONObject c=new JSONObject();String cid=uid();c.put("id",cid);c.put("name","general");c.put("createdAt",System.currentTimeMillis());channels.put(c);o.put("channels",channels);o.put("activeChannelId",cid);JSONObject rb=new JSONObject();JSONObject lr=new JSONObject();lr.put(cid,0);rb.put("Local",lr);o.put("readBy",rb);o.put("messages",new JSONArray());return o;}catch(Exception e){return new JSONObject();}
 }
 public static boolean addMember(JSONObject chat,String alias,String role){try{String a=alias==null?"":alias.trim();if(a.isEmpty())return false;JSONArray m=chat.optJSONArray("members");if(m==null){m=new JSONArray();chat.put("members",m);}for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&a.equalsIgnoreCase(x.optString("alias")))return false;}JSONObject x=new JSONObject();x.put("id",uid());x.put("alias",a);x.put("role",role==null?"member":role);x.put("local",false);m.put(x);return true;}catch(Exception ignored){}return false;}
 public static boolean updateMemberRole(JSONObject chat,String alias,String role){try{JSONArray m=chat.optJSONArray("members");if(m==null)return false;for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&alias.equalsIgnoreCase(x.optString("alias"))){if(x.optBoolean("local")&&"owner".equals(x.optString("role")))return false;x.put("role",role==null?"member":role);return true;}}}catch(Exception ignored){}return false;}
 public static boolean removeMember(JSONObject chat,String alias){try{JSONArray m=chat.optJSONArray("members");if(m==null)return false;JSONArray out=new JSONArray();boolean removed=false;for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x==null)continue;if(alias.equalsIgnoreCase(x.optString("alias"))&&!x.optBoolean("local")){removed=true;continue;}out.put(x);}if(removed){chat.put("members",out);JSONObject rb=chat.optJSONObject("readBy");if(rb!=null)rb.remove(alias);}return removed;}catch(Exception ignored){}return false;}
 public static String localAlias(JSONObject chat){return chat.optString("localAlias","Local");}
 public static String addChannel(JSONObject chat,String name){try{JSONArray a=chat.optJSONArray("channels");if(a==null){a=new JSONArray();chat.put("channels",a);}String id=uid();JSONObject c=new JSONObject();c.put("id",id);String n=name==null?"":name.trim();c.put("name",n.isEmpty()?"channel":n);c.put("createdAt",System.currentTimeMillis());a.put(c);chat.put("activeChannelId",id);return id;}catch(Exception e){return "";}}
 public static boolean renameChannel(JSONObject chat,String channelId,String name){try{JSONArray a=chat.optJSONArray("channels");if(a==null)return false;String n=name==null?"":name.trim();if(n.isEmpty())return false;for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c!=null&&channelId.equals(c.optString("id"))){c.put("name",n);return true;}}}catch(Exception ignored){}return false;}
 public static boolean deleteChannel(JSONObject chat,String channelId){try{JSONArray a=chat.optJSONArray("channels");if(a==null||a.length()<=1)return false;JSONArray out=new JSONArray();String next="";for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i);if(c==null)continue;if(!channelId.equals(c.optString("id"))){out.put(c);if(next.isEmpty())next=c.optString("id");}}chat.put("channels",out);JSONArray msgs=chat.optJSONArray("messages"),kept=new JSONArray();if(msgs!=null)for(int i=0;i<msgs.length();i++){JSONObject m=msgs.optJSONObject(i);if(m!=null&&!channelId.equals(m.optString("channelId")))kept.put(m);}chat.put("messages",kept);JSONObject rb=chat.optJSONObject("readBy");if(rb!=null){JSONArray names=rb.names();if(names!=null)for(int i=0;i<names.length();i++){JSONObject r=rb.optJSONObject(names.optString(i));if(r!=null)r.remove(channelId);}}if(channelId.equals(chat.optString("activeChannelId")))chat.put("activeChannelId",next);return true;}catch(Exception ignored){}return false;}
 public static void setActiveChannel(JSONObject chat,String channelId){try{if(channelId!=null&&!channelId.trim().isEmpty())chat.put("activeChannelId",channelId.trim());}catch(Exception ignored){}}
 public static void markChannelRead(JSONObject chat,String channelId){markChannelRead(chat,channelId,localAlias(chat));}
 public static void markChannelRead(JSONObject chat,String channelId,String alias){try{JSONObject rb=chat.optJSONObject("readBy");if(rb==null){rb=new JSONObject();chat.put("readBy",rb);}JSONObject user=rb.optJSONObject(alias);if(user==null){user=new JSONObject();rb.put(alias,user);}user.put(channelId,System.currentTimeMillis());}catch(Exception ignored){}}
 private static long readAt(JSONObject chat,String channelId,String alias){JSONObject rb=chat.optJSONObject("readBy"),u=rb==null?null:rb.optJSONObject(alias);return u==null?0:u.optLong(channelId);}
 public static int unreadCount(JSONObject chat,String channelId,String alias){long read=readAt(chat,channelId,alias);int n=0;JSONArray m=chat.optJSONArray("messages");if(m!=null)for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("channelId"))&&x.optLong("createdAt")>read&&!x.optString("author").equalsIgnoreCase(alias==null?"Local":alias))n++;}return n;}
 public static int mentionCount(JSONObject chat,String channelId,String alias){String who=alias==null||alias.trim().isEmpty()?"Local":alias.trim();String needle="@"+who.toLowerCase();long read=readAt(chat,channelId,who);int n=0;JSONArray m=chat.optJSONArray("messages");if(m!=null)for(int i=0;i<m.length();i++){JSONObject x=m.optJSONObject(i);if(x!=null&&channelId.equals(x.optString("channelId"))&&x.optLong("createdAt")>read&&x.optString("text").toLowerCase().contains(needle))n++;}return n;}
 public static void addMessage(JSONObject chat,String text,String author){addMessage(chat,text,author,chat.optString("activeChannelId"),null);}
 public static void addMessage(JSONObject chat,String text,String author,String channelId,String threadId){try{JSONArray a=chat.optJSONArray("messages");if(a==null){a=new JSONArray();chat.put("messages",a);}JSONObject m=new JSONObject();m.put("id",uid());m.put("channelId",channelId==null||channelId.trim().isEmpty()?chat.optString("activeChannelId"):channelId.trim());m.put("text",text==null?"":text.trim());m.put("author",author==null||author.trim().isEmpty()?localAlias(chat):author.trim());m.put("createdAt",System.currentTimeMillis());if(threadId==null||threadId.trim().isEmpty())m.put("threadId",JSONObject.NULL);else m.put("threadId",threadId.trim());a.put(m);}catch(Exception ignored){}}
 public static String pretty(JSONObject o){return o==null?"{}":o.toString();}
 private static JSONObject parse(String s){try{return s==null||s.trim().isEmpty()?new JSONObject():new JSONObject(s);}catch(Exception e){return new JSONObject();}}
}
