package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.CalendarContract;import android.view.*;import android.widget.*;import org.json.JSONObject;

/** Omnitrix Suit Wave 1. v4.0 file-native productivity + Android adapter surface. */
public class SuiteWave1Activity extends Activity {
 public static final String EXTRA_ID="id",EXTRA_NAME="name"; private String id,name;
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);id=getIntent().getStringExtra(EXTRA_ID);name=getIntent().getStringExtra(EXTRA_NAME);if(id==null)id="";if(name==null)name="Omnitrix App";build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(26));root.setBackgroundColor(Color.rgb(1,5,3));sv.addView(root);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);root.addView(logo,new LinearLayout.LayoutParams(dp(68),dp(68)));root.addView(text(name,24,Color.rgb(229,255,236)));TextView meta=text("Omnitrix Suit v4.0 · NEO-0001",11,Color.rgb(104,185,130));meta.setPadding(0,dp(4),0,dp(16));root.addView(meta);if(id.equals("neomail"))mail(root);else if(id.equals("noogle-calendar"))calendar(root);else if(id.equals("noogle-maps"))maps(root);else if(id.equals("noogle-news"))searchBridge(root,"Search current news","latest news");else if(id.equals("noogle-translate"))translate(root);else if(id.equals("noogle-play"))play(root);else if(id.equals("noogle-cloud"))workspace(root,"Cloud workspace","Shared NEO Cloud is available through the suite cloud hub.");else if(id.equals("noogle-docs"))editor(root,"Document","Write and save a file-native document.");else if(id.equals("noogle-sheets"))editor(root,"Sheet / CSV","Enter comma-separated rows or working data.");else if(id.equals("noogle-slides"))editor(root,"Slide outline","Draft slide titles and content blocks.");else if(id.equals("noogle-keep"))editor(root,"Keep note","Capture notes and checklists.");else if(id.equals("noogle-account"))account(root);else workspace(root,name,"Module registered in the Omnitrix Suit.");Button back=secondary("BACK TO OMNITRIX SUIT");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(48));bp.setMargins(0,dp(18),0,0);root.addView(back,bp);back.setOnClickListener(v->finish());setContentView(sv);}
 private void account(LinearLayout r){r.addView(card("NEO-0001\nFounding Profile · ACTIVE\nLocal-first identity boundary"));r.addView(text("Account services inherit the active Omnitrix profile. Wallet secrets remain outside this surface.",12,Color.rgb(176,215,188)));}
 private void editor(LinearLayout r,String label,String hint){TextView n=text(hint,12,Color.rgb(174,211,186));n.setPadding(0,0,0,dp(10));r.addView(n);EditText e=new EditText(this);JSONObject rec=FileNativeStore.findByApp(this,id);if(rec!=null)e.setText(FileNativeStore.body(this,rec.optString("id")));else e.setText(getSharedPreferences("omnitrix_wave1",MODE_PRIVATE).getString(id,""));e.setHint(label);e.setMinLines(12);e.setGravity(Gravity.TOP);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(95,125,105));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),dp(12),dp(12),dp(12));r.addView(e,new LinearLayout.LayoutParams(-1,dp(300)));Button save=primary("SAVE + BACKGROUND E2EE SYNC");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.setMargins(0,dp(10),0,0);r.addView(save,lp);save.setOnClickListener(v->{JSONObject m=FileNativeStore.save(this,id,name,e.getText().toString(),true);Toast.makeText(this,"Saved rev "+m.optLong("rev")+"; encrypted sync scheduled",Toast.LENGTH_SHORT).show();});}
 private void workspace(LinearLayout r,String title,String note){r.addView(card(title));TextView t=text(note,12,Color.rgb(174,211,186));t.setPadding(0,dp(12),0,0);r.addView(t);}
 private void mail(LinearLayout r){r.addView(card("NEOMAIL COMPOSER"));EditText to=input("To"),sub=input("Subject"),body=input("Message");body.setMinLines(8);body.setGravity(Gravity.TOP);r.addView(to);r.addView(sub);r.addView(body,new LinearLayout.LayoutParams(-1,dp(190)));Button send=primary("OPEN EMAIL APP");r.addView(send,new LinearLayout.LayoutParams(-1,dp(50)));send.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"+Uri.encode(to.getText().toString())));i.putExtra(Intent.EXTRA_SUBJECT,sub.getText().toString());i.putExtra(Intent.EXTRA_TEXT,body.getText().toString());try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No email provider installed",Toast.LENGTH_SHORT).show();}});r.addView(text("Neomail currently uses the device email provider adapter; native hosted mail remains a separate service backend.",11,Color.rgb(112,145,121)));}
 private void calendar(LinearLayout r){r.addView(card("NOOGLE CALENDAR"));Button b=primary("CREATE CALENDAR EVENT");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_INSERT).setData(CalendarContract.Events.CONTENT_URI);i.putExtra(CalendarContract.Events.TITLE,"NEO Event");try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No calendar provider available",Toast.LENGTH_SHORT).show();}});}
 private void maps(LinearLayout r){r.addView(card("NOOGLE MAPS"));EditText q=input("Search destination or business");r.addView(q);Button b=primary("OPEN MAP");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{String s=q.getText().toString().trim();if(s.isEmpty())return;Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(s)));try{startActivity(i);}catch(Exception e){openSearch(s+" map");}});}
 private void translate(LinearLayout r){r.addView(card("NOOGLE TRANSLATE"));EditText q=input("Text to translate");r.addView(q);EditText lang=input("Target language (example: Spanish)");r.addView(lang);Button b=primary("TRANSLATE WITH NOOGLE SEARCH");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->openSearch("translate to "+lang.getText().toString()+": "+q.getText().toString()));}
 private void searchBridge(LinearLayout r,String title,String preset){r.addView(card(title));Button b=primary("OPEN IN NOOGLE");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->openSearch(preset));}
 private void play(LinearLayout r){r.addView(card("NOOGLE PLAY STORE · BETA CATALOG"));r.addView(text("NEO-native apps launch from the Omnitrix Suit. Compatible external Android apps use approved install/intent adapters.",12,Color.rgb(174,211,186)));Button b=primary("OPEN SUITE CATALOG");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->startActivity(new Intent(this,SuiteLauncherActivity.class)));}
 private void openSearch(String q){Intent i=new Intent(this,MainActivityV14.class);i.putExtra("search_query",q);startActivity(i);}private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(!hint.equals("Message"));e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(95,125,105));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),0,dp(12),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,0,0,dp(8));e.setLayoutParams(p);return e;}private TextView card(String s){TextView t=text(s,17,Color.rgb(220,255,230));t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackgroundColor(Color.rgb(5,20,12));return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
