package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.view.*;import android.widget.*;

/** Omnitrix Suit v3.3 Wave 3: platform, device, telecom, smart-home and safety betas. */
public class SuiteWave3Activity extends Activity {
 public static final String EXTRA_ID="id",EXTRA_NAME="name";private String id,name;private LinearLayout root;
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);id=getIntent().getStringExtra(EXTRA_ID);name=getIntent().getStringExtra(EXTRA_NAME);if(id==null)id="";if(name==null)name="Omnitrix";build();}
 private void build(){ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(28));root.setBackgroundColor(Color.rgb(1,5,3));scroll.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);head.addView(logo,new LinearLayout.LayoutParams(dp(64),dp(64)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(text(name,23,Color.rgb(228,255,235)));words.addView(text("Omnitrix Suit v3.3 · BETA",11,Color.rgb(208,255,121)));head.addView(words);root.addView(head);TextView note=text(description(),12,Color.rgb(171,211,184));note.setPadding(0,dp(14),0,dp(18));root.addView(note);render();Button back=secondary("BACK TO OMNITRIX SUIT");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.setMargins(0,dp(18),0,0);root.addView(back,lp);back.setOnClickListener(v->finish());setContentView(scroll);}
 private void render(){switch(id){case"noogle-home":devicePanel("SMART HOME CONTROL","Open Wi-Fi, Bluetooth and connected-device controls. NEO smart-home discovery will sit on this adapter layer.",Settings.ACTION_WIFI_SETTINGS,Settings.ACTION_BLUETOOTH_SETTINGS);break;case"neopixel":devicePanel("NEOPIXEL DEVICE CENTER","Manage this Android device today; future NeoPixel phones, tablets and watches inherit the same Omnitrix account surface.",Settings.ACTION_DEVICE_INFO_SETTINGS,Settings.ACTION_DISPLAY_SETTINGS);break;case"omnicast":devicePanel("OMNICAST","Use Android media/display controls as the first casting compatibility layer.",Settings.ACTION_CAST_SETTINGS,Settings.ACTION_DISPLAY_SETTINGS);break;case"neofit":devicePanel("NEOFIT","Fitness and health software foundation. No health records are collected by this beta.",Settings.ACTION_APPLICATION_SETTINGS,Settings.ACTION_PRIVACY_SETTINGS);break;case"noogle-fi":telecom();break;case"noogle-neo":cloud();break;case"find-device":devicePanel("FIND MY DEVICE","Open Android location and security controls. Remote NEO device location requires a future authenticated device service.",Settings.ACTION_LOCATION_SOURCE_SETTINGS,Settings.ACTION_SECURITY_SETTINGS);break;case"authenticator":security();break;case"voice":voice();break;case"family-link":family();break;case"omnitrix-os":osPanel("OMNITRIXOS","Omnibook operating-system control plane foundation. Android hosts this compatibility preview while a dedicated OS image is developed.");break;case"neo-wear":osPanel("NEO WEAR OS","Wearable profile, notification and device-control foundation. Hardware pairing remains delegated to approved Android wearable adapters.");break;case"noogle-tv-os":osPanel("NOOGLE TV OS","Smart-TV launcher and media-control foundation. Compatible TV/casting providers will connect through adapters rather than copied proprietary software.");break;default:root.addView(card("Module registered. Functional adapter work continues in the Omnitrix platform layer."));}}
 private void telecom(){root.addView(card("NEO WIRE MOBILE / NOOGLE FI\nCarrier control foundation. This beta can open Android network settings and the dialer; actual MVNO service requires carrier/network agreements and provisioning."));button("MOBILE NETWORK SETTINGS",()->safeIntent(new Intent(Settings.ACTION_WIRELESS_SETTINGS)));button("OPEN DIALER",()->safeIntent(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"))));}
 private void cloud(){root.addView(card("NOOGLE NEO\nLocal backup/status foundation for expanded NEO storage. The public GitHub repository is not used as private cloud storage."));button("ANDROID BACKUP SETTINGS",()->safeIntent(new Intent(Settings.ACTION_PRIVACY_SETTINGS)));button("OPEN NOOGLE CLOUD BETA",()->{Intent i=new Intent(this,SuiteWave1Activity.class);i.putExtra(SuiteWave1Activity.EXTRA_ID,"noogle-cloud");i.putExtra(SuiteWave1Activity.EXTRA_NAME,"Noogle Cloud");startActivity(i);});}
 private void security(){root.addView(card("NOOGLE AUTHENTICATOR\nSecurity-center beta. It does not store OTP seeds in plaintext or inside GitHub. Device lock and credential protection remain the current trust anchor."));button("DEVICE SECURITY",()->safeIntent(new Intent(Settings.ACTION_SECURITY_SETTINGS)));button("OMNITRIX SECURITY ENTRY",()->startActivity(new Intent(this,XcpKeyActivity.class)));}
 private void voice(){root.addView(card("NOOGLE VOICE / TALK\nTelephone + VoIP adapter foundation. Calls currently hand off to approved Android dialer/VoIP providers."));button("OPEN PHONE DIALER",()->safeIntent(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"))));button("OPEN OMNITRIX BROWSER",()->startActivity(new Intent(this,MainActivityV14.class)));}
 private void family(){root.addView(card("NOOGLE FAMILY LINK\nLocal family-policy preview. This beta stores only a local screen-time target and opens Android parental/safety controls where available."));EditText mins=new EditText(this);mins.setHint("Daily screen-time target (minutes)");mins.setInputType(2);mins.setTextColor(Color.WHITE);mins.setHintTextColor(Color.rgb(100,130,108));mins.setBackgroundColor(Color.rgb(5,20,12));root.addView(mins,new LinearLayout.LayoutParams(-1,dp(52)));button("SAVE LOCAL TARGET",()->{getSharedPreferences("omnitrix_family",MODE_PRIVATE).edit().putString("daily_minutes",mins.getText().toString().trim()).apply();Toast.makeText(this,"Family target saved locally",Toast.LENGTH_SHORT).show();});button("ANDROID DIGITAL WELLBEING",()->safeIntent(new Intent(Settings.ACTION_SETTINGS)));}
 private void osPanel(String title,String detail){root.addView(card(title+"\n"+detail));button("DEVICE INFORMATION",()->safeIntent(new Intent(Settings.ACTION_DEVICE_INFO_SETTINGS)));button("SYSTEM SETTINGS",()->safeIntent(new Intent(Settings.ACTION_SETTINGS)));}
 private void devicePanel(String title,String detail,String action1,String action2){root.addView(card(title+"\n"+detail));button("PRIMARY DEVICE CONTROL",()->safeIntent(new Intent(action1)));button("MORE DEVICE SETTINGS",()->safeIntent(new Intent(action2)));}
 private void button(String label,Runnable r){Button b=primary(label);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(8),0,0);root.addView(b,p);b.setOnClickListener(v->r.run());}
 private void safeIntent(Intent i){try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No compatible Android control found",Toast.LENGTH_SHORT).show();}}
 private String description(){return"Wave 3 uses Android system controls and explicit adapters as the first functional layer. It does not claim carrier service, remote-device management, proprietary TV integration, or hardware support that has not been provisioned.";}
 private TextView card(String s){TextView t=text(s,14,Color.rgb(218,255,227));t.setPadding(dp(16),dp(16),dp(16),dp(16));t.setBackgroundColor(Color.rgb(5,20,12));return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
