package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.CalendarContract;import android.view.*;import android.widget.*;import org.json.*;

/** Omnitrix Suit Wave 1. v4.1 multi-file productivity + Android adapter surface. */
public class SuiteWave1Activity extends Activity {
 public static final String EXTRA_ID="id",EXTRA_NAME="name"; private String id,name,activeFileId;
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);id=getIntent().getStringExtra(EXTRA_ID);name=getIntent().getStringExtra(EXTRA_NAME);activeFileId=getIntent().getStringExtra("file_id");if(id==null)id="";if(name==null)name="Omnitrix App";build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(26));root.setBackgroundColor(Color.rgb(1,5,3));sv.addView(root);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);root.addView(logo,new LinearLayout.LayoutParams(dp(68),dp(68)));root.addView(text(name,24,Color.rgb(229,255,236)));TextView meta=text("Omnitrix Suit v4.1 · NEO-0001",11,Color.rgb(104,185,130));meta.setPadding(0,dp(4),0,dp(16));root.addView(meta);if(id.equals("neomail"))mail(root);else if(id.equals("noogle-calendar"))calendar(root);else if(id.equals("noogle-maps"))maps(root);else if(id.equals("noogle-news"))searchBridge(root,"Search current news","latest news");else if(id.equals("noogle-translate"))translate(root);else if(id.equals("noogle-play"))play(root);else if(id.equals("noogle-cloud"))workspace(root,"Cloud workspace","Shared NEO Cloud is available through the suite cloud hub.");else if(id.equals("noogle-docs"))editor(root,"Document","Write and save file-native documents.");else if(id.equals("noogle-sheets"))editor(root,"Sheet / CSV","Create multiple sheets with stable file IDs.");else if(id.equals("noogle-slides"))editor(root,"Slide outline","Create multiple slide decks and revision histories.");else if(id.equals("noogle-keep"))editor(root,"Keep note","Create independent notes and checklists.");else if(id.equals("noogle-account"))account(root);else workspace(root,name,"Module registered in the Omnitrix Suit.");Button back=secondary("BACK TO OMNITRIX SUIT");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(48));bp.setMargins(0,dp(18),0,0);root.addView(back,bp);back.setOnClickListener(v->finish());setContentView(sv);}
 private void account(LinearLayout r){r.addView(card("NEO-0001\nFounding Profile · ACTIVE\nLocal-first identity boundary"));r.addView(text("Account services inherit the active Omnitrix profile. Wallet secrets remain outside this surface.",12,Color.rgb(176,215,188)));}
 private void editor(LinearLayout r,String label,String hint){r.addView(text(hint,12,Color.rgb(174,211,186)));EditText title=input("File title");r.addView(title);EditText e=new EditText(this);JSONObject rec=activeFileId==null?FileNativeStore.findByApp(this,id):FileNativeStore.find(this,activeFileId);if(rec!=null&&!rec.optBoolean("deleted")){activeFileId=rec.optString("id");title.setText(rec.optString("title",name));e.setText(FileNativeStore.body(this,activeFileId));}else{activeFileId=null;title.setText(name+" file");String legacy=getSharedPreferences("omnitrix_wave1",MODE_PRIVATE).getString(id,"");if(!legacy.isEmpty())e.setText(legacy);}e.setHint(label);e.setMinLines(12);e.setGravity(Gravity.TOP);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(95,125,105));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),dp(12),dp(12),dp(12));r.addView(e,new LinearLayout.LayoutParams(-1,dp(300)));Button save=primary("SAVE + BACKGROUND E2EE SYNC");r.addView(save,new LinearLayout.LayoutParams(-1,dp(50)));save.setOnClickListener(v->{String t=title.getText().toString().trim();if(t.isEmpty())t=name+" file";JSONObject m=activeFileId==null?FileNativeStore.create(this,id,t,e.getText().toString(),true):FileNativeStore.saveId(this,activeFileId,id,t,e.getText().toString(),true);activeFileId=m.optString("id");Toast.makeText(this,"Saved rev "+m.optLong("rev")+"; encrypted sync scheduled",Toast.LENGTH_SHORT).show();});Button files=secondary("OPEN / CREATE FILE");r.addView(files,new LinearLayout.LayoutParams(-1,dp(48)));files.setOnClickListener(v->chooseFile());TextView count=text("Workspace files: "+FileNativeStore.listByApp(this,id,false).length(),11,Color.rgb(104,185,130));r.addView(count);}
 private void chooseFile(){JSONArray a=FileNativeStore.listByApp(this,id,false);String[] rows=new String[a.length()+1];rows[0]="＋ New file";for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);rows[i+1]=(m==null?"File":m.optString("title"))+" · rev "+(m==null?0:m.optLong("rev"));}new AlertDialog.Builder(this).setTitle(name+" workspace").setItems(rows,(d,w)->{Intent next=new Intent(this,SuiteWave1Activity.class).putExtra(EXTRA_ID,id).putExtra(EXTRA_NAME,name);if(w>0){JSONObject m=a.optJSONObject(w-1);if(m!=null)next.putExtra("file_id",m.optString("id"));}startActivity(next);finish();}).setNegativeButton("Cancel",null).show();}
 private void workspace(LinearLayout r,String title,String note){r.addView(card(title));TextView t=text(note,12,Color.rgb(174,211,186));t.setPadding(0,dp(12),0,0);r.addView(t);}
 private void mail(LinearLayout r){r.addView(card("NEOMAIL COMPOSER"));EditText to=input("To"),sub=input("Subject"),body=input("Message");body.setMinLines(8);body.setGravity(Gravity.TOP);r.addView(to);r.addView(sub);r.addView(body,new LinearLayout.LayoutParams(-1,dp(190)));Button send=primary("OPEN EMAIL APP");r.addView(send,new LinearLayout.LayoutParams(-1,dp(50)));send.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"+Uri.encode(to.getText().toString())));i.putExtra(Intent.EXTRA_SUBJECT,sub.getText().toString());i.putExtra(Intent.EXTRA_TEXT,body.getText().toString());try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No email provider installed",Toast.LENGTH_SHORT).show();}});r.addView(text("Neomail currently uses the device email provider adapter; native hosted mail remains a separate service backend.",11,Color.rgb(112,145,121)));}
 private void calendar(LinearLayout r){r.addView(card("NOOGLE CALENDAR"));Button b=primary("CREATE CALENDAR EVENT");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_INSERT).setData(CalendarContract.Events.CONTENT_URI);i.putExtra(CalendarContract.Events.TITLE,"NEO Event");try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No calendar provider available",Toast.LENGTH_SHORT).show();}});}
 private void maps(LinearLayout r){r.addView(card("NOOGLE MAPS"));EditText q=input("Search destination or business");r.addView(q);Button b=primary("OPEN MAP");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{String s=q.getText().toString().trim();if(s.isEmpty())return;Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(s)));try{startActivity(i);}catch(Exception e){openSearch(s+" map");}});}
 private void translate(LinearLayout r){r.addView(card("NOOGLE TRANSLATE"));EditText q=input("Text to translate");r.addView(q);EditText lang=input("Target language (example: Spanish)");r.addView(lang);Button b=primary("TRANSLATE WITH NOOGLE SEARCH");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->openSearch("translate to "+lang.getText().toString()+": "+q.getText().toString()));}
 private void searchBridge(LinearLayout r,String title,String preset){r.addView(card(title));Button b=primary("OPEN IN NOOGLE");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->openSearch(preset));}
 private void play(LinearLayout r){r.addView(card("NOOGLE PLAY STORE · BETA CATALOG"));r.addView(text("NEO-native apps launch from the Omnitrix Suit. Compatible external Android apps use approved install/intent adapters.",12,Color.rgb(174,211,186)));Button b=primary("OPEN SUITE CATALOG");r.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->startActivity(new Intent(this,SuiteLauncherActivity.class)));}
 private void openSearch(String q){Intent i=new Intent(this,MainActivityV14.class);i.putExtra("search_query",q);startActivity(i);}private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(!hint.equals("Message"));e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(95,125,105));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),0,dp(12),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,0,0,dp(8));e.setLayoutParams(p);return e;}private TextView card(String s){TextView t=text(s,17,Color.rgb(220,255,230));t.setPadding(dp(14),dp(14),dp(14),dp(14));t.setBackgroundColor(Color.rgb(5,20,12));return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
