package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;

/** Omnitrix Suit v3.2 Wave 2. Interactive beta adapters + local-first collaboration surfaces. */
public class SuiteWave2Activity extends Activity {
 public static final String EXTRA_ID="id",EXTRA_NAME="name";private String id,name;private LinearLayout body;
 @Override public void onCreate(Bundle s){super.onCreate(s);id=getIntent().getStringExtra(EXTRA_ID);name=getIntent().getStringExtra(EXTRA_NAME);if(id==null)id="";if(name==null)name="Omnitrix App";getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);build();}
 private void build(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(22),dp(18),dp(22));scroll.addView(body);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);body.addView(logo,new LinearLayout.LayoutParams(dp(72),dp(72)));body.addView(text(name,24,Color.rgb(228,255,235)));body.addView(text("Omnitrix Suit v3.2 · BETA",11,Color.rgb(116,255,151)));TextView note=text("Functional beta surface. Hosted media, messaging, meeting, geospatial and travel backends will be promoted to LIVE only after production infrastructure is connected.",11,Color.rgb(142,182,154));note.setPadding(0,dp(8),0,dp(16));body.addView(note);render();shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"NEO"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);}
 private void render(){switch(id){
  case "neotube": searchModule("Search and watch video across the open web.","Search videos","video");break;
  case "neotube-music": mediaOpen("Choose audio from this device or search the web.","audio/*","music");break;
  case "neotube-tv": searchModule("Discover live TV and public streaming sources.","Search live TV","live tv");break;
  case "noogle-photos": mediaOpen("Open photos from this device using Android's secure document picker.","image/*","photos");break;
  case "noogle-podcasts": searchModule("Find podcast episodes and feeds.","Search podcasts","podcast");break;
  case "noogle-books": searchModule("Search books, previews and public-domain libraries.","Search books","books");break;
  case "noogle-meet": meet();break;
  case "noogle-chat": localWorkspace("Noogle Chat local room","Type a local message or meeting note…");break;
  case "noogle-forms": localWorkspace("Noogle Forms draft","Draft questions, choices and response notes…");break;
  case "noogle-earth": geo("Explore a place","geo:0,0?q=");break;
  case "noogle-flights": searchModule("Search flight routes and fares across public travel sources.","Search flights","flights");break;
  case "noogle-lens": lens();break;
  default: body.addView(text("This Wave 2 module is registered but has no handler yet.",14,Color.LTGRAY));
 }}
 private void searchModule(String desc,String hint,String suffix){body.addView(text(desc,14,Color.rgb(196,229,204)));EditText q=input(hint);body.addView(q);Button b=primary("SEARCH WITH NOOGLE");body.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->openNoogle(q.getText().toString()+" "+suffix));}
 private void mediaOpen(String desc,String mime,String suffix){body.addView(text(desc,14,Color.rgb(196,229,204)));Button open=primary("OPEN DEVICE MEDIA");body.addView(open,new LinearLayout.LayoutParams(-1,dp(52)));open.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No compatible media picker found",Toast.LENGTH_SHORT).show();}});Button search=secondary("SEARCH "+suffix.toUpperCase());body.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));search.setOnClickListener(v->openNoogle(suffix));}
 private void meet(){body.addView(text("Create or join a meeting through compatible installed conferencing software. Omnitrix does not silently enroll you in a third-party service.",14,Color.rgb(196,229,204)));EditText room=input("Meeting code or URL");body.addView(room);Button open=primary("OPEN MEETING LINK");body.addView(open,new LinearLayout.LayoutParams(-1,dp(52)));open.setOnClickListener(v->{String s=room.getText().toString().trim();if(s.isEmpty())return;Uri u=Uri.parse(s.contains("://")?s:"https://"+s);try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){Toast.makeText(this,"No meeting handler found",Toast.LENGTH_SHORT).show();}});}
 private void localWorkspace(String title,String hint){body.addView(text(title+" is local-first in this beta.",14,Color.rgb(196,229,204)));EditText editor=input(hint);editor.setMinLines(8);editor.setGravity(Gravity.TOP);String key="wave2_"+id;editor.setText(getSharedPreferences("omnitrix_suite",MODE_PRIVATE).getString(key,""));body.addView(editor,new LinearLayout.LayoutParams(-1,dp(240)));Button save=primary("SAVE LOCALLY");body.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));save.setOnClickListener(v->{getSharedPreferences("omnitrix_suite",MODE_PRIVATE).edit().putString(key,editor.getText().toString()).apply();Toast.makeText(this,"Saved on this device",Toast.LENGTH_SHORT).show();});}
 private void geo(String hint,String base){body.addView(text("Noogle Earth beta hands coordinates/place queries to an installed map/geo provider, with Noogle search as fallback.",14,Color.rgb(196,229,204)));EditText q=input(hint);body.addView(q);Button b=primary("EXPLORE");body.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{String s=q.getText().toString().trim();if(s.isEmpty())return;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(base+Uri.encode(s))));}catch(Exception e){openNoogle(s+" map earth");}});}
 private void lens(){body.addView(text("Noogle Lens beta launches the device camera. Visual recognition remains local/adapter-only until a production vision service is connected.",14,Color.rgb(196,229,204)));Button camera=primary("OPEN CAMERA");body.addView(camera,new LinearLayout.LayoutParams(-1,dp(52)));camera.setOnClickListener(v->{Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);try{startActivity(i);}catch(Exception e){Toast.makeText(this,"Camera unavailable",Toast.LENGTH_SHORT).show();}});Button pick=secondary("CHOOSE IMAGE");body.addView(pick,new LinearLayout.LayoutParams(-1,dp(50)));pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivity(i);});}
 private void openNoogle(String q){try{String enc=URLEncoder.encode(q==null?"":q.trim(),StandardCharsets.UTF_8.name());Intent i=new Intent(this,MainActivityV14.class);i.putExtra("open_url","https://shemsizedek.github.io/neo-system/noogle/?q="+enc);startActivity(i);}catch(Exception e){startActivity(new Intent(this,MainActivityV14.class));}}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(102,132,112));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;}
 private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(190,235,202));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
