package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;

/** v4.11 consumer-facing sync diagnostics. Displays metadata/counters only; never document bodies, chat bodies, or XCP Key material. */
public class SyncHealthActivity extends Activity {
 @Override public void onCreate(Bundle s){super.onCreate(s);build();}
 @Override protected void onResume(){super.onResume();build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(22));r.setBackgroundColor(Color.rgb(1,5,3));sv.addView(r);r.addView(text("NEO CLOUD · SYNC HEALTH",24,Color.WHITE));r.addView(text("Omnitrix Suit v4.11 · encrypted provider diagnostics",12,Color.rgb(116,255,151)));r.addView(card("FILE SYNC\n"+BackgroundFileSync.status(this)));r.addView(card("NOOGLE CHAT\n"+ChatSyncHealth.status(this)));Button sync=new Button(this);sync.setText("SYNC NOW");r.addView(sync,new LinearLayout.LayoutParams(-1,dp(52)));sync.setOnClickListener(v->{BackgroundFileSync.scheduleNow(this);Toast.makeText(this,"Encrypted sync queued",Toast.LENGTH_SHORT).show();});Button provider=new Button(this);provider.setText("OPEN STORAGE PROVIDER");r.addView(provider,new LinearLayout.LayoutParams(-1,dp(50)));provider.setOnClickListener(v->startActivity(new Intent(this,CloudProviderActivity.class)));r.addView(text("This screen exposes timestamps, counts, conflicts and failures only. File contents, chat message bodies, account encryption keys, and wallet/XCP Key material are not displayed or logged here.",11,Color.LTGRAY));setContentView(sv);}
 private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(14),dp(12),dp(14));t.setBackgroundColor(Color.rgb(5,20,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,dp(8));t.setLayoutParams(p);return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,dp(6),0,dp(6));return t;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
