package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;

/** v3.7 trusted-device, recovery-package, and E2EE control surface. */
public class TrustedDevicesActivity extends Activity{
 private SharedPreferences p; private AccountE2eeVault vault; private ProfileSyncVault sync;
 @Override public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("omnitrix_trusted_devices_v1",MODE_PRIVATE);vault=new AccountE2eeVault(this);sync=new ProfileSyncVault(this);vault.ensure();build();}
 private void build(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(22),dp(18),dp(24));r.setBackgroundColor(Color.rgb(1,5,3));sv.addView(r);r.addView(text("NEO ACCOUNT SECURITY",24,Color.rgb(229,255,236)));r.addView(text("Omnitrix Suit v3.7 · E2EE · NEO-0001",11,Color.rgb(104,185,130)));r.addView(card("THIS DEVICE\n"+sync.deviceId()+"\nTrusted locally"));EditText dev=input("Trusted device ID");r.addView(dev);Button trust=primary("TRUST DEVICE");r.addView(trust,new LinearLayout.LayoutParams(-1,dp(50)));trust.setOnClickListener(v->{String d=dev.getText().toString().trim();if(d.isEmpty())return;JSONArray a=read();JSONObject o=new JSONObject();try{o.put("id",d);o.put("trustedAt",System.currentTimeMillis());a.put(o);}catch(Exception ignored){}p.edit().putString("devices",a.toString()).apply();SuiteSyncBus.notify(this,"NEO Account","Trusted device added: "+d);recreate();});section(r,"TRUSTED DEVICES",read());EditText pass=input("Recovery passphrase (10+ characters)");r.addView(pass);EditText pkg=input("Recovery package");pkg.setMinLines(5);pkg.setSingleLine(false);r.addView(pkg,new LinearLayout.LayoutParams(-1,dp(160)));Button exp=secondary("GENERATE ENCRYPTED RECOVERY PACKAGE");r.addView(exp,new LinearLayout.LayoutParams(-1,dp(50)));exp.setOnClickListener(v->{try{pkg.setText(vault.exportRecovery(pass.getText().toString()));SuiteSyncBus.notify(this,"NEO Account","Encrypted recovery package generated");}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});Button imp=secondary("IMPORT RECOVERY PACKAGE");r.addView(imp,new LinearLayout.LayoutParams(-1,dp(50)));imp.setOnClickListener(v->{try{vault.importRecovery(pkg.getText().toString().trim(),pass.getText().toString());SuiteSyncBus.notify(this,"NEO Account","Account E2EE key restored on this device");Toast.makeText(this,"Account encryption key restored",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Recovery import failed",Toast.LENGTH_LONG).show();}});r.addView(text("Recovery packages contain only the NEO account encryption key, encrypted by your recovery passphrase. They never contain the XCP Key or wallet signing material.",11,Color.rgb(120,150,130)));setContentView(sv);}
 private JSONArray read(){try{return new JSONArray(p.getString("devices","[]"));}catch(Exception e){return new JSONArray();}}
 private void section(LinearLayout r,String title,JSONArray a){r.addView(text(title,12,Color.rgb(118,255,151)));if(a.length()==0){r.addView(card("No additional trusted devices."));return;}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null){TextView t=card(o.optString("id")+"\nTap to revoke");final int n=i;t.setOnClickListener(v->{JSONArray old=read(),x=new JSONArray();for(int j=0;j<old.length();j++)if(j!=n)x.put(old.optJSONObject(j));p.edit().putString("devices",x.toString()).apply();recreate();});r.addView(t);}}}
 private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.rgb(95,125,105));e.setBackgroundColor(Color.rgb(5,20,12));e.setPadding(dp(12),0,dp(12),0);return e;}private TextView card(String s){TextView t=text(s,13,Color.rgb(220,255,230));t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setBackgroundColor(Color.rgb(5,20,12));return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
