package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.bitcoinj.base.BitcoinNetwork;import org.bitcoinj.base.ScriptType;import org.bitcoinj.crypto.DumpedPrivateKey;import java.util.concurrent.*;

/** v4.14 focused non-custodial wallet: balance first, Send/Receive primary, tools contextual. */
public class WalletDashboardActivity extends Activity {
 private static final int REQ_UNLOCK=2001;private XcpKeyVault vault;private final ExecutorService io=Executors.newSingleThreadExecutor();private TextView address,summary,activity,status;private Button refresh,send,receive;private String publicAddress="";
 @Override public void onCreate(Bundle s){super.onCreate(s);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);vault=new XcpKeyVault(this);buildUi();if(vault.hasKey())authenticate();else status.setText("Wallet is not connected. Return to Omnitrix security setup when you want to add an XCP Key.");}
 private void buildUi(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.rgb(1,5,3));ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(22),dp(20),dp(24));scroll.addView(root);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);top.addView(logo,new LinearLayout.LayoutParams(dp(56),dp(56)));top.addView(text("  Wallet",26,Color.rgb(227,255,234)));root.addView(top);address=text("Locked",11,Color.rgb(145,255,171));address.setTextIsSelectable(true);address.setPadding(0,dp(10),0,dp(8));root.addView(address);summary=hero("BTC · —\nXCP · —\n∞ NOMNI · —");root.addView(summary);status=text("Authenticate to load your wallet.",12,Color.rgb(181,214,191));status.setPadding(0,dp(10),0,dp(14));root.addView(status);
  LinearLayout actions=new LinearLayout(this);send=primary("Send");receive=primary("Receive");actions.addView(send,new LinearLayout.LayoutParams(0,dp(54),1f));actions.addView(receive,new LinearLayout.LayoutParams(0,dp(54),1f));root.addView(actions);send.setEnabled(false);receive.setEnabled(false);send.setOnClickListener(v->startActivity(new Intent(this,XcpComposerActivity.class)));receive.setOnClickListener(v->{Intent i=new Intent(this,ReceiveActivity.class);i.putExtra(ReceiveActivity.EXTRA_ADDRESS,publicAddress);startActivity(i);});
  LinearLayout tools=new LinearLayout(this);refresh=quiet("Refresh");Button track=quiet("Track TX");Button market=quiet("Market");tools.addView(refresh,new LinearLayout.LayoutParams(0,dp(46),1f));tools.addView(track,new LinearLayout.LayoutParams(0,dp(46),1f));tools.addView(market,new LinearLayout.LayoutParams(0,dp(46),1f));root.addView(tools);refresh.setEnabled(false);refresh.setOnClickListener(v->load());track.setOnClickListener(v->startActivity(new Intent(this,TxStatusActivity.class)));market.setOnClickListener(v->startActivity(new Intent(this,MarketMatrixActivity.class)));
  TextView h=text("Recent activity",13,Color.rgb(119,255,151));h.setPadding(0,dp(22),0,dp(8));root.addView(h);activity=text("No activity loaded yet.",12,Color.rgb(192,226,201));activity.setTextIsSelectable(true);root.addView(activity);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1f));shell.addView(OmnitrixNav.bar(this,"Wallet"),new LinearLayout.LayoutParams(-1,dp(54)));setContentView(shell);}
 private void authenticate(){KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);if(km==null||!km.isDeviceSecure()){status.setText("Android device lock is required.");return;}Intent i=km.createConfirmDeviceCredentialIntent("Omnitrix Wallet","Unlock your wallet");if(i!=null)startActivityForResult(i,REQ_UNLOCK);else unlock();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_UNLOCK&&result==RESULT_OK)unlock();else if(req==REQ_UNLOCK)status.setText("Wallet remained locked.");}
 private void unlock(){try{publicAddress=vault.withUnlockedXcpKey(k->DumpedPrivateKey.fromBase58(BitcoinNetwork.MAINNET,new String(k)).getKey().toAddress(ScriptType.P2PKH,BitcoinNetwork.MAINNET).toString());address.setText(shortAddress(publicAddress));refresh.setEnabled(true);send.setEnabled(true);receive.setEnabled(true);load();}catch(Exception e){status.setText("Could not unlock wallet: "+safe(e));}}
 private void load(){if(publicAddress.isEmpty()){authenticate();return;}refresh.setEnabled(false);status.setText("Refreshing balances…");io.execute(()->{try{WalletNetwork.WalletSnapshot s=WalletNetwork.load(publicAddress);runOnUiThread(()->render(s));}catch(Exception e){runOnUiThread(()->{refresh.setEnabled(true);status.setText("Refresh failed: "+safe(e));});}});}
 private void render(WalletNetwork.WalletSnapshot s){refresh.setEnabled(true);double btc=s.btcSats/100000000.0;summary.setText(String.format(java.util.Locale.US,"BTC · %.8f\nXCP · %s\n∞ NOMNI · %s",btc,s.find("XCP").display(),s.find("NOMNI").display()));StringBuilder a=new StringBuilder();for(String row:s.activity){if(a.length()>0)a.append("\n\n");a.append("• ").append(row);}activity.setText(a.length()==0?"No recent activity returned.":a.toString());status.setText("Wallet refreshed");}
 private String shortAddress(String a){return a.length()>16?a.substring(0,8)+"…"+a.substring(a.length()-6):a;}private TextView hero(String s){TextView t=text(s,19,Color.rgb(220,255,230));t.setPadding(dp(18),dp(18),dp(18),dp(18));t.setBackgroundColor(Color.rgb(5,20,12));return t;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setMinWidth(0);b.setTextColor(Color.rgb(0,22,8));b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button quiet(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(11);b.setMinWidth(0);b.setMinimumWidth(0);b.setTextColor(Color.rgb(188,235,201));b.setBackgroundColor(Color.rgb(7,25,15));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}private String safe(Exception e){String s=e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}@Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
