package io.neo.omnitrix;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;
/** Clean first-run entry with an optional protected XCP Key wallet boundary. */
public class XcpKeyActivity extends Activity {
 private static final int REQ_UNLOCK=1441,REQ_IMPORT=1442;private XcpKeyVault vault;private TextView status;
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);vault=new XcpKeyVault(this);buildUi();}
 private void buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(24),dp(36),dp(24),dp(28));root.setBackgroundColor(Color.rgb(1,5,3));scroll.addView(root);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.omnitrix_logo);root.addView(logo,new LinearLayout.LayoutParams(dp(120),dp(120)));TextView title=text("OMNITRIX",30,Color.rgb(225,255,234));title.setGravity(Gravity.CENTER);title.setPadding(0,dp(14),0,dp(4));root.addView(title);TextView profile=text("Search · Wallet · Cloud · NEO Suite",13,Color.rgb(113,170,132));profile.setGravity(Gravity.CENTER);root.addView(profile);status=text("",14,Color.rgb(202,255,217));status.setGravity(Gravity.CENTER);status.setPadding(0,dp(20),0,dp(16));root.addView(status);Button explore=button("EXPLORE OMNITRIX");explore.setOnClickListener(v->startActivity(new Intent(this,ConsumerHomeActivity.class)));root.addView(explore,new LinearLayout.LayoutParams(-1,dp(54)));Button wallet=secondary(vault.hasKey()?"UNLOCK SECURE WALLET":"SET UP SECURE WALLET");LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(-1,dp(50));wp.setMargins(0,dp(10),0,0);root.addView(wallet,wp);wallet.setOnClickListener(v->{if(vault.hasKey())authenticate(REQ_UNLOCK);else authenticate(REQ_IMPORT);});Button browser=secondary("OPEN NOOGLE BROWSER");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(50));bp.setMargins(0,dp(10),0,0);root.addView(browser,bp);browser.setOnClickListener(v->startActivity(new Intent(this,NoogleBrowserActivity.class)));if(vault.hasKey()){Button remove=secondary("WALLET SECURITY OPTIONS");LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(48));rp.setMargins(0,dp(10),0,0);root.addView(remove,rp);remove.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Wallet security").setItems(new String[]{"Open wallet","Remove XCP Key from this device"},(d,w)->{if(w==0)startActivity(new Intent(this,WalletDashboardActivity.class));else new AlertDialog.Builder(this).setTitle("Remove secured XCP Key?").setMessage("This removes encrypted key material from this device. It does not affect blockchain assets.").setPositiveButton("Remove",(dd,ww)->{vault.forget();recreate();}).setNegativeButton("Cancel",null).show();}).show());}TextView note=text("You can explore Omnitrix without importing a wallet key. XCP Key setup is only required for protected Bitcoin / Counterparty signing and remains local to Android security.",12,Color.rgb(111,139,121));note.setGravity(Gravity.CENTER);note.setPadding(dp(6),dp(20),dp(6),0);root.addView(note);setContentView(scroll);updateStatus();}
 private void updateStatus(){if(vault.hasKey()){String fp=vault.fingerprint();status.setText("Secure wallet ready"+(fp.isEmpty()?"":"\nVault fingerprint: "+fp));}else status.setText("Welcome. Explore first, or set up your secure wallet when you are ready.");}
 private void authenticate(int requestCode){KeyguardManager km=(KeyguardManager)getSystemService(KEYGUARD_SERVICE);if(km==null||!km.isDeviceSecure()){new AlertDialog.Builder(this).setTitle("Device lock required").setMessage("Set a PIN, password, pattern, or supported biometric on Android first.").setPositiveButton("OK",null).show();return;}Intent intent=km.createConfirmDeviceCredentialIntent("Omnitrix security","Confirm your device identity");if(intent!=null)startActivityForResult(intent,requestCode);else onAuthenticated(requestCode);}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(resultCode==RESULT_OK)onAuthenticated(requestCode);else Toast.makeText(this,"Wallet remained locked",Toast.LENGTH_SHORT).show();}
 private void onAuthenticated(int requestCode){if(requestCode==REQ_IMPORT)showImportDialog();else if(requestCode==REQ_UNLOCK){try{vault.verifyUnlocked();startActivity(new Intent(this,WalletDashboardActivity.class));}catch(Exception e){status.setText("Secure wallet could not unlock. Re-authenticate or re-import the XCP Key on this device.");}}}
 private void showImportDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(8),dp(20),0);box.addView(text("Enter your mainnet Bitcoin/Counterparty XCP Key (WIF). It is encrypted immediately and never transmitted.",13,Color.DKGRAY));EditText key=new EditText(this);key.setHint("XCP Key");key.setSingleLine(true);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);box.addView(key,new LinearLayout.LayoutParams(-1,dp(56)));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Secure wallet").setView(box).setPositiveButton("Secure",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{char[] value=key.getText().toString().toCharArray();key.setText("");try{vault.importXcpKey(value);dialog.dismiss();Toast.makeText(this,"XCP Key secured",Toast.LENGTH_SHORT).show();recreate();}catch(Exception e){new AlertDialog.Builder(this).setTitle("XCP Key not accepted").setMessage(e.getMessage()==null?"Invalid XCP Key":e.getMessage()).setPositiveButton("OK",null).show();}}));dialog.show();}
 private TextView text(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,24,9));b.setTextSize(14);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(101,255,138));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(180,235,197));b.setTextSize(12);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(7,26,16));return b;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
}
