export const shamuelFamilyTrustKnowledge = Object.freeze({
  id: 'NEO-SHAMUEL-FAMILY-TRUST-CROSS-SYSTEM-001',
  status: 'CANONICAL_INTERNAL_OPERATIONAL_CONTEXT',
  primarySource: 'August 11 2021 Declaration of Trust for The Shamu-El Family Trust',
  operatingRoom: 'Shamu-El Family Trust Assistant Room',
  operatingAgent: 'NIA-009 STEWARD',
  routedSystems: Object.freeze([
    'NEO Algo',
    'NEO Oracle',
    'GISD / GISS NEO LMS',
    'NEOsync Digital Etheric Intelligence',
    'NEO Law',
    'Internal NEO Society Social Norms',
    'LEDGER',
    'SCROLL',
    'ATHENAEUM',
    'COMPASS',
    'ORIGIN',
    'NEO Library',
    'Neopedia',
  ]),
  sourcePriority: Object.freeze([
    'executed_source_fact',
    'approved_record',
    'canonical_internal_context',
    'user_assertion',
    'analysis',
    'external_secondary_commentary',
  ]),
  requiredSeparations: Object.freeze([
    'executed_source_fact',
    'user_assertion_or_architecture',
    'analysis_or_recommendation',
    'external_law_tax_or_regulatory_context',
    'unknown_or_missing_evidence',
  ]),
  approvalRequiredFor: Object.freeze([
    'money_movement',
    'beneficiary_distribution',
    'trade_or_custody_change',
    'trust_amendment_or_restatement',
    'trust_revocation_combination_division_or_termination',
    'trustee_or_signer_change',
    'deed_assignment_or_security_instrument',
    'tax_regulatory_court_or_financial_filing',
    'external_commitment',
    'legal_title_change',
    'promotion_of_unsupported_trust_fact_to_canonical_status',
  ]),
  internalNorms: Object.freeze([
    'stewardship_before_consumption',
    'source_before_assertion',
    'fiduciary_duty_before_convenience',
    'privacy_by_default',
    'disclose_conflicts',
    'avoid_undocumented_commingling',
    'record_material_decisions',
    'distinguish_roles_and_authorities',
    'internal_titles_do_not_replace_documented_legal_authority',
    'preserve_intergenerational_continuity_with_auditable_records',
  ]),
  boundaries: Object.freeze([
    'Executed instruments control trust-specific facts over derivative NEO records.',
    'Affiliated-trust relationships described in the Room remain asserted architecture until supporting governing records are reviewed.',
    'Internal NEO governance does not override applicable public law, tax law, fiduciary duties, court orders, title rules, or regulatory requirements.',
    'NEO outputs do not substitute for licensed legal, tax, accounting, investment, or fiduciary professionals where required.',
  ]),
});

export type ShamuelFamilyTrustKnowledge = typeof shamuelFamilyTrustKnowledge;
