import{appendAudit}from'./securityAudit'
import{revokeWalletReadiness,type WalletRail}from'./walletSession'
const KEY='neopay.device.trust.v1'
export type DeviceTrustRecord={fingerprint:string;trustedAt:string;lastSeenAt:string;label:string}
function coarseContext(){const nav=navigator as any,screenBucket=`${Math.round((screen?.width||0)/100)*100}x${Math.round((screen?.height||0)/100)*100}`;return{platform:String(nav.userAgentData?.platform||nav.platform||'unknown').slice(0,40),language:String(nav.language||'unknown').slice(0,20),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'unknown',screen:screenBucket,touch:Number(nav.maxTouchPoints||0)>0?'touch':'pointer'}}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
export function currentDeviceFingerprint(){return hash(JSON.stringify(coarseContext()))}
export function deviceTrustRecord():DeviceTrustRecord|null{try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v&&typeof v==='object'?v:null}catch{return null}}
export function trustCurrentDevice(label='This device'){const now=new Date().toISOString(),r:DeviceTrustRecord={fingerprint:currentDeviceFingerprint(),trustedAt:now,lastSeenAt:now,label:label.slice(0,60)};localStorage.setItem(KEY,JSON.stringify(r));appendAudit('policy_change','Trusted-device context enrolled using coarse local browser characteristics.');return r}
export function clearDeviceTrust(){localStorage.removeItem(KEY);appendAudit('policy_change','Trusted-device context removed.')}
export function validateDeviceTrust(){const r=deviceTrustRecord();if(!r)return{configured:false,match:false,reason:'No trusted-device context is enrolled.'};const current=currentDeviceFingerprint(),match=current===r.fingerprint;if(match){const next={...r,lastSeenAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(next));return{configured:true,match:true,record:next,reason:'Trusted-device context matches.'}}for(const rail of['raw','unisat','xverse']as WalletRail[])revokeWalletReadiness(rail,'Trusted-device context changed.');appendAudit('transaction_blocked','Trusted-device context changed. All wallet Send readiness was revoked.');return{configured:true,match:false,record:r,reason:'Browser/device context changed. Re-enroll this device and rerun wallet compatibility testing before Send.'}}
