import{useEffect,useMemo,useState}from'react'
import{Bitcoin,Send,X}from'lucide-react'
import{broadcastBitcoinTransaction}from'./bitcoinService'
import{buildNativeBitcoinTransaction,getBitcoinFeeRates,type BitcoinFeeMode,type BitcoinFeeRates}from'./nativeBitcoin'
import{neoPaySigner,type SignerState}from'./signer'
import'./nativeBitcoin.css'

export type NativeBitcoinRequest={destination?:string;amountBtc?:number;label?:string;memo?:string}
const EVENT='neopay-native-btc-send'
export function openNativeBitcoinSend(request:NativeBitcoinRequest={}){window.dispatchEvent(new CustomEvent(EVENT,{detail:request}))}
function short(v:string){return v.length>18?`${v.slice(0,8)}…${v.slice(-8)}`:v}
export function NativeBitcoinSendOverlay(){
 const[open,setOpen]=useState(false),[signer,setSigner]=useState<SignerState>(()=>neoPaySigner.state()),[destination,setDestination]=useState(''),[amount,setAmount]=useState(''),[mode,setMode]=useState<BitcoinFeeMode>('normal'),[rates,setRates]=useState<BitcoinFeeRates|null>(null),[status,setStatus]=useState(''),[label,setLabel]=useState(''),[memo,setMemo]=useState('')
 useEffect(()=>{const handler=(e:Event)=>{const r=(e as CustomEvent<NativeBitcoinRequest>).detail||{};setDestination(r.destination||'');setAmount(r.amountBtc?String(r.amountBtc):'');setLabel(r.label||'');setMemo(r.memo||'');setStatus('');setSigner(neoPaySigner.state());setOpen(true);void getBitcoinFeeRates().then(setRates)};window.addEventListener(EVENT,handler);return()=>window.removeEventListener(EVENT,handler)},[])
 useEffect(()=>{if(open)void getBitcoinFeeRates().then(setRates)},[open])
 const rate=useMemo(()=>rates?.[mode]||0,[rates,mode])
 const connect=async()=>{try{setSigner(await neoPaySigner.connect())}catch(e:any){setStatus(e.message)}}
 const send=async()=>{try{setStatus('');let s=neoPaySigner.state();if(!s.connected){s=await neoPaySigner.connect();setSigner(s)}if(!s.connected||!s.address)throw new Error('Connect a compatible user-controlled Bitcoin signer.');const btc=Number(amount);if(!Number.isFinite(btc)||btc<=0)throw new Error('Enter a valid BTC amount.');setStatus('Selecting UTXOs and calculating network fee…');const plan=await buildNativeBitcoinTransaction({source:s.address,destination,amountBtc:btc,feeMode:mode});const details=`Send ${btc.toFixed(8)} BTC\nTo: ${destination}\n${label?`Recipient: ${label}\n`:''}${memo?`Memo: ${memo}\n`:''}Network fee: ${plan.feeSats.toLocaleString()} sats @ ${plan.feeRate} sat/vB\nChange: ${(plan.changeSats/1e8).toFixed(8)} BTC\nInputs: ${plan.selectedUtxos}\n\nContinue to NEOpay security review?`;if(!window.confirm(details)){setStatus('Bitcoin send cancelled.');return}setStatus('Waiting for local wallet approval…');const signed=await neoPaySigner.sign({unsignedTxHex:plan.unsignedTxHex,summary:{action:'btc-send',asset:'BTC',amount:btc,destination,source:s.address,networkFeeSats:plan.feeSats,feeRate:plan.feeRate,feeMode:mode}});setStatus('Broadcasting signed Bitcoin transaction…');const txid=await broadcastBitcoinTransaction(signed);setStatus(`Submitted ${short(txid)} · receipt tracking started.`)}catch(e:any){setStatus(e?.message||'Native Bitcoin send failed.')}}
 return <><button className="neopay-btc-launch" onClick={()=>{setOpen(true);setSigner(neoPaySigner.state());void getBitcoinFeeRates().then(setRates)}}><Bitcoin size={16}/>Bitcoin</button>{open&&<div className="neopay-btc-backdrop" role="dialog" aria-modal="true" aria-label="Send Bitcoin"><div className="neopay-btc-sheet"><button className="neopay-btc-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="btc-head"><Bitcoin size={24}/><div><h2>Send Bitcoin</h2><span>Native BTC · user-controlled signing</span></div></div><div className="btc-status-grid"><div><span>Signer</span><strong>{signer.connected?signer.name:'Locked'}</strong></div><div><span>Wallet</span><strong>{signer.address?short(signer.address):'Not connected'}</strong></div><div><span>Fee market</span><strong>{rates?`${rate} sat/vB`:'Loading…'}</strong></div></div>{!signer.connected&&<button className="btc-secondary" onClick={()=>void connect()}>Connect Local Signer</button>}<label>Destination<input value={destination} onChange={e=>setDestination(e.target.value.trim())} placeholder="Bitcoin address"/></label><label>BTC Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0.00000000"/></label><label>Network Speed<select value={mode} onChange={e=>setMode(e.target.value as BitcoinFeeMode)}><option value="economy">Economy {rates?`· ${rates.economy} sat/vB`:''}</option><option value="normal">Normal {rates?`· ${rates.normal} sat/vB`:''}</option><option value="priority">Priority {rates?`· ${rates.priority} sat/vB`:''}</option></select></label>{(label||memo)&&<div className="btc-request-meta">{label&&<span>Recipient: {label}</span>}{memo&&<span>Memo: {memo}</span>}</div>}<button className="btc-primary" onClick={()=>void send()}><Send size={16}/>Review & Send Bitcoin</button>{status&&<p className="btc-status">{status}</p>}<p className="btc-fine">NEOpay selects confirmed UTXOs, applies dust protection, caps estimated fees at 200,000 sats, creates change back to the signer address, and never stores your private key.</p></div></div>}</>
}
