import{useEffect,useMemo,useState}from'react'
import{Bitcoin,Send,X}from'lucide-react'
import{broadcastBitcoinTransaction}from'./bitcoinService'
import{buildNativeBitcoinTransaction,getBitcoinFeeRates,type BitcoinFeeMode,type BitcoinFeeRates}from'./nativeBitcoin'
import{neoPaySigner,type SignerState}from'./signer'
import{connectUniSat,discoverWalletProviders}from'./walletProviderRegistry'
import{getPsbtWalletAdapter}from'./psbtWalletAdapters'
import{settleNativeBitcoinWithPsbtAdapter,settleNativeBitcoinWithUniSat}from'./psbtSettlement'
import'./nativeBitcoin.css'

export type NativeBitcoinRequest={destination?:string;amountBtc?:number;label?:string;memo?:string}
const EVENT='neopay-native-btc-send'
export function openNativeBitcoinSend(request:NativeBitcoinRequest={}){window.dispatchEvent(new CustomEvent(EVENT,{detail:request}))}
function short(v:string){return v.length>18?`${v.slice(0,8)}…${v.slice(-8)}`:v}
export function NativeBitcoinSendOverlay(){
 const[open,setOpen]=useState(false),[signer,setSigner]=useState<SignerState>(()=>neoPaySigner.state()),[psbtWallet,setPsbtWallet]=useState<{id:string;name:string;address:string}|null>(null),[destination,setDestination]=useState(''),[amount,setAmount]=useState(''),[mode,setMode]=useState<BitcoinFeeMode>('normal'),[rates,setRates]=useState<BitcoinFeeRates|null>(null),[status,setStatus]=useState(''),[label,setLabel]=useState(''),[memo,setMemo]=useState('')
 useEffect(()=>{const handler=(e:Event)=>{const r=(e as CustomEvent<NativeBitcoinRequest>).detail||{};setDestination(r.destination||'');setAmount(r.amountBtc?String(r.amountBtc):'');setLabel(r.label||'');setMemo(r.memo||'');setStatus('');setSigner(neoPaySigner.state());setOpen(true);void getBitcoinFeeRates().then(setRates)};window.addEventListener(EVENT,handler);return()=>window.removeEventListener(EVENT,handler)},[])
 useEffect(()=>{if(open)void getBitcoinFeeRates().then(setRates)},[open])
 const rate=useMemo(()=>rates?.[mode]||0,[rates,mode]),providers=discoverWalletProviders(),unisatReady=providers.some(p=>p.id==='unisat'&&p.compatible),xverseReady=providers.some(p=>p.id==='xverse'&&p.compatible)
 const connectRaw=async()=>{try{setSigner(await neoPaySigner.connect());setPsbtWallet(null)}catch(e:any){setStatus(e.message)}}
 const connectUniSatPsbt=async()=>{try{const s=await connectUniSat();setPsbtWallet({id:'unisat',name:'UniSat Wallet',address:s.address});setStatus('UniSat connected for PSBT signing.')}catch(e:any){setStatus(e.message)}}
 const connectXverse=async()=>{try{const a=getPsbtWalletAdapter('xverse');if(!a)throw new Error('Xverse adapter is unavailable.');const s=await a.connect();setPsbtWallet({id:a.id,name:a.name,address:s.address});setStatus('Xverse connected for PSBT signing.')}catch(e:any){setStatus(e.message)}}
 const send=async()=>{try{setStatus('');const btc=Number(amount);if(!Number.isFinite(btc)||btc<=0)throw new Error('Enter a valid BTC amount.');const raw=neoPaySigner.state();let wallet=psbtWallet;if(!raw.connected&&!wallet){if(xverseReady){const a=getPsbtWalletAdapter('xverse')!;const s=await a.connect();wallet={id:a.id,name:a.name,address:s.address};setPsbtWallet(wallet)}else if(unisatReady){const u=await connectUniSat();wallet={id:'unisat',name:'UniSat Wallet',address:u.address};setPsbtWallet(wallet)}}const source=raw.connected&&raw.address?raw.address:wallet?.address;if(!source)throw new Error('Connect a compatible raw signer, UniSat, or Xverse PSBT wallet.');setStatus('Selecting UTXOs and calculating network fee…');const plan=await buildNativeBitcoinTransaction({source,destination,amountBtc:btc,feeMode:mode});const path=raw.connected?'Raw transaction signer':wallet?.name||'PSBT wallet';const details=`Send ${btc.toFixed(8)} BTC\nTo: ${destination}\n${label?`Recipient: ${label}\n`:''}${memo?`Memo: ${memo}\n`:''}Network fee: ${plan.feeSats.toLocaleString()} sats @ ${plan.feeRate} sat/vB\nChange: ${(plan.changeSats/1e8).toFixed(8)} BTC\nInputs: ${plan.selectedUtxos}\nSigning path: ${path}\n\nContinue to NEOpay security review?`;if(!window.confirm(details)){setStatus('Bitcoin send cancelled.');return}const summary={action:'btc-send',asset:'BTC',amount:btc,destination,source,networkFeeSats:plan.feeSats,feeRate:plan.feeRate,feeMode:mode};if(raw.connected){setStatus('Waiting for local wallet approval…');const signed=await neoPaySigner.sign({unsignedTxHex:plan.unsignedTxHex,summary});setStatus('Broadcasting signed Bitcoin transaction…');const txid=await broadcastBitcoinTransaction(signed);setStatus(`Submitted ${short(txid)} · receipt tracking started.`)}else if(wallet?.id==='unisat'){setStatus('Building PSBT and waiting for UniSat approval…');const result=await settleNativeBitcoinWithUniSat(plan,summary);setStatus(`Submitted ${short(result.txid)} through UniSat PSBT · receipt tracking started.`)}else if(wallet){setStatus(`Building PSBT and waiting for ${wallet.name} approval…`);const result=await settleNativeBitcoinWithPsbtAdapter(wallet.id,plan,summary,wallet.address);setStatus(`Submitted ${short(result.txid)} through ${result.providerName} · receipt tracking started.`)}else throw new Error('No PSBT wallet is connected.')}catch(e:any){setStatus(e?.message||'Native Bitcoin send failed.')}}
 return <><button className="neopay-btc-launch" onClick={()=>{setOpen(true);setSigner(neoPaySigner.state());void getBitcoinFeeRates().then(setRates)}}><Bitcoin size={16}/>Bitcoin</button>{open&&<div className="neopay-btc-backdrop" role="dialog" aria-modal="true" aria-label="Send Bitcoin"><div className="neopay-btc-sheet"><button className="neopay-btc-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="btc-head"><Bitcoin size={24}/><div><h2>Send Bitcoin</h2><span>Native BTC · raw signer or PSBT wallet</span></div></div><div className="btc-status-grid"><div><span>Raw signer</span><strong>{signer.connected?signer.name:'Not connected'}</strong></div><div><span>PSBT wallet</span><strong>{psbtWallet?`${psbtWallet.name} ${short(psbtWallet.address)}`:(unisatReady||xverseReady)?'Available':'Not detected'}</strong></div><div><span>Fee market</span><strong>{rates?`${rate} sat/vB`:'Loading…'}</strong></div></div>{!signer.connected&&<div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8}}><button className="btc-secondary" onClick={()=>void connectRaw()}>Raw Signer</button><button className="btc-secondary" disabled={!unisatReady} onClick={()=>void connectUniSatPsbt()}>UniSat</button><button className="btc-secondary" disabled={!xverseReady} onClick={()=>void connectXverse()}>Xverse</button></div>}<label>Destination<input value={destination} onChange={e=>setDestination(e.target.value.trim())} placeholder="Bitcoin address"/></label><label>BTC Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0.00000000"/></label><label>Network Speed<select value={mode} onChange={e=>setMode(e.target.value as BitcoinFeeMode)}><option value="economy">Economy {rates?`· ${rates.economy} sat/vB`:''}</option><option value="normal">Normal {rates?`· ${rates.normal} sat/vB`:''}</option><option value="priority">Priority {rates?`· ${rates.priority} sat/vB`:''}</option></select></label>{(label||memo)&&<div className="btc-request-meta">{label&&<span>Recipient: {label}</span>}{memo&&<span>Memo: {memo}</span>}</div>}<button className="btc-primary" onClick={()=>void send()}><Send size={16}/>Review & Send Bitcoin</button>{status&&<p className="btc-status">{status}</p>}<p className="btc-fine">PSBT signing is enabled for native SegWit/Taproot wallet accounts. Every PSBT is integrity-checked before wallet approval. NEOpay never stores your private key.</p></div></div>}</>
}
