import {useEffect,useMemo,useState} from 'react'
import {Activity,Copy,RefreshCw,Search,ShieldCheck,WalletCards} from 'lucide-react'
import {broadcastSignedTransaction,composeOrder,getAddressBalances,getAddressTransactions,getApiHealth,getAsset,getOrderMatches,getOrders,getUserOrders,isLikelyBitcoinAddress} from './counterpartyService'
import {extractUnsignedTxHex,neoPaySigner,type SignerState} from './signer'
import './neopay.css'

const DEFAULT_ADDRESS='1NySA74g62Mr28Unp4uCxwtQv9FkD7AVpk'
const TREASURY_ADDRESS='18FyntJG9hdXYvanm67mGgbyo1P7adckvg'
const NOMNI_ICON='https://coindaddy.io/content/images/icons/xcp/NOMNI.png'
type Tab='dashboard'|'wallet'|'balances'|'transactions'|'neoscan'|'exchange'|'orders'|'trades'|'dispensers'|'economics'|'assets'|'settings'
function rows(v:any){return Array.isArray(v)?v:(v?.result??[])}
function qty(v:any){const n=Number(v??0);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:8}):'—'}
function short(v:string){return v&&v.length>18?`${v.slice(0,8)}…${v.slice(-8)}`:v||'—'}
function txidFrom(v:any){const r=v?.result??v;return r?.tx_hash??r?.txid??r?.transaction_hash??null}

export function NEOpayApp(){
 const[tab,setTab]=useState<Tab>('dashboard'),[address,setAddress]=useState(DEFAULT_ADDRESS)
 const[balances,setBalances]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[asset,setAsset]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[userOrders,setUserOrders]=useState<any[]>([]),[trades,setTrades]=useState<any[]>([])
 const[error,setError]=useState(''),[loading,setLoading]=useState(false),[lastUpdated,setLastUpdated]=useState('Never'),[apiOnline,setApiOnline]=useState(false)
 const[signer,setSigner]=useState<SignerState>(neoPaySigner.state()),[side,setSide]=useState<'BUY'|'SELL'>('BUY'),[amount,setAmount]=useState(''),[price,setPrice]=useState(''),[orderStatus,setOrderStatus]=useState('Review only — no transaction prepared.')

 const refresh=async()=>{if(!isLikelyBitcoinAddress(address)){setError('Enter a valid Bitcoin/Counterparty address.');return}setLoading(true);setError('');const results=await Promise.allSettled([getAddressBalances(address),getAddressTransactions(address),getAsset('NOMNI'),getOrders(),getUserOrders(address),getOrderMatches(),getApiHealth()]);const[b,t,a,o,u,m,h]=results;if(b.status==='fulfilled')setBalances(rows(b.value));else setBalances([]);if(t.status==='fulfilled')setTransactions(rows(t.value));else setTransactions([]);if(a.status==='fulfilled')setAsset(a.value?.result??a.value);else setAsset(null);if(o.status==='fulfilled')setOrders(o.value);else setOrders([]);if(u.status==='fulfilled')setUserOrders(rows(u.value));else setUserOrders([]);if(m.status==='fulfilled')setTrades(m.value);else setTrades([]);setApiOnline(h.status==='fulfilled');const failures=results.filter(r=>r.status==='rejected');if(failures.length)setError(`Some NEOpay gateway data is unavailable (${failures.length}/7 requests). Retry or view API status in Settings.`);setLastUpdated(new Date().toLocaleTimeString());setLoading(false)}
 useEffect(()=>{void refresh()},[])
 const nomni=balances.find(b=>String(b.asset).toUpperCase()==='NOMNI'),xcp=balances.find(b=>String(b.asset).toUpperCase()==='XCP')
 const parsedOrders=useMemo(()=>orders.map(o=>{const give=String(o.give_asset||'').toUpperCase(),get=String(o.get_asset||'').toUpperCase(),giveQ=Number(o.give_remaining??o.give_quantity??0),getQ=Number(o.get_remaining??o.get_quantity??0);if(give==='NOMNI'&&get==='XCP')return{...o,side:'ask',price:giveQ?getQ/giveQ:0,nomni:giveQ,xcp:getQ};if(give==='XCP'&&get==='NOMNI')return{...o,side:'bid',price:getQ?giveQ/getQ:0,nomni:getQ,xcp:giveQ};return null}).filter(Boolean) as any[],[orders])
 const asks=parsedOrders.filter(o=>o.side==='ask').sort((a,b)=>a.price-b.price),bids=parsedOrders.filter(o=>o.side==='bid').sort((a,b)=>b.price-a.price),bestAsk=asks[0]?.price,bestBid=bids[0]?.price,spread=Number.isFinite(bestAsk)&&Number.isFinite(bestBid)?bestAsk-bestBid:null
 const connectSigner=async()=>{try{const s=await neoPaySigner.connect();setSigner(s);if(s.address)setAddress(s.address);setOrderStatus(`Signer connected: ${s.name}`)}catch(e:any){setOrderStatus(e.message)}}
 const reviewAndSign=async()=>{try{const a=Number(amount),p=Number(price);if(!Number.isFinite(a)||a<=0||!Number.isFinite(p)||p<=0)throw new Error('Enter a valid amount and price.');if(asset?.divisible===false&&!Number.isInteger(a))throw new Error('NOMNI is indivisible; use a whole-number NOMNI amount.');const total=a*p;const summary=`${side} ${a} NOMNI @ ${p} XCP = ${total} XCP\nSource: ${address}\nNEOpay never receives your private key.\n\nContinue to transaction construction?`;if(!window.confirm(summary)){setOrderStatus('Order review cancelled.');return}const nomniUnits=asset?.divisible===false?Math.round(a):Math.round(a*1e8),xcpUnits=Math.round(total*1e8);const input=side==='BUY'?{source:address,give_asset:'XCP' as const,give_quantity:xcpUnits,get_asset:'NOMNI' as const,get_quantity:nomniUnits}:{source:address,give_asset:'NOMNI' as const,give_quantity:nomniUnits,get_asset:'XCP' as const,get_quantity:xcpUnits};setOrderStatus('Constructing unsigned Counterparty order…');const composed=await composeOrder(input);const unsignedTxHex=extractUnsignedTxHex(composed);if(!signer.connected)throw new Error('Unsigned transaction prepared, but no compatible user-controlled signer is connected. Nothing was broadcast.');setOrderStatus('Waiting for your wallet signature…');const signed=await neoPaySigner.sign({unsignedTxHex,summary:{market:'NOMNI/XCP',side,amount:a,price:p,total,source:address}});if(!window.confirm('Your wallet returned a signed transaction. Broadcast it to the Counterparty/Bitcoin network now?')){setOrderStatus('Signed transaction was not broadcast.');return}setOrderStatus('Broadcasting signed transaction…');const result=await broadcastSignedTransaction(signed);const txid=txidFrom(result);if(!txid)throw new Error('Broadcast response did not contain a transaction hash; NEOpay will not claim success.');setOrderStatus(`Broadcast submitted: ${txid}`);void refresh()}catch(e:any){setOrderStatus(e.message||'Order workflow failed.')}}
 const nav:[Tab,string][]=[['dashboard','Dashboard'],['wallet','Wallet'],['balances','Balances'],['transactions','Transactions'],['neoscan','NEOSCAN'],['exchange','Exchange'],['orders','My Orders'],['trades','Trades'],['dispensers','Dispensers'],['economics','Economics'],['assets','Assets'],['settings','Settings']]
 return <div className="np-shell"><aside className="np-side"><div className="np-brand"><div className="np-logo">N</div><div><b>NEOpay</b><span>NOMNI Wallet • W.O.M.E. Digital Ledger</span></div></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="np-safe"><ShieldCheck size={16}/>Non-custodial. Never enter a private key or seed phrase.</div></aside><main className="np-main"><header className="np-header"><div><p>WORLD OPEN MARKET EXCHANGE</p><h1>NEOpay</h1></div><div className="np-actions"><button onClick={()=>navigator.clipboard?.writeText(address)}><Copy size={15}/>Copy</button><button onClick={()=>void refresh()} disabled={loading}><RefreshCw size={15}/>Refresh</button></div></header>
 {error&&<div className="np-error"><b>NEOpay data notice</b><span>{error}</span><button onClick={()=>void refresh()}>Retry</button></div>}
 {tab==='dashboard'&&<><section className="np-stats"><Card label="NOMNI Balance" value={qty(nomni?.quantity)} sub="Gateway-proxied on-chain balance"/><Card label="XCP Balance" value={qty(xcp?.quantity)} sub="Gateway-proxied on-chain balance"/><Card label="BTC Balance" value="Data unavailable" sub="Bitcoin balance provider not connected"/><Card label="NOMNI Supply" value={asset?qty(asset.supply??asset.quantity):'Data unavailable'} sub="Counterparty asset metadata"/></section><section className="np-grid"><Panel title="Latest Transactions"><TxTable items={transactions.slice(0,8)}/></Panel><Panel title="NOMNI / XCP Market"><div className="np-market"><Metric label="Best Bid" value={bestBid?`${bestBid.toFixed(8)} XCP`:'Data unavailable'}/><Metric label="Best Ask" value={bestAsk?`${bestAsk.toFixed(8)} XCP`:'Data unavailable'}/><Metric label="Spread" value={spread!==null?spread.toFixed(8):'Data unavailable'}/><Metric label="Open Orders" value={String(parsedOrders.length)}/></div></Panel></section></>}
 {tab==='wallet'&&<Panel title="Wallet / Signer"><label className="np-label">Counterparty / Bitcoin address</label><div className="np-inputrow"><input value={address} onChange={e=>setAddress(e.target.value.trim())}/><button onClick={()=>void refresh()}><Search size={16}/>Load</button></div><div className="np-scan"><Metric label="Signer" value={signer.connected?signer.name:(signer.available?'AVAILABLE':'NOT CONNECTED')}/><Metric label="Network" value={signer.network||'mainnet'}/></div><button onClick={()=>void connectSigner()} disabled={!signer.available}>Connect User-Controlled Signer</button><p className="np-muted">NEOpay never requests, stores, or transmits your private key or seed phrase.</p><div className="np-address"><WalletCards size={18}/>{address}</div></Panel>}
 {tab==='balances'&&<Panel title="Balances"><div className="np-tablewrap"><table><thead><tr><th>Asset</th><th>Quantity</th><th>Type</th><th>Issuer</th><th>Estimated Value</th></tr></thead><tbody>{balances.length?balances.map((b,i)=><tr key={`${b.asset}-${i}`}><td>{String(b.asset).toUpperCase()==='NOMNI'&&<img alt="NOMNI" className="np-coin" src={NOMNI_ICON}/>} {b.asset}</td><td>{qty(b.quantity)}</td><td>{b.asset_type??'Counterparty asset'}</td><td>{short(b.issuer)}</td><td>Data unavailable</td></tr>):<tr><td colSpan={5}>No balance data available.</td></tr>}</tbody></table></div></Panel>}
 {tab==='transactions'&&<Panel title="Transaction History"><TxTable items={transactions}/></Panel>}
 {tab==='neoscan'&&<Panel title="NEOSCAN"><p className="np-muted">Address and NOMNI asset views use the NEOpay production gateway.</p><div className="np-scan"><Metric label="Address" value={short(address)}/><Metric label="NOMNI issuer" value={short(asset?.issuer)}/><Metric label="NOMNI supply" value={asset?qty(asset.supply??asset.quantity):'Data unavailable'}/><Metric label="Treasury" value={short(TREASURY_ADDRESS)}/></div></Panel>}
 {tab==='exchange'&&<><section className="np-stats"><Card label="Market" value="NOMNI / XCP" sub="Counterparty DEX"/><Card label="Best Bid" value={bestBid?bestBid.toFixed(8):'Data unavailable'} sub="XCP per NOMNI"/><Card label="Best Ask" value={bestAsk?bestAsk.toFixed(8):'Data unavailable'} sub="XCP per NOMNI"/><Card label="Spread" value={spread!==null?spread.toFixed(8):'Data unavailable'} sub="Ask minus bid"/></section><section className="np-grid"><OrderBook title="Sell Orders" items={asks}/><OrderBook title="Buy Orders" items={bids}/></section><Panel title="Place Order — User-Controlled Signing"><div className="np-tradeform"><select value={side} onChange={e=>setSide(e.target.value as 'BUY'|'SELL')}><option>BUY</option><option>SELL</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="NOMNI amount" inputMode="decimal"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price in XCP" inputMode="decimal"/><button onClick={()=>void reviewAndSign()}>Review Order</button></div><p className="np-muted">{orderStatus}</p><p className="np-muted">Signing happens only inside a compatible user-controlled browser wallet. Broadcasting fails closed unless the production gateway broadcast route is configured.</p></Panel></>}
 {tab==='orders'&&<Panel title="My Orders"><OrderRows items={userOrders}/></Panel>}
 {tab==='trades'&&<Panel title="Recent Trades"><div className="np-tablewrap"><table><thead><tr><th>Time</th><th>Forward</th><th>Backward</th><th>Status</th><th>Transaction</th></tr></thead><tbody>{trades.length?trades.map((t,i)=><tr key={i}><td>{t.block_time??t.block_index??'—'}</td><td>{t.forward_asset} {qty(t.forward_quantity)}</td><td>{t.backward_asset} {qty(t.backward_quantity)}</td><td>{t.status??'—'}</td><td>{short(t.tx0_hash??t.id)}</td></tr>):<tr><td colSpan={5}>Trade data unavailable.</td></tr>}</tbody></table></div></Panel>}
 {tab==='dispensers'&&<Panel title="Dispensers"><p className="np-muted">Dispenser reads will use the same gateway. Create/Close execution remains gated by the signer pipeline.</p></Panel>}
 {tab==='economics'&&<><section className="np-stats"><Card label="Total NOMNI Supply" value={asset?qty(asset.supply??asset.quantity):'Data unavailable'} sub="On-chain metadata"/><Card label="Treasury Address" value={short(TREASURY_ADDRESS)} sub="Configured reference"/><Card label="Holder Count" value="Data unavailable" sub="Indexer not connected"/><Card label="Market Activity" value={`${parsedOrders.length} open orders`} sub="Calculated from fetched orders"/></section><Panel title="NOMNI Supply Over Time"><p>Live Supply Over Time shows how the recorded NOMNI token supply changes across blockchain history. It is derived from Counterparty ledger data and should update as new blockchain data becomes available.</p><div className="np-placeholder">Historical supply data unavailable</div></Panel></>}
 {tab==='assets'&&<Panel title="NOMNI Asset"><div className="np-asset"><img alt="NOMNI" src={NOMNI_ICON}/><div><h2>NOMNI</h2><p>{asset?.description||'Data unavailable'}</p></div></div><div className="np-scan"><Metric label="Issuer" value={short(asset?.issuer)}/><Metric label="Supply" value={asset?qty(asset.supply??asset.quantity):'Data unavailable'}/><Metric label="Divisible" value={asset?.divisible===undefined?'Data unavailable':String(asset.divisible)}/><Metric label="Treasury" value={short(TREASURY_ADDRESS)}/></div></Panel>}
 {tab==='settings'&&<Panel title="Settings / API Status"><div className="np-scan"><Metric label="NEOpay Gateway" value={apiOnline?'ONLINE':'OFFLINE / UNCONFIGURED'}/><Metric label="NEOpay Frontend" value="ONLINE"/><Metric label="Signing" value={signer.connected?'CONNECTED':signer.available?'AVAILABLE':'NOT CONNECTED'}/><Metric label="Last refresh" value={lastUpdated}/></div><p className="np-muted">GitHub is primary. Base44 remains secondary. The browser no longer calls Counterparty directly.</p></Panel>}
 </main></div>}
function Card({label,value,sub}:{label:string,value:string,sub:string}){return <div className="np-card"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Panel({title,children}:{title:string,children:any}){return <section className="np-panel"><div className="np-paneltitle"><Activity size={17}/><b>{title}</b></div>{children}</section>}
function Metric({label,value}:{label:string,value:string}){return <div className="np-metric"><span>{label}</span><b>{value}</b></div>}
function TxTable({items}:{items:any[]}){return <div className="np-tablewrap"><table><thead><tr><th>Type</th><th>Source</th><th>Destination</th><th>Block</th><th>Transaction</th><th>Validity</th></tr></thead><tbody>{items.length?items.map((t,i)=><tr key={t.tx_hash||i}><td>{t.type||t.transaction_type||t.event||'transaction'}</td><td>{short(t.source)}</td><td>{short(t.destination)}</td><td>{t.block_index??'—'}</td><td title={t.tx_hash}>{short(t.tx_hash)}</td><td>{t.valid??t.status??'—'}</td></tr>):<tr><td colSpan={6}>Transaction data unavailable.</td></tr>}</tbody></table></div>}
function OrderBook({title,items}:{title:string,items:any[]}){return <Panel title={title}><div className="np-tablewrap"><table><thead><tr><th>Price</th><th>NOMNI</th><th>XCP</th></tr></thead><tbody>{items.length?items.slice(0,20).map((o,i)=><tr key={o.tx_hash||i}><td>{o.price.toFixed(8)}</td><td>{qty(o.nomni)}</td><td>{qty(o.xcp)}</td></tr>):<tr><td colSpan={3}>Order data unavailable.</td></tr>}</tbody></table></div></Panel>}
function OrderRows({items}:{items:any[]}){return <div className="np-tablewrap"><table><thead><tr><th>Give</th><th>Get</th><th>Status</th><th>Transaction</th></tr></thead><tbody>{items.length?items.map((o,i)=><tr key={o.tx_hash||i}><td>{o.give_asset} {qty(o.give_quantity)}</td><td>{o.get_asset} {qty(o.get_quantity)}</td><td>{o.status??'—'}</td><td>{short(o.tx_hash)}</td></tr>):<tr><td colSpan={4}>No order data available.</td></tr>}</tbody></table></div>}
