import{useMemo,useState}from'react'
import{BookUser,Copy,QrCode,Send,Trash2,X}from'lucide-react'
import{buildBitcoinPaymentUri,loadContacts,parseBitcoinPaymentRequest,qrImageUrl,recentRecipients,removeContact,upsertContact,type NEOpayContact}from'./contactIntelligence'
import{openUnifiedSend}from'./sendBridge'
import'./contacts.css'

const TREASURY='18FyntJG9hdXYvanm67mGgbyo1P7adckvg'
function short(v:string){return v.length>18?`${v.slice(0,8)}…${v.slice(-8)}`:v}
export function NEOpayContactCenter(){
 const[open,setOpen]=useState(false),[contacts,setContacts]=useState<NEOpayContact[]>(()=>loadContacts()),[name,setName]=useState(''),[address,setAddress]=useState(''),[ces,setCes]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState('')
 const[requestAmount,setRequestAmount]=useState(''),[requestLabel,setRequestLabel]=useState('NEOpay payment'),[requestMemo,setRequestMemo]=useState(''),[importRequest,setImportRequest]=useState('')
 const recent=useMemo(()=>recentRecipients(8),[contacts,open])
 const requestUri=useMemo(()=>{try{return buildBitcoinPaymentUri({address:TREASURY,amountBtc:Number(requestAmount)||undefined,label:requestLabel,message:requestMemo})}catch{return''}},[requestAmount,requestLabel,requestMemo])
 const add=()=>{try{setContacts(upsertContact({name,address,cesAccount:ces,note,trusted:true}));setName('');setAddress('');setCes('');setNote('');setMessage('Contact saved and trusted on this device.')}catch(e:any){setMessage(e.message)}}
 const remove=(id:string)=>{setContacts(removeContact(id));setMessage('Contact removed.')}
 const prepare=(contact:NEOpayContact|{address:string})=>{const saved='name'in contact?contact:contacts.find(c=>c.address.toLowerCase()===contact.address.toLowerCase());openUnifiedSend({destination:contact.address,label:saved?.name,cesAccount:saved?.cesAccount});setOpen(false)}
 const importAndSend=()=>{try{const parsed=parseBitcoinPaymentRequest(importRequest);if(parsed.amountBtc)throw new Error(`This request asks for ${parsed.amountBtc} BTC. Native BTC transaction construction is not enabled in this NEOpay send form yet, so NEOpay will not reinterpret it as a Counterparty asset payment.`);openUnifiedSend({destination:parsed.address,label:parsed.label,memo:parsed.message});setOpen(false)}catch(e:any){setMessage(e.message)}}
 return <><button className="neopay-contact-launch" onClick={()=>setOpen(true)}><BookUser size={16}/>Contacts</button>{open&&<div className="neopay-contact-backdrop" role="dialog" aria-modal="true"><div className="neopay-contact-sheet"><button className="neopay-contact-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="contact-head"><BookUser size={22}/><div><h2>Contacts & Requests</h2><span>Bitcoin address remains the settlement identity.</span></div></div>
 <section className="contact-section"><h3>Saved Contacts</h3><div className="contact-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><input value={address} onChange={e=>setAddress(e.target.value.trim())} placeholder="Bitcoin / Counterparty address"/><input value={ces} onChange={e=>setCes(e.target.value)} placeholder="CES account number (optional)"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Note (optional)"/></div><button className="contact-primary" onClick={add}>Save Trusted Contact</button>{message&&<p className="contact-msg">{message}</p>}{contacts.length?<div className="contact-list">{contacts.map(c=><div className="contact-row" key={c.id}><div><strong>{c.name}</strong><span>{short(c.address)}{c.cesAccount?` · CES ${c.cesAccount}`:''}</span>{c.note&&<small>{c.note}</small>}</div><div><button onClick={()=>prepare(c)} title="Send to contact"><Send size={15}/></button><button onClick={()=>navigator.clipboard?.writeText(c.address)} title="Copy address"><Copy size={15}/></button><button onClick={()=>remove(c.id)} title="Remove"><Trash2 size={15}/></button></div></div>)}</div>:<p className="contact-empty">No contacts saved yet.</p>}</section>
 <section className="contact-section"><h3>Recent Recipients</h3>{recent.length?<div className="contact-list">{recent.map(r=><div className="contact-row" key={r.address}><div><strong>{r.contact?.name||'Recent recipient'}</strong><span>{short(r.address)} · {r.count} transaction{r.count===1?'':'s'}</span></div><button onClick={()=>prepare(r)}><Send size={15}/></button></div>)}</div>:<p className="contact-empty">No locally recorded recipients yet.</p>}</section>
 <section className="contact-section"><h3>Import Payment Request</h3><p className="contact-empty">Paste a Bitcoin address or standard bitcoin: URI. Address-only requests can load into Send. BTC-denominated requests fail closed until NEOpay's native BTC constructor is enabled.</p><div className="contact-form"><input value={importRequest} onChange={e=>setImportRequest(e.target.value)} placeholder="bitcoin:address or address"/></div><button className="contact-primary" onClick={importAndSend}><Send size={15}/>Load in Send</button></section>
 <section className="contact-section"><h3>Receive / Payment Request</h3><p className="contact-empty">Generate a standard Bitcoin payment URI for the NEO Treasury address. The QR contains only public payment-request data.</p><div className="contact-form"><input value={requestAmount} onChange={e=>setRequestAmount(e.target.value)} inputMode="decimal" placeholder="BTC amount (optional)"/><input value={requestLabel} onChange={e=>setRequestLabel(e.target.value)} placeholder="Label"/><input value={requestMemo} onChange={e=>setRequestMemo(e.target.value)} placeholder="Message"/></div>{requestUri&&<div className="payment-request"><img src={qrImageUrl(requestUri)} alt="Bitcoin payment request QR"/><code>{requestUri}</code><div><button onClick={()=>navigator.clipboard?.writeText(requestUri)}><Copy size={15}/>Copy Request</button><a href={requestUri}><QrCode size={15}/>Open Wallet</a></div></div>}</section>
 </div></div>}</>
}
