import {useEffect,useMemo,useState} from 'react'
import {ArrowDownLeft,ArrowUpRight,BarChart3,Landmark,RefreshCw,Search,Send,ShieldCheck,Store,WalletCards} from 'lucide-react'
import {broadcastBitcoinTransaction,getBitcoinAddressSummary,satsToBtc} from './bitcoinService'
import {composeOrder,composeSend,getAddressBalances,getAddressTransactions,getApiHealth,getAsset,getDispensers,getOrderMatches,getOrders,isLikelyBitcoinAddress} from './counterpartyService'
import {extractUnsignedTxHex,neoPaySigner,type SignerState} from './signer'
import {getMarketRates,type MarketRates} from './marketRates'
import {getCesTraderData,loadCesProfile,saveCesProfile,type CesProfile,type CesTraderData} from './cesWalletService'
import './wallet.css'

const DEFAULT_ADDRESS='18FyntJG9hdXYvanm67mGgbyo1P7adckvg'
const NOMNI_ICON='https://coindaddy.io/content/images/icons/xcp/NOMNI.png'
type View='home'|'assets'|'send'|'trade'|'market'|'activity'|'settings'
function rows(v:any){return Array.isArray(v)?v:(v?.result??[])}
function short(v:string){return v?.length>18?`${v.slice(0,8)}…${v.slice(-8)}`:v||'—'}
function units(v:any,divisible=true){const n=Number(v??0);if(!Number.isFinite(n))return'—';const value=divisible&&Math.abs(n)>100000000?n/100000000:n;return value.toLocaleString(undefined,{maximumFractionDigits:8})}
function rawAmount(v:any,divisible=true){const n=Number(v??0);if(!Number.isFinite(n))return 0;return divisible&&Math.abs(n)>100000000?n/100000000:n}
function nomniAmount(v:any){return`∞${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:8})}`}
function usd(v:number){return v>0?`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:v<1?8:2})}`:'—'}

export function NEOpayWallet(){
 const[view,setView]=useState<View>('home'),[address,setAddress]=useState(DEFAULT_ADDRESS),[signer,setSigner]=useState<SignerState>(neoPaySigner.state())
 const[balances,setBalances]=useState<any[]>([]),[btc,setBtc]=useState(0),[asset,setAsset]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[matches,setMatches]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[dispensers,setDispensers]=useState<any[]>([])
 const[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[online,setOnline]=useState(false),[lastUpdated,setLastUpdated]=useState('—')
 const[to,setTo]=useState(''),[sendAsset,setSendAsset]=useState('NOMNI'),[sendAmount,setSendAmount]=useState(''),[sendStatus,setSendStatus]=useState('')
 const[side,setSide]=useState<'BUY'|'SELL'>('BUY'),[tradeAmount,setTradeAmount]=useState(''),[tradePrice,setTradePrice]=useState(''),[tradeStatus,setTradeStatus]=useState('')
 const[assetQuery,setAssetQuery]=useState('NOMNI'),[assetResult,setAssetResult]=useState<any>(null)
 const[rates,setRates]=useState<MarketRates>({btcUsd:0,xcpUsd:0,nomniXcp:0,nomniUsd:0,nomniBtc:0,updatedAt:''})
 const[cesProfile,setCesProfile]=useState<CesProfile>(()=>loadCesProfile(DEFAULT_ADDRESS)),[ces,setCes]=useState<CesTraderData>({transactions:[],online:false})

 const refresh=async()=>{
  if(!isLikelyBitcoinAddress(address)){setNotice('Enter a valid Bitcoin address.');return}
  setLoading(true);setNotice('')
  const result=await Promise.allSettled([getAddressBalances(address),getAddressTransactions(address),getAsset('NOMNI'),getOrders(),getOrderMatches(),getDispensers('NOMNI'),getBitcoinAddressSummary(address),getApiHealth()])
  const[b,t,a,o,m,d,bs,h]=result
  if(b.status==='fulfilled')setBalances(rows(b.value));if(t.status==='fulfilled')setTransactions(rows(t.value));if(a.status==='fulfilled')setAsset(a.value?.result??a.value);if(o.status==='fulfilled')setOrders(rows(o.value));if(m.status==='fulfilled')setMatches(rows(m.value));if(d.status==='fulfilled')setDispensers(rows(d.value));if(bs.status==='fulfilled')setBtc(satsToBtc(bs.value.total));setOnline(h.status==='fulfilled')
  const failed=result.filter(x=>x.status==='rejected').length;if(failed)setNotice(`${failed} data source${failed===1?'':'s'} could not be reached. Available balances and market data are still shown.`)
  setLastUpdated(new Date().toLocaleTimeString());setLoading(false)
 }
 useEffect(()=>{void refresh();if(neoPaySigner.state().available)void connect(true)},[])
 useEffect(()=>{setCesProfile(p=>({...p,walletAddress:address}))},[address])

 const balanceMap=useMemo(()=>new Map(balances.map(b=>[String(b.asset).toUpperCase(),b])),[balances])
 const nomni=balanceMap.get('NOMNI'),xcp=balanceMap.get('XCP')
 const nomniQty=rawAmount(nomni?.quantity,asset?.divisible!==false),xcpQty=rawAmount(xcp?.quantity)
 const book=useMemo(()=>orders.map(o=>{const ga=String(o.give_asset||'').toUpperCase(),ra=String(o.get_asset||'').toUpperCase(),g=Number(o.give_remaining??o.give_quantity??0),r=Number(o.get_remaining??o.get_quantity??0);if(ga==='NOMNI'&&ra==='XCP')return{...o,kind:'ASK',price:g?r/g:0,amount:g};if(ga==='XCP'&&ra==='NOMNI')return{...o,kind:'BID',price:r?g/r:0,amount:r};return null}).filter(Boolean) as any[],[orders])
 const asks=book.filter(x=>x.kind==='ASK').sort((a,b)=>a.price-b.price),bids=book.filter(x=>x.kind==='BID').sort((a,b)=>b.price-a.price),bestAsk=asks[0]?.price,bestBid=bids[0]?.price
 const nomniXcp=bestBid&&bestAsk?(bestBid+bestAsk)/2:(bestBid||bestAsk||0)
 useEffect(()=>{void getMarketRates(nomniXcp).then(setRates).catch(()=>{})},[nomniXcp])
 useEffect(()=>{void getCesTraderData(cesProfile).then(setCes).catch(e=>setCes({transactions:[],online:false,message:e.message}))},[cesProfile.accountNumber,cesProfile.walletAddress])
 const portfolioUsd=btc*rates.btcUsd+xcpQty*rates.xcpUsd+nomniQty*rates.nomniUsd
 const portfolioNomni=rates.nomniUsd?portfolioUsd/rates.nomniUsd:nomniQty

 const connect=async(silent=false)=>{try{const s=await neoPaySigner.connect();setSigner(s);if(s.address){setAddress(s.address);setTimeout(()=>void refresh(),0)}}catch(e:any){if(!silent)setNotice(e.message)} }
 const approveAndBroadcast=async(composed:any,summary:Record<string,string|number|boolean|undefined>,setStatus:(s:string)=>void)=>{const unsigned=extractUnsignedTxHex(composed);if(!signer.connected)throw new Error('Connect a compatible wallet before approving a transaction.');setStatus('Waiting for approval…');const signed=await neoPaySigner.sign({unsignedTxHex:unsigned,summary});setStatus('Sending to Bitcoin…');const txid=await broadcastBitcoinTransaction(signed);setStatus(`Submitted ${short(txid)}`);await refresh();return txid}
 const sendNow=async()=>{try{setSendStatus('');const amount=Number(sendAmount);if(!isLikelyBitcoinAddress(to))throw new Error('Enter a valid destination address.');if(!Number.isFinite(amount)||amount<=0)throw new Error('Enter an amount greater than zero.');const upper=sendAsset.trim().toUpperCase();const meta=upper==='NOMNI'?asset:await getAsset(upper).then((v:any)=>v?.result??v);const divisible=meta?.divisible!==false;if(!divisible&&!Number.isInteger(amount))throw new Error(`${upper} uses whole units.`);const quantity=divisible?Math.round(amount*1e8):Math.round(amount);setSendStatus('Preparing transaction…');const composed=await composeSend({source:address,destination:to,asset:upper,quantity});await approveAndBroadcast(composed,{action:'send',asset:upper,amount,destination:to,source:address},setSendStatus);setSendAmount('')}catch(e:any){setSendStatus(e.message||'Unable to prepare transaction.')}}
 const tradeNow=async()=>{try{setTradeStatus('');const amount=Number(tradeAmount),price=Number(tradePrice);if(!Number.isFinite(amount)||amount<=0||!Number.isFinite(price)||price<=0)throw new Error('Enter a valid amount and price.');const nomniUnits=asset?.divisible===false?Math.round(amount):Math.round(amount*1e8),xcpUnits=Math.round(amount*price*1e8);const params=side==='BUY'?{source:address,give_asset:'XCP' as const,give_quantity:xcpUnits,get_asset:'NOMNI' as const,get_quantity:nomniUnits}:{source:address,give_asset:'NOMNI' as const,give_quantity:nomniUnits,get_asset:'XCP' as const,get_quantity:xcpUnits};setTradeStatus('Preparing order…');const composed=await composeOrder(params);await approveAndBroadcast(composed,{action:'order',market:'NOMNI/XCP',side,amount,price,source:address},setTradeStatus)}catch(e:any){setTradeStatus(e.message||'Unable to prepare order.')}}
 const lookup=async()=>{try{const value=assetQuery.trim().toUpperCase();setAssetResult(await getAsset(value).then((v:any)=>v?.result??v))}catch(e:any){setAssetResult({error:e.message})}}
 const saveCes=()=>{const p={accountNumber:cesProfile.accountNumber.trim(),walletAddress:address};saveCesProfile(p);setCesProfile(p);setNotice('CES account settings saved on this device.')}
 const nav:[View,string,any][]=[['home','Home',WalletCards],['assets','Assets',Search],['send','Send',Send],['trade','Trade',BarChart3],['market','Market',Store],['activity','Activity',RefreshCw],['settings','More',Landmark]]

 return <div className="neo-wallet">
  <header className="wallet-top"><div className="wallet-wordmark"><div className="wallet-mark">∞</div><div><strong>NEOpay</strong><span>NOMNI · Bitcoin · Counterparty</span></div></div><button className="icon-btn" onClick={()=>void refresh()} aria-label="Refresh"><RefreshCw size={18} className={loading?'spin':''}/></button></header>
  <main className="wallet-main">
   {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
   {view==='home'&&<><section className="balance-hero treasury-hero"><div className="balance-head"><span>NEO Treasury & Owner Wallet</span><span className={online?'live':'muted'}>{online?'● Live':'○ Updating'}</span></div><strong>{nomniAmount(portfolioNomni)}</strong><small>{usd(portfolioUsd)} estimated portfolio · {address}</small><div className="treasury-status"><span>✓ Treasury address loaded</span><span>{signer.connected?`✓ Signer connected: ${signer.name}`:'Signer approval required to transact'}</span></div><div className="hero-actions"><button onClick={()=>setView('send')}><ArrowUpRight size={18}/>Send</button><button onClick={()=>navigator.clipboard?.writeText(address)}><ArrowDownLeft size={18}/>Receive</button><button onClick={()=>setView('trade')}><BarChart3 size={18}/>Trade</button></div></section><section className="rate-grid"><Metric label="NOMNI / USD" value={rates.nomniUsd?`∞1 = ${usd(rates.nomniUsd)}`:'—'}/><Metric label="XCP / USD" value={usd(rates.xcpUsd)}/><Metric label="BTC / USD" value={usd(rates.btcUsd)}/><Metric label="NOMNI / BTC" value={rates.nomniBtc?`∞1 = ${rates.nomniBtc.toFixed(8)} BTC`:'—'}/><Metric label="NOMNI / XCP" value={rates.nomniXcp?`∞1 = ${rates.nomniXcp.toFixed(8)} XCP`:'—'}/></section><section className="asset-list"><AssetRow symbol="NOMNI" name="NEO denominated currency" amount={nomniAmount(nomniQty)} image={NOMNI_ICON}/><AssetRow symbol="BTC" name="Bitcoin" amount={`${btc.toFixed(8)} BTC · ${usd(btc*rates.btcUsd)}`} icon="₿"/><AssetRow symbol="XCP" name="Counterparty" amount={`${units(xcp?.quantity)} XCP · ${usd(xcpQty*rates.xcpUsd)}`} icon="X"/>{balances.filter(b=>!['XCP','NOMNI'].includes(String(b.asset).toUpperCase())).slice(0,6).map((b,i)=><AssetRow key={`${b.asset}-${i}`} symbol={b.asset} name="Counterparty Asset" amount={units(b.quantity,b.divisible!==false)} icon={String(b.asset).slice(0,1)}/>)}</section><section className="card ces-card"><h2>CES Trader Account</h2><div className="list-row"><div><strong>CES Account</strong><span>{cesProfile.accountNumber||'Not entered'}</span></div><b>{ces.online?'Live':'Linked locally'}</b></div><div className="list-row"><div><strong>Wallet</strong><span>{short(address)}</span></div><b>{ces.balance!==undefined?`${ces.balance.toLocaleString()} ${ces.currency||'CES'}`:'—'}</b></div><div className="list-row"><div><strong>CES history</strong><span>{ces.message||`${ces.transactions.length} trader transactions`}</span></div><button className="text-link" onClick={()=>setView('settings')}>Manage</button></div></section></>}
   {view==='assets'&&<section className="card"><h2>Asset Explorer</h2><div className="form-row"><input value={assetQuery} onChange={e=>setAssetQuery(e.target.value)} placeholder="Ticker or asset name"/><button onClick={()=>void lookup()}>Search</button></div>{assetResult&&<div className="asset-detail">{assetResult.error?<p>{assetResult.error}</p>:<><h3>{assetResult.asset||assetQuery.toUpperCase()}</h3><dl><div><dt>Issuer</dt><dd>{short(assetResult.issuer)}</dd></div><div><dt>Supply</dt><dd>{String(assetResult.asset||assetQuery).toUpperCase()==='NOMNI'?nomniAmount(rawAmount(assetResult.supply??assetResult.quantity,assetResult.divisible!==false)):units(assetResult.supply??assetResult.quantity,assetResult.divisible!==false)}</dd></div><div><dt>Divisible</dt><dd>{String(assetResult.divisible??'—')}</dd></div><div><dt>Locked</dt><dd>{String(assetResult.locked??'—')}</dd></div></dl></>}</div>}</section>}
   {view==='send'&&<section className="card"><h2>Send Assets</h2><label>Asset<input value={sendAsset} onChange={e=>setSendAsset(e.target.value.toUpperCase())} placeholder="XCP, NOMNI, …"/></label><label>Destination<input value={to} onChange={e=>setTo(e.target.value.trim())} placeholder="Bitcoin address"/></label><label>Amount<input value={sendAmount} onChange={e=>setSendAmount(e.target.value)} inputMode="decimal" placeholder={sendAsset==='NOMNI'?'∞0.00':'0.00'}/></label><button className="primary" onClick={()=>void sendNow()}>Review & Approve</button>{sendStatus&&<p className="status-line">{sendStatus}</p>}<p className="fine">Approval happens in your connected wallet. NEOpay never publishes or stores your private key in GitHub Pages.</p></section>}
   {view==='trade'&&<><section className="market-strip"><Metric label="Best bid" value={bestBid?`∞1 = ${bestBid.toFixed(8)} XCP`:'—'}/><Metric label="Best ask" value={bestAsk?`∞1 = ${bestAsk.toFixed(8)} XCP`:'—'}/><Metric label="Trades" value={String(matches.length)}/></section><section className="card"><h2>NOMNI / XCP</h2><div className="segmented"><button className={side==='BUY'?'active':''} onClick={()=>setSide('BUY')}>Buy</button><button className={side==='SELL'?'active':''} onClick={()=>setSide('SELL')}>Sell</button></div><label>NOMNI amount<input value={tradeAmount} onChange={e=>setTradeAmount(e.target.value)} inputMode="decimal" placeholder="∞0"/></label><label>Price in XCP<input value={tradePrice} onChange={e=>setTradePrice(e.target.value)} inputMode="decimal" placeholder={side==='BUY'&&bestBid?String(bestBid):bestAsk?String(bestAsk):'0.00000000'}/></label><button className="primary" onClick={()=>void tradeNow()}>Review Order</button>{tradeStatus&&<p className="status-line">{tradeStatus}</p>}</section></>}
   {view==='market'&&<><section className="card"><h2>Order Book</h2><div className="book"><div><b>Buy</b>{bids.slice(0,8).map((x,i)=><span key={i}>{nomniAmount(x.amount)} <em>{x.price.toFixed(8)} XCP</em></span>)}</div><div><b>Sell</b>{asks.slice(0,8).map((x,i)=><span key={i}>{nomniAmount(x.amount)} <em>{x.price.toFixed(8)} XCP</em></span>)}</div></div></section><section className="card"><h2>Dispensers</h2>{dispensers.length?dispensers.slice(0,12).map((d,i)=><div className="list-row" key={i}><div><strong>{d.asset||'NOMNI'}</strong><span>{short(d.source)}</span></div><div><b>{String(d.asset||'NOMNI').toUpperCase()==='NOMNI'?nomniAmount(rawAmount(d.give_quantity,d.asset_info?.divisible!==false)):units(d.give_quantity,d.asset_info?.divisible!==false)}</b><span>{units(d.satoshirate)} sats</span></div></div>):<p className="fine">No active NOMNI dispenser data returned.</p>}</section></>}
   {view==='activity'&&<><section className="card"><h2>Wallet Activity</h2>{transactions.length?transactions.slice(0,30).map((t,i)=><div className="list-row" key={i}><div><strong>{t.tx_type||t.type||'Transaction'}</strong><span>{short(t.tx_hash||t.txid||'')}</span></div><div><b>{t.asset||''}</b><span>{t.status||t.block_index||''}</span></div></div>):<p className="fine">No wallet activity returned for this address.</p>}</section><section className="card"><h2>CES Trader History</h2>{ces.transactions.length?ces.transactions.slice(0,30).map((t:any,i)=><div className="list-row" key={i}><div><strong>{t.type||t.description||'CES transaction'}</strong><span>{t.date||t.timestamp||''}</span></div><b>{t.amount??''} {t.currency||ces.currency||''}</b></div>):<p className="fine">{ces.message||'No CES trader history returned.'}</p>}</section></>}
   {view==='settings'&&<><section className="card"><h2>Treasury Wallet</h2><label>Wallet Address<input value={address} onChange={e=>setAddress(e.target.value.trim())}/></label><button className="primary" onClick={()=>void refresh()}>Load Address</button><button className="secondary" onClick={()=>void connect()}>{signer.connected?`Connected: ${signer.name}`:'Connect Local Signer'}</button><div className="security-note"><ShieldCheck size={20}/><div><b>User-controlled signing</b><span>The treasury address loads automatically. Transaction authority is activated only through your local signer; private keys are never committed to the site.</span></div></div></section><section className="card"><h2>CES Account</h2><label>CES Account Number<input value={cesProfile.accountNumber} onChange={e=>setCesProfile({...cesProfile,accountNumber:e.target.value})} placeholder="Enter your CES account number"/></label><label>Linked Wallet<input value={address} readOnly/></label><button className="primary" onClick={saveCes}>Save CES Link</button><p className="fine">Every account holder can link their CES account number to their Bitcoin/Counterparty wallet for exchange identity. Live CES balances and history require an authorized CES API connection.</p></section><section className="card"><h2>Network</h2><div className="list-row"><div><strong>Counterparty</strong><span>Core API v2</span></div><b>{online?'Online':'Unavailable'}</b></div><div className="list-row"><div><strong>Bitcoin</strong><span>Esplora-compatible API</span></div><b>{btc>=0?'Online':'Unavailable'}</b></div><div className="list-row"><div><strong>CES</strong><span>{cesProfile.accountNumber||'Account not linked'}</span></div><b>{ces.online?'Online':'Configured locally'}</b></div><div className="list-row"><div><strong>Updated</strong></div><b>{lastUpdated}</b></div></section></>}
  </main>
  <nav className="wallet-nav">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}><Icon size={19}/><span>{label}</span></button>)}</nav>
 </div>
}
function AssetRow({symbol,name,amount,icon,image}:{symbol:string;name:string;amount:string;icon?:string;image?:string}){return <button className="asset-row"><div className="asset-icon">{image?<img src={image} alt=""/>:icon}</div><div><strong>{symbol}</strong><span>{name}</span></div><b>{amount}</b></button>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
