import type{NativeBitcoinPlan}from'./nativeBitcoin'
import type{NativeBitcoinPsbt}from'./psbtEngine'

function bytes(hex:string){if(!/^[0-9a-f]*$/i.test(hex)||hex.length%2)throw new Error('PSBT hex is malformed.');const a:number[]=[];for(let i=0;i<hex.length;i+=2)a.push(parseInt(hex.slice(i,i+2),16));return a}
function vi(b:number[],o:number){const x=b[o];if(x<0xfd)return{x,n:o+1};if(x===0xfd)return{x:b[o+1]|b[o+2]<<8,n:o+3};if(x===0xfe)return{x:(b[o+1]|b[o+2]<<8|b[o+3]<<16|b[o+4]<<24)>>>0,n:o+5};throw new Error('Unsupported PSBT varint.')}
function map(b:number[],o:number){const entries:{key:number[];value:number[]}[]=[];for(;;){const k=vi(b,o);o=k.n;if(k.x===0)return{entries,next:o};const key=b.slice(o,o+k.x);o+=k.x;const v=vi(b,o);o=v.n;const value=b.slice(o,o+v.x);o+=v.x;if(key.length!==k.x||value.length!==v.x)throw new Error('Truncated PSBT map.');entries.push({key,value})}}
function txCounts(hex:string){const b=bytes(hex);let o=4;const ic=vi(b,o);o=ic.n;for(let i=0;i<ic.x;i++){o+=36;const s=vi(b,o);o=s.n+s.x+4}const oc=vi(b,o);return{inputs:ic.x,outputs:oc.x}}
export type PsbtValidation={valid:true;inputs:number;outputs:number;feeSats:number;feeRate:number;addressType:string}
export function validateNativeBitcoinPsbt(psbt:NativeBitcoinPsbt,plan:NativeBitcoinPlan):PsbtValidation{
 const b=bytes(psbt.psbtHex);if(b.slice(0,5).join(',')!=='112,115,98,116,255')throw new Error('Invalid PSBT magic bytes.');let o=5;const g=map(b,o);o=g.next;const unsigned=g.entries.find(e=>e.key.length===1&&e.key[0]===0);if(!unsigned)throw new Error('PSBT is missing the unsigned transaction.');const unsignedHex=unsigned.value.map(x=>x.toString(16).padStart(2,'0')).join('');if(unsignedHex!==plan.unsignedTxHex)throw new Error('PSBT unsigned transaction does not match the reviewed Bitcoin plan.');const counts=txCounts(unsignedHex);if(counts.inputs!==plan.selectedUtxos)throw new Error('PSBT input count does not match the reviewed plan.');for(let i=0;i<counts.inputs;i++){const m=map(b,o);o=m.next;if(!m.entries.some(e=>e.key.length===1&&e.key[0]===1))throw new Error(`PSBT input ${i} is missing witness_utxo.`)}for(let i=0;i<counts.outputs;i++){const m=map(b,o);o=m.next}if(o!==b.length)throw new Error('PSBT contains trailing unreviewed data.');if(counts.outputs!==(plan.changeSats>=546?2:1))throw new Error('PSBT output count does not match destination/change plan.');if(plan.inputSats-plan.amountSats-plan.changeSats!==plan.feeSats)throw new Error('Bitcoin plan fee arithmetic failed validation.');if(plan.feeSats<=0||plan.feeRate<=0)throw new Error('Bitcoin plan contains an invalid fee.');return{valid:true,inputs:counts.inputs,outputs:counts.outputs,feeSats:plan.feeSats,feeRate:plan.feeRate,addressType:psbt.addressType}
}
