import{appendAudit}from'./securityAudit'
import{activateEmergencyLockdown,lockdownState}from'./emergencyLockdown'
const KEY='neopay.recovery.hardening.v1',DEVICE='neopay.trusted.device.v1'
export type RecoveryHardening={recoveryDelayMinutes:number;trustedDevice:boolean;lastRotatedAt?:string;compromiseMode:boolean}
const DEFAULTS:RecoveryHardening={recoveryDelayMinutes:5,trustedDevice:false,compromiseMode:false}
export function loadRecoveryHardening():RecoveryHardening{try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...DEFAULTS}}}
export function saveRecoveryHardening(v:RecoveryHardening){const next={...v,recoveryDelayMinutes:Math.max(0,Math.min(1440,Math.round(Number(v.recoveryDelayMinutes)||0)))};localStorage.setItem(KEY,JSON.stringify(next));appendAudit('policy_change',`Recovery hardening updated: delay ${next.recoveryDelayMinutes} minutes; trusted device ${next.trustedDevice?'enabled':'disabled'}.`);return next}
export function rotateRecoveryMarker(){const v=loadRecoveryHardening(),next={...v,lastRotatedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(next));appendAudit('policy_change','Recovery credentials were rotated.');return next}
export function setTrustedDevice(enabled:boolean){const id=enabled?(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`):'';if(enabled)localStorage.setItem(DEVICE,id);else localStorage.removeItem(DEVICE);const next=saveRecoveryHardening({...loadRecoveryHardening(),trustedDevice:enabled});return{settings:next,deviceId:enabled?id:undefined}}
export function recoveryAvailableAt(){const state=lockdownState(),settings=loadRecoveryHardening();if(!state.active||!state.activatedAt)return Date.now();return Date.parse(state.activatedAt)+settings.recoveryDelayMinutes*60_000}
export function recoveryDelayRemaining(){return Math.max(0,recoveryAvailableAt()-Date.now())}
export function requireRecoveryDelay(){const left=recoveryDelayRemaining();if(left>0)throw new Error(`Recovery delay is still active for ${Math.ceil(left/60000)} minute(s).`)}
export function activateCompromiseMode(){const state=activateEmergencyLockdown('Compromise suspected mode activated.');for(const key of['neopay.contacts.v1','neopay.wallet.preferred.v1','neopay.wallet.diagnostics.v1','neopay.wallet.readiness.v1','neopay.security.preferences.v1'])try{localStorage.removeItem(key)}catch{}const next={...loadRecoveryHardening(),compromiseMode:true,trustedDevice:false};localStorage.removeItem(DEVICE);localStorage.setItem(KEY,JSON.stringify(next));appendAudit('wallet_lock','Compromise suspected mode cleared local contacts, wallet preferences, diagnostics, readiness attestations and trusted-device marker. Blockchain funds were not altered.');return state}
export function clearCompromiseFlag(){const next={...loadRecoveryHardening(),compromiseMode:false};localStorage.setItem(KEY,JSON.stringify(next));appendAudit('wallet_unlock','Compromise mode flag cleared after recovery.');return next}
