import{appendAudit}from'./securityAudit'
import{revokeWalletReadiness,type WalletRail}from'./walletSession'
const KEY='neopay.wallet.session-continuity.v1'
export type WalletIdentity={rail:WalletRail;address:string;provider:string}
export type ContinuityState={identity:WalletIdentity;establishedAt:string;lastVerifiedAt:string}
function norm(v:string){return String(v||'').trim().toLowerCase()}
export function sessionContinuity():ContinuityState|null{try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v?.identity?.rail&&v?.identity?.address?v:null}catch{return null}}
export function establishSessionContinuity(identity:WalletIdentity){const now=new Date().toISOString(),state:ContinuityState={identity:{...identity,address:identity.address.trim()},establishedAt:now,lastVerifiedAt:now};localStorage.setItem(KEY,JSON.stringify(state));appendAudit('wallet_unlock',`Wallet session continuity established for ${identity.rail} provider ${identity.provider}.`);return state}
export function verifySessionContinuity(identity:WalletIdentity){const saved=sessionContinuity();if(!saved)return{ok:false,reason:'No trusted wallet session is established. Run the wallet compatibility test again.'};const railChanged=saved.identity.rail!==identity.rail,addressChanged=norm(saved.identity.address)!==norm(identity.address),providerChanged=norm(saved.identity.provider)!==norm(identity.provider);if(railChanged||addressChanged||providerChanged){for(const rail of['raw','unisat','xverse'] as WalletRail[])revokeWalletReadiness(rail,'Wallet identity changed during an active session.');const changes=[railChanged?'wallet rail':null,addressChanged?'source address/account':null,providerChanged?'provider':null].filter(Boolean).join(', ');localStorage.removeItem(KEY);appendAudit('transaction_blocked',`Wallet session continuity failed because ${changes} changed. Send authorization was revoked.`);return{ok:false,reason:`Wallet session changed (${changes}). Send authorization was revoked. Reconnect and run the compatibility test again.`}}const next={...saved,lastVerifiedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(next));return{ok:true,state:next}}
export function clearSessionContinuity(reason='Wallet session ended.'){localStorage.removeItem(KEY);appendAudit('wallet_lock',reason)}
