import{contactByAddress}from'./contactIntelligence'
import{listReceipts}from'./receiptCenter'
import{assessTransactionAnomaly,type RiskLevel}from'./anomalyDetection'
const KEY='neopay.transaction.policy.v1'
export type TransactionPolicy={perTransactionBtc:number;dailyBtc:number;highFeeSats:number;largePaymentBtc:number;newRecipientWarning:boolean}
export type PolicyAssessment={allowed:boolean;requiresStrongApproval:boolean;warnings:string[];dailySpentBtc:number;remainingDailyBtc:number;riskScore:number;riskLevel:RiskLevel}
const DEFAULTS:TransactionPolicy={perTransactionBtc:0.25,dailyBtc:0.5,highFeeSats:50000,largePaymentBtc:0.1,newRecipientWarning:true}
export function loadTransactionPolicy():TransactionPolicy{try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...DEFAULTS}}}
export function saveTransactionPolicy(p:TransactionPolicy){const clean={perTransactionBtc:Math.max(0,Number(p.perTransactionBtc)||0),dailyBtc:Math.max(0,Number(p.dailyBtc)||0),highFeeSats:Math.max(0,Math.round(Number(p.highFeeSats)||0)),largePaymentBtc:Math.max(0,Number(p.largePaymentBtc)||0),newRecipientWarning:Boolean(p.newRecipientWarning)};localStorage.setItem(KEY,JSON.stringify(clean));return clean}
function todayStart(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()}
export function dailyBitcoinSpent(){return listReceipts().filter(r=>new Date(r.submittedAt).getTime()>=todayStart()&&r.state!=='failed'&&String(r.review.asset).toUpperCase()==='BTC').reduce((n,r)=>n+Number(r.review.amount||0),0)}
export function assessBitcoinPolicy(amountBtc:number,feeSats:number,destination:string):PolicyAssessment{const p=loadTransactionPolicy(),warnings:string[]=[],spent=dailyBitcoinSpent(),next=spent+amountBtc,anomaly=assessTransactionAnomaly({amountBtc,feeSats,destination});let allowed=!anomaly.block,strong=anomaly.requiresElevatedApproval;if(p.perTransactionBtc>0&&amountBtc>p.perTransactionBtc){allowed=false;warnings.push(`Payment exceeds your ${p.perTransactionBtc} BTC per-transaction limit.`)}if(p.dailyBtc>0&&next>p.dailyBtc){allowed=false;warnings.push(`Payment would exceed your ${p.dailyBtc} BTC daily limit.`)}if(p.highFeeSats>0&&feeSats>p.highFeeSats){strong=true;warnings.push(`Network fee ${feeSats.toLocaleString()} sats exceeds your high-fee threshold.`)}if(p.largePaymentBtc>0&&amountBtc>=p.largePaymentBtc){strong=true;warnings.push('Large-payment approval required by your local policy.')}if(p.newRecipientWarning&&!contactByAddress(destination)){strong=true;warnings.push('Recipient is not saved in your NEOpay contacts. Verify the address carefully.')}if(anomaly.level!=='low')warnings.push(`Anomaly risk ${anomaly.level.toUpperCase()} (${anomaly.score}/100): ${anomaly.reasons.join(' ')}`);if(anomaly.block)warnings.push('Transaction blocked because local anomaly score reached the critical threshold.');return{allowed,requiresStrongApproval:strong,warnings,dailySpentBtc:spent,remainingDailyBtc:p.dailyBtc>0?Math.max(0,p.dailyBtc-spent):Infinity,riskScore:anomaly.score,riskLevel:anomaly.level}}
