import type{NativeBitcoinPlan}from'./nativeBitcoin'
import type{WalletRail}from'./walletSession'
const TTL_MS=2*60*1000
export type TransactionIntent={version:1;source:string;destination:string;amountBtc:number;feeSats:number;feeRate:number;changeSats:number;unsignedTxHex:string;rail:WalletRail;createdAt:string;expiresAt:string;digest:string}
function canonical(v:Omit<TransactionIntent,'digest'>){return JSON.stringify({version:v.version,source:v.source.trim().toLowerCase(),destination:v.destination.trim().toLowerCase(),amountBtc:Number(v.amountBtc.toFixed(8)),feeSats:Math.round(v.feeSats),feeRate:Number(v.feeRate),changeSats:Math.round(v.changeSats),unsignedTxHex:v.unsignedTxHex.toLowerCase(),rail:v.rail,createdAt:v.createdAt,expiresAt:v.expiresAt})}
async function sha256(text:string){const bytes=new TextEncoder().encode(text),hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function sealTransactionIntent(plan:NativeBitcoinPlan,rail:WalletRail){const now=Date.now(),base:Omit<TransactionIntent,'digest'>={version:1,source:plan.source,destination:plan.destination,amountBtc:plan.amountBtc,feeSats:plan.feeSats,feeRate:plan.feeRate,changeSats:plan.changeSats,unsignedTxHex:plan.unsignedTxHex,rail,createdAt:new Date(now).toISOString(),expiresAt:new Date(now+TTL_MS).toISOString()};return{...base,digest:await sha256(canonical(base))}}
export async function verifyTransactionIntent(intent:TransactionIntent,plan:NativeBitcoinPlan,rail:WalletRail){if(Date.parse(intent.expiresAt)<=Date.now())return{ok:false,reason:'Transaction review authorization expired. Rebuild and review the payment again.'};const current={version:1 as const,source:plan.source,destination:plan.destination,amountBtc:plan.amountBtc,feeSats:plan.feeSats,feeRate:plan.feeRate,changeSats:plan.changeSats,unsignedTxHex:plan.unsignedTxHex,rail,createdAt:intent.createdAt,expiresAt:intent.expiresAt},digest=await sha256(canonical(current));if(digest!==intent.digest)return{ok:false,reason:'Transaction intent changed after review. Destination, amount, fee, source, transaction bytes, or signing rail no longer match the approved payment.'};return{ok:true,digest}}
export function shortIntentDigest(intent:TransactionIntent){return`${intent.digest.slice(0,8)}…${intent.digest.slice(-8)}`}
