import{useEffect,useState}from'react'
import{Cable,CheckCircle2,RefreshCw,ShieldAlert,X}from'lucide-react'
import{neoPaySigner,type SignerState}from'./signer'
import{discoverWalletProviders,type WalletProviderRecord}from'./walletProviderRegistry'
import'./walletConnections.css'

function cap(v?:boolean){return v?'Supported':'Not declared'}
export function WalletConnectionCenter(){
 const[open,setOpen]=useState(false),[state,setState]=useState<SignerState>(()=>neoPaySigner.state()),[providers,setProviders]=useState<WalletProviderRecord[]>(()=>discoverWalletProviders()),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const refresh=()=>{setState(neoPaySigner.state());setProviders(discoverWalletProviders())}
 useEffect(()=>{const id=window.setInterval(refresh,1500);return()=>window.clearInterval(id)},[])
 const connect=async()=>{setBusy(true);setMessage('');try{setState(await neoPaySigner.connect());setMessage('Wallet connected and capability check passed.')}catch(e:any){setMessage(e?.message||'Unable to connect wallet.')}finally{setBusy(false);setProviders(discoverWalletProviders())}}
 const disconnect=async()=>{setBusy(true);try{await neoPaySigner.disconnect();refresh();setMessage('Wallet disconnected.')}finally{setBusy(false)}}
 const c=state.capabilities
 return <><button className="neopay-wallet-launch" onClick={()=>{refresh();setOpen(true)}}><Cable size={16}/>Wallet</button>{open&&<div className="wallet-connect-backdrop" role="dialog" aria-modal="true" aria-label="NEOpay Wallet Connection Center"><div className="wallet-connect-sheet"><button className="wallet-connect-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="wallet-connect-head"><Cable size={24}/><div><h2>Wallet Connection Center</h2><span>Detect · verify · connect</span></div></div><div className="wallet-health"><div><span>Active provider</span><strong>{state.name}</strong></div><div><span>Status</span><strong>{state.connected?'Connected':state.available?'Detected':'Not connected'}</strong></div><div><span>Network</span><strong>{state.network||'—'}</strong></div><div><span>Address type</span><strong>{state.addressType||'—'}</strong></div></div>{state.address&&<div className="wallet-address"><CheckCircle2 size={16}/><span>{state.address}</span></div>}<section className="wallet-capabilities"><h3>Active Signer Capabilities</h3><div><span>Raw transaction signing</span><b>{cap(c?.rawTransaction)}</b></div><div><span>PSBT signing</span><b>{cap(c?.psbt)}</b></div><div><span>Legacy</span><b>{cap(c?.legacy)}</b></div><div><span>SegWit</span><b>{cap(c?.segwit)}</b></div><div><span>Taproot</span><b>{cap(c?.taproot)}</b></div></section><section className="wallet-capabilities"><h3>Detected Wallet Providers</h3>{providers.map(p=><div key={p.id} style={{display:'block'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><span>{p.name}</span><b>{p.detected?(p.compatible?'Ready':p.mode==='psbt'?'PSBT detected':'Detected'):'Not detected'}</b></div><small style={{display:'block',opacity:.72,marginTop:4}}>{p.note}</small></div>)}</section>{!state.available&&<div className="wallet-warning"><ShieldAlert size={18}/><span>No raw-transaction-compatible NEOpay signer is active. PSBT-capable wallets such as UniSat can be detected, but NEOpay will not misuse them until the PSBT construction path is implemented.</span></div>}<div className="wallet-connect-actions"><button onClick={refresh}><RefreshCw size={15}/>Rescan</button>{state.connected?<button className="danger" disabled={busy} onClick={()=>void disconnect()}>Disconnect</button>:<button className="primary" disabled={!state.available||busy} onClick={()=>void connect()}>{busy?'Connecting…':'Connect Compatible Wallet'}</button>}</div>{message&&<p className="wallet-connect-msg">{message}</p>}<p className="wallet-connect-fine">Provider discovery is read-only until you choose Connect. NEOpay never requests a seed phrase or private key.</p></div></div>}</>
}
