import {useState} from 'react'
import {Activity,Brain,CheckCircle2,ClipboardCheck,ShieldCheck,Sparkles,UserRound} from 'lucide-react'
import './neotherapy.css'
const pillars=['Nous','Perception','Cognition','Resonance','Illumination','Integration','Transformation']
const steps=['Orientation','Observation','Noological Dialogue','Cognitive Alignment','Nous Field Practice','Reflection','Integration']
const labels=['FACT','PERCEPTION','HYPOTHESIS','UNKNOWN'] as const
export function NeotherapyApp(){
 const[view,setView]=useState<'practitioner'|'participant'>('practitioner');const[step,setStep]=useState(0);const[consent,setConsent]=useState(false);const[safety,setSafety]=useState(false);const[classification,setClassification]=useState<typeof labels[number]>('UNKNOWN');const canPractice=consent&&safety
 return <div className="nt-shell"><aside className="nt-side"><div className="nt-brand"><div className="nt-mark">N</div><div><b>NEOTHERAPY™</b><span>NOUS FIELD THERAPY</span></div></div><nav><button className={view==='practitioner'?'active':''} onClick={()=>setView('practitioner')}><ClipboardCheck size={17}/>Neotherapist Console</button><button className={view==='participant'?'active':''} onClick={()=>setView('participant')}><UserRound size={17}/>Participant Portal</button></nav><div className="nt-boundary"><ShieldCheck size={18}/><span>NFM-001 is an experimental Noological sensory practice. No clinical efficacy is asserted.</span></div></aside>
 <main className="nt-main"><header><div><p>NEO SYSTEM • NOOLOGY</p><h1>{view==='practitioner'?'Neotherapist Console':'Participant Portal'}</h1></div><span className="nt-status"><i/> v1.0 CORE</span></header>
 {view==='practitioner'?<><section className="nt-stats"><Card icon={<CheckCircle2/>} title="Credential" value="ACTIVE" sub="C.Neo. workspace"/><Card icon={<Sparkles/>} title="Modality" value="NFM-001" sub="True Green Light • experimental"/><Card icon={<Activity/>} title="Session" value={(step+1)+'/7'} sub={steps[step]}/><Card icon={<ShieldCheck/>} title="Guardrails" value={canPractice?'READY':'HOLD'} sub="Consent + safety required"/></section>
 <section className="nt-grid"><article className="nt-card"><h2>Session Protocol</h2><p className="muted">Canonical Neotherapy cycle</p><div className="nt-steps">{steps.map((s,i)=><button key={s} className={i===step?'current':i<step?'done':''} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</div></article><article className="nt-card"><h2>Consent & Safety</h2><p className="muted">NFM-001 cannot begin until both controls are satisfied.</p><label className="nt-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><b>Active informed consent</b><small>Voluntary participation and withdrawal rights confirmed.</small></span></label><label className="nt-check"><input type="checkbox" checked={safety} onChange={e=>setSafety(e.target.checked)}/><span><b>Safety screen complete</b><small>Protocol and stop criteria reviewed.</small></span></label><div className={'nt-gate '+(canPractice?'ready':'hold')}>{canPractice?'NFM-001 READY':'NFM-001 ON HOLD'}</div></article></section>
 <section className="nt-grid"><article className="nt-card"><h2>Noological Dialogue</h2><p className="muted">Classify propositions without forcing certainty.</p><textarea placeholder="Enter the proposition being examined…"/><div className="nt-labels">{labels.map(x=><button key={x} className={classification===x?'selected':''} onClick={()=>setClassification(x)}>{x}</button>)}</div><div className="nt-evidence"><b>Evidence state</b><span>O2 • Observation</span></div></article><article className="nt-card"><h2>Seven Pillars</h2><div className="nt-pillars">{pillars.map((p,i)=><div key={p}><span>{p}</span><progress max="100" value={35+i*7}/></div>)}</div><small className="muted">Demonstration values only; not diagnostic scores.</small></article></section></>:<>
 <section className="nt-hero"><Brain size={36}/><div><h2>Your Neotherapy Workspace</h2><p>Review consent, integration exercises, and observations through the Seven Pillars of Noology.</p></div></section><section className="nt-stats"><Card icon={<Brain/>} title="Program" value="NEO-TH 101" sub="Foundations of Neotherapy"/><Card icon={<Sparkles/>} title="Modality" value="NFM-001" sub="Experimental classification"/><Card icon={<ShieldCheck/>} title="Agency" value="VOLUNTARY" sub="Exercises may be declined"/><Card icon={<Brain/>} title="Framework" value="7 PILLARS" sub="Noological development"/></section><section className="nt-card"><h2>Participant Rights</h2><div className="nt-rights"><span>Ask questions</span><span>Request evidence</span><span>Decline an exercise</span><span>Withdraw consent</span><span>Review your records</span></div></section></>}</main></div>}
function Card({icon,title,value,sub}:{icon:React.ReactNode;title:string;value:string;sub:string}){return <article className="nt-card nt-stat"><div>{icon}<span>{title}</span></div><strong>{value}</strong><small>{sub}</small></article>}
