const $=id=>document.getElementById(id);const BTC='https://mempool.space/api';const XCP='https://api.counterparty.io:4000/v2';
function destination(raw){const v=raw.trim();if(!v)return null;try{return new URL(v).href}catch{}if(/^[\w.-]+\.[a-z]{2,}(?:\/.*)?$/i.test(v))return'https://'+v;return`../noogle/?q=${encodeURIComponent(v)}`}
function titleFor(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
function updateLibraryCounts(){const b=window.omnitrixState?.getBookmarks?.()||[],h=window.omnitrixState?.getHistory?.()||[];$('bookmarkCount').textContent=`${b.length} bookmark${b.length===1?'':'s'}`;$('historyCount').textContent=`${h.length} recent page${h.length===1?'':'s'}`}
function browse(raw){const url=destination(raw);if(!url)return;localStorage.setItem('omnitrix-last',url);window.omnitrixState?.addHistory?.({url,title:titleFor(url)});updateLibraryCounts();window.open(url,'_blank','noopener,noreferrer')}
$('barForm').addEventListener('submit',e=>{e.preventDefault();browse($('bar').value)});$('go').onclick=()=>browse($('bar').value);$('heroForm').addEventListener('submit',e=>{e.preventDefault();browse($('heroSearch').value)});document.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>browse(b.dataset.url));$('newTab').onclick=()=>window.open(location.href,'_blank','noopener');$('refresh').onclick=()=>location.reload();$('back').onclick=()=>history.back();$('forward').onclick=()=>history.forward();
async function json(url){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function hydrate(){const tasks=[json(`${BTC}/v1/prices`).then(d=>$('btcPrice').textContent=d.USD?`$${Number(d.USD).toLocaleString()}`:'Live'),json(`${BTC}/v1/fees/recommended`).then(d=>$('btcFees').textContent=`Fee ${d.halfHourFee??d.fastestFee??'—'} sat/vB`),json(`${XCP}/`).then(d=>{$('xcpHeight').textContent=`Block ${d.result?.counterparty_height??'—'}`;$('xcpState').textContent=d.result?.ledger_state||'Connected'})];const settled=await Promise.allSettled(tasks);$('networkLight').style.color=settled.some(x=>x.status==='fulfilled')?'var(--accent)':'#e87878'}hydrate();
function closePanels(){['minerDrawer','skinPanel','libraryPanel'].forEach(id=>$(id)?.classList.remove('open'))}
function openMiner(){closePanels();$('minerDrawer').classList.add('open')}$('minerBtn').onclick=openMiner;$('openMiner').onclick=openMiner;$('closeMiner').onclick=()=>$('minerDrawer').classList.remove('open');$('skinBtn').onclick=()=>{closePanels();$('skinPanel').classList.add('open')};$('closeSkin').onclick=()=>$('skinPanel').classList.remove('open');
function renderLibrary(){const panel=$('libraryList'),bookmarks=window.omnitrixState?.getBookmarks?.()||[],recent=window.omnitrixState?.getHistory?.()||[];const rows=[];rows.push('<strong>Bookmarks</strong>');if(!bookmarks.length)rows.push('<div class="libraryItem"><span>No bookmarks yet.</span></div>');bookmarks.forEach(item=>rows.push(`<div class="libraryItem"><span>${item.title}</span><div><button data-open="${item.url}">Open</button><button data-remove="${item.url}">Remove</button></div></div>`));rows.push('<strong>Recent</strong>');recent.slice(0,20).forEach(item=>rows.push(`<div class="libraryItem"><span>${item.title}</span><button data-open="${item.url}">Open</button></div>`));panel.innerHTML=rows.join('');panel.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>browse(b.dataset.open));panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{window.omnitrixState.removeBookmark(b.dataset.remove);updateLibraryCounts();renderLibrary()})}
$('libraryBtn').onclick=()=>{closePanels();renderLibrary();$('libraryPanel').classList.add('open')};$('closeLibrary').onclick=()=>$('libraryPanel').classList.remove('open');$('bookmarkBtn').onclick=()=>{const raw=$('bar').value.trim()||localStorage.getItem('omnitrix-last')||location.href;const url=destination(raw)||raw;window.omnitrixState?.addBookmark?.({url,title:titleFor(url)});updateLibraryCounts();$('bookmarkBtn').textContent='Saved';setTimeout(()=>$('bookmarkBtn').textContent='Bookmark',1200)};
function firstMiner(d){return d?.discoveredMiners?.[0]||d?.devices?.[0]||d?.payload||d||{}}
function renderTelemetry(d){const p=firstMiner(d);$('minerState').textContent=d?.agentState||d?.status||'Connected';$('minerDetail').textContent=p.worker||p.minerId||p.host||'Telemetry live';const h=p.hashrateTh??p.hashrateTH??p.hashrate??p.hashRate;$('hashrate').textContent=h===undefined?'—':typeof h==='number'?`${Number(h).toLocaleString()}${p.hashrateTh!==undefined||p.hashrateTH!==undefined?' TH/s':' H/s'}`:String(h);const t=p.temperatureC??p.temperature??p.temp;$('temp').textContent=t===undefined?'—':`${Number(t).toFixed(1)} °C`;const w=p.powerW??p.power??p.watts;$('power').textContent=w===undefined?'—':`${Number(w).toLocaleString()} W`;$('pool').textContent=p.pool||p.poolUrl||'Connected'}
let pollTimer=null;$('connectMiner').onclick=async()=>{try{let url=$('adapterUrl').value.trim();const token=$('adapterToken')?.value.trim()||'';let connection;if(!url){const found=await window.omnitrixMiner.discover();if(!found)throw new Error('No NEO Miner found. Enter your miner URL.');url=found.url;$('adapterUrl').value=url}connection=await window.omnitrixMiner.connect(url,token);if(connection.data)renderTelemetry(connection.data);if(connection.ws){connection.ws.onmessage=e=>{try{renderTelemetry(JSON.parse(e.data))}catch{}}}else if(connection.poll){clearInterval(pollTimer);pollTimer=setInterval(async()=>{try{renderTelemetry(await connection.poll())}catch{$('minerState').textContent='Reconnecting…'}},5000)}}catch(e){$('minerState').textContent='Not connected';$('minerDetail').textContent=e.message}};
const skins=$('skins');function addSkin(s){const b=document.createElement('button');b.className='skin';b.innerHTML=`<b>${s.name}</b><small>Tap to apply</small>`;b.onclick=()=>window.omnitrixThemes.applySkin(s);skins.appendChild(b)};window.omnitrixThemes.skins.forEach(addSkin);addSkin(window.omnitrixThemes.generatedSkin());$('generateSkin').onclick=()=>{const s=window.omnitrixThemes.generatedSkin();s.name='Fresh '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});s.accent=`hsl(${Math.floor(Math.random()*360)} 72% 67%)`;s.accent2=`hsl(${Math.floor(Math.random()*360)} 62% 66%)`;window.omnitrixThemes.applySkin(s);addSkin(s)};
updateLibraryCounts();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});