const $=id=>document.getElementById(id);const BTC='https://mempool.space/api';const XCP='https://api.counterparty.io:4000/v2';
function settings(){return window.omnitrixState?.getSettings?.()||{search:'noogle',matrixRain:true,restoreSession:true}}
function destination(raw){const v=raw.trim();if(!v)return null;try{return new URL(v).href}catch{}if(/^[\w.-]+\.[a-z]{2,}(?:\/.*)?$/i.test(v))return'https://'+v;const q=encodeURIComponent(v),s=settings().search;return s==='google'?`https://www.google.com/search?q=${q}`:s==='duckduckgo'?`https://duckduckgo.com/?q=${q}`:`../noogle/?q=${q}`}
function titleFor(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
function updateLibraryCounts(){const b=window.omnitrixState?.getBookmarks?.()||[],h=window.omnitrixState?.getHistory?.()||[];$('bookmarkCount').textContent=`${b.length} bookmark${b.length===1?'':'s'}`;$('historyCount').textContent=`${h.length} recent page${h.length===1?'':'s'}`;renderFavorites()}
function browse(raw){const url=destination(raw);if(!url)return;localStorage.setItem('omnitrix-last',url);window.omnitrixState?.addHistory?.({url,title:titleFor(url)});window.omnitrixState?.saveSession?.({lastUrl:url});updateLibraryCounts();window.open(url,'_blank','noopener,noreferrer')}
function renderFavorites(){const bar=$('favoritesBar');if(!bar)return;const items=window.omnitrixState?.getBookmarks?.()||[];bar.innerHTML=items.slice(0,12).map(x=>`<button data-fav="${x.url}">★ ${x.title}</button>`).join('')||'<button data-fav="../noogle/">★ Noogle</button>';bar.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>browse(b.dataset.fav))}
$('barForm').addEventListener('submit',e=>{e.preventDefault();browse($('bar').value)});$('go').onclick=()=>browse($('bar').value);$('heroForm').addEventListener('submit',e=>{e.preventDefault();browse($('heroSearch').value)});document.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>browse(b.dataset.url));$('newTab').onclick=()=>window.open(location.href,'_blank','noopener');$('refresh').onclick=()=>location.reload();$('back').onclick=()=>history.back();$('forward').onclick=()=>history.forward();
async function json(url){const r=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function hydrate(){const tasks=[json(`${BTC}/v1/prices`).then(d=>$('btcPrice').textContent=d.USD?`$${Number(d.USD).toLocaleString()}`:'Live'),json(`${BTC}/v1/fees/recommended`).then(d=>$('btcFees').textContent=`Fee ${d.halfHourFee??d.fastestFee??'—'} sat/vB`),json(`${XCP}/`).then(d=>{$('xcpHeight').textContent=`Block ${d.result?.counterparty_height??'—'}`;$('xcpState').textContent=d.result?.ledger_state||'Connected'})];const settled=await Promise.allSettled(tasks);$('networkLight').style.color=settled.some(x=>x.status==='fulfilled')?'var(--accent)':'#e87878'}hydrate();
function closePanels(){['minerDrawer','skinPanel','libraryPanel','settingsPanel','downloadsPanel'].forEach(id=>$(id)?.classList.remove('open'))}
function openMiner(){closePanels();$('minerDrawer').classList.add('open')}$('minerBtn').onclick=openMiner;$('openMiner').onclick=openMiner;$('closeMiner').onclick=()=>$('minerDrawer').classList.remove('open');$('skinBtn').onclick=()=>{closePanels();$('skinPanel').classList.add('open')};$('closeSkin').onclick=()=>$('skinPanel').classList.remove('open');
function renderLibrary(){const panel=$('libraryList'),bookmarks=window.omnitrixState?.getBookmarks?.()||[],recent=window.omnitrixState?.getHistory?.()||[];const rows=['<strong>Bookmarks</strong>'];if(!bookmarks.length)rows.push('<div class="libraryItem"><span>No bookmarks yet.</span></div>');bookmarks.forEach(item=>rows.push(`<div class="libraryItem"><span>${item.title}</span><div><button data-open="${item.url}">Open</button><button data-remove="${item.url}">Remove</button></div></div>`));rows.push('<strong>Recent</strong>');recent.slice(0,20).forEach(item=>rows.push(`<div class="libraryItem"><span>${item.title}</span><button data-open="${item.url}">Open</button></div>`));panel.innerHTML=rows.join('');panel.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>browse(b.dataset.open));panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{window.omnitrixState.removeBookmark(b.dataset.remove);updateLibraryCounts();renderLibrary()})}
$('libraryBtn').onclick=()=>{closePanels();renderLibrary();$('libraryPanel').classList.add('open')};$('closeLibrary').onclick=()=>$('libraryPanel').classList.remove('open');$('bookmarkBtn').onclick=()=>{const raw=$('bar').value.trim()||localStorage.getItem('omnitrix-last')||settings().homepage||'../noogle/';const url=destination(raw)||raw;window.omnitrixState?.addBookmark?.({url,title:titleFor(url)});updateLibraryCounts();$('bookmarkBtn').textContent='✓';setTimeout(()=>$('bookmarkBtn').textContent='★',900)};
$('downloadsBtn').onclick=()=>{closePanels();const rows=window.omnitrixState?.getDownloads?.()||[];$('downloadsList').innerHTML=rows.length?rows.map(x=>`<div class="downloadItem">${x.name||x.url}</div>`).join(''):'<div class="downloadItem">Downloads made by websites are managed by your device. Omnitrix will expose full download management in the installable app.</div>';$('downloadsPanel').classList.add('open')};$('closeDownloads').onclick=()=>$('downloadsPanel').classList.remove('open');
function openSettings(){closePanels();const s=settings();$('settingHomepage').value=s.homepage||'../noogle/';$('settingSearch').value=s.search||'noogle';$('settingRain').checked=s.matrixRain!==false;$('settingPrivacy').checked=!!s.privacyMode;$('settingRestore').checked=s.restoreSession!==false;$('settingsPanel').classList.add('open')}$('settingsBtn').onclick=openSettings;$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('open');$('saveSettings').onclick=()=>{const s=window.omnitrixState.saveSettings({homepage:$('settingHomepage').value.trim()||'../noogle/',search:$('settingSearch').value,matrixRain:$('settingRain').checked,privacyMode:$('settingPrivacy').checked,restoreSession:$('settingRestore').checked});document.getElementById('matrixRain').style.display=s.matrixRain?'block':'none';$('settingsPanel').classList.remove('open')};
function firstMiner(d){return d?.discoveredMiners?.[0]||d?.devices?.[0]||d?.payload||d||{}}function renderTelemetry(d){const p=firstMiner(d);$('minerState').textContent=d?.agentState||d?.status||'Connected';$('minerDetail').textContent=p.worker||p.minerId||p.host||'Telemetry live';const h=p.hashrateTh??p.hashrateTH??p.hashrate??p.hashRate;$('hashrate').textContent=h===undefined?'—':typeof h==='number'?`${Number(h).toLocaleString()}${p.hashrateTh!==undefined||p.hashrateTH!==undefined?' TH/s':' H/s'}`:String(h);const t=p.temperatureC??p.temperature??p.temp;$('temp').textContent=t===undefined?'—':`${Number(t).toFixed(1)} °C`;const w=p.powerW??p.power??p.watts;$('power').textContent=w===undefined?'—':`${Number(w).toLocaleString()} W`;$('pool').textContent=p.pool||p.poolUrl||'Connected'}
let pollTimer=null;$('connectMiner').onclick=async()=>{try{let url=$('adapterUrl').value.trim();const token=$('adapterToken')?.value.trim()||'';if(!url){const found=await window.omnitrixMiner.discover();if(!found)throw new Error('No NEO Miner found. Enter your miner URL.');url=found.url;$('adapterUrl').value=url}const connection=await window.omnitrixMiner.connect(url,token);if(connection.data)renderTelemetry(connection.data);if(connection.poll){clearInterval(pollTimer);pollTimer=setInterval(async()=>{try{renderTelemetry(await connection.poll())}catch{$('minerState').textContent='Reconnecting…'}},5000)}}catch(e){$('minerState').textContent='Not connected';$('minerDetail').textContent=e.message}};
const skins=$('skins');function addSkin(s){const b=document.createElement('button');b.className='skin';b.innerHTML=`<b>${s.name}</b><small>Tap to apply</small>`;b.onclick=()=>window.omnitrixThemes.applySkin(s);skins.appendChild(b)};window.omnitrixThemes.skins.forEach(addSkin);addSkin(window.omnitrixThemes.generatedSkin());$('generateSkin').onclick=()=>{const s=window.omnitrixThemes.generatedSkin();s.name='Fresh Matrix '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});window.omnitrixThemes.applySkin(s);addSkin(s)};
const s=settings();if(document.getElementById('matrixRain'))document.getElementById('matrixRain').style.display=s.matrixRain===false?'none':'block';if(s.restoreSession){const last=window.omnitrixState?.getSession?.()?.lastUrl||localStorage.getItem('omnitrix-last');if(last)$('bar').value=last}updateLibraryCounts();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});