function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function authorized(request,env){const configured=String(env.MODULE_ADAPTER_TOKEN||'');return !!configured&&String(request.headers.get('authorization')||'')===`Bearer ${configured}`}
function actor(request){return String(request.headers.get('x-neo-federation-actor')||'neo-government-federation').toLowerCase().slice(0,240)}
async function enterpriseFetch(env,path,init={}){const id=env.ENTERPRISE_STORE.idFromName('neo-enterprise'),stub=env.ENTERPRISE_STORE.get(id);return stub.fetch(new Request(`https://enterprise-store${path}`,{method:init.method||'GET',headers:{'x-neo-actor':init.actor||'neo-government-federation','x-neo-role':'EXECUTIVE_ADMIN','content-type':'application/json'},body:init.body?JSON.stringify(init.body):undefined}))}
async function enterpriseJson(env,path,init={}){const r=await enterpriseFetch(env,path,init);let b={};try{b=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(b.error||`Enterprise store returned ${r.status}`),{status:r.status});return b}
const DEFAULT_POLICY={singleApprovalLimit:10000,hardHoldAbove:100000,requiredApproversAboveSingle:2,requireRequesterSeparation:true,currency:'USD',enabled:true};
function normalizePolicy(input={}){const num=(v,d)=>Math.max(0,Number(v??d));return{singleApprovalLimit:num(input.singleApprovalLimit,DEFAULT_POLICY.singleApprovalLimit),hardHoldAbove:num(input.hardHoldAbove,DEFAULT_POLICY.hardHoldAbove),requiredApproversAboveSingle:Math.min(5,Math.max(2,Number(input.requiredApproversAboveSingle||2))),requireRequesterSeparation:input.requireRequesterSeparation!==false,currency:String(input.currency||'USD').toUpperCase().slice(0,12),enabled:input.enabled!==false}}
export class PolicyStore{
  constructor(state){this.storage=state.storage}
  async policy(orgId){return normalizePolicy(await this.storage.get(`policy:${orgId}`)||DEFAULT_POLICY)}
  async setPolicy(orgId,input,who){const p=normalizePolicy(input);await this.storage.put(`policy:${orgId}`,p);await this.event(orgId,'POLICY_UPDATE',who,JSON.stringify(p));return p}
  async vote(orgId,approvalId,who,decision,note=''){const v={orgId,approvalId,actor:who,decision,note:String(note).slice(0,1000),createdAt:new Date().toISOString()};await this.storage.put(`vote:${orgId}:${approvalId}:${who}`,v);await this.event(orgId,'DECISION_VOTE',who,`${approvalId} · ${decision}`);return v}
  async votes(orgId,approvalId){return[...(await this.storage.list({prefix:`vote:${orgId}:${approvalId}:`})).values()]}
  async clearVotes(orgId,approvalId){const rows=await this.storage.list({prefix:`vote:${orgId}:${approvalId}:`});for(const k of rows.keys())await this.storage.delete(k)}
  async event(orgId,type,who,note=''){const e={id:crypto.randomUUID(),orgId,type,actor:who,note,createdAt:new Date().toISOString()};await this.storage.put(`event:${Date.now()}:${e.id}`,e);return e}
  async recent(){return[...(await this.storage.list({prefix:'event:'})).values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100)}
  async fetch(request){const u=new URL(request.url),parts=u.pathname.split('/').filter(Boolean);
    if(request.method==='GET'&&u.pathname==='/events')return json({events:await this.recent()});
    if(parts[0]==='policies'&&parts[1]){const orgId=decodeURIComponent(parts[1]);if(request.method==='GET')return json({orgId,policy:await this.policy(orgId)});if(request.method==='PUT'){const b=await request.json();return json({ok:true,orgId,policy:await this.setPolicy(orgId,b,request.headers.get('x-actor')||'unknown')})}}
    if(parts[0]==='votes'&&parts[1]&&parts[2]){const orgId=decodeURIComponent(parts[1]),approvalId=decodeURIComponent(parts[2]);if(request.method==='GET')return json({votes:await this.votes(orgId,approvalId)});if(request.method==='POST'){const b=await request.json();return json({vote:await this.vote(orgId,approvalId,String(b.actor||'unknown'),String(b.decision||''),b.note||'')},201)}if(request.method==='DELETE'){await this.clearVotes(orgId,approvalId);return json({ok:true})}}
    return json({error:'Policy store route not found'},404)}
}
async function policyFetch(env,path,init={}){const id=env.POLICY_STORE.idFromName('neo-enterprise-policy'),stub=env.POLICY_STORE.get(id);return stub.fetch(new Request(`https://policy-store${path}`,{method:init.method||'GET',headers:{'content-type':'application/json','x-actor':init.actor||'system'},body:init.body?JSON.stringify(init.body):undefined}))}
async function policyJson(env,path,init={}){const r=await policyFetch(env,path,init),b=await r.json();if(!r.ok)throw Object.assign(new Error(b.error||'Policy store error'),{status:r.status});return b}
function orgSummary(org,s){const pick=l=>l.filter(x=>x.orgId===org.id),ledger=pick(s.ledger),inflow=ledger.filter(x=>x.direction==='IN').reduce((n,x)=>n+Number(x.amount||0),0),outflow=ledger.filter(x=>x.direction==='OUT').reduce((n,x)=>n+Number(x.amount||0),0),terminals=pick(s.terminals),approvals=pick(s.approvals),invoices=pick(s.invoices);return{id:org.id,name:org.name,type:org.type,visibility:org.visibility,status:org.status,members:pick(s.members).length,wallets:pick(s.wallets).length,terminals:{total:terminals.length,ready:terminals.filter(x=>['READY','ACTIVE'].includes(x.status)).length,attention:terminals.filter(x=>!['READY','ACTIVE'].includes(x.status)).length},approvals:{pending:approvals.filter(x=>x.status==='PENDING').length,total:approvals.length},invoices:{draft:invoices.filter(x=>x.status==='DRAFT').length,total:invoices.length},books:{inflow,outflow,net:inflow-outflow}}}
async function summary(env){const s=await enterpriseJson(env,'/snapshot');const organizations=await Promise.all(s.orgs.map(async o=>({...orgSummary(o,s),policy:(await policyJson(env,`/policies/${encodeURIComponent(o.id)}`)).policy})));const pending=s.approvals.filter(x=>x.status==='PENDING').sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,50);const pendingApprovals=await Promise.all(pending.map(async a=>{const policy=(await policyJson(env,`/policies/${encodeURIComponent(a.orgId)}`)).policy,votes=(await policyJson(env,`/votes/${encodeURIComponent(a.orgId)}/${encodeURIComponent(a.id)}`)).votes,amount=Number(a.amount||0),required=policy.enabled&&amount>policy.singleApprovalLimit?policy.requiredApproversAboveSingle:1;return{...a,policy:{requiredApprovers:required,hardHold:policy.enabled&&amount>=policy.hardHoldAbove,separation:policy.requireRequesterSeparation},votes:votes.map(v=>({actor:v.actor,decision:v.decision,createdAt:v.createdAt}))}}));return{ok:true,generatedAt:new Date().toISOString(),organizations,totals:{organizations:organizations.length,members:s.members.length,wallets:s.wallets.length,terminals:s.terminals.length,pendingApprovals:pendingApprovals.length,netBooks:organizations.reduce((n,o)=>n+o.books.net,0)},pendingApprovals,terminalAttention:s.terminals.filter(x=>!['READY','ACTIVE'].includes(x.status)),recentEvents:s.audit.slice(0,40),policyEvents:(await policyJson(env,'/events')).events.slice(0,25)}}
async function finalizeDecision(env,orgId,approvalId,decision,who,note){const result=await enterpriseJson(env,`/orgs/${encodeURIComponent(orgId)}/approvals/${encodeURIComponent(approvalId)}/decision`,{method:'POST',actor:who,body:{decision}});await enterpriseJson(env,`/orgs/${encodeURIComponent(orgId)}/ledger`,{method:'POST',actor:who,body:{description:`EXECUTIVE_DECISION ${decision} · ${approvalId}${note?' · '+note:''}`,direction:'IN',amount:0,currency:'USD',account:'Executive Decision Audit',source:'GOVERNMENT_FEDERATION'}});await policyFetch(env,`/votes/${encodeURIComponent(orgId)}/${encodeURIComponent(approvalId)}`,{method:'DELETE',actor:who});return result.record}
async function decide(env,request,orgId,approvalId){let b={};try{b=await request.json()}catch{return json({ok:false,error:'JSON body required.'},400)}const decision=String(b.decision||'').toUpperCase();if(!['APPROVED','REJECTED','HOLD'].includes(decision))return json({ok:false,error:'Decision must be APPROVED, REJECTED, or HOLD.'},400);const who=actor(request),note=String(b.note||'').trim().slice(0,2000),ws=await enterpriseJson(env,`/orgs/${encodeURIComponent(orgId)}/workspace`),approval=ws.approvals.find(x=>String(x.id)===String(approvalId));if(!approval)return json({ok:false,error:'Approval not found.'},404);if(approval.status!=='PENDING')return json({ok:false,error:`Approval is already ${approval.status}.`},409);const policy=(await policyJson(env,`/policies/${encodeURIComponent(orgId)}`)).policy,amount=Number(approval.amount||0);
  if(decision!=='APPROVED'){return json({ok:true,final:true,decision:await finalizeDecision(env,orgId,approvalId,decision,who,note),policy})}
  if(policy.enabled&&policy.requireRequesterSeparation&&String(approval.requestedBy||'').toLowerCase()===who)return json({ok:false,error:'Separation-of-duties policy prevents the requester from approving their own request.',code:'REQUESTER_CANNOT_APPROVE'},403);
  if(policy.enabled&&amount>=policy.hardHoldAbove)return json({ok:true,final:true,decision:await finalizeDecision(env,orgId,approvalId,'HOLD',who,`POLICY_HARD_HOLD · requested approval · ${note}`),policyOutcome:'HARD_HOLD',policy});
  const required=policy.enabled&&amount>policy.singleApprovalLimit?policy.requiredApproversAboveSingle:1;await policyFetch(env,`/votes/${encodeURIComponent(orgId)}/${encodeURIComponent(approvalId)}`,{method:'POST',actor:who,body:{actor:who,decision:'APPROVED',note}});const votes=(await policyJson(env,`/votes/${encodeURIComponent(orgId)}/${encodeURIComponent(approvalId)}`)).votes.filter(v=>v.decision==='APPROVED'),approvers=[...new Set(votes.map(v=>v.actor))];if(approvers.length<required)return json({ok:true,final:false,status:'AWAITING_ADDITIONAL_APPROVAL',approvalId,requiredApprovers:required,collectedApprovers:approvers.length,approvers,policy});return json({ok:true,final:true,decision:await finalizeDecision(env,orgId,approvalId,'APPROVED',who,note),requiredApprovers:required,approvers,policy})}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/health')return json({ok:true,service:'neo-enterprise-federation',version:'3.0',scope:'executive federation + policy engine',policyEngine:true});if(!authorized(request,env))return json({ok:false,error:'Federation authorization required.'},401);try{if(request.method==='GET'&&u.pathname==='/summary')return json(await summary(env));const pm=u.pathname.match(/^\/organizations\/([^/]+)\/policy$/);if(pm){if(request.method==='GET')return json(await policyJson(env,`/policies/${encodeURIComponent(pm[1])}`));if(request.method==='PUT')return json(await policyJson(env,`/policies/${encodeURIComponent(pm[1])}`,{method:'PUT',actor:actor(request),body:await request.json()}))}const org=u.pathname.match(/^\/organizations\/([^/]+)$/);if(request.method==='GET'&&org){const ws=await enterpriseJson(env,`/orgs/${encodeURIComponent(org[1])}/workspace`);return json({ok:true,organization:ws.org,role:ws.role,members:ws.members.length,wallets:ws.wallets.length,terminals:ws.terminals,books:ws.books,pendingApprovals:ws.approvals.filter(x=>x.status==='PENDING'),invoices:ws.invoices,audit:ws.audit,policy:(await policyJson(env,`/policies/${encodeURIComponent(org[1])}`)).policy})}const dm=u.pathname.match(/^\/organizations\/([^/]+)\/approvals\/([^/]+)\/decision$/);if(request.method==='POST'&&dm)return decide(env,request,dm[1],dm[2]);return json({ok:false,error:'Not found'},404)}catch(error){return json({ok:false,error:String(error?.message||error)},error?.status||502)}}};