function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}

function authorized(request,env){const configured=String(env.MODULE_ADAPTER_TOKEN||'');if(!configured)return false;const auth=String(request.headers.get('authorization')||'');return auth===`Bearer ${configured}`}

async function enterpriseFetch(env,path){const id=env.ENTERPRISE_STORE.idFromName('neo-enterprise');const stub=env.ENTERPRISE_STORE.get(id);return stub.fetch(new Request(`https://enterprise-store${path}`,{headers:{'x-neo-actor':'neo-government-federation','x-neo-role':'EXECUTIVE_ADMIN','content-type':'application/json'}}))}

async function enterpriseJson(env,path){const response=await enterpriseFetch(env,path);let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||`Enterprise store returned ${response.status}`);return body}

function orgSummary(org,snapshot){const pick=list=>list.filter(item=>item.orgId===org.id);const ledger=pick(snapshot.ledger);const inflow=ledger.filter(x=>x.direction==='IN').reduce((n,x)=>n+Number(x.amount||0),0);const outflow=ledger.filter(x=>x.direction==='OUT').reduce((n,x)=>n+Number(x.amount||0),0);const terminals=pick(snapshot.terminals);const approvals=pick(snapshot.approvals);const invoices=pick(snapshot.invoices);return{id:org.id,name:org.name,type:org.type,visibility:org.visibility,status:org.status,members:pick(snapshot.members).length,wallets:pick(snapshot.wallets).length,terminals:{total:terminals.length,ready:terminals.filter(x=>x.status==='READY'||x.status==='ACTIVE').length,attention:terminals.filter(x=>!['READY','ACTIVE'].includes(x.status)).length},approvals:{pending:approvals.filter(x=>x.status==='PENDING').length,total:approvals.length},invoices:{draft:invoices.filter(x=>x.status==='DRAFT').length,total:invoices.length},books:{inflow,outflow,net:inflow-outflow}}}

async function summary(env){const s=await enterpriseJson(env,'/snapshot');const orgs=s.orgs.map(org=>orgSummary(org,s));const pendingApprovals=s.approvals.filter(x=>x.status==='PENDING').sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,50);const terminalAttention=s.terminals.filter(x=>!['READY','ACTIVE'].includes(x.status));const recentEvents=s.audit.slice(0,40);return{ok:true,generatedAt:new Date().toISOString(),organizations:orgs,totals:{organizations:orgs.length,members:s.members.length,wallets:s.wallets.length,terminals:s.terminals.length,pendingApprovals:pendingApprovals.length,netBooks:orgs.reduce((n,o)=>n+o.books.net,0)},pendingApprovals,terminalAttention,recentEvents}}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health')return json({ok:true,service:'neo-enterprise-federation',version:'1.0',scope:'read-only executive federation'});if(!authorized(request,env))return json({ok:false,error:'Federation authorization required.'},401);try{if(request.method==='GET'&&url.pathname==='/summary')return json(await summary(env));const org=url.pathname.match(/^\/organizations\/([^/]+)$/);if(request.method==='GET'&&org){const ws=await enterpriseJson(env,`/orgs/${encodeURIComponent(org[1])}/workspace`);return json({ok:true,organization:ws.org,role:ws.role,members:ws.members.length,wallets:ws.wallets.length,terminals:ws.terminals,books:ws.books,pendingApprovals:ws.approvals.filter(x=>x.status==='PENDING'),invoices:ws.invoices,audit:ws.audit});}return json({ok:false,error:'Not found'},404)}catch(error){return json({ok:false,error:String(error?.message||error)},502)}}};