import { useEffect, useMemo, useState } from 'react'
import { Activity, CheckCircle2, Clock3, Database, GitBranch, Network, Radio, RefreshCw, ShieldCheck, Siren, TriangleAlert, Users } from 'lucide-react'

type Mission={id:string;objective:string;priority:string;status:string;route:string[];updatedAt:string;dependencies?:string[];attempts?:number;sla?:{dueAt?:string}}
type Approval={id:string;missionId:string;action:string;status:string;requestedAt:string}
type Connector={connectorId:string;state:string;checkedAt:string;detail?:Record<string,unknown>}
type Event={id:string;type:string;missionId:string|null;timestamp:string;detail:Record<string,unknown>}
type InboundEvent={id:string;source:string;type:string;status:string;receivedAt:string;missionId?:string;ruleId?:string}
type RouterHealth={ok:boolean;configured:string[];providers:{id:string;configured:boolean;roles?:string[]}[];capabilities:string[]}
type Telemetry={generatedAt:string;summary:{total:number;queued:number;blocked?:number;running:number;retryWait?:number;awaitingApproval:number;terminal:number;pendingApprovals:number};missions:Mission[];approvals:Approval[];connectors:Connector[];events:Event[];inboundEvents?:InboundEvent[];eventStore?:{mode:string;durable:boolean};persistence?:{mode:string;durable:boolean};deadLetters?:unknown[];workerFleet?:{id:string;role:string;state?:string}[];routerHealth?:RouterHealth;command?:{summary?:{incidents:number;correlatedClusters:number;escalations:number;slaAtRisk:number;slaBreached:number;deadLetters:number;routerReady?:boolean|null;configuredRouterProviders?:number};routerHealth?:RouterHealth|null;clusters?:{key:string;count:number;sources:string[];pattern:string}[];escalations?:{eventId:string;tier:number;severity:string;action:string;approvalRequired:boolean}[];sla?:{missionId:string;state:string}[];policies?:{id:string;source?:string;type?:string;decision?:string;severity?:string;escalationTier?:number}[]}}
const fallback:Telemetry={generatedAt:'',summary:{total:0,queued:0,running:0,awaitingApproval:0,terminal:0,pendingApprovals:0},missions:[],approvals:[],connectors:[],events:[],inboundEvents:[],persistence:{mode:'memory',durable:false},eventStore:{mode:'memory',durable:false}}
function badge(state:string){if(['healthy','bound','running','completed','approved','routed','on_track','ready'].includes(state))return'authorized';if(['degraded','awaiting_approval','pending','unbound','blocked','retry_wait','at_risk','unknown'].includes(state))return'manual_review';return'settlement_pending'}
export function RouterControlCenter(){const[data,setData]=useState<Telemetry>(fallback),[loading,setLoading]=useState(false),[source,setSource]=useState<'live'|'fallback'>('fallback');const refresh=async()=>{setLoading(true);try{const r=await fetch('/api/router-telemetry',{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json());setSource('live')}catch{setSource('fallback')}finally{setLoading(false)}};useEffect(()=>{refresh();const t=window.setInterval(refresh,15000);return()=>window.clearInterval(t)},[]);const pending=useMemo(()=>data.approvals.filter(a=>a.status==='pending'),[data.approvals]);const durable=Boolean(data.persistence?.durable),eventDurable=Boolean(data.eventStore?.durable),cmd=data.command?.summary,routerReady=cmd?.routerReady??data.routerHealth?.ok??null,routerProviders=cmd?.configuredRouterProviders??data.routerHealth?.configured.length??0
return <><section className="principles"><span>ORIGIN / NIA-001</span><span>MISSION ENGINE v9</span><span>OPERATIONS COMMAND CENTER</span><span>POLICY INTELLIGENCE</span><span>HUMAN APPROVAL</span></section>
<section className="stats"><div className="card stat"><div><span>Command State</span><strong>ACTIVE</strong><small>{source==='live'?'Live telemetry':'Fallback snapshot'}</small></div><Network size={22}/></div><div className="card stat"><div><span>Router Readiness</span><strong>{routerReady===true?'READY':routerReady===false?'OFFLINE':'UNKNOWN'}</strong><small>{routerProviders} configured providers</small></div><Radio size={22}/></div><div className="card stat"><div><span>Persistence</span><strong>{durable&&eventDurable?'DURABLE':'VOLATILE'}</strong><small>{data.persistence?.mode||'memory'} / {data.eventStore?.mode||'memory'}</small></div><Database size={22}/></div><div className="card stat"><div><span>Escalations</span><strong>{cmd?.escalations??0}</strong><small>{cmd?.correlatedClusters??0} correlated clusters</small></div><Siren size={22}/></div><div className="card stat"><div><span>SLA Risk</span><strong>{(cmd?.slaAtRisk??0)+(cmd?.slaBreached??0)}</strong><small>{cmd?.slaBreached??0} breached</small></div><Clock3 size={22}/></div></section>
{(!durable||!eventDurable)&&<section className="card focus"><TriangleAlert size={26}/><h2>Durable Operations Required</h2><p>Autonomous mutations remain fail-closed until Redis-backed mission and event state are configured.</p></section>}
<section className="focusgrid"><div className="card focus"><Siren size={26}/><h2>Escalation Board</h2>{(data.command?.escalations??[]).slice(0,8).map(e=><p key={e.eventId}><b>Tier {e.tier} · {e.severity}</b><br/>{e.action}{e.approvalRequired?' · approval required':''}</p>)}{!(data.command?.escalations?.length)&&<p>No active escalations.</p>}</div><div className="card focus"><Users size={26}/><h2>Worker Fleet</h2>{(data.workerFleet??[]).map(w=><p key={w.id}><b>{w.role}</b><br/><span className="mono">{w.id}</span> · {w.state||'registered'}</p>)}{!(data.workerFleet?.length)&&<p>Worker telemetry awaiting live runtime.</p>}</div></section>
<section className="card tablecard"><div className="paneltitle"><div><span>Incident & Correlation Registry</span><small>Cross-source and repeated-event clusters</small></div><Radio size={18}/></div><div className="tablewrap"><table><thead><tr><th>Correlation</th><th>Pattern</th><th>Count</th><th>Sources</th></tr></thead><tbody>{(data.command?.clusters??[]).map(c=><tr key={c.key}><td className="mono">{c.key}</td><td>{c.pattern}</td><td>{c.count}</td><td>{c.sources.join(', ')}</td></tr>)}</tbody></table></div></section>
<section className="card tablecard"><div className="paneltitle"><div><span>Mission & SLA Board</span><small>Queue state, retries and service-level posture</small></div><button className="iconbutton" onClick={refresh} disabled={loading}><RefreshCw size={17}/></button></div><div className="tablewrap"><table><thead><tr><th>Mission</th><th>Priority</th><th>Status</th><th>SLA</th><th>Route</th></tr></thead><tbody>{data.missions.map(m=>{const s=data.command?.sla?.find(x=>x.missionId===m.id)?.state||'none';return <tr key={m.id}><td className="mono">{m.id}</td><td>{m.priority}</td><td><span className={'pill '+badge(m.status)}>{m.status}</span></td><td><span className={'pill '+badge(s)}>{s}</span></td><td>{m.route.join(' → ')}</td></tr>})}</tbody></table></div></section>
<section className="focusgrid"><div className="card focus"><ShieldCheck size={26}/><h2>Approval Inbox</h2>{pending.length===0?<p>No pending approvals.</p>:pending.map(a=><p key={a.id}><b>{a.action}</b><br/><span className="mono">{a.missionId}</span></p>)}</div><div className="card focus"><Activity size={26}/><h2>Dead-Letter Recovery</h2><p><b>{cmd?.deadLetters??data.deadLetters?.length??0}</b> missions awaiting recovery review.</p><p>Recovery remains governed; failed high-impact work is never silently replayed.</p></div></section>
<section className="card tablecard"><div className="paneltitle"><div><span>Policy Registry</span><small>Visible command rules and escalation posture</small></div><ShieldCheck size={18}/></div><div className="tablewrap"><table><thead><tr><th>Policy</th><th>Source</th><th>Event</th><th>Decision</th><th>Severity</th><th>Tier</th></tr></thead><tbody>{(data.command?.policies??[]).map(p=><tr key={p.id}><td>{p.id}</td><td>{p.source||'*'}</td><td>{p.type||'*'}</td><td>{p.decision||'mission'}</td><td>{p.severity||'medium'}</td><td>{p.escalationTier??1}</td></tr>)}</tbody></table></div></section>
<section className="card tablecard"><div className="paneltitle"><div><span>Connector Fabric</span><small>Heartbeat and degradation state</small></div><GitBranch size={18}/></div><div className="tablewrap"><table><thead><tr><th>Connector</th><th>Status</th><th>Control</th></tr></thead><tbody>{data.connectors.map(c=><tr key={c.connectorId}><td>{c.connectorId}</td><td><span className={'pill '+badge(c.state)}>{c.state}</span></td><td>{['degraded','unbound'].includes(c.state)?<><TriangleAlert size={14}/> fallback / remediation</>:<><CheckCircle2 size={14}/> governed</>}</td></tr>)}</tbody></table></div></section>
<section className="card focus"><Activity size={26}/><h2>V9 Command Boundary</h2><p>Command intelligence can classify, correlate, prioritize and escalate operations. Consequential external writes remain subject to the existing approval boundary.</p><p><small>Telemetry generated: {data.generatedAt||'local fallback'}</small></p></section></>}
