import { useEffect, useMemo, useState } from 'react'
import { Activity, CheckCircle2, Clock3, Database, GitBranch, Network, Radio, RefreshCw, ShieldCheck, TriangleAlert } from 'lucide-react'

type Mission={id:string;objective:string;priority:string;status:string;route:string[];updatedAt:string;dependencies?:string[];attempts?:number;nextAttemptAt?:string|null}
type Approval={id:string;missionId:string;action:string;status:string;requestedAt:string}
type Connector={connectorId:string;state:string;checkedAt:string;detail?:Record<string,unknown>}
type Event={id:string;type:string;missionId:string|null;timestamp:string;detail:Record<string,unknown>}
type InboundEvent={id:string;source:string;type:string;status:string;receivedAt:string;missionId?:string;ruleId?:string}
type Telemetry={generatedAt:string;summary:{total:number;queued:number;blocked?:number;running:number;retryWait?:number;awaitingApproval:number;terminal:number;pendingApprovals:number};missions:Mission[];approvals:Approval[];connectors:Connector[];events:Event[];inboundEvents?:InboundEvent[];eventStore?:{mode:string;durable:boolean};persistence?:{mode:string;durable:boolean}}
const fallback:Telemetry={generatedAt:'',summary:{total:1,queued:0,blocked:0,running:1,retryWait:0,awaitingApproval:0,terminal:0,pendingApprovals:0},missions:[{id:'NEO-ROUTER-MISSION-001',objective:'Triage and safely rebase stale neo-system pull requests, rerun CI, preserve provenance, and stop at approval gates before consequential merges.',priority:'high',status:'running',route:['github-native','asana-native','airbyte-agent-engine'],updatedAt:''}],approvals:[],connectors:[{connectorId:'github-native',state:'healthy',checkedAt:''},{connectorId:'asana-native',state:'healthy',checkedAt:''},{connectorId:'airbyte-agent-engine',state:'degraded',checkedAt:'',detail:{reason:'schema_discovery_error'}}],events:[],inboundEvents:[],eventStore:{mode:'memory',durable:false},persistence:{mode:'memory',durable:false}}
function badge(state:string){if(['healthy','bound','running','completed','approved','routed'].includes(state))return'authorized';if(['degraded','awaiting_approval','pending','unbound','blocked','retry_wait'].includes(state))return'manual_review';return'settlement_pending'}

export function RouterControlCenter(){
 const[data,setData]=useState<Telemetry>(fallback),[loading,setLoading]=useState(false),[source,setSource]=useState<'live'|'fallback'>('fallback')
 const refresh=async()=>{setLoading(true);try{const r=await fetch('/api/router-telemetry',{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json());setSource('live')}catch{setSource('fallback')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=window.setInterval(refresh,15000);return()=>window.clearInterval(t)},[])
 const pending=useMemo(()=>data.approvals.filter(a=>a.status==='pending'),[data.approvals]);const durable=Boolean(data.persistence?.durable);const eventDurable=Boolean(data.eventStore?.durable)
 return <>
  <section className="principles"><span>ORIGIN / NIA-001</span><span>MISSION ENGINE v7</span><span>EVENT-DRIVEN OPERATIONS</span><span>DEDUPLICATION</span><span>HUMAN APPROVAL</span></section>
  <section className="stats">
   <div className="card stat"><div><span>Mission Engine</span><strong>ACTIVE</strong><small>{source==='live'?'Live telemetry':'Fallback snapshot'}</small></div><Network size={22}/></div>
   <div className="card stat"><div><span>Operations State</span><strong>{durable?'DURABLE':'VOLATILE'}</strong><small>{data.persistence?.mode||'memory'}</small></div><Database size={22}/></div>
   <div className="card stat"><div><span>Inbound Events</span><strong>{data.inboundEvents?.length??0}</strong><small>{eventDurable?'durable inbox':'volatile inbox'}</small></div><Radio size={22}/></div>
   <div className="card stat"><div><span>Approval Inbox</span><strong>{data.summary.pendingApprovals}</strong><small>High-impact actions waiting</small></div><ShieldCheck size={22}/></div>
  </section>
  {(!durable||!eventDurable)&&<section className="card focus"><TriangleAlert size={26}/><h2>Persistent Event Operations Not Yet Activated</h2><p>Mission and event ingestion remain fail-closed for autonomous mutations until Redis-backed durable state is configured.</p></section>}
  <section className="card tablecard"><div className="paneltitle"><div><span>Event Stream</span><small>Verified, deduplicated inbound triggers</small></div><Radio size={18}/></div><div className="tablewrap"><table><thead><tr><th>Source</th><th>Event</th><th>Status</th><th>Rule</th><th>Mission</th></tr></thead><tbody>{(data.inboundEvents??[]).slice(0,20).map(e=><tr key={e.id}><td>{e.source}</td><td>{e.type}</td><td><span className={'pill '+badge(e.status)}>{e.status}</span></td><td>{e.ruleId||'—'}</td><td className="mono">{e.missionId||'—'}</td></tr>)}</tbody></table></div></section>
  <section className="card tablecard"><div className="paneltitle"><div><span>Mission Queue</span><small>Dependency-aware, retry-capable lifecycle state</small></div><button className="iconbutton" onClick={refresh} disabled={loading}><RefreshCw size={17}/></button></div><div className="tablewrap"><table><thead><tr><th>Mission</th><th>Priority</th><th>Status</th><th>Attempt</th><th>Dependencies</th><th>Route</th></tr></thead><tbody>{data.missions.map(m=><tr key={m.id}><td className="mono">{m.id}</td><td>{m.priority}</td><td><span className={'pill '+badge(m.status)}>{m.status}</span></td><td>{m.attempts??0}</td><td>{m.dependencies?.join(', ')||'—'}</td><td>{m.route.join(' → ')}</td></tr>)}</tbody></table></div></section>
  <section className="focusgrid"><div className="card focus"><ShieldCheck size={26}/><h2>Approval Inbox</h2>{pending.length===0?<p>No pending approvals. Consequential writes remain gated.</p>:pending.map(a=><p key={a.id}><b>{a.action}</b><br/><span className="mono">{a.missionId}</span></p>)}</div><div className="card focus"><Clock3 size={26}/><h2>Execution History</h2>{data.events.slice(0,8).map(e=><p key={e.id}><b>{e.type}</b><br/><span className="mono">{e.missionId||'router'}</span></p>)}</div></section>
  <section className="card tablecard"><div className="paneltitle"><div><span>Connector Fabric</span><small>Heartbeat, binding and degradation state</small></div><GitBranch size={18}/></div><div className="tablewrap"><table><thead><tr><th>Connector</th><th>Status</th><th>Control</th></tr></thead><tbody>{data.connectors.map(c=><tr key={c.connectorId}><td>{c.connectorId}</td><td><span className={'pill '+badge(c.state)}>{c.state}</span></td><td>{['degraded','unbound'].includes(c.state)?<><TriangleAlert size={14}/> fallback / remediation</>:<><CheckCircle2 size={14}/> governed</>}</td></tr>)}</tbody></table></div></section>
  <section className="card focus"><Activity size={26}/><h2>V7 Event Boundary</h2><p>Inbound events are verified, deduplicated and matched against explicit policy rules before ORIGIN creates a mission. Event-triggered external writes still pass through the existing approval boundary.</p><p><small>Telemetry generated: {data.generatedAt||'local fallback'}</small></p></section>
 </>
}
