import { McpServer } from "@modelcontextprotocol/server";
import { createMcpHandler } from "agents/mcp/server";
import { z } from "zod";
export interface Env { DB: D1Database; }
const respond = (x: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(x, null, 2) }] });
function createServer(env: Env) {
  const server = new McpServer({ name: "NEO-PACER", version: "1.2.0" });
  server.registerTool("list_cases", { description: "List NEO-PACER cases.", inputSchema: { status: z.string().optional() } }, async ({ status }) => { const q = status ? env.DB.prepare("SELECT * FROM cases WHERE status=? ORDER BY opened_at DESC").bind(status) : env.DB.prepare("SELECT * FROM cases ORDER BY opened_at DESC"); const r = await q.all(); return respond({ cases: r.results ?? [] }); });
  server.registerTool("get_case", { description: "Load a case with evidence, claims, title chain, orders, contradictions, and accountability records.", inputSchema: { case_no: z.string() } }, async ({ case_no }) => { const c = await env.DB.prepare("SELECT * FROM cases WHERE case_no=?").bind(case_no).first(); if (!c) return { isError: true, content: [{ type: "text" as const, text: `Case not found: ${case_no}` }] }; const [e,t,cl,o,x,p] = await Promise.all([env.DB.prepare("SELECT * FROM evidence WHERE case_no=? ORDER BY evidence_id").bind(case_no).all(),env.DB.prepare("SELECT * FROM title_chain WHERE case_no=? ORDER BY seq").bind(case_no).all(),env.DB.prepare("SELECT * FROM claims WHERE case_no=? ORDER BY claim_id").bind(case_no).all(),env.DB.prepare("SELECT * FROM orders WHERE case_no=? ORDER BY issued_at DESC").bind(case_no).all(),env.DB.prepare("SELECT * FROM contradictions WHERE case_no=? ORDER BY contradiction_id").bind(case_no).all(),env.DB.prepare("SELECT * FROM professional_accountability WHERE case_no=? ORDER BY record_id").bind(case_no).all()]); return respond({case:c,evidence:e.results??[],title_chain:t.results??[],claims:cl.results??[],orders:o.results??[],contradictions:x.results??[],professional_accountability:p.results??[]}); });
  server.registerTool("search_neo_pacer", { description: "Search cases, evidence, claims, title instruments, and orders.", inputSchema: { query: z.string().min(1), limit: z.number().int().min(1).max(100).default(30) } }, async ({ query, limit }) => { const like=`%${query}%`; const [a,b,c,d,e]=await Promise.all([env.DB.prepare("SELECT case_no id, caption title, COALESCE(summary,'') text, 'case' kind FROM cases WHERE case_no LIKE ? OR caption LIKE ? OR summary LIKE ? LIMIT ?").bind(like,like,like,limit).all(),env.DB.prepare("SELECT evidence_id id, title, COALESCE(notes,'') text, 'evidence' kind FROM evidence WHERE evidence_id LIKE ? OR title LIKE ? OR notes LIKE ? OR source_ref LIKE ? LIMIT ?").bind(like,like,like,like,limit).all(),env.DB.prepare("SELECT claim_id id, proposition title, COALESCE(notes,'') text, 'claim' kind FROM claims WHERE claim_id LIKE ? OR proposition LIKE ? OR notes LIKE ? LIMIT ?").bind(like,like,like,limit).all(),env.DB.prepare("SELECT CAST(title_node_id AS TEXT) id, instrument_name title, COALESCE(notes,'') text, 'title_chain' kind FROM title_chain WHERE instrument_name LIKE ? OR property_description LIKE ? OR notes LIKE ? LIMIT ?").bind(like,like,like,limit).all(),env.DB.prepare("SELECT order_id id, title, operative_text text, 'order' kind FROM orders WHERE order_id LIKE ? OR title LIKE ? OR operative_text LIKE ? LIMIT ?").bind(like,like,like,limit).all()]); return respond({query,results:[...(a.results??[]),...(b.results??[]),...(c.results??[]),...(d.results??[]),...(e.results??[])].slice(0,limit)}); });
  server.registerTool("get_evidence", { description: "Retrieve an evidence record with authentication status.", inputSchema: { evidence_id: z.string() } }, async ({ evidence_id }) => { const r=await env.DB.prepare("SELECT * FROM evidence WHERE evidence_id=?").bind(evidence_id).first(); if(!r)return{isError:true,content:[{type:"text" as const,text:`Evidence not found: ${evidence_id}`}]}; return respond(r); });
  server.registerTool("add_investigative_lead", { description: "Add an investigative lead. Additive only; prior records are not rewritten.", inputSchema: { case_no:z.string(),person_or_entity:z.string(),role:z.string().optional(),duty_or_authority:z.string().optional(),alleged_act_or_omission:z.string(),supporting_evidence_ref:z.string().optional(),notes:z.string().optional() } }, async (i) => { const r=await env.DB.prepare("INSERT INTO professional_accountability (case_no,person_or_entity,role,duty_or_authority,alleged_act_or_omission,supporting_evidence_ref,status,notes) VALUES(?,?,?,?,?,?,'INVESTIGATIVE_LEAD',?)").bind(i.case_no,i.person_or_entity,i.role??null,i.duty_or_authority??null,i.alleged_act_or_omission,i.supporting_evidence_ref??null,i.notes??null).run(); return respond({success:r.success,record_id:r.meta?.last_row_id??null}); });
  server.registerTool("add_contradiction", { description: "Record adverse or contradictory evidence without rewriting the original claim.", inputSchema: { case_no:z.string(),claim_id:z.string().optional(),adverse_source_ref:z.string().optional(),description:z.string(),severity:z.enum(["LOW","MEDIUM","HIGH","CRITICAL"]).default("MEDIUM") } }, async (i) => { const r=await env.DB.prepare("INSERT INTO contradictions (case_no,claim_id,adverse_source_ref,description,severity,status) VALUES(?,?,?,?,?,'OPEN')").bind(i.case_no,i.claim_id??null,i.adverse_source_ref??null,i.description,i.severity).run(); return respond({success:r.success,contradiction_id:r.meta?.last_row_id??null}); });
  server.registerTool("add_docket_entry", { description: "Add a new docket event. NEO-PACER preserves prior docket entries.", inputSchema: { docket_no:z.string(),case_no:z.string(),seq:z.number().int().positive(),filer:z.string().optional(),filing_type:z.string(),title:z.string(),description:z.string().optional(),access_level:z.enum(["PUBLIC","RESTRICTED","SEALED","SACRED-INTERNAL"]).default("PUBLIC") } }, async (i) => { const filed_at=new Date().toISOString(); const r=await env.DB.prepare("INSERT INTO docket (docket_no,case_no,seq,filed_at,filer,filing_type,title,description,access_level,is_original) VALUES(?,?,?,?,?,?,?,?,?,1)").bind(i.docket_no,i.case_no,i.seq,filed_at,i.filer??null,i.filing_type,i.title,i.description??null,i.access_level).run(); return respond({success:r.success,docket_no:i.docket_no,filed_at}); });
  return server;
}
export default { async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> { const url=new URL(request.url); if(url.pathname==="/")return Response.json({name:"NEO-PACER",version:"1.2.0",description:"Public Access to Noocratic Ecclesiastical Records",health:"/health",mcp:"/mcp"}); if(url.pathname==="/health"){const x=await env.DB.prepare("SELECT COUNT(*) count FROM cases").first<{count:number}>(); return Response.json({ok:true,service:"NEO-PACER",version:"1.2.0",database:"D1",cases:x?.count??0});} if(url.pathname==="/mcp")return createMcpHandler(()=>createServer(env))(request,env,ctx); return new Response("Not Found",{status:404}); } } satisfies ExportedHandler<Env>;
