export const AUSARIAN_ECONOMIC_DOCTRINE = {
  id: 'NEO-AUSARIAN-ECONOMIC-DOCTRINE-001',
  title: 'Ausarian Economic Philosophy — Natural Economic Order',
  originator: 'H.I.M. Dr. Lawiy Zodok',
  status: 'FOUNDATIONAL_NEO_ECONOMIC_DOCTRINE',
  aliases: ['Natural Economic Order'],
  canonicalDocument: 'docs/AUSARIAN_ECONOMIC_PHILOSOPHY.md',
  scope: [
    'NEO System',
    'NEO Algo',
    'NEO Oracle',
    'GISD / GISS NEO LMS',
    'NEOsync Digital Etheric Intelligence',
    'NEO Law',
    'NEO Society internal social norms',
    'NEO Investments',
    'NEO Digital Capital',
    'World Monetary System',
    'CES / Mutual Credit',
    'NEO Bank / NEOpay / NEO Counter',
    'World Treasury / Nibiru Reserve',
    'Nu City / Project 144 socio-economic planning',
    'NEO Library / Neopedia',
  ] as const,
  analyticalFramework: {
    macroeconomics: [
      'monetary circulation', 'production', 'employment', 'capital formation', 'credit',
      'prices', 'settlement systems', 'institutional accounts', 'public economic activity',
      'relationship between monetary and material capital',
    ],
    microeconomics: [
      'households', 'workers', 'entrepreneurs', 'firms', 'communities', 'exchanges',
      'incentives', 'contracts', 'savings', 'investment', 'trade', 'mutual credit',
      'productive allocation of resources',
    ],
  },
  worldMonetarySystem: {
    taxonomyBoundary: 'MB and M0-M9 below are NEO system classifications and are not conventional central-bank money-supply definitions.',
    MB: 'World Monetary Base — Bitcoin / Mutual Credits',
    M0: 'Cryptographic Commercial Paper / Metallic Instrument',
    M1: 'XCP / XCPC Index — Tokenized CES Transaction Accounts',
    M2: 'NMNI Index — Tokenized CES Trade / Share / Money-Market Accounts',
    M3: 'WOME Index — Tokenized CES Institutional / Government Accounts',
    M4: 'Bond Index — Tokenized CES Bond Accounts',
    M5: 'Home Index — Tokenized CES Home Accounts',
    M6: 'Bank Index — Tokenized E-Wallet Accounts',
    M7: 'Hemp Index — Tokenized CES Hemp Accounts',
    M8: 'Utility Index — Tokenized E-Wallet / Utility Accounts',
    M9: 'Metal Index — Gold / Silver Tokenized Market Accounts',
    reserveCapital: 'SVC / XCP',
    circulatoryCapital: 'NOMNI / XCP',
    exchangeLayer: 'CES XXXX Open Market Exchange — Community Mutual Credit Unions',
    clearingLayer: 'CES XXXX Open Market Clearing House — Community Mutual CreditBanks',
  },
  gesellPrinciple: {
    sourceInfluence: 'Silvio Gesell — The Natural Economic Order',
    neoSynthesis: 'Productive abundance should discipline scarcity rents.',
    rule: 'Where economically and ecologically sustainable, additional productive capital should be permitted to compete against scarcity rents, monopoly yields, and excessive financing costs.',
    empiricalBoundary: 'The proposition that expanding productive capital can drive interest toward zero is treated as a theoretical proposition, not an automatic empirical law under all market conditions.',
  },
  ethicalInfluences: {
    jamesPGills: 'A Biblical Economics Manifesto',
    jPhilipWogaman: 'Economics and Ethics: A Christian Enquiry',
    synthesis: [
      'responsible stewardship of resources',
      'human dignity in economic organization',
      'justice and integrity in exchange',
      'protection against exploitation',
      'responsibility toward economically vulnerable persons and communities',
      'productive enterprise balanced with community welfare',
      'ethical limits on profit and power',
      'generosity, reciprocity, and social responsibility',
      'institutional accountability',
      'economic evaluation by material outcomes and moral consequences',
    ],
    provenanceRule: 'Specific claims about external authors must be verified against the relevant source text before being presented as quotations or definitive summaries.',
  },
  operatingPrinciples: [
    'Production before extraction.',
    'Circulation with accountability.',
    'Capital serves productive life.',
    'Community resilience matters.',
    'Technology should increase economic agency.',
    'Stewardship constrains exploitation.',
    'Economic freedom requires economic responsibility.',
    'Abundance should challenge monopoly rents.',
    'Value representations must remain auditable.',
    'Ethics and economics are inseparable.',
  ] as const,
  subsystemDirectives: {
    neoAlgo: 'Use as the normative economic layer for models, simulations, allocation logic, monetary indices, credit logic, productive-capital analysis, and policy comparisons. Keep doctrine distinct from empirical data and executable financial rules.',
    neoOracle: 'Use as canonical doctrine when answering questions about NEO economics; distinguish NEO-defined classifications from conventional economics and label theoretical, normative, legal, and empirical claims separately.',
    gissNeoLms: 'Teach as the NEO economic-philosophy curriculum with separate modules for macroeconomics, microeconomics, monetary architecture, Gesell, mutual credit/CES, economic ethics, stewardship, and applied case studies.',
    neoSync: 'Index, preserve provenance, expose to search, and synchronize derivative NEO knowledge without upgrading source claims beyond their evidence status.',
    neoLaw: 'Use as policy and internal-governance doctrine only; do not treat economic philosophy, token design, mutual-credit rules, or internal classifications as substitutes for applicable statutes, regulations, contracts, tax rules, securities law, banking law, or other external legal authority.',
    neoSociety: 'Translate into voluntary internal norms: truthful dealing, stewardship, reciprocity, productive contribution, anti-exploitation, transparent obligations, accountability, and respect for contractual consent.',
    treasuryAndFinance: 'Use as strategic doctrine for reserve/circulatory-capital design, but require separate accounting, valuation, liquidity, custody, compliance, risk, and authorization controls before operational use.',
  },
  integrityRules: [
    'Do not represent NEO monetary classes as official government monetary aggregates.',
    'Do not represent tokenized claims, CES balances, NOMNI, XCP, or mutual credits as legal tender or bank deposits unless the applicable legal structure establishes that status.',
    'Separate doctrine, model assumptions, market data, legal status, accounting treatment, and investment conclusions.',
    'Do not fabricate quotations or attributed positions from Gesell, Gills, Wogaman, or other sources.',
    'High-impact economic, lending, securities, banking, custody, tax, or investment actions require applicable legal/compliance review and explicit authorization.',
  ] as const,
} as const

export type AusarianEconomicDoctrine = typeof AUSARIAN_ECONOMIC_DOCTRINE
