import type { ProvenanceGraph, ProvenanceEdge, ProvenanceRelation } from './provenanceGraph'
import type { TitleAuditReport } from './titleAuditor'

export type ClaimantType = 'PERSON'|'TRUST'|'ESTATE'|'ORGANIZATION'|'ISSUER'|'CUSTODIAN'|'BENEFICIARY'|'SUCCESSOR'|'WALLET'|'OFFICE'|'INSTITUTION'|'OTHER'
export type InterestType = 'LEGAL_TITLE'|'BENEFICIAL_INTEREST'|'CUSTODY'|'CONTROL'|'POSSESSION'|'ISSUANCE'|'SUCCESSION'|'ECONOMIC_BENEFIT'|'CLAIM_ONLY'|'UNKNOWN'
export type InterestStatus = 'DOCUMENTED'|'PARTIALLY_DOCUMENTED'|'ASSERTED'|'CONTESTED'|'UNRESOLVED'
export type ClaimantInput={id:string;label:string;type:ClaimantType;identifiers?:Record<string,string>;assertedInterests?:InterestType[];assertedNodeId?:string;notes?:string[]}
export type ClaimantInterest={claimantId:string;claimantLabel:string;nodeId?:string;interests:InterestType[];status:InterestStatus;supportingEdgeIds:string[];sourceRecordIds:string[];sourceHitIds:string[];confidence:number;notes:string[]}
export type InterestOverlap={id:string;claimantIds:string[];interestTypes:InterestType[];relation:'COMPATIBLE'|'COMPETING'|'NESTED'|'UNKNOWN';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';relatedEdgeIds:string[];description:string}
export type ClaimantResolutionReport={subjectAuditId?:string;claimants:ClaimantInterest[];overlaps:InterestOverlap[];unresolvedClaimantIds:string[];competingClaimantIds:string[];followUpEvidenceRequests:string[];generatedAt:string;boundary:string}
const uniq=<T>(v:T[])=>[...new Set(v)]
const norm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
function relationToInterest(r:ProvenanceRelation,d:'FROM'|'TO'):InterestType[]{switch(r){case'HELD_BY':return d==='TO'?['CUSTODY','POSSESSION']:['CLAIM_ONLY'];case'CONTROLLED_BY':return d==='TO'?['CONTROL']:['CLAIM_ONLY'];case'BENEFITS':return d==='TO'?['ECONOMIC_BENEFIT','BENEFICIAL_INTEREST']:['CLAIM_ONLY'];case'ISSUED_BY':return d==='TO'?['ISSUANCE']:['CLAIM_ONLY'];case'SUCCESSOR_OF':return d==='FROM'?['SUCCESSION']:['CLAIM_ONLY'];case'ASSIGNED_TO':case'TRANSFERRED_TO':return d==='TO'?['LEGAL_TITLE']:['CLAIM_ONLY'];case'ORIGINATED_BY':case'AUTHORED_BY':return['CLAIM_ONLY'];default:return['UNKNOWN']}}
function resolveNode(g:ProvenanceGraph,c:ClaimantInput){if(c.assertedNodeId)return g.nodes.find(n=>n.id===c.assertedNodeId);const ids=Object.entries(c.identifiers??{}),byId=g.nodes.find(n=>ids.some(([k,v])=>n.identifiers[k]?.toLowerCase()===v.toLowerCase()));if(byId)return byId;const label=c.label.toLowerCase();return g.nodes.find(n=>n.label.toLowerCase()===label||n.aliases.some(a=>a.toLowerCase()===label))??g.nodes.find(n=>n.label.toLowerCase().includes(label)||label.includes(n.label.toLowerCase()))}
function interestFromEdges(g:ProvenanceGraph,id:string){const edges=g.edges.filter(e=>e.from===id||e.to===id),interests:InterestType[]=[];for(const e of edges){if(e.from===id)interests.push(...relationToInterest(e.relation,'FROM'));if(e.to===id)interests.push(...relationToInterest(e.relation,'TO'))}return{edges,interests:uniq(interests.filter(i=>i!=='UNKNOWN'))}}
function statusFromEdges(edges:ProvenanceEdge[],asserted:boolean):InterestStatus{if(!edges.length)return asserted?'ASSERTED':'UNRESOLVED';if(edges.some(e=>e.status==='CONTESTED'||e.status==='UNRESOLVED'))return'CONTESTED';if(edges.every(e=>e.status==='DOCUMENTED'))return'DOCUMENTED';if(edges.some(e=>e.status==='ASSERTED'||e.status==='INFERRED'))return'PARTIALLY_DOCUMENTED';return'UNRESOLVED'}
export function resolveClaimantInterests(graph:ProvenanceGraph,inputs:ClaimantInput[],audit?:TitleAuditReport,generatedAt=new Date()):ClaimantResolutionReport{const claimants:ClaimantInterest[]=inputs.map(c=>{const node=resolveNode(graph,c),x=node?interestFromEdges(graph,node.id):{edges:[] as ProvenanceEdge[],interests:[] as InterestType[]},s=statusFromEdges(x.edges,Boolean(c.assertedInterests?.length));return{claimantId:c.id,claimantLabel:c.label,nodeId:node?.id,interests:uniq([...(c.assertedInterests??[]),...x.interests]),status:s,supportingEdgeIds:x.edges.map(e=>e.id),sourceRecordIds:uniq(x.edges.flatMap(e=>e.sourceRecordIds)),sourceHitIds:uniq(x.edges.flatMap(e=>e.sourceHitIds)),confidence:!node?0.2:s==='DOCUMENTED'?0.9:s==='PARTIALLY_DOCUMENTED'?0.7:s==='CONTESTED'?0.45:s==='ASSERTED'?0.35:0.25,notes:c.notes??[]}});const overlaps:InterestOverlap[]=[];for(let i=0;i<claimants.length;i++)for(let j=i+1;j<claimants.length;j++){const a=claimants[i],b=claimants[j],shared=uniq(a.interests.filter(x=>b.interests.includes(x))),comp=shared.some(x=>['LEGAL_TITLE','BENEFICIAL_INTEREST','CONTROL','CUSTODY','SUCCESSION'].includes(x));if(!shared.length&&!a.interests.length&&!b.interests.length)continue;overlaps.push({id:`OVERLAP-${norm(`${a.claimantId}-${b.claimantId}`)}`,claimantIds:[a.claimantId,b.claimantId],interestTypes:shared,relation:comp?'COMPETING':shared.length?'NESTED':'COMPATIBLE',severity:comp?(shared.includes('LEGAL_TITLE')||shared.includes('BENEFICIAL_INTEREST')?'CRITICAL':'HIGH'):shared.length?'MEDIUM':'LOW',relatedEdgeIds:uniq([...a.supportingEdgeIds,...b.supportingEdgeIds]),description:comp?`${a.claimantLabel} and ${b.claimantLabel} have overlapping interests requiring governing-instrument review.`:`${a.claimantLabel} and ${b.claimantLabel} do not presently show a same-class priority conflict.`})}return{subjectAuditId:audit?.auditId,claimants,overlaps,unresolvedClaimantIds:claimants.filter(c=>!c.nodeId||c.status==='UNRESOLVED').map(c=>c.claimantId),competingClaimantIds:uniq(overlaps.filter(o=>o.relation==='COMPETING').flatMap(o=>o.claimantIds)),followUpEvidenceRequests:uniq([...claimants.filter(c=>!c.nodeId).map(c=>`Resolve ${c.claimantLabel} to a stable identifier or canonical graph node.`),...claimants.filter(c=>c.status==='ASSERTED'||c.status==='PARTIALLY_DOCUMENTED').map(c=>`Obtain primary instruments establishing ${c.claimantLabel}'s asserted interest.`),...overlaps.filter(o=>o.relation==='COMPETING').map(o=>`Obtain governing instruments, chronology, capacity and jurisdiction for ${o.claimantIds.join(' vs ')}.`),...(audit?.defects??[]).flatMap(d=>d.evidenceNeeded.map(n=>`Title-audit follow-up: ${n}`))]),generatedAt:generatedAt.toISOString(),boundary:'This resolver classifies evidentiary interests and conflicts. It does not adjudicate beneficial ownership, probate rights, fiduciary rights, wallet ownership, corporate authority, priority, or legal title.'}}
export const neoClaimantInterestResolver={id:'NEO-CLAIMANT-INTEREST-RESOLVER',title:'NEO Claimant & Beneficial-Interest Resolver',role:'MULTI_CLAIMANT_INTEREST_OVERLAP_CONFLICT_AND_CAPACITY_ANALYSIS',principles:['Legal title, beneficial interest, custody, control, possession, issuance and economic benefit are distinct.','Authorship or origination is provenance evidence, not automatic legal title.','A wallet address or filing record is not automatically a beneficial owner.','Competing claims remain visible until governing instruments or authoritative determinations resolve them.','Stable identifiers and dated instruments outrank name similarity.','The resolver identifies intersections and gaps; it does not manufacture priority.'] as const} as const
