import type { ProvenanceGraph, ProvenanceEdge, ProvenanceRelation } from './provenanceGraph'
import type { TitleAuditReport } from './titleAuditor'

export type ClaimantType='PERSON'|'TRUST'|'ESTATE'|'ORGANIZATION'|'ISSUER'|'CUSTODIAN'|'BENEFICIARY'|'SUCCESSOR'|'WALLET'|'OFFICE'|'INSTITUTION'|'OTHER'
export type InterestType='LEGAL_TITLE'|'BENEFICIAL_INTEREST'|'CUSTODY'|'CONTROL'|'POSSESSION'|'ISSUANCE'|'SUCCESSION'|'ECONOMIC_BENEFIT'|'CLAIM_ONLY'|'UNKNOWN'
export type InterestStatus='DOCUMENTED'|'PARTIALLY_DOCUMENTED'|'ASSERTED'|'CONTESTED'|'UNRESOLVED'
export type ClaimantInput={id:string;label:string;type:ClaimantType;identifiers?:Record<string,string>;assertedInterests?:InterestType[];assertedNodeId?:string;notes?:string[]}
export type ClaimantInterest={claimantId:string;claimantLabel:string;nodeId?:string;interests:InterestType[];status:InterestStatus;supportingEdgeIds:string[];sourceRecordIds:string[];sourceHitIds:string[];confidence:number;notes:string[]}
export type InterestOverlap={id:string;claimantIds:string[];interestTypes:InterestType[];relation:'COMPATIBLE'|'COMPETING'|'NESTED'|'UNKNOWN';severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';relatedEdgeIds:string[];description:string}
export type ClaimantResolutionReport={subjectAuditId?:string;claimants:ClaimantInterest[];overlaps:InterestOverlap[];unresolvedClaimantIds:string[];competingClaimantIds:string[];followUpEvidenceRequests:string[];generatedAt:string;boundary:string}
const uniq=<T>(v:T[])=>[...new Set(v)]
const norm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
function relationToInterest(r:ProvenanceRelation,d:'FROM'|'TO'):InterestType[]{switch(r){case'HELD_BY':return d==='TO'?['CUSTODY','POSSESSION']:['CLAIM_ONLY'];case'CONTROLLED_BY':return d==='TO'?['CONTROL']:['CLAIM_ONLY'];case'BENEFITS':return d==='TO'?['ECONOMIC_BENEFIT','BENEFICIAL_INTEREST']:['CLAIM_ONLY'];case'ISSUED_BY':return d==='TO'?['ISSUANCE']:['CLAIM_ONLY'];case'SUCCESSOR_OF':return d==='FROM'?['SUCCESSION']:['CLAIM_ONLY'];case'ASSIGNED_TO':case'TRANSFERRED_TO':return d==='TO'?['LEGAL_TITLE']:['CLAIM_ONLY'];default:return['UNKNOWN']}}
function resolveNode(g:ProvenanceGraph,c:ClaimantInput){if(c.assertedNodeId)return g.nodes.find(n=>n.id===c.assertedNodeId);const ids=Object.entries(c.identifiers??{});return g.nodes.find(n=>ids.some(([k,v])=>n.identifiers[k]?.toLowerCase()===v.toLowerCase()))??g.nodes.find(n=>n.label.toLowerCase()===c.label.toLowerCase()||n.aliases.some(a=>a.toLowerCase()===c.label.toLowerCase()))}
function status(edges:ProvenanceEdge[],asserted:boolean):InterestStatus{if(!edges.length)return asserted?'ASSERTED':'UNRESOLVED';if(edges.some(e=>e.status==='CONTESTED'||e.status==='UNRESOLVED'))return'CONTESTED';if(edges.every(e=>e.status==='DOCUMENTED'))return'DOCUMENTED';return'PARTIALLY_DOCUMENTED'}
export function resolveClaimantInterests(graph:ProvenanceGraph,inputs:ClaimantInput[],audit?:TitleAuditReport,generatedAt=new Date()):ClaimantResolutionReport{const claimants=inputs.map(c=>{const node=resolveNode(graph,c);const edges=node?graph.edges.filter(e=>e.from===node.id||e.to===node.id):[];const inferred=uniq(edges.flatMap(e=>[...(e.from===node?.id?relationToInterest(e.relation,'FROM'):[]),...(e.to===node?.id?relationToInterest(e.relation,'TO'):[])])).filter(i=>i!=='UNKNOWN');const s=status(edges,!!c.assertedInterests?.length);return{claimantId:c.id,claimantLabel:c.label,nodeId:node?.id,interests:uniq([...(c.assertedInterests??[]),...inferred]),status:s,supportingEdgeIds:edges.map(e=>e.id),sourceRecordIds:uniq(edges.flatMap(e=>e.sourceRecordIds)),sourceHitIds:uniq(edges.flatMap(e=>e.sourceHitIds)),confidence:!node?.id?.length?.0?0.2:s==='DOCUMENTED'?0.9:s==='PARTIALLY_DOCUMENTED'?0.7:s==='CONTESTED'?0.45:s==='ASSERTED'?0.35:0.25,notes:c.notes??[]} as ClaimantInterest});const overlaps:InterestOverlap[]=[];for(let i=0;i<claimants.length;i++)for(let j=i+1;j<claimants.length;j++){const a=claimants[i],b=claimants[j],shared=a.interests.filter(x=>b.interests.includes(x)),comp=shared.some(x=>['LEGAL_TITLE','BENEFICIAL_INTEREST','CONTROL','CUSTODY','SUCCESSION'].includes(x));overlaps.push({id:`OVERLAP-${norm(a.claimantId+'-'+b.claimantId)}`,claimantIds:[a.claimantId,b.claimantId],interestTypes:shared,relation:comp?'COMPETING':shared.length?'NESTED':'COMPATIBLE',severity:comp?(shared.some(x=>x==='LEGAL_TITLE'||x==='BENEFICIAL_INTEREST')?'CRITICAL':'HIGH'):shared.length?'MEDIUM':'LOW',relatedEdgeIds:uniq([...a.supportingEdgeIds,...b.supportingEdgeIds]),description:comp?'Potentially competing interests require governing-instrument and chronology review.':'No unresolved same-class priority is inferred from this comparison.'})}const unresolved=claimants.filter(c=>!c.nodeId||c.status==='UNRESOLVED').map(c=>c.claimantId),competing=uniq(overlaps.filter(o=>o.relation==='COMPETING').flatMap(o=>o.claimantIds));return{subjectAuditId:audit?.auditId,claimants,overlaps,unresolvedClaimantIds:unresolved,competingClaimantIds:competing,followUpEvidenceRequests:uniq([...claimants.filter(c=>!c.nodeId).map(c=>`Resolve ${c.claimantLabel} to a stable identifier.`),...overlaps.filter(o=>o.relation==='COMPETING').map(o=>`Obtain governing instruments, chronology, capacity evidence and jurisdiction for ${o.claimantIds.join(' vs ')}.`),...(audit?.defects??[]).flatMap(d=>d.evidenceNeeded)]),generatedAt:generatedAt.toISOString(),boundary:'Evidentiary classification only; this resolver does not adjudicate ownership, priority, probate, fiduciary rights, wallet ownership, or legal title.'}}
