import { neoDoctrineRegistry, type NeoDoctrineRecord } from './doctrineRegistry'
import { neoMaxims, type NeoMaxim } from './maxims'
import { noologicalDisciplines, type NoologicalDiscipline } from './disciplines'
import { sacredRecordsOfTheMoors, type SacredRecordOfMoorsEntry } from './sacredRecordsMoors'
import { sacredRecordsGraphNodes, sacredGraphNeighbors, type SacredGraphNode } from './sacredRecordsKnowledgeGraph'
import { templistTeachings, type TemplistTeaching } from './templistDoctrine'
import { nooneProject, type NooneProjectNode } from './nooneProjectRoot'
import { secretSocietiesUnmaskedSourceRecords } from './counterInfluenceIntelligence'
import { ecclesiasticalAuthorities, inheritanceClaims, inheritanceSources, sacredCorpus } from './globalInheritanceTitleSchema'

export type NoogleNoologicalResultKind = 'PROJECT_ROOT'|'COUNTER_INFLUENCE'|'DISCIPLINE'|'DOCTRINE'|'MAXIM'|'SOURCE_RECORD'|'KNOWLEDGE_GRAPH'|'TITLE_INHERITANCE'|'TEMPLIST'
export type NoogleNoologicalResult = { id:string; kind:NoogleNoologicalResultKind; title:string; summary:string; score:number; provenance:string; tags:string[]; sourceRefs:string[]; graph?:{nodeType:string;neighborCount:number;relatedNodeIds:string[];sensitiveClassification?:boolean} }
export type NoogleNoologicalQuery = { text:string; limit?:number; preferredDomains?:string[]; includeSourceDerived?:boolean; includeNeoSynthesis?:boolean }
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9\-\s]/g,' ')
const termsFor=(query:string)=>[...new Set(normalize(query).split(/\s+/).filter(Boolean))]
function scoreText(q:string[],title:string,body:string,tags:string[]){if(!q.length)return 1;const t=normalize(title),b=normalize(body),tagText=normalize(tags.join(' '));return q.reduce((s,x)=>{if(t===x)s+=12;if(t.includes(x))s+=7;if(tagText.includes(x))s+=4;if(b.includes(x))s+=2;return s},0)}
function projectRootResult(item:NooneProjectNode,terms:string[]):NoogleNoologicalResult{const body=`${item.role} ${item.children?.join(' ')??''}`;return{id:item.id,kind:'PROJECT_ROOT',title:item.title,summary:item.role,score:scoreText(terms,item.title,body,item.tags)+8,provenance:'FOUNDATIONAL_MASTER_BLUEPRINT',tags:['noone-project','project-of-projects',item.domain.toLowerCase(),...item.tags],sourceRefs:item.sourcePages.map(p=>`Noone Society Presents the Noone Project — p.${p}`),graph:{nodeType:item.domain,neighborCount:item.children?.length??0,relatedNodeIds:item.children??[]}}}
function influenceResult(item:(typeof secretSocietiesUnmaskedSourceRecords)[number],terms:string[]):NoogleNoologicalResult{return{id:item.id,kind:'COUNTER_INFLUENCE',title:item.title,summary:item.summary,score:scoreText(terms,item.title,item.summary,[...item.tags])+7,provenance:'SOURCE_DERIVED',tags:['counter-influence','special-interest',...item.tags],sourceRefs:[...item.sourceRefs]}}
function disciplineResult(item:NoologicalDiscipline,terms:string[]):NoogleNoologicalResult{const tags=[...item.domains,...item.related.map(x=>x.toLowerCase())];const body=`${item.definition} ${item.functionInNeoSystem} ${item.questions.join(' ')}`;return{id:item.id,kind:'DISCIPLINE',title:item.name,summary:item.definition,score:scoreText(terms,item.name,body,tags)+3,provenance:item.provenanceClass,tags,sourceRefs:item.sourceRefs??[]}}
function doctrineResult(item:NeoDoctrineRecord,terms:string[]):NoogleNoologicalResult{const body=`${item.teaching} ${item.operationalization}`;return{id:item.id,kind:'DOCTRINE',title:item.title,summary:item.teaching,score:scoreText(terms,item.title,body,item.tags)+2,provenance:item.evidenceClass,tags:item.tags,sourceRefs:item.source?[`${item.source.title}${item.source.pageOrSection?` — ${item.source.pageOrSection}`:''}`]:[]}}
function maximResult(item:NeoMaxim,terms:string[]):NoogleNoologicalResult{const tags=[item.domain];return{id:item.id,kind:'MAXIM',title:item.title,summary:item.statement,score:scoreText(terms,item.title,`${item.statement} ${item.operationalMeaning}`,tags)+1,provenance:'NEO_MAXIM',tags,sourceRefs:[]}}
function sacredRecordResult(item:SacredRecordOfMoorsEntry,terms:string[]):NoogleNoologicalResult{const body=`${item.summary} ${item.sourceClaims.join(' ')} ${item.controls.join(' ')}`;const sourceRef=`${item.source.title} — PDF p.${item.source.pdfPage}${item.source.printedPage?` / printed p.${item.source.printedPage}`:''}${item.source.section?` — ${item.source.section}`:''}`;return{id:item.id,kind:'SOURCE_RECORD',title:item.title,summary:item.summary,score:scoreText(terms,item.title,body,item.tags)+4,provenance:item.evidenceClass,tags:item.tags,sourceRefs:[sourceRef]}}
function graphResult(item:SacredGraphNode,terms:string[]):NoogleNoologicalResult{const neighbors=sacredGraphNeighbors(item.id);const body=`${(item.aliases??[]).join(' ')} ${item.summary} ${neighbors.map(({edge,node})=>`${edge.relation} ${node.name}`).join(' ')}`;return{id:item.id,kind:'KNOWLEDGE_GRAPH',title:item.name,summary:item.summary,score:scoreText(terms,item.name,body,item.tags)+5,provenance:'SOURCE_GRAPH',tags:[item.type.toLowerCase(),...item.tags],sourceRefs:item.sourcePages.map(p=>`Let's Set The Record Straight! — PDF p.${p}`),graph:{nodeType:item.type,neighborCount:neighbors.length,relatedNodeIds:neighbors.slice(0,12).map(({node})=>node.id),sensitiveClassification:item.sensitiveClassification}}}
function templistResult(item:TemplistTeaching,terms:string[]):NoogleNoologicalResult{return{id:item.id,kind:'TEMPLIST',title:`Templist ${item.number}: ${item.title}`,summary:item.teaching,score:scoreText(terms,item.title,`${item.teaching} ${item.operationalization}`,item.tags)+6,provenance:item.evidenceClass,tags:['templist',`19x${item.number}`,String(item.multiplier),...item.tags],sourceRefs:[`The Templist Scroll — p.${item.sourcePage}`]}}
function inheritanceResults(terms:string[]):NoogleNoologicalResult[]{const sourceResults=inheritanceSources.map(source=>({id:source.id,kind:'TITLE_INHERITANCE' as const,title:source.title,summary:source.sourceStatement??source.title,score:scoreText(terms,source.title,`${source.sourceStatement??''} ${(source.notes??[]).join(' ')}`,['title','inheritance','provenance','ecclesiastical'])+6,provenance:source.status,tags:['title','inheritance','provenance',source.kind.toLowerCase()],sourceRefs:source.citation?[source.citation]:[]}));const authorityResults=ecclesiasticalAuthorities.map(authority=>({id:authority.id,kind:'TITLE_INHERITANCE' as const,title:authority.name,summary:`${authority.jurisdictionClaim} ${authority.powersDeclared.join(' ')}`,score:scoreText(terms,authority.name,`${authority.aliases.join(' ')} ${authority.jurisdictionClaim} ${authority.powersDeclared.join(' ')}`,['temple','ecclesiastical','divan','authority'])+6,provenance:authority.status,tags:['temple','ecclesiastical','authority',...authority.aliases.map(normalize)],sourceRefs:authority.sourceRefs}));const corpusResults=sacredCorpus.map(entry=>({id:entry.id,kind:'TITLE_INHERITANCE' as const,title:entry.canonicalName,summary:`${entry.traditionClass} sacred-corpus record classified as ${entry.roleInNeoEcclesiology.toLowerCase()} within the World Temple declaration.`,score:scoreText(terms,entry.canonicalName,`${entry.aliases.join(' ')} ${entry.traditionClass} ${entry.roleInNeoEcclesiology}`,['sacred-corpus','scripture','deed-poll'])+5,provenance:'SOURCE_DECLARED',tags:['sacred-corpus','scripture',entry.traditionClass.toLowerCase(),entry.roleInNeoEcclesiology.toLowerCase()],sourceRefs:entry.sourceRefs}));const claimResults=inheritanceClaims.map(claim=>({id:claim.id,kind:'TITLE_INHERITANCE' as const,title:`Global Indigenous Inheritance Claim ${claim.id}`,summary:`${claim.titleBasis.join('; ')}. Probate status: ${claim.probateStatus}. Remedies: ${claim.remediesRequested.join(', ')}.`,score:scoreText(terms,claim.id,`${claim.titleBasis.join(' ')} ${claim.defectTheory.join(' ')} ${claim.remediesRequested.join(' ')}`,['probate','restitution','intellectual-property','title-search','world-credit-clock'])+7,provenance:claim.evidenceStatus,tags:['probate','restitution','intellectual-property','title-search','world-credit-clock'],sourceRefs:claim.sourceRefs}));return[...sourceResults,...authorityResults,...corpusResults,...claimResults]}
export function searchNoogleNoology(query:NoogleNoologicalQuery):NoogleNoologicalResult[]{const terms=termsFor(query.text);const preferred=new Set((query.preferredDomains??[]).map(normalize));let results:NoogleNoologicalResult[]=[...nooneProject.nodes.map(i=>projectRootResult(i,terms)),...secretSocietiesUnmaskedSourceRecords.map(i=>influenceResult(i,terms)),...inheritanceResults(terms),...templistTeachings.map(i=>templistResult(i,terms)),...sacredRecordsGraphNodes.map(i=>graphResult(i,terms)),...noologicalDisciplines.map(i=>disciplineResult(i,terms)),...neoDoctrineRegistry.map(i=>doctrineResult(i,terms)),...sacredRecordsOfTheMoors.map(i=>sacredRecordResult(i,terms)),...neoMaxims.map(i=>maximResult(i,terms))];if(query.includeSourceDerived===false)results=results.filter(i=>i.provenance!=='SOURCE_DERIVED'&&!i.provenance.startsWith('SOURCE_'));if(query.includeNeoSynthesis===false)results=results.filter(i=>!i.provenance.includes('SYNTHESIS'));results=results.map(r=>({...r,score:r.score+r.tags.reduce((b,t)=>b+(preferred.has(normalize(t))?3:0),0)}));return results.filter(i=>terms.length===0||i.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,Math.max(1,query.limit??12))}
export type NoogleNoologicalPanel={query:string;topResult?:NoogleNoologicalResult;projectRoot:NoogleNoologicalResult[];counterInfluence:NoogleNoologicalResult[];inheritanceRecords:NoogleNoologicalResult[];templist:NoogleNoologicalResult[];graphNodes:NoogleNoologicalResult[];relatedDisciplines:NoogleNoologicalResult[];doctrine:NoogleNoologicalResult[];sacredRecords:NoogleNoologicalResult[];maxims:NoogleNoologicalResult[];provenanceClasses:string[]}
export function buildNoogleNoologicalPanel(text:string):NoogleNoologicalPanel{const results=searchNoogleNoology({text,limit:120});return{query:text,topResult:results[0],projectRoot:results.filter(i=>i.kind==='PROJECT_ROOT').slice(0,20),counterInfluence:results.filter(i=>i.kind==='COUNTER_INFLUENCE').slice(0,12),inheritanceRecords:results.filter(i=>i.kind==='TITLE_INHERITANCE').slice(0,14),templist:results.filter(i=>i.kind==='TEMPLIST').slice(0,19),graphNodes:results.filter(i=>i.kind==='KNOWLEDGE_GRAPH').slice(0,12),relatedDisciplines:results.filter(i=>i.kind==='DISCIPLINE').slice(0,6),doctrine:results.filter(i=>i.kind==='DOCTRINE').slice(0,8),sacredRecords:results.filter(i=>i.kind==='SOURCE_RECORD').slice(0,8),maxims:results.filter(i=>i.kind==='MAXIM').slice(0,6),provenanceClasses:[...new Set(results.map(i=>i.provenance))]}}
