import type { ClaimantResolutionReport, ClaimantInterest, InterestType } from './claimantInterestResolver'
import type { TitleAuditReport } from './titleAuditor'
import type { ProvenanceGraph } from './provenanceGraph'

export type PriorityFactor='DOCUMENTARY_STATUS'|'CHRONOLOGY'|'INSTRUMENT_RELATION'|'CAPACITY_AUTHORITY'|'PROVENANCE_CONTINUITY'|'CONFLICT_LOAD'|'TITLE_DEFECT_LOAD'
export type PriorityBand='STRONGER_DOCUMENTARY_POSITION'|'MIXED_DOCUMENTARY_POSITION'|'WEAKER_DOCUMENTARY_POSITION'|'UNRESOLVED'
export type PriorityFinding={claimantId:string;claimantLabel:string;interest:InterestType;score:number;band:PriorityBand;factors:Record<PriorityFactor,number>;supportingEdgeIds:string[];sourceRecordIds:string[];warnings:string[]}
export type PairwisePriority={claimantIds:[string,string];interest:InterestType;result:'AHEAD_ON_DOCUMENTARY_RECORD'|'BEHIND_ON_DOCUMENTARY_RECORD'|'SUBSTANTIALLY_TIED'|'NOT_COMPARABLE';delta:number;reason:string}
export type PriorityReport={subjectAuditId?:string;findings:PriorityFinding[];comparisons:PairwisePriority[];unresolvedQuestions:string[];generatedAt:string;boundary:string}
const uniq=<T>(v:T[])=>[...new Set(v)]
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))
function statusScore(c:ClaimantInterest){return c.status==='DOCUMENTED'?95:c.status==='PARTIALLY_DOCUMENTED'?72:c.status==='CONTESTED'?42:c.status==='ASSERTED'?32:18}
function chronologyScore(graph:ProvenanceGraph,c:ClaimantInterest){const dates=c.supportingEdgeIds.map(id=>graph.edges.find(e=>e.id===id)?.date).filter(Boolean) as string[];return dates.length?75:35}
function continuityScore(graph:ProvenanceGraph,c:ClaimantInterest){const edges=c.supportingEdgeIds.map(id=>graph.edges.find(e=>e.id===id)).filter(Boolean);if(!edges.length)return 20;const documented=edges.filter(e=>e?.status==='DOCUMENTED').length;return Math.round(100*documented/edges.length)}
function conflictLoad(report:ClaimantResolutionReport,id:string){return report.overlaps.filter(o=>o.claimantIds.includes(id)&&o.relation==='COMPETING').reduce((n,o)=>n+(o.severity==='CRITICAL'?30:o.severity==='HIGH'?20:10),0)}
function defects(audit:TitleAuditReport|undefined){return audit?.defects.reduce((n,d)=>n+(d.severity==='CRITICAL'?25:d.severity==='HIGH'?15:d.severity==='MEDIUM'?8:3),0)??0}
function capacityScore(c:ClaimantInterest){return c.interests.some(i=>['LEGAL_TITLE','SUCCESSION','CUSTODY','CONTROL'].includes(i))?(c.status==='DOCUMENTED'?80:45):60}
function instrumentScore(c:ClaimantInterest,interest:InterestType){if(!c.interests.includes(interest))return 0;if(interest==='CLAIM_ONLY')return 20;if(['LEGAL_TITLE','BENEFICIAL_INTEREST','SUCCESSION'].includes(interest))return c.status==='DOCUMENTED'?90:55;return c.status==='DOCUMENTED'?75:50}
function band(score:number):PriorityBand{return score>=78?'STRONGER_DOCUMENTARY_POSITION':score>=55?'MIXED_DOCUMENTARY_POSITION':score>=30?'WEAKER_DOCUMENTARY_POSITION':'UNRESOLVED'}
export function evaluatePriorityOfInterest(graph:ProvenanceGraph,resolution:ClaimantResolutionReport,audit?:TitleAuditReport,generatedAt=new Date()):PriorityReport{const interests=uniq(resolution.claimants.flatMap(c=>c.interests).filter(i=>i!=='UNKNOWN'));const findings:PriorityFinding[]=[];for(const c of resolution.claimants)for(const interest of interests.filter(i=>c.interests.includes(i))){const factors:Record<PriorityFactor,number>={DOCUMENTARY_STATUS:statusScore(c),CHRONOLOGY:chronologyScore(graph,c),INSTRUMENT_RELATION:instrumentScore(c,interest),CAPACITY_AUTHORITY:capacityScore(c),PROVENANCE_CONTINUITY:continuityScore(graph,c),CONFLICT_LOAD:Math.max(0,100-conflictLoad(resolution,c.claimantId)),TITLE_DEFECT_LOAD:Math.max(0,100-defects(audit))};const score=clamp(factors.DOCUMENTARY_STATUS*.25+factors.CHRONOLOGY*.1+factors.INSTRUMENT_RELATION*.2+factors.CAPACITY_AUTHORITY*.1+factors.PROVENANCE_CONTINUITY*.2+factors.CONFLICT_LOAD*.1+factors.TITLE_DEFECT_LOAD*.05);const warnings:string[]=[];if(c.status!=='DOCUMENTED')warnings.push('Interest is not fully documented.');if(resolution.competingClaimantIds.includes(c.claimantId))warnings.push('Competing claimant overlap remains unresolved.');if(audit?.defects.length)warnings.push('Underlying title audit contains unresolved defects.');findings.push({claimantId:c.claimantId,claimantLabel:c.claimantLabel,interest,score,band:band(score),factors,supportingEdgeIds:c.supportingEdgeIds,sourceRecordIds:c.sourceRecordIds,warnings})}const comparisons:PairwisePriority[]=[];for(const interest of interests){const rows=findings.filter(f=>f.interest===interest);for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i],b=rows[j],delta=a.score-b.score;comparisons.push({claimantIds:[a.claimantId,b.claimantId],interest,result:Math.abs(delta)<8?'SUBSTANTIALLY_TIED':delta>0?'AHEAD_ON_DOCUMENTARY_RECORD':'BEHIND_ON_DOCUMENTARY_RECORD',delta:Math.abs(delta),reason:'Comparison reflects evidence quality and graph position only; governing-law priority rules are not inferred.'})}}return{subjectAuditId:audit?.auditId,findings,comparisons,unresolvedQuestions:uniq([...resolution.followUpEvidenceRequests,...(audit?.unresolvedQuestions??[]),'Which governing law and jurisdiction control priority for the specific interest?','Which operative instrument supplies any priority, perfection, notice, recording, probate, trust, or succession rule?']),generatedAt:generatedAt.toISOString(),boundary:'This engine ranks documentary positions for review. It does not adjudicate legal priority, ownership, lien perfection, probate rights, trust rights, sovereign authority, or entitlement. Governing law and competent legal determination control those questions.'}}
export const neoPriorityInterestEngine={id:'NEO-PRIORITY-OF-INTEREST',title:'NEO Priority-of-Interest Engine',sequence:['LOAD_TITLE_AUDIT','LOAD_CLAIMANT_RESOLUTION','SEPARATE_INTEREST_CLASSES','SCORE_DOCUMENTARY_STATUS','SCORE_CHRONOLOGY','SCORE_INSTRUMENT_RELATION','SCORE_CAPACITY','SCORE_PROVENANCE_CONTINUITY','APPLY_CONFLICT_AND_DEFECT_LOAD','GENERATE_PAIRWISE_MATRIX','QUEUE_GOVERNING_LAW_REVIEW'] as const,principles:['Priority is interest-specific, not person-specific.','Earlier evidence is not automatically legally superior.','Custody, control, possession and issuance are not silently converted into title.','Missing governing-law rules remain unresolved.','Scores describe documentary position, not adjudicated legal entitlement.'] as const} as const
