apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orange-esop
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      serviceAccountName: neo-system-runtime
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT_ID/neo-system/orange-esop:latest
          env:
            - name: ORANGE_ESOP_STORE
              value: firestore
          ports:
            - containerPort: 8080
