import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { once } from 'node:events';
import { createNeoPlatformApi, PLATFORM_REGISTRY } from './server.mjs';
import { createIntegrationHub, IntegrationHubError, createNeopassSubjectResolver } from './integration-hub.mjs';
import { createComposioProviderAdapter } from './provider-adapter.mjs';
import { createCommandRouter } from './command-router.mjs';
import { APPLICATION_REGISTRY, createControlPlane } from './control-plane.mjs';
import { TEMPLE_APPLICATION_ID, createTempleAdapter } from './temple-adapter.mjs';
import { createGoogleNeopassAuth } from './neopass-google-auth.mjs';

Date.now = () => Date.parse('2026-09-10T01:00:00.000Z');

const marketData={async snapshot({assets}={}){return{service:'neo-prime-market-data',apiVersion:'v1',status:'ok',generatedAt:'2026-08-25T00:00:00.000Z',bitcoin:{symbol:'BTC',priceUsd:112000,blockHeight:910144,status:'ok',errors:[]},counterparty:Object.fromEntries((assets||['XCP','NOMNI']).map(symbol=>[symbol,{symbol,status:'ok'}]))}},async asset(symbol){return{symbol:String(symbol).toUpperCase(),status:'ok',supply:900000000}}};
async function withServer(fn, options={}){const server=createNeoPlatformApi({now:()=> '2026-08-25T00:00:00.000Z',marketData,subjectResolver:req=>String(req.headers['x-neopass-subject']||'').trim()||null,...options});server.listen(0,'127.0.0.1');await once(server,'listening');const{port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{server.close();await once(server,'close')}}

function fakeComposio(){
	const sessions=[];
	return {
		sessions,
		async createSession(subject){sessions.push({subject,id:`trs_${subject}`});return{session_id:`trs_${subject}`}},
		async listTools(){return{items:[{slug:'GITHUB_LIST_REPOS',name:'GITHUB_LIST_REPOS',toolkit:'github',capability:'development.repositories.list'},{slug:'GITHUB_CREATE_ISSUE',name:'GITHUB_CREATE_ISSUE',toolkit:'github',capability:'development.issues.create'},{slug:'GITHUB_LIST_FILES',name:'GITHUB_LIST_FILES',toolkit:'github',capability:'files.repositories.list'},{slug:'GITHUB_LIST_LIBRARY',name:'GITHUB_LIST_LIBRARY',toolkit:'github',capability:'files.library.list'}]}},
		async execute(sessionId,toolSlug){return{data:{toolSlug,token:'session-secret',nested:{password:'hidden'},status:'ok'},error:null,sessionId}}
	};
}

function authHeaders(subject='subject-a'){return{authorization:'Bearer opaque-neopass-token', 'x-neopass-subject':subject, 'content-type':'application/json'}}
function token({subject,secret,issuer,expiresAt=Math.floor(Date.now()/1000)+300}){const encode=value=>Buffer.from(value).toString('base64url');const header=encode(JSON.stringify({alg:'HS256',typ:'JWT'}));const payload=encode(JSON.stringify({sub:subject,iss:issuer,exp:expiresAt}));return `${header}.${payload}.${createHmac('sha256',secret).update(`${header}.${payload}`).digest('base64url')}`}

test('serves the public Templist portal at the root route',async()=>{await withServer(async base=>{const response=await fetch(`${base}/`);const body=await response.text();assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/^text\/html/);assert.match(body,/<title>Templist Portal/);assert.match(body,/Member Login/);assert.match(response.headers.get('content-security-policy'),/frame-ancestors 'self' https:\/\/holytemples\.org/)})});

test('serves the restored government workspace only to authenticated members',async()=>{const authService={session:async subject=>({subject,displayName:'Executive Admin',role:'executive-admin',neopassStatus:'active'})};const subjectResolver=req=>req.headers.authorization==='Bearer valid'?'google:admin':null;await withServer(async base=>{const denied=await fetch(`${base}/portal/government`,{redirect:'manual'});assert.equal(denied.status,302);const allowed=await fetch(`${base}/portal/government`,{headers:{authorization:'Bearer valid'}});assert.equal(allowed.status,200);const html=await allowed.text();assert.match(html,/Government Administration/);assert.match(html,/Members/);assert.match(html,/Smart Contracts/);assert.match(html,/Write controls locked/)},{authService,subjectResolver})});

test('exposes Google sign-in and directs the verified member to NEO eGAAS',async()=>{const records=new Map();const registry={getNEOpassCredential:async subject=>records.get(subject)||null,async upsert(_collection,record){records.set(record.subject,record);return record}};const authService=createGoogleNeopassAuth({clientId:'client.apps.googleusercontent.com',jwtSecret:'secret',registry,verifyGoogleCredential:async()=>({sub:'google-1',email:'member@example.com',email_verified:true,name:'Temple Member'}),now:()=>Date.parse('2026-09-10T00:00:00.000Z')});await withServer(async base=>{const page=await fetch(`${base}/`).then(r=>r.text());assert.match(page,/g_id_signin/);const script=await fetch(`${base}/portal.js`).then(r=>r.text());assert.match(script,/form\.action='\/auth\/google\/continue'/);const login=await fetch(`${base}/api/v1/auth/google`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential:'verified-google-token'})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert.match(cookie,/neo_pass_session=.*HttpOnly.*Secure.*SameSite=Lax/);const body=await login.json();assert.equal(body.member.neopassStatus,'pending');assert.equal(records.get('google:google-1').provider,'google');const dashboard=await fetch(`${base}/portal`,{headers:{cookie:cookie.split(';')[0]}});const dashboardHtml=await dashboard.text();assert.equal(dashboard.status,200);assert.match(dashboardHtml,/<title>NEO eGAAS Dashboard/);assert.match(dashboardHtml,/Temple Member/);assert.match(dashboardHtml,/Government Administration/);assert.match(dashboardHtml,/href="\/portal\/government"/);assert.match(dashboardHtml,/GISS Dashboard/);assert.match(dashboardHtml,/NEOpay/)},{authService,subjectResolver:createNeopassSubjectResolver({secret:'secret',issuer:'neo-pass'})})});

test('uses a top-level Google continuation to retain the secure session on mobile',async()=>{const records=new Map();const registry={getNEOpassCredential:async subject=>records.get(subject)||null,async upsert(_collection,record){records.set(record.subject,record);return record}};const authService=createGoogleNeopassAuth({clientId:'client.apps.googleusercontent.com',jwtSecret:'secret',registry,verifyGoogleCredential:async()=>({sub:'mobile-1',email:'member@example.com',email_verified:true,name:'Mobile Member'})});await withServer(async base=>{const response=await fetch(`${base}/auth/google/continue`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({credential:'verified-google-token'}),redirect:'manual'});assert.equal(response.status,303);assert.equal(response.headers.get('location'),'/portal');assert.match(response.headers.get('set-cookie'),/neo_pass_session=.*HttpOnly.*Secure.*SameSite=Lax/)},{authService,subjectResolver:createNeopassSubjectResolver({secret:'secret',issuer:'neo-pass'})})});

test('bootstraps the first Google identity as executive admin and permits password login',async()=>{const records=new Map();const registry={getNEOpassCredential:async subject=>records.get(subject)||null,getNEOpassCredentialByLogin:async login=>[...records.values()].find(value=>value.usernameKey===login.toLowerCase()||value.emailKey===login.toLowerCase())||null,async upsert(_collection,record){records.set(record.subject,record);return record}};const authService=createGoogleNeopassAuth({clientId:'client.apps.googleusercontent.com',jwtSecret:'secret',registry,executiveAdminEmail:'NooneUniversity@gmail.com',executiveAdminUsername:'Shemsizedek',verifyGoogleCredential:async()=>({sub:'admin-1',email:'NooneUniversity@gmail.com',email_verified:true,name:'Executive Admin'}),now:()=>Date.parse('2026-09-10T00:00:00.000Z')});await withServer(async base=>{const google=await fetch(`${base}/api/v1/auth/google`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential:'verified'})});const cookie=google.headers.get('set-cookie').split(';')[0];const account=records.get('google:admin-1');assert.equal(account.username,'Shemsizedek');assert.equal(account.role,'executive-admin');assert.equal(account.status,'active');const dashboard=await fetch(`${base}/portal`,{headers:{cookie}});assert.equal(dashboard.status,200);assert.match(await dashboard.text(),/NEO eGAAS Dashboard/);const setup=await fetch(`${base}/setup-executive`,{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password:'StrongTemple!144',confirm:'StrongTemple!144'}),redirect:'manual'});assert.equal(setup.status,303);assert.equal(records.get('google:admin-1').passwordHash.startsWith('scrypt$'),true);const login=await fetch(`${base}/login`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({login:'Shemsizedek',password:'StrongTemple!144'}),redirect:'manual'});assert.equal(login.status,303);assert.equal(login.headers.get('location'),'/portal');assert.match(login.headers.get('set-cookie'),/neo_pass_session=/)},{authService,subjectResolver:createNeopassSubjectResolver({secret:'secret',issuer:'neo-pass'})})});

test('admits the verified executive to the dashboard when registry persistence is unavailable',async()=>{const registry={getNEOpassCredential:async()=>{throw new Error('firestore unavailable')},upsert:async()=>{throw new Error('firestore unavailable')}};const authService=createGoogleNeopassAuth({clientId:'client.apps.googleusercontent.com',jwtSecret:'secret',registry,executiveAdminEmail:'NooneUniversity@gmail.com',executiveAdminUsername:'Shemsizedek',verifyGoogleCredential:async()=>({sub:'admin-mobile',email:'NooneUniversity@gmail.com',email_verified:true,name:'Executive Admin'})});await withServer(async base=>{const login=await fetch(`${base}/auth/google/continue`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({credential:'verified'}),redirect:'manual'});assert.equal(login.status,303);assert.equal(login.headers.get('location'),'/portal');const cookie=login.headers.get('set-cookie').split(';')[0];const dashboard=await fetch(`${base}/portal`,{headers:{cookie}});assert.equal(dashboard.status,200);const html=await dashboard.text();assert.match(html,/NEO eGAAS Dashboard/);assert.match(html,/H\.I\.M Dr\. Lawiy Zodok/)},{authService,subjectResolver:createNeopassSubjectResolver({secret:'secret',issuer:'neo-pass'})})});

test('rejects unconfigured and invalid Google sign-in attempts',async()=>{await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/auth/google`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).status,503)});const authService=createGoogleNeopassAuth({clientId:'client',jwtSecret:'secret',registry:{getNEOpassCredential:async()=>null,upsert:async()=>null},verifyGoogleCredential:async()=>{throw new Error('invalid')}});await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/auth/google`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential:'bad'})})).status,401)},{authService})});

test('publishes ten-platform registry including Tokenworks, NEO Banks, and Nibiru Reserve',async()=>{await withServer(async base=>{const health=await fetch(`${base}/health`).then(r=>r.json());assert.equal(health.status,'ok');assert.equal(health.platforms,10);const registry=await fetch(`${base}/api/v1/platforms`).then(r=>r.json());assert.equal(registry.platforms.length,Object.keys(PLATFORM_REGISTRY).length);assert.ok(registry.platforms.some(p=>p.id==='neo-tokenworks'));assert.ok(registry.platforms.some(p=>p.id==='neo-banks'));assert.ok(registry.platforms.some(p=>p.id==='nibiru-reserve'))})});
test('publishes platform capability and health endpoints',async()=>{await withServer(async base=>{const capabilities=await fetch(`${base}/api/v1/platforms/neo-tokenworks/capabilities`).then(r=>r.json());assert.equal(capabilities.platform,'neo-tokenworks');assert.equal(capabilities.readOnly,true);assert.ok(capabilities.services.includes('neopass'));const health=await fetch(`${base}/api/v1/platforms/neo-banks/health`).then(r=>r.json());assert.equal(health.status,'ok')})});
test('publishes normalized NEO Prime market and asset endpoints',async()=>{await withServer(async base=>{const snapshot=await fetch(`${base}/api/v1/prime/markets?assets=XCP,NOMNI`).then(r=>r.json());assert.equal(snapshot.bitcoin.symbol,'BTC');assert.ok(snapshot.counterparty.NOMNI);const asset=await fetch(`${base}/api/v1/prime/assets/nomni`).then(r=>r.json());assert.equal(asset.symbol,'NOMNI')})});
test('rejects unknown platforms and write methods',async()=>{await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/platforms/not-real`)).status,404);const write=await fetch(`${base}/api/v1/platforms`,{method:'POST'});assert.equal(write.status,405);assert.equal((await write.json()).readOnly,true)})});
test('requires a NEOpass identity for integration routes',async()=>{await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations`);assert.equal(response.status,401);assert.equal((await response.json()).error,'neopass_identity_required')})});
test('lists subject-scoped integrations and retrieves status',async()=>{const composio=fakeComposio();await withServer(async base=>{const list=await fetch(`${base}/api/v1/integrations`,{headers:authHeaders()}).then(r=>r.json());assert.equal(list.integrations[0].name,'github');assert.deepEqual(list.integrations[0].classifications,['read','write']);const status=await fetch(`${base}/api/v1/integrations/github/status`,{headers:authHeaders()}).then(r=>r.json());assert.equal(status.status.name,'github');assert.equal(status.status.health,'ready');assert.equal(composio.sessions.length,1)},{integrationHub:createIntegrationHub({composio,now:()=> '2026-08-25T00:00:00.000Z'})})});
test('executes an approved read and normalizes plus redacts output',async()=>{const composio=fakeComposio();const audits=[];await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations/execute-read`,{method:'POST',headers:authHeaders(),body:JSON.stringify({integration:'github',tool:'GITHUB_LIST_REPOS',arguments:{}})});const body=await response.json();assert.equal(response.status,200);assert.equal(body.readOnly,true);assert.equal(body.data.token,'[REDACTED]');assert.equal(body.data.nested.password,'[REDACTED]');assert.equal(audits[0].allowed,true);assert.equal(audits[0].classification,'read');assert.equal(JSON.stringify(audits).includes('opaque'),false)},{integrationHub:createIntegrationHub({composio,audit:event=>audits.push(event)})})});
test('rejects write capabilities before execution',async()=>{const composio=fakeComposio();await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations/execute-read`,{method:'POST',headers:authHeaders(),body:JSON.stringify({integration:'github',tool:'GITHUB_CREATE_ISSUE'})});assert.equal(response.status,403);assert.equal((await response.json()).error,'read_only_operation_required')},{integrationHub:createIntegrationHub({composio})})});
test('returns controlled errors for unknown integrations and Composio session failures',async()=>{await withServer(async base=>{const unknown=await fetch(`${base}/api/v1/integrations/slack/status`,{headers:authHeaders()});assert.equal(unknown.status,404);assert.equal((await unknown.json()).error,'integration_not_found')},{integrationHub:createIntegrationHub({composio:fakeComposio()})});const failing={async createSession(){throw new IntegrationHubError('composio_authentication_failed','Composio authentication failed.',502)}};await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations`,{headers:authHeaders()});assert.equal(response.status,502);assert.equal((await response.json()).error,'composio_authentication_failed')},{integrationHub:createIntegrationHub({composio:failing})})});
test('isolates Composio sessions by NEOpass subject',async()=>{const composio=fakeComposio();await withServer(async base=>{await fetch(`${base}/api/v1/integrations`,{headers:authHeaders('subject-a')});await fetch(`${base}/api/v1/integrations`,{headers:authHeaders('subject-b')});assert.deepEqual(composio.sessions.map(session=>session.subject),['subject-a','subject-b'])},{integrationHub:createIntegrationHub({composio})})});
test('verifies production NEOpass HS256 bearer subjects and fails closed',()=>{const secret='test-neopass-secret';const resolve=createNeopassSubjectResolver({secret,issuer:'neo'});const valid=token({subject:'member-1',secret,issuer:'neo'});assert.equal(resolve({headers:{authorization:`Bearer ${valid}`}}),'member-1');assert.equal(resolve({headers:{authorization:`Bearer ${token({subject:'member-1',secret,issuer:'wrong'})}`}}),null);assert.equal(resolve({headers:{authorization:'Bearer malformed'}}),null);assert.equal(resolve({headers:{authorization:`Bearer ${token({subject:'member-1',secret,issuer:'neo',expiresAt:1})}`}}),null);assert.equal(createNeopassSubjectResolver({})({headers:{authorization:`Bearer ${valid}`}}),null)});
test('provider adapter exposes a provider-neutral read capability contract',async()=>{const composio=fakeComposio();const adapter=createComposioProviderAdapter({composio,now:()=> '2026-08-25T00:00:00.000Z'});const sessionId=await adapter.createSession('subject-a');const capabilities=await adapter.listCapabilities(sessionId);assert.equal(capabilities[0].provider,'composio');assert.equal(capabilities[0].classification,'read');const result=await adapter.executeRead(sessionId,capabilities[0],{});assert.equal(result.data.status,'ok');assert.equal(capabilities[0].lastSuccessfulOperation,'2026-08-25T00:00:00.000Z');await assert.rejects(()=>adapter.executeRead(sessionId,capabilities[1],{}),/read_only_operation_required/)});
test('provider adapter does not derive capabilities from descriptions alone',async()=>{const composio={async createSession(){return{session_id:'session'}},async listTools(){return{items:[{slug:'COMPOSIO_SEARCH_TOOLS',name:'search_tools',description:'Search calendar events',toolkit:{slug:'COMPOSIO'}}]}},async execute(){throw new Error('must not execute')}};const adapter=createComposioProviderAdapter({composio});assert.equal((await adapter.listCapabilities('session')).length,0)});
test('command router normalizes authenticated read commands and redacts provider secrets',async()=>{const composio=fakeComposio();const integrationHub=createIntegrationHub({composio});const router=createCommandRouter({integrationHub,now:()=> '2026-08-25T00:00:00.000Z'});const result=await router.execute('subject-a',{capability:'development.repositories.list',parameters:{}});assert.equal(result.ok,true);assert.equal(result.capability,'development.repositories.list');assert.equal(result.provider,'composio');assert.equal(result.data.token,'[REDACTED]');assert.equal(result.timestamp,'2026-08-25T00:00:00.000Z')});
test('HTTP command route authenticates and returns a normalized read response',async()=>{const composio=fakeComposio();await withServer(async base=>{const response=await fetch(`${base}/api/v1/commands/execute`,{method:'POST',headers:authHeaders(),body:JSON.stringify({capability:'development.repositories.list',parameters:{}})});const body=await response.json();assert.equal(response.status,200);assert.equal(body.ok,true);assert.equal(body.provider,'composio');assert.equal(body.capability,'development.repositories.list')},{integrationHub:createIntegrationHub({composio})})});
test('HTTP command capability catalog and status hide provider tool slugs',async()=>{const composio=fakeComposio();await withServer(async base=>{const catalog=await fetch(`${base}/api/v1/commands/capabilities`,{headers:authHeaders()});const body=await catalog.json();assert.equal(catalog.status,200);assert.ok(body.capabilities.some(item=>item.capability==='development.repositories.list'));assert.equal(JSON.stringify(body).includes('GITHUB_LIST_REPOS'),false);const status=await fetch(`${base}/api/v1/commands/capabilities/development.repositories.list/status`,{headers:authHeaders()});assert.equal(status.status,200);assert.equal((await status.json()).classification,'read')},{integrationHub:createIntegrationHub({composio})})});
test('command router normalizes provider failures and redacts secrets',async()=>{const audits=[];const router=createCommandRouter({audit:event=>audits.push(event),integrationHub:{executeCapability:async()=>{const error=new Error('provider token=secret-value unavailable');error.status=503;throw error}}});await assert.rejects(()=>router.execute('subject-a',{capability:'development.repositories.list'}),error=>error.code==='provider_failure'&&error.status===503&&error.message.includes('token=[REDACTED]')&&!error.message.includes('secret-value'));assert.equal(JSON.stringify(audits).includes('secret-value'),false)});
test('command router rejects missing identity, unknown capability, provider failure, and mutation',async()=>{const composio=fakeComposio();const integrationHub=createIntegrationHub({composio});const router=createCommandRouter({integrationHub});await assert.rejects(()=>router.execute(null,{capability:'development.repositories.list'}),error=>error.code==='neopass_identity_required');await assert.rejects(()=>router.execute('subject-a',{capability:'development.unknown.list'}),error=>error.code==='unknown_capability');await assert.rejects(()=>router.execute('subject-a',{capability:'development.issues.create'}),error=>error.code==='read_only_operation_required');const failing=createCommandRouter({integrationHub:{executeCapability:async()=>{throw new Error('provider unavailable')}}});await assert.rejects(()=>failing.execute('subject-a',{capability:'development.repositories.list'}),/provider unavailable/)});
test('control plane registers applications and enforces namespace policy',async()=>{const composio=fakeComposio();const audits=[];const integrationHub=createIntegrationHub({composio});const router=createCommandRouter({integrationHub});const controlPlane=createControlPlane({commandRouter:router,audit:event=>audits.push(event),now:()=> '2026-08-25T00:00:00.000Z',requestId:()=> 'req-1'});assert.equal(Object.keys(APPLICATION_REGISTRY).length,9);const capabilities=await controlPlane.capabilities('subject-a','neo-cipher');assert.ok(capabilities.capabilities.every(item=>item.capability.startsWith('files.')||item.capability.startsWith('calendar.')||item.capability.startsWith('tasks.')));const result=await controlPlane.execute('subject-a','neo-cipher',{capability:'files.repositories.list',parameters:{}});assert.equal(result.requestId,'req-1');assert.equal(result.status,'ok');await assert.rejects(()=>controlPlane.execute('subject-a','neo-cipher',{capability:'email.messages.list'}),error=>error.code==='application_capability_forbidden');assert.equal(audits.at(-1).allow,false)});
test('control plane rejects unknown apps, missing identity, mutations, and isolates subjects',async()=>{const composio=fakeComposio();const controlPlane=createControlPlane({commandRouter:createCommandRouter({integrationHub:createIntegrationHub({composio})})});await assert.rejects(()=>controlPlane.capabilities('subject-a','not-registered'),error=>error.code==='unknown_application');await assert.rejects(()=>controlPlane.capabilities(null,'neo-pads'),error=>error.code==='neopass_identity_required');await controlPlane.capabilities('subject-a','neo-pads');await assert.rejects(()=>controlPlane.execute('subject-a','neo-pads',{capability:'development.issues.create'}),error=>error.code==='application_capability_forbidden');await controlPlane.capabilities('subject-b','neo-pads');assert.deepEqual(composio.sessions.map(session=>session.subject),['subject-a','subject-b'])});
test('HTTP control plane routes return normalized responses and auth failures',async()=>{const composio=fakeComposio();await withServer(async base=>{const missing=await fetch(`${base}/api/v1/control-plane/applications/neo-pads/capabilities`);assert.equal(missing.status,401);const discovery=await fetch(`${base}/api/v1/control-plane/applications/neo-pads/capabilities`,{headers:authHeaders()});assert.equal(discovery.status,200);const execution=await fetch(`${base}/api/v1/control-plane/applications/neo-pads/commands`,{method:'POST',headers:authHeaders(),body:JSON.stringify({capability:'development.repositories.list',parameters:{}})});assert.equal(execution.status,403);const allowed=await fetch(`${base}/api/v1/control-plane/applications/neo-pads/commands`,{method:'POST',headers:authHeaders(),body:JSON.stringify({capability:'files.repositories.list',parameters:{}})});assert.equal(allowed.status,200);assert.equal((await allowed.json()).status,'ok')},{integrationHub:createIntegrationHub({composio})})});
test('World Temple adapter exposes read-only application health, capabilities, and normalized reads',async()=>{const composio=fakeComposio();const audits=[];const controlPlane=createControlPlane({commandRouter:createCommandRouter({integrationHub:createIntegrationHub({composio})}),now:()=> '2026-08-25T00:00:00.000Z',audit:event=>audits.push(event)});const temple=createTempleAdapter({controlPlane,now:()=> '2026-08-25T00:00:00.000Z',requestId:()=> 'temple-req',audit:event=>audits.push(event)});assert.equal(temple.applicationId,TEMPLE_APPLICATION_ID);const health=await temple.health('subject-a');assert.equal(health.registered,true);assert.equal(health.readOnly,true);const capabilities=await temple.capabilities('subject-a');assert.ok(Array.isArray(capabilities.capabilities));const response=await temple.read('subject-a',{capability:'library.catalog.discovery',parameters:{}});assert.equal(response.ok,true);assert.equal(response.application,'world-temple');assert.equal(response.requestId,'temple-req');assert.equal(response.capability,'library.catalog.discovery');assert.equal(JSON.stringify(audits).includes('token'),false)});
test('World Temple adapter enforces identity, subject isolation, and mutation boundaries',async()=>{const composio=fakeComposio();const controlPlane=createControlPlane({commandRouter:createCommandRouter({integrationHub:createIntegrationHub({composio})})});const temple=createTempleAdapter({controlPlane});await assert.rejects(()=>temple.health(null),error=>error.code==='neopass_identity_required');await assert.rejects(()=>temple.read('subject-a',{capability:'store.checkout.execute'}),error=>error.code==='temple_capability_forbidden');await temple.capabilities('subject-a');await temple.capabilities('subject-b');assert.deepEqual(composio.sessions.map(session=>session.subject),['subject-a','subject-b'])});
test('HTTP World Temple routes require NEOpass and preserve read-only boundaries',async()=>{const composio=fakeComposio();await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/temple/health`)).status,401);const health=await fetch(`${base}/api/v1/temple/health`,{headers:authHeaders()});assert.equal(health.status,200);const read=await fetch(`${base}/api/v1/temple/read`,{method:'POST',headers:authHeaders(),body:JSON.stringify({capability:'store.checkout.execute'})});assert.equal(read.status,403);assert.equal((await read.json()).error,'temple_capability_forbidden')},{integrationHub:createIntegrationHub({composio})})});
