import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createNeoPlatformApi, PLATFORM_REGISTRY } from './server.mjs';

const marketData={async snapshot({assets}={}){return{service:'neo-prime-market-data',apiVersion:'v1',status:'ok',generatedAt:'2026-08-25T00:00:00.000Z',bitcoin:{symbol:'BTC',priceUsd:112000,blockHeight:910144,status:'ok',errors:[]},counterparty:Object.fromEntries((assets||['XCP','NOMNI']).map(symbol=>[symbol,{symbol,status:'ok'}]))}},async asset(symbol){return{symbol:String(symbol).toUpperCase(),status:'ok',supply:900000000}}};
const teraboxClient={async userInfo(){return{errno:0,uk:'u-1'}},async quota(){return{errno:0,total:1000,used:250}},async list({dir,page,num}){return{errno:0,dir,page,num,list:[{fs_id:11,path:`${dir}/report.pdf`}]}},async search({key,page,num}){return{errno:0,key,page,num,list:[{fs_id:11,server_filename:'report.pdf'}]}},async downloadLinks(fids){return{errno:0,list:fids.map(fs_id=>({fs_id,dlink:`https://download.example/${fs_id}`}))}}};
const mutations=[];
const teraboxRuntime={configured:()=>true,authorizationUrl:()=> 'https://www.terabox.com/wap/outside/login?clientId=client-1&state=state-1',async status(){return{service:'terabox',configured:true,liveMode:'read-only',connected:true,userId:'u-1',apiDomain:'https://api.example',uploadDomain:'https://upload.example',refreshTokenPresent:true,connectedAt:'2026-08-25T00:00:00.000Z',tokenStore:'runtime-memory',durable:false}},async complete(code,state){return{connected:true,userId:'u-1',expiresIn:172800,apiDomain:'https://api.example',uploadDomain:'https://upload.example',refreshTokenPresent:true,health:{ok:true,clientId:'client-1',user:{errno:0},quota:{errno:0}},codeAccepted:code==='abc'&&state==='state-1'}},async client(){return teraboxClient},async fileOperation(input){mutations.push(input);return{errno:0,request_id:'op-1'}}};
const operatorHeaders={authorization:'Bearer operator-test-token'};
async function withServer(fn,{env={NEO_OPERATOR_API_TOKEN:'operator-test-token',NEO_STORAGE_WRITE_TOKEN:'write-test-token',TERABOX_LIVE_MODE:'read-only'}}={}){const server=createNeoPlatformApi({now:()=> '2026-08-25T00:00:00.000Z',marketData,teraboxRuntime,env});server.listen(0,'127.0.0.1');await once(server,'listening');const{port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{server.close();await once(server,'close')}}

test('publishes ten-platform registry including Tokenworks, NEO Banks, and Nibiru Reserve',async()=>{await withServer(async base=>{const health=await fetch(`${base}/health`).then(r=>r.json());assert.equal(health.status,'ok');assert.equal(health.platforms,10);const registry=await fetch(`${base}/api/v1/platforms`).then(r=>r.json());assert.equal(registry.platforms.length,Object.keys(PLATFORM_REGISTRY).length);assert.ok(registry.platforms.some(p=>p.id==='neo-tokenworks'));assert.ok(registry.platforms.some(p=>p.id==='neo-banks'));assert.ok(registry.platforms.some(p=>p.id==='nibiru-reserve'))})});
test('publishes platform capability and health endpoints',async()=>{await withServer(async base=>{const capabilities=await fetch(`${base}/api/v1/platforms/neo-tokenworks/capabilities`).then(r=>r.json());assert.equal(capabilities.platform,'neo-tokenworks');assert.equal(capabilities.readOnly,true);assert.ok(capabilities.services.includes('neopass'));const health=await fetch(`${base}/api/v1/platforms/neo-banks/health`).then(r=>r.json());assert.equal(health.status,'ok')})});
test('publishes normalized NEO Prime market and asset endpoints',async()=>{await withServer(async base=>{const snapshot=await fetch(`${base}/api/v1/prime/markets?assets=XCP,NOMNI`).then(r=>r.json());assert.equal(snapshot.bitcoin.symbol,'BTC');assert.ok(snapshot.counterparty.NOMNI);const asset=await fetch(`${base}/api/v1/prime/assets/nomni`).then(r=>r.json());assert.equal(asset.symbol,'NOMNI')})});
test('protects TeraBox routes with operator authentication',async()=>{await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/storage/terabox/status`)).status,401);assert.equal((await fetch(`${base}/api/v1/storage/terabox/status`,{headers:{authorization:'Bearer wrong'}})).status,401)})});
test('publishes protected TeraBox status, authorization URL, and state-bound callback',async()=>{await withServer(async base=>{const status=await fetch(`${base}/api/v1/storage/terabox/status`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(status.service,'terabox');const auth=await fetch(`${base}/api/v1/storage/terabox/auth-url`,{headers:operatorHeaders}).then(r=>r.json());assert.match(auth.authorizationUrl,/state=state-1/);assert.equal((await fetch(`${base}/api/v1/storage/terabox/callback?code=abc`,{headers:operatorHeaders})).status,400);const connected=await fetch(`${base}/api/v1/storage/terabox/callback?code=abc&state=state-1`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(connected.codeAccepted,true)})});
test('serves authenticated read-only file metadata, search, and download links',async()=>{await withServer(async base=>{const user=await fetch(`${base}/api/v1/storage/terabox/user`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(user.data.uk,'u-1');const quota=await fetch(`${base}/api/v1/storage/terabox/quota`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(quota.data.total,1000);const files=await fetch(`${base}/api/v1/storage/terabox/files?dir=%2Fapps%2Fneo`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(files.data.list[0].fs_id,11);const search=await fetch(`${base}/api/v1/storage/terabox/search?key=report`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(search.data.list[0].server_filename,'report.pdf');const links=await fetch(`${base}/api/v1/storage/terabox/download-links?fids=11`,{headers:operatorHeaders}).then(r=>r.json());assert.equal(links.sensitive,true);assert.equal(links.data.list[0].fs_id,'11')})});
test('controlled mutations fail closed in read-only mode',async()=>{await withServer(async base=>{const response=await fetch(`${base}/api/v1/storage/terabox/file-operations`,{method:'POST',headers:{...operatorHeaders,'content-type':'application/json','x-neo-storage-write-token':'write-test-token'},body:JSON.stringify({operation:'rename',filelist:[{path:'/a',newname:'b'}],confirm:true})});assert.equal(response.status,403)})});
test('controlled mutations require separate write credential and explicit confirmation',async()=>{await withServer(async base=>{const common={method:'POST',headers:{...operatorHeaders,'content-type':'application/json'},body:JSON.stringify({operation:'rename',filelist:[{path:'/a',newname:'b'}],confirm:true})};assert.equal((await fetch(`${base}/api/v1/storage/terabox/file-operations`,common)).status,401);const missingConfirm=await fetch(`${base}/api/v1/storage/terabox/file-operations`,{...common,headers:{...common.headers,'x-neo-storage-write-token':'write-test-token'},body:JSON.stringify({operation:'rename',filelist:[{path:'/a',newname:'b'}]})});assert.equal(missingConfirm.status,409)},{env:{NEO_OPERATOR_API_TOKEN:'operator-test-token',NEO_STORAGE_WRITE_TOKEN:'write-test-token',TERABOX_LIVE_MODE:'controlled-write'}})});
test('controlled mutations execute only when all gates pass',async()=>{mutations.length=0;await withServer(async base=>{const response=await fetch(`${base}/api/v1/storage/terabox/file-operations`,{method:'POST',headers:{...operatorHeaders,'content-type':'application/json','x-neo-storage-write-token':'write-test-token'},body:JSON.stringify({operation:'copy',filelist:[{path:'/a',dest:'/b'}],confirm:true})});assert.equal(response.status,200);const payload=await response.json();assert.equal(payload.controlledWrite,true);assert.equal(payload.operation,'copy');assert.equal(mutations.length,1);assert.equal(mutations[0].operation,'copy')},{env:{NEO_OPERATOR_API_TOKEN:'operator-test-token',NEO_STORAGE_WRITE_TOKEN:'write-test-token',TERABOX_LIVE_MODE:'controlled-write'}})});
test('rejects unknown platforms and unrelated write methods',async()=>{await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/platforms/not-real`)).status,404);const write=await fetch(`${base}/api/v1/platforms`,{method:'POST'});assert.equal(write.status,405)})});
