import http from 'node:http';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { createNeoPrimeMarketData } from '../neo-prime/market-data.mjs';
import { createIntegrationHub, resolveNeopassSubject, IntegrationHubError } from './integration-hub.mjs';
import { createCommandRouter, CommandRouterError } from './command-router.mjs';
import { createControlPlane, ControlPlaneError } from './control-plane.mjs';
import { createTempleAdapter, TempleAdapterError } from './temple-adapter.mjs';
import { createGissHttpHandler } from './giss-http-routes.mjs';
import { clearSessionCookie, sessionCookie } from './neopass-google-auth.mjs';

export const PLATFORM_REGISTRY = {
  neopay: { name: 'NEOpay', source: ['apps/neopay', 'src/neopay'], services: ['wallet', 'portfolio', 'transaction-compose', 'dex-quotes'] },
  'neo-teller': { name: 'NEO Teller', source: ['server/neo-teller-backend'], services: ['atm-session', 'deposit-status', 'withdrawal-status', 'fx-quotes'] },
  'neo-books': { name: 'NEO Books', source: ['src/books'], services: ['chart-of-accounts', 'ledger-status', 'treasury-summary', 'reports'] },
  'neo-prime': { name: 'NEO Prime', source: ['server/neo-prime'], services: ['markets', 'research', 'quotes', 'signals'] },
  'neo-exchange': { name: 'NEO Exchange', source: ['neo-system market stack'], services: ['markets', 'orders-read', 'quotes', 'settlement-compose'] },
  'neo-generator': { name: 'NEO Generator', source: ['server/miner-generator'], services: ['products', 'hashpower-quotes', 'contracts-read', 'capacity'] },
  'neo-miner': { name: 'NEO Miner', source: ['src/miner', 'server/miner-agent', 'server/miner-controller', 'server/miner-commerce'], services: ['fleet', 'telemetry', 'jobs-read', 'commerce-read'] },
  'neo-tokenworks': { name: 'NEO Tokenworks', source: ['server/neo-tokenworks'], services: ['neopass', 'address-proof', 'shared-access', 'escrow-planning', 'token-tracking'] },
  'neo-banks': { name: 'NEO Banks', source: ['server/neo-tokenworks', 'server/nibiru-reserve', 'server/neo-teller-backend', 'apps/neopay'], services: ['token-lending-sandbox', 'neopass-consumer', 'ces-position-observation', 'iso-20022-translation', 'compliance-gates'] },
  'nibiru-reserve': { name: 'Nibiru Reserve System', source: ['server/nibiru-reserve', 'server/neo-tokenworks'], services: ['ces-position-observation', 'blockchain-settlement-linkage', 'reserve-snapshot', 'iso-20022-canonical-mapping', 'reconciliation-gates'] }
};
const OCI_SERVICE_REGISTRY = JSON.parse(readFileSync(new URL('../../infra/oci/neo-system-services.json', import.meta.url), 'utf8'));
function json(res,status,body){const payload=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(payload),'access-control-allow-origin':'*','cache-control':'no-store'});res.end(payload);}
function portal(res, googleClientId=''){
  const body=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="The official Templist member portal of the World Temple of Karast."><title>Templist Portal | World Temple of Karast</title><style>
  :root{color-scheme:dark;--ink:#f7f2df;--muted:#b7b0a0;--gold:#d6b665;--panel:#131715;--line:#343a32}*{box-sizing:border-box}body{margin:0;background:#090c0b;color:var(--ink);font-family:Inter,system-ui,sans-serif;line-height:1.5}a{color:inherit}.shell{min-height:100vh;background:radial-gradient(circle at 50% -10%,#273027 0,transparent 45%)}header,main,footer{width:min(1100px,calc(100% - 2rem));margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:1.25rem 0;border-bottom:1px solid var(--line)}.brand{font-family:Georgia,serif;font-weight:700;letter-spacing:.04em}.home{color:var(--muted);text-decoration:none}.hero{padding:clamp(4rem,10vw,8rem) 0 3rem;max-width:760px}.eyebrow{color:var(--gold);font-size:.78rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase}h1{font:700 clamp(2.7rem,8vw,5.7rem)/.98 Georgia,serif;margin:.75rem 0 1.25rem}p{color:var(--muted);font-size:1.08rem}.actions{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:2rem}.button{display:inline-block;padding:.85rem 1.1rem;border:1px solid var(--gold);border-radius:999px;text-decoration:none;font-weight:750}.button.primary{background:var(--gold);color:#12150f}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;padding:2rem 0 5rem}.card{background:var(--panel);border:1px solid var(--line);border-radius:1rem;padding:1.25rem;text-decoration:none}.card strong{display:block;color:var(--gold);margin-bottom:.35rem}.card span{color:var(--muted)}footer{border-top:1px solid var(--line);padding:1.5rem 0 2rem;color:var(--muted);font-size:.9rem}@media(max-width:700px){.grid{grid-template-columns:1fr}header{align-items:flex-start}.hero{padding-top:3.5rem}}
  .login{margin-top:2rem;padding:1.25rem;background:var(--panel);border:1px solid var(--line);border-radius:1rem;max-width:430px}.login h2{font:700 1.35rem Georgia,serif;margin:0 0 .35rem}.login p{font-size:.95rem;margin:.25rem 0 1rem}.member{display:none}.member.visible{display:block}.status{color:var(--gold);font-weight:700}.logout{margin-top:.75rem;background:transparent;color:var(--muted);border:0;text-decoration:underline;cursor:pointer}
  </style><script src="/portal.js" defer></script><script src="https://accounts.google.com/gsi/client" async defer></script></head><body><div class="shell"><header><div class="brand">WORLD TEMPLE OF KARAST</div><a class="home" href="https://holytemples.org/">Return to Temple</a></header><main><section class="hero"><div class="eyebrow">Holy See Global District</div><h1>Templist Portal</h1><p>The official digital gate for World Congregation members, Temple education, public governance resources, and the developing NEO eGovernment services.</p><div class="login" aria-live="polite"><div id="signed-out"><h2>Member Login</h2><p>Sign in securely with Google to enter through NEOpass.</p>${googleClientId?`<div id="g_id_onload" data-client_id="${googleClientId.replace(/[&<>\"']/g,'')}" data-callback="handleGoogleCredential" data-auto_prompt="false"></div><div class="g_id_signin" data-type="standard" data-shape="pill" data-theme="outline" data-text="signin_with" data-size="large" data-logo_alignment="left"></div>`:'<p class="status">Google Sign-In is awaiting administrator configuration.</p>'}</div><div id="signed-in" class="member"><h2 id="member-name">NEOpass Member</h2><p id="member-status"></p><div class="actions"><a class="button primary" href="/portal">Open Member Dashboard</a></div><button id="logout" class="logout" type="button">Sign out</button></div></div><div class="actions"><a class="button" href="https://holytemples.org/world-congregation/">World Congregation</a><a class="button" href="https://holytemples.org/contact/">Request Assistance</a></div></section><section class="grid" aria-label="Portal services"><a class="card" href="https://holytemples.org/global-district/"><strong>Global District</strong><span>Public institutions, offices, and governance.</span></a><a class="card" href="https://holytemples.org/world-education/"><strong>World Education</strong><span>GISD curriculum and Temple learning.</span></a><a class="card" href="https://holytemples.org/world-library/"><strong>World Library</strong><span>Books, tablets, audio, and study resources.</span></a></section></main><footer>Official portal of the World Temple of Karast · Powered by the NEO System</footer></div></body></html>`;
  res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'public, max-age=300','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','content-security-policy':"default-src 'none'; script-src 'self' https://accounts.google.com/gsi/client; style-src 'unsafe-inline' https://accounts.google.com/gsi/style; img-src 'self' data: https://lh3.googleusercontent.com; frame-src https://accounts.google.com/gsi/; connect-src 'self' https://accounts.google.com/gsi/; frame-ancestors 'self' https://holytemples.org; base-uri 'none'; form-action 'self'"});
  res.end(body);
}

function portalScript(res){const body=`window.handleGoogleCredential=async function(response){const box=document.querySelector('.login');try{box.setAttribute('aria-busy','true');const result=await fetch('/api/v1/auth/google',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential:response.credential})});const data=await result.json();if(!result.ok)throw new Error(data.message||'Sign-in failed');showMember(data.member)}catch(error){document.getElementById('signed-out').insertAdjacentHTML('beforeend','<p class="status">'+escapeHtml(error.message)+'</p>')}finally{box.removeAttribute('aria-busy')}};function escapeHtml(value){const p=document.createElement('p');p.textContent=value;return p.innerHTML}function showMember(member){document.getElementById('signed-out').style.display='none';document.getElementById('signed-in').classList.add('visible');document.getElementById('member-name').textContent=member.displayName||'NEOpass Member';document.getElementById('member-status').textContent=member.neopassStatus==='active'?'NEOpass active · Member services available':'Google verified · Temple membership verification pending'}async function session(){const response=await fetch('/api/v1/auth/session');if(response.ok){const data=await response.json();if(data.authenticated)showMember(data.member)}}document.addEventListener('DOMContentLoaded',()=>{session();document.getElementById('logout')?.addEventListener('click',async()=>{await fetch('/api/v1/auth/logout',{method:'POST'});location.reload()})});`;res.writeHead(200,{'content-type':'application/javascript; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'public, max-age=300','x-content-type-options':'nosniff'});res.end(body)}

function memberPortal(res, subject){const body=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Member Dashboard | NEOpass</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#090c0b;color:#f7f2df;font:16px/1.5 Inter,system-ui,sans-serif}main{width:min(960px,calc(100% - 2rem));margin:auto;padding:3rem 0}a{color:#d6b665}.panel{margin-top:2rem;padding:1.5rem;background:#131715;border:1px solid #343a32;border-radius:1rem}h1{font:700 clamp(2.2rem,7vw,4.5rem)/1 Georgia,serif;margin:.5rem 0}p{color:#b7b0a0}.status{color:#d6b665;font-weight:700}</style></head><body><main><a href="/">← Templist Portal</a><div class="panel"><p class="status">NEOpass session verified</p><h1>Member Dashboard</h1><p>Your Google identity is securely connected. Temple Citizen and Book of Life verification determine access to protected GISS services.</p><p>Session: ${String(subject).replace(/[&<>\"']/g,'')}</p><p><a href="/api/v1/temple/giss/dashboard">Check GISS dashboard access</a></p></div></main></body></html>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'self' https://holytemples.org; base-uri 'none'; form-action 'none'"});res.end(body)}

export function createNeoPlatformApi({ now=()=>new Date().toISOString(), audit=()=>{}, marketData=createNeoPrimeMarketData({now}), integrationHub=createIntegrationHub({now,audit}), commandRouter=createCommandRouter({integrationHub,now,audit}), controlPlane=createControlPlane({commandRouter,now,audit}), templeAdapter=createTempleAdapter({controlPlane,now,audit}), subjectResolver=resolveNeopassSubject, templeGissRuntime=null, authService=null }={}) {
  const gissHandler=createGissHttpHandler({service:templeGissRuntime?.service||null,subjectResolver,now});
  return http.createServer(async(req,res)=>{try{
    if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-neopass-subject'});return res.end();}
    const url=new URL(req.url||'/','http://neo.local');
    if(req.method==='GET'&&url.pathname==='/')return portal(res,authService?.clientId);
    if(req.method==='GET'&&url.pathname==='/portal.js')return portalScript(res);
    if(req.method==='GET'&&url.pathname==='/portal'){const subject=subjectResolver(req);if(!subject){res.writeHead(302,{location:'/'});return res.end();}return memberPortal(res,subject);}
    if(req.method==='POST'&&url.pathname==='/api/v1/auth/google'){
      if(!authService)return json(res,503,{error:'google_signin_not_configured',message:'Google Sign-In is awaiting administrator configuration.'});
      let body='';for await(const chunk of req){body+=chunk;if(body.length>20000)return json(res,413,{error:'request_too_large'});}
      const {credential}=JSON.parse(body||'{}');if(!credential)return json(res,400,{error:'google_credential_required'});
      try{const result=await authService.login(credential);res.setHeader('set-cookie',sessionCookie(result.token));return json(res,200,{authenticated:true,member:result.member});}catch{return json(res,401,{error:'google_identity_not_verified',message:'Google could not verify this sign-in.'});}
    }
    if(req.method==='GET'&&url.pathname==='/api/v1/auth/session'){const subject=subjectResolver(req);return json(res,200,subject?{authenticated:true,member:authService?await authService.session(subject):{subject,displayName:'NEOpass Member',neopassStatus:'authenticated'}}:{authenticated:false});}
    if(req.method==='POST'&&url.pathname==='/api/v1/auth/logout'){res.setHeader('set-cookie',clearSessionCookie());return json(res,200,{authenticated:false});}
    if(url.pathname==='/health')return json(res,200,{service:'neo-platform-api',status:'ok',generatedAt:now(),platforms:Object.keys(PLATFORM_REGISTRY).length,ociRegisteredServices:OCI_SERVICE_REGISTRY.services.length,giss:templeGissRuntime?.service?'ready':'not_configured'});
    if(await gissHandler(req,res,url)) return;
    if(url.pathname.startsWith('/api/v1/integrations')){const subject=subjectResolver(req);if(!subject)return json(res,401,{error:'neopass_identity_required',readOnly:true});if(req.method==='GET'&&url.pathname==='/api/v1/integrations')return json(res,200,{apiVersion:'v1',subject,readOnly:true,...await integrationHub.list(subject)});const m=url.pathname.match(/^\/api\/v1\/integrations\/([^/]+)\/status$/);if(req.method==='GET'&&m)return json(res,200,{apiVersion:'v1',subject,readOnly:true,integration:m[1],status:await integrationHub.status(subject,m[1])});if(req.method==='POST'&&url.pathname==='/api/v1/integrations/execute-read'){let body='';for await(const chunk of req)body+=chunk;return json(res,200,{apiVersion:'v1',subject,...await integrationHub.execute(subject,JSON.parse(body||'{}'))});}}
    if(url.pathname==='/api/v1/commands/execute'){const subject=subjectResolver(req);if(!subject)return json(res,401,{error:'neopass_identity_required',readOnly:true});if(req.method!=='POST')return json(res,405,{error:'method_not_allowed',readOnly:true});let body='';for await(const chunk of req)body+=chunk;return json(res,200,await commandRouter.execute(subject,JSON.parse(body||'{}')));}
    const cc=url.pathname.match(/^\/api\/v1\/control-plane\/applications\/([^/]+)\/capabilities$/),ce=url.pathname.match(/^\/api\/v1\/control-plane\/applications\/([^/]+)\/commands$/);if(cc||ce){const subject=subjectResolver(req);if(!subject)return json(res,401,{error:'neopass_identity_required',readOnly:true});const id=decodeURIComponent((cc||ce)[1]);if(cc){if(req.method!=='GET')return json(res,405,{error:'method_not_allowed',readOnly:true});return json(res,200,{apiVersion:'v1',readOnly:true,...await controlPlane.capabilities(subject,id)});}if(req.method!=='POST')return json(res,405,{error:'method_not_allowed',readOnly:true});let body='';for await(const chunk of req)body+=chunk;return json(res,200,await controlPlane.execute(subject,id,JSON.parse(body||'{}')));}
    const tr=url.pathname.match(/^\/api\/v1\/temple\/(health|capabilities|read)$/);if(tr){const subject=subjectResolver(req);if(!subject)return json(res,401,{error:'neopass_identity_required',readOnly:true});if(tr[1]!=='read'&&req.method!=='GET')return json(res,405,{error:'method_not_allowed',readOnly:true});if(tr[1]==='health')return json(res,200,await templeAdapter.health(subject));if(tr[1]==='capabilities')return json(res,200,await templeAdapter.capabilities(subject));if(req.method!=='POST')return json(res,405,{error:'method_not_allowed',readOnly:true});let body='';for await(const chunk of req)body+=chunk;return json(res,200,await templeAdapter.read(subject,JSON.parse(body||'{}')));}
    if(url.pathname==='/api/v1/commands/capabilities'||url.pathname.match(/^\/api\/v1\/commands\/capabilities\/[^/]+\/status$/)){const subject=subjectResolver(req);if(!subject)return json(res,401,{error:'neopass_identity_required',readOnly:true});if(req.method!=='GET')return json(res,405,{error:'method_not_allowed',readOnly:true});const sm=url.pathname.match(/^\/api\/v1\/commands\/capabilities\/([^/]+)\/status$/);if(sm)return json(res,200,{apiVersion:'v1',readOnly:true,...await commandRouter.capabilityStatus(subject,decodeURIComponent(sm[1]))});return json(res,200,{apiVersion:'v1',readOnly:true,...await commandRouter.listCapabilities(subject)});}
    if(req.method!=='GET')return json(res,405,{error:'method_not_allowed',readOnly:true});if(url.pathname==='/api/v1/platforms')return json(res,200,{apiVersion:'v1',generatedAt:now(),platforms:Object.entries(PLATFORM_REGISTRY).map(([id,v])=>({id,name:v.name,services:v.services}))});if(url.pathname==='/api/v1/oci/services')return json(res,200,{apiVersion:'v1',generatedAt:now(),...OCI_SERVICE_REGISTRY});if(url.pathname==='/api/v1/prime/markets'){const assets=(url.searchParams.get('assets')||'XCP,NOMNI').split(',').map(v=>v.trim()).filter(Boolean).slice(0,20);return json(res,200,await marketData.snapshot({assets}));}const pa=url.pathname.match(/^\/api\/v1\/prime\/assets\/([^/]+)$/);if(pa)return json(res,200,await marketData.asset(pa[1]));const m=url.pathname.match(/^\/api\/v1\/platforms\/([^/]+)(?:\/(health|capabilities))?$/);if(m){const[,id,action='capabilities']=m,item=PLATFORM_REGISTRY[id];if(!item)return json(res,404,{error:'platform_not_found',platform:id});if(action==='health')return json(res,200,{platform:id,name:item.name,status:'ok',generatedAt:now(),readOnly:true});return json(res,200,{platform:id,name:item.name,status:'ready',generatedAt:now(),readOnly:true,source:item.source,services:item.services,transactionalExecution:'disabled-until-auth-and-runtime-binding'});}return json(res,404,{error:'not_found'});
  }catch(error){if(error instanceof IntegrationHubError||error instanceof CommandRouterError||error instanceof ControlPlaneError||error instanceof TempleAdapterError)return json(res,error.status,{error:error.code,message:error.message,readOnly:true});return json(res,502,{error:'upstream_failure',message:error?.message||'unknown error'});}});
}
export function startNeoPlatformApi({port=Number(process.env.PORT||8787)}={}){const server=createNeoPlatformApi();server.listen(port,()=>console.log(`NEO Platform API listening on :${port}`));return server;}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)startNeoPlatformApi();
