import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { once } from 'node:events';
import { createNeoPlatformApi, PLATFORM_REGISTRY } from './server.mjs';
import { createIntegrationHub, IntegrationHubError, createNeopassSubjectResolver } from './integration-hub.mjs';

const marketData={async snapshot({assets}={}){return{service:'neo-prime-market-data',apiVersion:'v1',status:'ok',generatedAt:'2026-08-25T00:00:00.000Z',bitcoin:{symbol:'BTC',priceUsd:112000,blockHeight:910144,status:'ok',errors:[]},counterparty:Object.fromEntries((assets||['XCP','NOMNI']).map(symbol=>[symbol,{symbol,status:'ok'}]))}},async asset(symbol){return{symbol:String(symbol).toUpperCase(),status:'ok',supply:900000000}}};
async function withServer(fn, options={}){const server=createNeoPlatformApi({now:()=> '2026-08-25T00:00:00.000Z',marketData,subjectResolver:req=>String(req.headers['x-neopass-subject']||'').trim()||null,...options});server.listen(0,'127.0.0.1');await once(server,'listening');const{port}=server.address();try{await fn(`http://127.0.0.1:${port}`)}finally{server.close();await once(server,'close')}}

function fakeComposio(){
	const sessions=[];
	return {
		sessions,
		async createSession(subject){sessions.push({subject,id:`trs_${subject}`});return{session_id:`trs_${subject}`}},
		async listTools(){return{items:[{slug:'GITHUB_LIST_REPOS',name:'GITHUB_LIST_REPOS',toolkit:'github'},{slug:'GITHUB_CREATE_ISSUE',name:'GITHUB_CREATE_ISSUE',toolkit:'github'}]}},
		async execute(sessionId,toolSlug){return{data:{toolSlug,token:'session-secret',nested:{password:'hidden'},status:'ok'},error:null,sessionId}}
	};
}

function authHeaders(subject='subject-a'){return{authorization:'Bearer opaque-neopass-token', 'x-neopass-subject':subject, 'content-type':'application/json'}}
function token({subject,secret,issuer,expiresAt=Math.floor(Date.now()/1000)+300}){const encode=value=>Buffer.from(value).toString('base64url');const header=encode(JSON.stringify({alg:'HS256',typ:'JWT'}));const payload=encode(JSON.stringify({sub:subject,iss:issuer,exp:expiresAt}));return `${header}.${payload}.${createHmac('sha256',secret).update(`${header}.${payload}`).digest('base64url')}`}

test('publishes ten-platform registry including Tokenworks, NEO Banks, and Nibiru Reserve',async()=>{await withServer(async base=>{const health=await fetch(`${base}/health`).then(r=>r.json());assert.equal(health.status,'ok');assert.equal(health.platforms,10);const registry=await fetch(`${base}/api/v1/platforms`).then(r=>r.json());assert.equal(registry.platforms.length,Object.keys(PLATFORM_REGISTRY).length);assert.ok(registry.platforms.some(p=>p.id==='neo-tokenworks'));assert.ok(registry.platforms.some(p=>p.id==='neo-banks'));assert.ok(registry.platforms.some(p=>p.id==='nibiru-reserve'))})});
test('publishes platform capability and health endpoints',async()=>{await withServer(async base=>{const capabilities=await fetch(`${base}/api/v1/platforms/neo-tokenworks/capabilities`).then(r=>r.json());assert.equal(capabilities.platform,'neo-tokenworks');assert.equal(capabilities.readOnly,true);assert.ok(capabilities.services.includes('neopass'));const health=await fetch(`${base}/api/v1/platforms/neo-banks/health`).then(r=>r.json());assert.equal(health.status,'ok')})});
test('publishes normalized NEO Prime market and asset endpoints',async()=>{await withServer(async base=>{const snapshot=await fetch(`${base}/api/v1/prime/markets?assets=XCP,NOMNI`).then(r=>r.json());assert.equal(snapshot.bitcoin.symbol,'BTC');assert.ok(snapshot.counterparty.NOMNI);const asset=await fetch(`${base}/api/v1/prime/assets/nomni`).then(r=>r.json());assert.equal(asset.symbol,'NOMNI')})});
test('rejects unknown platforms and write methods',async()=>{await withServer(async base=>{assert.equal((await fetch(`${base}/api/v1/platforms/not-real`)).status,404);const write=await fetch(`${base}/api/v1/platforms`,{method:'POST'});assert.equal(write.status,405);assert.equal((await write.json()).readOnly,true)})});
test('requires a NEOpass identity for integration routes',async()=>{await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations`);assert.equal(response.status,401);assert.equal((await response.json()).error,'neopass_identity_required')})});
test('lists subject-scoped integrations and retrieves status',async()=>{const composio=fakeComposio();await withServer(async base=>{const list=await fetch(`${base}/api/v1/integrations`,{headers:authHeaders()}).then(r=>r.json());assert.equal(list.integrations[0].name,'github');assert.deepEqual(list.integrations[0].classifications,['read','write']);const status=await fetch(`${base}/api/v1/integrations/github/status`,{headers:authHeaders()}).then(r=>r.json());assert.equal(status.status.name,'github');assert.equal(status.status.health,'ready');assert.equal(composio.sessions.length,1)},{integrationHub:createIntegrationHub({composio,now:()=> '2026-08-25T00:00:00.000Z'})})});
test('executes an approved read and normalizes plus redacts output',async()=>{const composio=fakeComposio();const audits=[];await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations/execute-read`,{method:'POST',headers:authHeaders(),body:JSON.stringify({integration:'github',tool:'GITHUB_LIST_REPOS',arguments:{}})});const body=await response.json();assert.equal(response.status,200);assert.equal(body.readOnly,true);assert.equal(body.data.token,'[REDACTED]');assert.equal(body.data.nested.password,'[REDACTED]');assert.equal(audits[0].allowed,true);assert.equal(audits[0].classification,'read');assert.equal(JSON.stringify(audits).includes('opaque'),false)},{integrationHub:createIntegrationHub({composio,audit:event=>audits.push(event)})})});
test('rejects write capabilities before execution',async()=>{const composio=fakeComposio();await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations/execute-read`,{method:'POST',headers:authHeaders(),body:JSON.stringify({integration:'github',tool:'GITHUB_CREATE_ISSUE'})});assert.equal(response.status,403);assert.equal((await response.json()).error,'read_only_operation_required')},{integrationHub:createIntegrationHub({composio})})});
test('returns controlled errors for unknown integrations and Composio session failures',async()=>{await withServer(async base=>{const unknown=await fetch(`${base}/api/v1/integrations/slack/status`,{headers:authHeaders()});assert.equal(unknown.status,404);assert.equal((await unknown.json()).error,'integration_not_found')},{integrationHub:createIntegrationHub({composio:fakeComposio()})});const failing={async createSession(){throw new IntegrationHubError('composio_authentication_failed','Composio authentication failed.',502)}};await withServer(async base=>{const response=await fetch(`${base}/api/v1/integrations`,{headers:authHeaders()});assert.equal(response.status,502);assert.equal((await response.json()).error,'composio_authentication_failed')},{integrationHub:createIntegrationHub({composio:failing})})});
test('isolates Composio sessions by NEOpass subject',async()=>{const composio=fakeComposio();await withServer(async base=>{await fetch(`${base}/api/v1/integrations`,{headers:authHeaders('subject-a')});await fetch(`${base}/api/v1/integrations`,{headers:authHeaders('subject-b')});assert.deepEqual(composio.sessions.map(session=>session.subject),['subject-a','subject-b'])},{integrationHub:createIntegrationHub({composio})})});
test('verifies production NEOpass HS256 bearer subjects and fails closed',()=>{const secret='test-neopass-secret';const resolve=createNeopassSubjectResolver({secret,issuer:'neo'});const valid=token({subject:'member-1',secret,issuer:'neo'});assert.equal(resolve({headers:{authorization:`Bearer ${valid}`}}),'member-1');assert.equal(resolve({headers:{authorization:`Bearer ${token({subject:'member-1',secret,issuer:'wrong'})}`}}),null);assert.equal(resolve({headers:{authorization:'Bearer malformed'}}),null);assert.equal(resolve({headers:{authorization:`Bearer ${token({subject:'member-1',secret,issuer:'neo',expiresAt:1})}`}}),null);assert.equal(createNeopassSubjectResolver({})({headers:{authorization:`Bearer ${valid}`}}),null)});
