import http from 'node:http';import {URL} from 'node:url';import {FirestoreNeotherapyStore} from './firestore-store.mjs'
const PORT=Number(process.env.PORT||8080);let store;const getStore=()=>store||(store=new FirestoreNeotherapyStore());const json=(res,s,b)=>{res.writeHead(s,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(b))}
const body=async req=>{let x='';for await(const c of req)x+=c;return x?JSON.parse(x):{}}
const audit=(action,resourceId,actorId='system')=>getStore().appendAudit({id:crypto.randomUUID(),actorId,action,resourceType:'NEOTHERAPY',resourceId,timestamp:new Date().toISOString()})
export const handler=async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,service:'neotherapy'});if(req.method==='GET'&&u.pathname==='/api/neotherapy/status')return json(res,200,{service:'neotherapy',storage:'firestore',persistent:true,boundary:'participant data is not general NEO intelligence'});if(req.method==='POST'&&u.pathname==='/api/neotherapy/canary'){const result=await getStore().canary('deploy');return json(res,result.ok?200:500,result);}if(req.method!=='POST'||u.pathname!=='/api/neotherapy')return json(res,404,{error:'NOT_FOUND'});const b=await body(req),a=u.searchParams.get('action');
if(a==='consent'){if(!b.participantId||!b.modalityId||!b.status)return json(res,400,{error:'INVALID_CONSENT'});const r={id:b.id||crypto.randomUUID(),participantId:b.participantId,modalityId:b.modalityId,version:b.version||'1.0',status:b.status,signedAt:b.status==='ACTIVE'?new Date().toISOString():b.signedAt,withdrawnAt:b.status==='WITHDRAWN'?new Date().toISOString():undefined};await getStore().saveConsent(r);await audit('CONSENT_'+r.status,r.id,b.actorId);return json(res,200,r)}
if(a==='credential'){if(!b.practitionerId||!b.status)return json(res,400,{error:'INVALID_CREDENTIAL'});const r={id:b.id||crypto.randomUUID(),practitionerId:b.practitionerId,level:b.level||'C.Neo.',status:b.status,modalities:Array.isArray(b.modalities)?b.modalities:[]};await getStore().saveCredential(r);await audit('CREDENTIAL_'+r.status,r.id,b.actorId);return json(res,200,r)}
if(a==='authorize'){const c=await getStore().getConsent(b.participantId,b.modalityId),k=await getStore().getCredential(b.practitionerId);if(!c||c.status!=='ACTIVE')return json(res,403,{authorized:false,error:'ACTIVE_CONSENT_REQUIRED'});if(!k||k.status!=='ACTIVE')return json(res,403,{authorized:false,error:'ACTIVE_CREDENTIAL_REQUIRED'});if(!k.modalities?.includes(b.modalityId))return json(res,403,{authorized:false,error:'MODALITY_AUTHORIZATION_REQUIRED'});if(!b.safetyScreenComplete)return json(res,403,{authorized:false,error:'SAFETY_SCREEN_REQUIRED'});await audit('MODALITY_AUTHORIZED',b.modalityId,b.practitionerId);return json(res,200,{authorized:true})}
if(a==='session'){if(!b.participantId||!b.practitionerId)return json(res,400,{error:'INVALID_SESSION'});const r={...b,id:b.id||crypto.randomUUID(),createdAt:b.createdAt||new Date().toISOString()};await getStore().saveSession(r);await audit('SESSION_SAVED',r.id,b.practitionerId);return json(res,200,r)}return json(res,404,{error:'UNKNOWN_ACTION'})}catch(e){console.error(e);return json(res,500,{error:'INTERNAL_ERROR'})}}
if(process.env.NODE_ENV!=='test')http.createServer(handler).listen(PORT,'0.0.0.0',()=>console.log('neotherapy listening',PORT));
