import crypto from 'node:crypto'
const clone=v=>structuredClone(v)
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v}
const bytes=v=>Buffer.from(JSON.stringify(canonical(v)))
export function createInstitutionalIdentity(input={}){if(!input.id||!input.trustDomain)throw new TypeError('identity id and trustDomain are required');return {id:input.id,type:input.type??'human',trustDomain:input.trustDomain,roles:clone(input.roles??[]),status:input.status??'active',keyIds:clone(input.keyIds??[]),createdAt:input.createdAt??new Date().toISOString()}}
export function registerSigningKey({identityId,keyId,publicKey,algorithm='Ed25519',createdAt=new Date().toISOString()}={}){if(!identityId||!keyId||!publicKey)throw new TypeError('identityId, keyId and publicKey are required');return {identityId,keyId,publicKey,algorithm,status:'active',createdAt,revokedAt:null,replacedBy:null}}
export function rotateSigningKey({key,newKeyId,newPublicKey,at=new Date().toISOString()}={}){if(!key||!newKeyId||!newPublicKey)throw new TypeError('key, newKeyId and newPublicKey are required');return {revoked:{...clone(key),status:'rotated',revokedAt:at,replacedBy:newKeyId},active:registerSigningKey({identityId:key.identityId,keyId:newKeyId,publicKey:newPublicKey,algorithm:key.algorithm,createdAt:at})}}
export function revokeSigningKey({key,at=new Date().toISOString(),reason='revoked'}={}){return {...clone(key),status:'revoked',revokedAt:at,revocationReason:reason}}
export function issueCapability(input={}){if(!input.id||!input.issuer||!input.subject||!input.action)throw new TypeError('capability id, issuer, subject and action are required');return {id:input.id,issuer:input.issuer,subject:input.subject,action:input.action,scope:clone(input.scope??{}),trustDomain:input.trustDomain??null,notBefore:input.notBefore??null,expiresAt:input.expiresAt??null,status:'active'}}
export function evaluateCapability({capability,subject,action,trustDomain,now=new Date()}={}){const t=+new Date(now),valid=Boolean(capability)&&capability.status==='active'&&capability.subject===subject&&capability.action===action&&(!trustDomain||!capability.trustDomain||capability.trustDomain===trustDomain)&&(!capability.notBefore||t>=+new Date(capability.notBefore))&&(!capability.expiresAt||t<+new Date(capability.expiresAt));return {authorized:valid,capabilityId:capability?.id??null,scope:clone(capability?.scope??{})}}
export function signAttestation({payload,identityId,keyId,privateKey,issuedAt=new Date().toISOString()}={}){if(!privateKey)throw new TypeError('privateKey is required');const envelope={payload:clone(payload),identityId,keyId,issuedAt},signature=crypto.sign(null,bytes(envelope),privateKey).toString('base64');return {...envelope,signature,algorithm:'Ed25519'}}
export function verifyAttestation({attestation,key,identity,expectedTrustDomain}={}){if(!attestation||!key||!identity)return {valid:false,reason:'missing-input'};if(key.status!=='active')return {valid:false,reason:'key-inactive'};if(identity.status!=='active'||key.identityId!==identity.id||attestation.identityId!==identity.id||attestation.keyId!==key.keyId)return {valid:false,reason:'identity-key-mismatch'};if(expectedTrustDomain&&identity.trustDomain!==expectedTrustDomain)return {valid:false,reason:'trust-domain-mismatch'};const {signature,algorithm,...envelope}=attestation;const valid=crypto.verify(null,bytes(envelope),key.publicKey,Buffer.from(signature,'base64'));return {valid,reason:valid?'verified':'bad-signature',identityId:identity.id,keyId:key.keyId,trustDomain:identity.trustDomain}}
export function createMissionProvenance({missionId,decisionId,attestation,capabilityId,parentMissionId=null}={}){if(!missionId||!decisionId||!attestation)throw new TypeError('missionId, decisionId and attestation are required');return {missionId,decisionId,parentMissionId,authorizedBy:attestation.identityId,keyId:attestation.keyId,capabilityId:capabilityId??null,attestationSignature:attestation.signature,recordedAt:new Date().toISOString()}}
