import crypto from 'node:crypto'
const clone=v=>structuredClone(v)
export function createWorkloadIdentity(input={}){if(!input.id||!input.trustDomain)throw new TypeError('workload id and trustDomain are required');return {id:input.id,type:input.type??'worker',trustDomain:input.trustDomain,roles:clone(input.roles??[]),status:input.status??'active',keyRef:input.keyRef??null,createdAt:input.createdAt??new Date().toISOString()}}
export function createExternalKeyRef(input={}){if(!input.provider||!input.keyId)throw new TypeError('provider and keyId are required');return {provider:input.provider,keyId:input.keyId,algorithm:input.algorithm??'Ed25519',version:input.version??'current',status:input.status??'active',metadata:clone(input.metadata??{})}}
export function issueEphemeralCredential({id=crypto.randomUUID(),subject,audience,scope={},ttlSeconds=300,now=new Date()}={}){if(!subject||!audience)throw new TypeError('subject and audience are required');const issuedAt=new Date(now),expiresAt=new Date(issuedAt.getTime()+Math.max(30,Number(ttlSeconds))*1000);return {id,subject,audience,scope:clone(scope),issuedAt:issuedAt.toISOString(),expiresAt:expiresAt.toISOString(),status:'active'}}
export function validateEphemeralCredential({credential,subject,audience,resource,now=new Date()}={}){if(!credential||credential.status!=='active')return {valid:false,reason:'credential-inactive'};if(credential.subject!==subject||credential.audience!==audience)return {valid:false,reason:'binding-mismatch'};if(+new Date(now)>=+new Date(credential.expiresAt))return {valid:false,reason:'credential-expired'};const allowed=credential.scope?.resources;if(resource&&Array.isArray(allowed)&&!allowed.includes(resource)&&!allowed.includes('*'))return {valid:false,reason:'resource-scope-denied'};return {valid:true,credentialId:credential.id}}
export function createSecretBroker({providers={}}={}){return {async lease({provider,secretRef,subject,audience,scope={},ttlSeconds=300}){const adapter=providers[provider];if(!adapter?.leaseSecret)throw new Error(`secret provider unavailable: ${provider}`);const credential=issueEphemeralCredential({subject,audience,scope,ttlSeconds});const value=await adapter.leaseSecret({secretRef,credential});return {credential,secret:{value,ref:secretRef,provider}}},async revoke({provider,credentialId}){const adapter=providers[provider];if(adapter?.revokeLease)await adapter.revokeLease({credentialId});return {revoked:true,credentialId}}}}
export function signWorkerLease({lease,signer}){if(!signer?.sign)throw new TypeError('signer.sign is required');const payload={...clone(lease),signedAt:new Date().toISOString()};return Promise.resolve(signer.sign(payload)).then(signature=>({...payload,signature}))}
export async function verifyWorkerLease({signedLease,verifier}){if(!signedLease||!verifier?.verify)return {valid:false,reason:'missing-input'};const {signature,...payload}=signedLease;const valid=await verifier.verify(payload,signature);return {valid:Boolean(valid),reason:valid?'verified':'bad-signature'}}
export function createRevocationRegistry(){const revoked=new Map();return {revoke(id,reason='revoked',at=new Date().toISOString()){revoked.set(id,{reason,at});return {id,reason,at}},isRevoked(id){return revoked.has(id)},get(id){return revoked.get(id)??null}}}
export function secureRuntimeDecision({workload,credential,keyRef,revocations,expectedTrustDomain,subject,audience,resource,now=new Date()}={}){if(!workload||workload.status!=='active')return {allowed:false,reason:'workload-inactive'};if(expectedTrustDomain&&workload.trustDomain!==expectedTrustDomain)return {allowed:false,reason:'trust-domain-mismatch'};if(!keyRef||keyRef.status!=='active'||revocations?.isRevoked(keyRef.keyId))return {allowed:false,reason:'key-unavailable'};const valid=validateEphemeralCredential({credential,subject:subject??workload.id,audience,resource,now});if(!valid.valid)return {allowed:false,reason:valid.reason};return {allowed:true,workloadId:workload.id,credentialId:credential.id,keyId:keyRef.keyId}}
